### ISSUE TITLE
SplitContainer splitter movement is not visible on WebView control

### ISSUE THREAD

**Issue by ninoxscutulata** [MicrosoftEdge/WebView2Feedback#3086] opened 2022-12-26 02:18 UTC
**Description**
I have datagridview and webview2 in splitcontainer.(orientation=horizontal, dock=fill)
After placing the textbox instead of webview2, if I grab the splitter with the mouse and move it, the splitter's movement is visible.
But when I place the webview2 in the splitcontainer, the splitter's movement disappears and is not visible.
Is it possible to make the splitter's movement visible on the webview2 area placed in the splitcontainer?
splitter disppears on webview2
https://stackoverflow.com/questions/73451793/splitcontainer-splitter-movement-is-not-visible-on-webview-control

**Operating System**
Windows 10 Pro, .NET Core 6.0

**Framework**
WinForms

**SDK/Runtime.**
SDK

**Version**
1.0.1549-prerelease

**Repro Steps**
https://drive.google.com/file/d/1cKL3iq2QseP6mi43KhobaCN_5Sc9zyS8/view?usp=sharing

**Screenshots**
https://i.stack.imgur.com/KYQQB.gif

**Comment by victorthoang** [comment] 2022-12-27 08:38
Hello @ninoxscutulata, could you please provide some more information about your inquiry? 

E.g.:

- Operating System 
- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK/Runtime.

This will help with figuring out how to best address your issue. Thanks! 

With holidays over and new year's approaching, I appreciate your patience!

**Comment by ninoxscutulata** [comment] 2022-12-27 17:22
Hello, @victorthoang victorthoang !!
I just updated some missing info. thank you :)

**Comment by champnic** [comment] 2023-02-01 20:34
Unfortunately I think this is a duplicate of the WPF overlap/airspace issue: #286

**Closed by champnic** 2023-02-01 20:34 UTC
Labels: bug
