### ISSUE TITLE
Distribute WebView2 in Production

### ISSUE THREAD

**Issue by elinside** [MicrosoftEdge/WebView2Feedback#1918] opened 2021-11-11 10:20 UTC
Dear WebView2 Team

My Task is to distribute WebView2 in our production environment, but its so hard to find the necessary information. We are running windows10 20H2, so there's no preinstalled runtime:
1.	Why do I need to install the runtime, when I have all the required files in the current edge stable app folder, under C:\Program Files (x86)\Microsoft\Edge\Application\95.0.1020.44?

2.	The runtime does not update, and these keys make no difference.
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EdgeUpdate]
"Update{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"=dword:00000001
"Install{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"=dword:00000001
"Allowsxs"=dword:00000000
"UpdateDefault"=dword:00000001
"InstallDefault"=dword:00000001

How can I make sure, it's always up to date?

3.	Where can I find the release notes for the runtime itself (not the SDK)?

4.	Because of security restrictions, MSEdge Browser is only allowed to reach external websites. This is solved through the proxy.pac
But our developers also want to create apps for internal websites.
Is it possible to set webview2 only proxy settings?

I hope some of my questions can be answered.

Thanks

**Comment by champnic** [comment] 2021-11-12 01:19
Hey @elinside -

Some of this is answered here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

1. The stable WebView2 runtime is kept separate from the stable Edge browser By Design, for reasons described here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#microsoft-edge-stable-channel-isnt-supported-for-webview2
2. Just to make sure - the WebView2 Runtime is installed, but you are not seeing it update? What version is it currently? These are the relevant policies (which it looks like you are setting): https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#microsoft-edge-webview. Allowsxs shouldn't have an effect. If it's updating it should automatically stay up to date without work required from you, but note that enterprise admins may choose to block updates. Let me know if it's still not updating and we can grab the installer logs.
3. The WebView2 release notes include some info about runtime fixes tagged with "Runtime-specific": https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes, and you can find other info here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel (though this looks laughably sparse unfortunately...)
4. You should be able to configure some aspects of a proxy using browser command-line args, see: https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277. You can set this for all WebView2 apps (or target specific apps) using registry keys: `[{Root}]\Software\Policies\Microsoft\Edge\WebView2\AdditionalBrowserArguments
"{AppId}"=""` or environment variables: `WEBVIEW_ADDITIONAL_BROWSER_ARGS=...`. More info here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1020.30#createcorewebview2environmentwithoptions

Let me know if you have more questions or need extra details. Thanks!

**Comment by elinside** [comment] 2021-11-12 10:14
Hello @champnic 
Thanks, this is very helpful.
Meanwhile the runtime has updated, I think it was because of the delay defined in AutoUpdateCheckPeriodMinutes...

Can you provide me the exact key&values I have to set in the registry to define the proxysettings?

[{Root}]\Software\Policies\Microsoft\Edge\WebView2\AdditionalBrowserArguments "{AppId}"=""

**Comment by champnic** [comment] 2021-11-13 00:48
Glad to hear @elinside! I'm going to close this issue for now, but please feel free to ask more questions if you need more clarity about anything :)

**Closed by champnic** 2021-11-13 00:48 UTC
Labels: question
