### ISSUE TITLE
Setting UserAgent not effective on first navigation.

### ISSUE THREAD

**Issue by wilva** [MicrosoftEdge/WebView2Feedback#2862] opened 2022-10-10 15:21 UTC
**Description**
Setting the UserAgent is not effective when navigating to a URL. 
Only once you navigate to the 2nd URL does the setting apply.

**Version**
Runtime: Release 106.0.1370.37
Framework: WPF, Win32
OS: Win10

**Repro Steps**
Take the standard demo WebView2Samples, WebView2WpfBrowser
In MainWindow.xaml change "www.bing.com" into "whatismybrowser.com" like so:
```
            <wv2:WebView2
                x:Name="webView"
                CreationProperties="{StaticResource EvergreenWebView2CreationProperties}"
                Source="https://www.whatismybrowser.com/"
            />

```

In MainWindowXaml.cs look for "WebView_CoreWebView2InitializationCompleted" and add a line for changing the UserAgent on WebView2 initialization completion.
eg.
```

        void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                webView.CoreWebView2.ProcessFailed += WebView_ProcessFailed;
                webView.CoreWebView2.DocumentTitleChanged += WebView_DocumentTitleChanged;
                webView.CoreWebView2.IsDocumentPlayingAudioChanged += WebView_IsDocumentPlayingAudioChanged;
                webView.CoreWebView2.IsMutedChanged += WebView_IsMutedChanged;
                WebViewSettings.UserAgent = "foobar";

```

Now compile and run.

On first navigation the website will tell you that you are using Edge 106 browser and you're up-to-date.

Press the "Go" button.

And... now the website tells you that it can't find what browser you are using and that the user agent string is "foobar".

It is expected that the user agent string was set on the first time and not after refreshing the site.

**Comment by victorthoang** [comment] 2022-10-10 16:43
hello @wilva, 

Thanks for your bug report. We will evaluate this bug and get back to you with our findings. @imicy for further investigation and triaging.

**Comment by ElyssaJyu** [comment] 2022-10-12 06:48
Hi @wilva, 
since setting change to `UserAgent` is made after `NavigationStarting` event, it won't be applied until the next top-level navigation, as documented in [CoreWebView2Settings](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings?view=webview2-dotnet-1.0.902.49). You will need to wait for the initialization to complete to get the property from the `CoreWebView2`.

**Comment by wilva** [comment] 2022-10-12 11:13
Hello @ElyssaJyu,

That makes sense, thank you.
The problem is that it still does not appear to work well. I have tested it a number of times and sometimes it appears to work like that and -at least for me- most of the time it does not.

To stay with the example from above. First set the .Source in MainWindow.xaml above to an empty string.
eg.
```
            <wv2:WebView2
                x:Name="webView"
                CreationProperties="{StaticResource EvergreenWebView2CreationProperties}"
                Source=""
            />
```
So now no site is loaded on starting the demo application.

On running the example again, it does not instantiate the WebView2 control.
Go to the address bar and enter "https://www.whatismybrowser.com/" in the URL bar.

It usually comes back with "Edge 106" as useragent, but also every now and then with "FooBar".
FWIW I have changed the URL a bit sometimes as "https://whatismybrowser.com/" (without the www. part), sometimes without the backslash at the end "https://www.whatismybrowser.com". Haven't found much consistency in that.

When looking at the events in a debugger it first comes past WebView_CoreWebView2InitializationCompleted and after that it triggers WebView_NavigationStarting.
So that would suggest that the creation of the WebView2 control is complete and the UserAgent is set before NavigationStarting is triggered. Yet the website still reports the wrong user agent.

**Comment by wilva** [comment] 2022-10-12 11:21
FWIW. I'm also seeing this in the Win32 interface where I am setting the UserAgent during creation and then navigate manually from a button. In that case the WebView2 control is created long before navigation happens.

**Comment by ElyssaJyu** [comment] 2022-10-13 08:10
Hi @wilva,
Whether leave `Source` as blank or enter "https://www.whatismybrowser.com/", when you load the demo, `UserAgent` hasn't been set until you click "Go" button on URL bar.

**Comment by wilva** [comment] 2022-10-14 10:59
Hi @ElyssaJyu ,

> After the WebView2 control is created, the set user agent triggers the NavigationStarting event and passes the property to the server

I do not see setting UserAgent triggering the NavigationStarting event.

Following my steps, that I described above, I see the following happen:
1. The control gets created by selecting the "Increase Zoom" menu option.
2. During WebView_CoreWebView2InitializationCompleted event, the UserAgent is set to "FooBar".
3. The control is rendered, the URL bar shows "about:blank".
4. There is NO navigationStarting event triggered at this time (which I confirmed by having a breakpoint on it)
5. Enter "https://www.whatismybrowser.com" in the URL bar and press the "go" button.
6. Now the NavigationStarting event triggers for the first time. This event triggers two times. It does this regardless of my line of code setting the UserAgent is commented out or not.

Every now and then I see the "FooBar" useragent reported, but most of the time it is the "Edge 106" one (one out of 20 times that I just tested it reported "FooBar")

The NavigationStarting event isn't triggered until I press on the "go" button which sends navigate from GoToPageCmdExecuted. It is not triggered by setting the UserAgent.
Maybe you are trying to say that it is during the NavigationStarting event that the UserAgent setting gets applied? But that the ship has sailed by that time?

You seem to be saying that it is not possible to have the first navigation of the WebView2 control to have a UserAgent set that is different from the default UserAgent.

Also note this other bugreport which might be related. https://github.com/MicrosoftEdge/WebView2Feedback/issues/1861

**Comment by wilva** [comment] 2022-10-14 15:18
Hi,

I kept wondering why you keep on insisting that your link negated my point of view as -when I read it- it actually seems to confirm my view. Turns out that the example WebView2WpfBrowser had changed since I had last downloaded it, I can see how that makes it a bit more confusing.

The StartPageUri logic did not exist in my version... so I updated to the version from today and my notes from above mostly still apply.
Except you need to comment out the Start page logic like so:
from:

```
        void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                // Setup host resource mapping for local files
                webView.CoreWebView2.SetVirtualHostNameToFolderMapping("appassets.example", "assets", CoreWebView2HostResourceAccessKind.DenyCors);
                // Set StartPage Uri
                webView.Source = new Uri(GetStartPageUri(webView.CoreWebView2));

```
into:

```
        void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                //// Setup host resource mapping for local files
                //webView.CoreWebView2.SetVirtualHostNameToFolderMapping("appassets.example", "assets", CoreWebView2HostResourceAccessKind.DenyCors);
                //// Set StartPage Uri
                //webView.Source = new Uri(GetStartPageUri(webView.CoreWebView2));
                WebViewSettings.UserAgent = "foobar";

```

This is so there is NO navigation on creating the WebView2 object, which is crucial to my report.

After that I still see everything I still reported earlier today.

Hope this helps.

**Comment by ElyssaJyu** [comment] 2022-10-17 06:48
Let me organize: What I replied above does not try to negate your point, but to explain why it cannot be effective on the first navigation, and works on the second time 
Also, I reproduce the demo by the steps. 
- Based on your setting, select the "Increase Zoom" menu option, initialization of the control's CoreWebView2 triggers. 
- During `WebView_CoreWebView2InitializationCompleted` event, the `UserAgent` is set to "FooBar". (But not send to the server yet at this moment)
- Enter "https://www.whatismybrowser.com/" in the URL bar and press the "go" button, then `NavigationStarting` event triggers (the change of `UserAgent` sends to the server at this moment, but not get applied immediately)
- on the next time `NavigationStarting` event triggers, "FooBar" is reported.  (what's why you will see "FooBar" useragent report after press "go" button twice.)

**Comment by wilva** [comment] 2022-10-17 08:46
Thank you @ElyssaJyu.

So is it not possible for the WebView2 control to use a different UserAgent on the first navigation?
Am I doing something wrong?

**Comment by ElyssaJyu** [comment] 2022-10-17 08:59
Unfortunately, by current design, the change to the UserAgent cannot get applied on the first navigation (the same situation on Win32 sample). But we will discuss your suggestion internally. And will let you know if anything changes. Thanks.

**Comment by wilva** [comment] 2022-10-17 09:02
Ok. 

Thanks for changing it into a feature request as that was indeed my next question.

**Comment by ElyssaJyu** [comment] 2022-10-18 08:43
As we investigated, "https://www.whatismybrowser.com/" website has a redirection, which will change userAgent back to default. 
![image](https://user-images.githubusercontent.com/111425758/196381525-9bf501da-e119-4804-b082-d32eda174e58.png)

![image](https://user-images.githubusercontent.com/111425758/196374367-5f733c23-bce3-434d-bcf1-d3412889fe26.png)

**Comment by plantree** [comment] 2022-10-18 08:43
Hi @wilva,

We have found that, the `URL redirect` will restore the `UserAgent`. You can test it in Edge too. Like this:

> Custom set user-agent in DevTools, and type `http://www.whatismybrowser.com/`. It will redirect to `https://www.whatismybrowser.com/`.

We don't know yet if this implementation works as expeceted, and the simple workaround might be using another website to get browser information.

**Comment by wilva** [comment] 2022-10-18 09:21
Hi,
It was my customer who brought this up. I don't think the website redirecting is relevant, but I will ask them.

Also not sure why a redirect should change the user agent? A user agent is not supposed to be dependent on URL AFAICT.
IMHO it should not matter what website you are accessing, after you set the User Agent to something else it should be consistently used for any website that you access, with or without redirects.

It is certainly possible that the origin of this redirect problem lies deeper than the WebView2 control itself or that there is more than one issue at hand. 

Either way.. that's some great detective work right there. :)

**Comment by plantree** [comment] 2022-10-19 02:46
Hi @wilva,

I am also confused about `redirect will reset user-agent`, but you could verify on Edge according to the method that Elyssa provides.

Later I will communicate with Edge team to get more information and sync with you later.

**Comment by wilva** [comment] 2022-10-19 11:45
Thanks, I don't doubt your findings on this.

**Comment by ElyssaJyu** [comment] 2022-11-17 02:53
I will close this issue as no fix needed, and feel free to reopen with more info so we can investigate further, thanks.

**Closed by ElyssaJyu** 2022-11-17 02:53 UTC
Labels: bug
