### ISSUE TITLE
Webview2 refuse to change EBwebview folder On ensurecorewebview2async

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1442] opened 2021-06-23 08:39 UTC
Code Used

c# 
winforms

```cs
 private async void Browser_Load(object sender, EventArgs e)
        {
            panel4.Visible = false;

            **var webView2Environment = await CoreWebView2Environment.CreateAsync(null, "C:\temp");
            await web.EnsureCoreWebView2Async(webView2Environment);**
      
            if (FireBrowser.Properties.Settings.Default.History == true)
            {
                FireBrowser.Properties.Settings.Default.History = true;
                Pauze.Visible = true;
                OnOf.Text = "History-On";
            }
            else
            {
                Pauze.Visible = false;
                FireBrowser.Properties.Settings.Default.History = false;
                OnOf.Text = "History-Off";
            }         
        }
```

[AB#34126329](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34126329)

**Comment by jarno9981** [comment] 2021-06-23 08:39
@champnic

**Comment by champnic** [comment] 2021-06-29 21:48
Hey @jarno9981 - Sorry I missed this ping earlier. This looks correct. When you run this code, is there already an environment or WebView2 running? How are you verifying that it's not using the expected user data folder?

**Comment by jarno9981** [comment] 2021-06-30 05:05
@champnic    i verify it on when the app is starting   and the folder should change with async in the documentation

**Comment by jarno9981** [comment] 2021-06-30 18:39
When i running the app i can see that all cache files from websites will appear in the temp folder and when i close the browser the temp files will dissapier

**Comment by champnic** [comment] 2021-07-01 00:18
If you see the cache files being created in the C:\temp folder then the C:\temp folder has correctly been set as the user data folder. What behavior are you expecting that's different than what you described?

**Comment by jarno9981** [comment] 2021-07-01 07:17
But EBwebview folder will not change i need it in a writable location now it always stays in program files folder

**Comment by champnic** [comment] 2021-07-01 16:02
> When i running the app i can see that all cache files from websites will appear in the temp folder

Can you give an example of what this looks like? Is `EBWebView` folder being created in C:\temp or not?

**Comment by jarno9981** [comment] 2021-07-01 16:41
The EBWebView folder creates its self in the excuteble folder but i want it in temp

**Comment by champnic** [comment] 2021-07-01 17:34
I've opened this bug on our backlog to take a closer look. If you have a sample app you can share that reproduces this behavior that would be helpful. Thanks!

**Comment by jarno9981** [comment] 2021-07-01 18:07
@champnic   https://github.com/jarno9981/FireBrowser full project with sln and everthing

**Comment by jarno9981** [comment] 2021-07-01 18:08
This the program with the bug that i am actavily developing

**Comment by jarno9981** [comment] 2021-07-01 18:55
@champnic it recommended to run release build and after you done setup you have to manauly restart de app

**Comment by champnic** [comment] 2021-07-01 22:02
@jarno9981 Thanks for sharing! I took a quick look. Was a bit surprised coming across the ContentCheck list :P 

It looks like you're setting the `Source` property in `InitializeComponent`. This will kickoff implicit initialization of the control, and so when you try and create/use the environment later it doesn't work. Instead you can remove that `Source` setting and rely on the explicit initialization you are doing when you call `EnsureCoreWebView2Async`. You can move the initial navigation to after the `await EnsureCoreWebView2Async;` call. Can you give that a try?

**Comment by jarno9981** [comment] 2021-07-02 06:24
I now content check list is long but you can trigger it on and off for child protection    

I will try what you say

**Comment by jarno9981** [comment] 2021-07-02 14:49
I have try but there is now a folder called edgebit in temp but still ebwebview folder is still showing in excutable folder not in temp

**Comment by jarno9981** [comment] 2021-07-04 14:22
@champnic https://github.com/jarno9981/FireTabs

Maybe the tab system that i coded has a conflict maybe

**Comment by champnic** [comment] 2021-11-25 01:50
Closing the bug linked to this item - we haven't been able to detect a problem here. Let me know if you are still running into this issue. Thanks!

**Closed by champnic** 2021-11-25 01:50 UTC
Labels: bug, tracked
