### ISSUE TITLE
Use WebView2 without user interface

### ISSUE THREAD

**Issue by RobertoBaruffa** [MicrosoftEdge/WebView2Feedback#1015] opened 2021-03-01 16:31 UTC
Hello,
 I'm trying to use WebView2 control without the user interface in a C# WinForms project.

I do these 4 steps into a C# class:

1) Create a new instance of WebView2 control:

     **_var webView2 = new WebView2();_**

2) Call the EnsureCoreWebView2Async method:

    **_await webView2.EnsureCoreWebView2Async();_**

3) Set the DOMContentLoaded event delegate:

    **_webView2.CoreWebView2.DOMContentLoaded += CoreWebView2OnDOMContentLoaded;_**

4) Now i'd like to set the Source Uri of the webView2 but **the problem** is that after the completion of step 2 (EnsureCoreWebViewAsync) the **webView2.CoreWebView2 is still null**.

Is this a bug? 

Please, can You tell me the best way to accomplish this?

Bye

Roberto

**Comment by pagoe-msft** [comment] 2021-03-01 23:48
@RobertoBaruffa does this repro if you follow our getting started guide? 

https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

After step 2 - you should be able to set the source.

**Comment by RobertoBaruffa** [comment] 2021-03-03 07:40
Hi @pagoe-msft,
 I'm working with WinForms project (not WPF). If I follow the same design pattern of WinForms getting started guide ( https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms ) everything works fine.

But I want to use webview2 without user interface, so I cant add the WebView2 control to a visible form.

My problems seems related to issue 202: https://github.com/MicrosoftEdge/WebView2Feedback/issues/202

**Comment by champnic** [comment] 2021-03-04 01:03
Hey @RobertoBaruffa - This seems like the same root cause as #202 which we are using to track this issue, so I'm going to close this one. I'll add a note over on #202 and see if we can bump the priority. Thanks!

**Closed by champnic** 2021-03-04 01:03 UTC

**Comment by RobertoBaruffa** [comment] 2021-03-04 08:41
Thank You @champnic 
 this is a very important feature to enable the adoption of the WebView2 control in my project.

Bye :-)
