### ISSUE TITLE
COMException: There is not enough space on the disk from InitCoreWebView2Async

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#3407] opened 2023-04-19 14:10 UTC
**Description**
When attempting to initialize a WebView2 control (WinForms), a customer is getting `COMException: There is not enough space on the disk. (Exception from HRESULT: 0x80070070)`
Exception stack:
```
Source: mscorlib
Stack:
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
```

**Version**
SDK: 1.0.1343.22
Runtime: 112.0.1722.48
Framework: WinForms
OS: Windows 10 (1607)
Note: we are running as an Excel VSTO add-in

**Repro Steps**
This same code has been working fine in many environments for a long time. There could be something odd about the environment, or a change in the WebView2 RT may be the trigger.
```
         CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync (browserExeFolder, userDataFolder, options);
         await EnsureCoreWebView2Async (webView2Environment);
```
The customer claims that there is plenty of space on disk for the EBWebView folder.

**Additional context**
I got a WebView2 log from the customer.  It shows some errors (including a confusing one about DPI awareness).  Excerpts:
```
[16924:9976:0419/122024.662:WARNING:chrome_main_delegate.cc(653)] This is Chrome version 112.0.1722.48 (not a warning)
. . .
[13440:6256:0419/122025.448:VERBOSE1:variations_field_trial_creator.cc(443)] VariationsSetupComplete
[13440:6256:0419/122025.668:ERROR:win_util.cc(1496)] failed to set WebView dpi awareness of 1: The operation completed successfully. (0x0)
[16924:9976:0419/122025.715:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
. . .
[13440:4340:0419/122025.904:VERBOSE1:wtm_interface_factory.cc(85)] WTM is not used for WebView.
[13440:6256:0419/122025.919:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[13440:6256:0419/122025.919:VERBOSE1:install_util.cc(278)] No existing install found.
. . .
[13440:6256:0419/122025.948:VERBOSE1:edge_share_features.cc(58)] IsEdgeShareEntryOnToolbar returning 0
[13440:6256:0419/122025.948:ERROR:api_wrapper.cc(102)] Calling IsEnclaveTypeSupported, error code 0
[13440:6256:0419/122025.963:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(311)] MutablePO2TS::MutablePO2TS
. . .
[16924:9976:0419/122027.583:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[6704:12468:0419/122028.234:ERROR:win_util.cc(1496)] failed to set WebView dpi awareness of 1: The operation completed successfully. (0x0)

Later:
[16924:9976:0419/122126.895:VERBOSE1:update_checker.cc(345)] RequestSender failed 429
[16924:9976:0419/122126.895:VERBOSE1:component_updater_service.cc(459)] Update completed with error 5
[10708:17120:0419/122227.454:ERROR:win_util.cc(1496)] failed to set WebView dpi awareness of 1: The operation completed successfully. (0x0)
```
Note the `ERROR:win_util.cc(1496)] failed to set WebView dpi awareness of 1: The operation completed successfully. (0x0)`
Confusing:  "... failed to set .. completed successfully..."

**Comment by ShaunLoganOracle** [comment] 2023-04-19 15:20
@sln162 Thanks for the pointer, I'll take a look. (Somehow when I previously searched this forum for "80070070" I did not find that issue).

**Comment by sln162** [comment] 2023-04-19 15:24
You're welcome. I'm looking forward to you helping the team find the problem.

**Comment by ShaunLoganOracle** [comment] 2023-04-20 12:19
@champnic 
Do you want me to continue using this issue thread or would you prefer to re-open #2926 and have me chime in there?
I have a request out to our customer to get the msedge_install.log files and a directory listing of c:\Program Files (x86)\Microsoft\EdgeWebView

**Comment by champnic** [comment] 2023-04-20 18:42
We can continue to use this issue until we confirm that it's the same as #2926 and the same mitigation works if needed. You can email me the logs at `champnic@microsoft.com` if you like, when you receive them. Thanks!

**Comment by ShaunLoganOracle** [comment] 2023-04-26 11:38
@champnic Sending the files via email.

**Comment by champnic** [comment] 2023-04-26 19:19
Thanks for the logs! There are a ton of EdgeWebView runtime version folders, and it looks like the installer is failing to delete them "due to exe in use". Can you check Task Manager or Process Explorer and see if there is an app or apps that have a ton of WebView2 opened using different versions of msedgewebview2.exe? You can see version from the command-line or path to msedgewebview2.exe in Task Manager details.

**Comment by LiangTheDev** [comment] 2023-04-26 19:21
This should be the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/3344. We are working with Edge installer team on the issue. For the workaround before it is fixed, please manually delete those old versions.

**Comment by champnic** [comment] 2023-04-26 19:24
Thanks @LiangTheDev! I'll close this issue for now as a duplicate of #3344.

**Closed as not planned by champnic** 2023-04-26 19:24 UTC
Labels: bug, status-circle back

**Comment by ShaunLoganOracle** [comment] 2023-04-26 19:36
Thanks, champnic and LiangTheDev.  #3344 seems to indicate that the msedgewebview2.exe files are not actually in use, so I will hold off asking the customer to check Task Mgr etc. And, I'll watch #3344 for progress.
In the meantime, I've asked the customer to delete the old versions as a workaround.
