### ISSUE TITLE
Privacy issue: X-Edge-Shopping-Flag sent to bing.com

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#3365] opened 2023-04-06 12:20 UTC
**Description**

When navigating to bing.com with an app that uses WebView2, the headers include an unexpected `X-Edge-Shopping-Flag`, which increase the likelihood the browser can be fingerprinted. Chromium does not include this header.

**Version**
SDK: 1.0.1619-prerelease
Runtime: Evergreen (109.0.1518.52)
Framework: WPF
OS: Win11 22H2 (OS Build 22621.521)

**Repro Steps**

- Open fiddler
- Navigate to bing.com
- Observe `X-Edge-Shopping-Flag` is present in the headers

[AB#44083061](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44083061)

**Comment by ningccn** [comment] 2023-04-07 01:53
thank you for your feedback for this issue. We will investigate.

**Comment by xu-ms** [comment] 2023-04-10 02:16
@RendijsSmukulis 
Thank you for your feedback. We investigated this issue. We have identified the root cause of the problem, and we will keep you updated on any further developments. Please let us know if you have any further questions or concerns in the meantime.

**Comment by novac42** [comment] 2023-04-19 06:02
@RendijsSmukulis Update: as @xu-ms mentioned earlier we have identified the root cause, and the fix is in pipeline to remove the flag in the request header. And we just want to clarify that since shopping feature is disabled in WebView2, it doesn't provide additional information about the user's configuration, as all it does is to identify the client as Edge version >= min version that provides this header (which is already provided by the UA string). Please let us know if there's more concern. Thanks!

**Comment by champnic** [comment] 2023-04-25 00:09
We've fixed this in runtimes version 113.0.1774.17+. Thanks!

**Closed by champnic** 2023-04-25 00:09 UTC
Labels: bug, tracked
