### ISSUE TITLE
Render the browser in the Canvas and still have it interactable. WPF

### ISSUE THREAD

**Issue by syromiatnikov** [MicrosoftEdge/WebView2Feedback#672] opened 2020-11-24 15:52 UTC
I would like to have a fully interactable browser inside an animatable WPF control and be able to have other controls on top of it.
[CefSharp ](https://github.com/cefsharp/CefSharp/tree/master/CefSharp.Wpf) has such possibility.

The browser is rendered on top of the window that makes animation look strange and has crop side effect when UI is overlapping with WebView2.
![image](https://user-images.githubusercontent.com/68421285/100117626-accf7980-2e7d-11eb-915c-fcd608392885.png)

**Comment by syromiatnikov** [comment] 2020-11-24 16:02
Probably duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/356

**Comment by pagoe-msft** [comment] 2020-12-01 19:17
@syromiatnikov 

Yes, this is a duplicate of #356. Its a limitation we are aware of and are working on a fix!

**Closed** 2020-12-03 07:58 UTC
Labels: feature request

**Comment by darbid** [comment] 2020-12-07 14:13
@pagoe-msft very interesting comment "Its a limitation we are aware of and are working on a fix!"

**Especially the bit..... and are working on a fix!** Very interested to know what that means.
