### ISSUE TITLE
NuGet package breaks resource generation in WinForms C# project.

### ISSUE THREAD

**Issue by JX75** [MicrosoftEdge/WebView2Feedback#2583] opened 2022-07-09 07:44 UTC
**Description**
Installing NuGet package v1.0.1264.42 in a WinForms C# project (VS2022, Net Core 6) breaks resource generation.

**Version**
SDK: 1.0.1264.42
Runtime: ?
Framework: WinForms Core 6
OS: Win10

**Repro Steps**

- Create WinForms C# project.
- Create resources (from project properties)
- Add a string resource.
- Show project hidden files.
- => in Resources.Designer.cs, the ResourceManager getter contains this line, WFApp being the name of the project:
`global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFApp.Properties.Resources", typeof(Resources).Assembly);`
- Include NuGet package 1.0.1264.42 of WebView2
- Modify and save Resources.resx
- => in Resources.Designer.cs, the ResourceManager getter nows contains this line, without the namespace:
`global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);`
- Include previous version of NuGet package 1.0.1245.22 of WebView2
- Modify and save Resources.resx
- => Resources.Designer.cs is normal again

**Screenshots**

**Additional context**

**Comment by Danielx64** [comment] 2022-07-09 23:21
I can reproduce this myself as well. I was still able to compile my app, not sure if that intended or just lucky.

**Comment by Ropack** [comment] 2022-07-25 16:39
Also faced this issue. I can add what I found during troubleshooting - it looks like Visual Studio doesn't recognize the csproj as a regular project, when the WebView2 package is included. For any other project it shows label "Project Properties" in Properties window, however for this project it reads "SynthesizedEmpty".

**Comment by MathieuSevegny** [comment] 2022-08-15 18:52
I have the same problem with my WPF project. Also, when I create a new class, the namespace given by Visual Studio doesn't include the name of the project.

**Comment by novac42** [comment] 2023-02-16 04:45
@JX75 @Ropack @MathieuSevegny @Danielx64 Do you still see this issue with the latest SDK and Runtime?

**Comment by Danielx64** [comment] 2023-02-16 05:15
> @JX75 @Ropack @MathieuSevegny @Danielx64 Do you still see this issue with the latest SDK and Runtime?

Let me check and get back to you, the app that I am using this on is already in production

**Comment by MathieuSevegny** [comment] 2023-02-18 23:57
@novac42 I updated to the latest stable NuGet version (1.0.1587.40) and I can't seem to replicate the issue. 🤷‍♂️

**Comment by Danielx64** [comment] 2023-02-19 00:02
> @novac42 I updated to the latest stable NuGet version (1.0.1587.40) and I can't seem to replicate the issue. 🤷‍♂️

Also the case here as well

**Comment by novac42** [comment] 2023-02-20 07:20
@MathieuSevegny @Danielx64 Thanks for the update. May I close the issue for now? You can reopen it if it reoccurs.

**Comment by Danielx64** [comment] 2023-02-20 07:33
> @MathieuSevegny @Danielx64 Thanks for the update. May I close the issue for now? You can reopen it if it reoccurs. 

Sure can

**Closed** 2023-02-20 07:37 UTC
Labels: bug
