### ISSUE TITLE
SessionEnding event is raised when WebView2 is uninstalled

### ISSUE THREAD

**Issue by elad-dp** [MicrosoftEdge/WebView2Feedback#2692] opened 2022-08-17 13:06 UTC
Hi, we have C# WPF application that uses WebView2. this is the xaml of the main form:
```
<Application x:Class="MyApp.MyAppMain"
	 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	 ShutdownMode="OnExplicitShutdown" SessionEnding="OnSessionEnding"
	 Startup="OnStartUp" DispatcherUnhandledException="OnDispatcherUnhandledException">
</Application>
```
When WebView2 is uninstalled (setup.exe --uninstall --msedgewebview --system-level) then [SessionEnding](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.sessionending) event is raised with ReasonSessionEnding parameter equals to Shutdown.

Looks like a bug, isn't it?

[AB#41315575](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41315575)

**Comment by plantree** [comment] 2022-10-08 07:36
Hi @elad-dp,

Sorry for replying so late. If it is possible, could you share the demo project for reproduction?

**Comment by plantree** [comment] 2022-10-09 06:39
Hi @elad-dp,
I have figured this out. **This is a feature, not a bug.**
Inside the uninstaller, there will be a shutdown event triggered, which is used to indicate those applications who rely on WV2 runtime that they need to take some action.
Hope to solve your problem. If you have no other questions, I will close this issue.

**Comment by elad-dp** [comment] 2022-10-10 19:43
Hi, thanks for the reply. it is strange that SessionEnding event is raised - according to the description of this event: "Occurs when the user ends the Windows session by logging off or shutting down the operating system".
Uninstallation of WebView2 is not related to SessionEnding, so why is it raised? if MS wants to indicate about WebView2 uninstallation there should be a dedicated event for that, but not SessionEnding which indicates what its name implies - Windows session is ending.

**Comment by plantree** [comment] 2022-10-11 06:37
Hi @elad-dp,

Documentation about `SessionEnding` looks a bit confusing...
As for how to trigger `SessionEnding` event, you could get more information by browsing [About Restart Manager
](https://learn.microsoft.com/en-us/windows/win32/rstmgr/about-restart-manager) and [Shutting Down
](https://learn.microsoft.com/en-us/windows/win32/shutdown/shutting-down)

For your last question, it might be difficult to distinguish. 
Can I ask why you're paying attention to this?

**Comment by elad-dp** [comment] 2022-10-11 09:37
It's because we have a product that registers to SessionEnding and performs various cleanup and application shutdown operations upon this event. if a user performs WebView2 uninstallation, we get SessionEnding event and perform the cleanup and application shutdown wrongly...

**Comment by plantree** [comment] 2022-10-14 06:10
Hi @elad-dp,

In this scenario, it might be OK to perform the cleanup and shutodown, because after performing WebView2 uninstallation, the runtime doesn't exist and applications which use WebView2 couldn't work correctly as they should.

**Comment by elad-dp** [comment] 2022-10-14 08:03
well, it depends on the type of the application. for example, our application has various functionalities. even if WebView2 is uninstalled the application should not shut down. it still offers other functionalities...

**Comment by plantree** [comment] 2022-10-14 08:54
You are right. As I know, if WebView2 is uninstalled, the better choice might be restarting the application and changing to a mode without WebView2, instead of running incorrectly。

**Comment by elad-dp** [comment] 2022-10-17 18:55
Hi @plantree, our application should not shut down in case of WebView2 uninstallation. The SessionEnding event should not be raised in that case since it causes our application to shut down.

**Comment by plantree** [comment] 2022-10-20 07:00
Hi @elad-dp,

Could you explain why the application should not shutdown in case of WebView2 uninstallation?
As I understand, if we don't have runtime, the application could not run correctly.

**Comment by elad-dp** [comment] 2022-10-20 07:04
Our application has fallback to the older WebBrowser Control, so even if WebView2 is not available the application functions correctly - it should not shut down in any case...

**Comment by plantree** [comment] 2022-10-24 03:19
Hi @elad-dp, 

It means we application has two modes, and it is not entirely dependent on WebView2. 

Perhaps we could **detect the availablility of WebView2 while initialization** and choose the mode, follow this link: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed.

When we receive the event of `SessionEnding`, the better choice might be trying to restart and change the mode.

BTW, this event could be canceled, follow this link: https://learn.microsoft.com/en-us/dotnet/api/system.windows.application.sessionending?view=windowsdesktop-6.0.

> You can detect when a session ends by handling the [SessionEnding](https://learn.microsoft.com/en-us/dotnet/api/system.windows.application.sessionending?view=windowsdesktop-6.0) event. If an application needs to prevent the session from ending, the [SessionEndingCancelEventArgs](https://learn.microsoft.com/en-us/dotnet/api/system.windows.sessionendingcanceleventargs?view=windowsdesktop-6.0) argument that is passed to the event handler exposes the [Cancel](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?view=windowsdesktop-6.0) that you set to true (the default value is false).

**Comment by elad-dp** [comment] 2022-10-24 06:58
what do you mean "the better choice might be trying to restart"? - SessionEnding is called when user session ends (user logs off). in response to SessionEnding our application cleans stuff and shuts down. why would the application restart in case the user logs off?

This is the point of the discussion here - SessionEnding event should not be raised when WebView2 is uninstalled. it should be raised only when the user session is ending, exactly as its name implies. not in any other unrelated scenario. otherwise it's obviously a bug that should be fixed by MS...

**Comment by plantree** [comment] 2022-10-24 08:46
Sorry, I may not have made it clear.

In my opinion, we have two differences:
1. Should the `SessionEnding` event be raised during WebView2 is uninstalled?
2. What should to be done if the `SessionEnding` event is raised?

For the first question, the current solution may not be easy to change. You can read this documentation about [Restart Manager](https://learn.microsoft.com/en-us/windows/win32/rstmgr/restart-manager-portal) to learn more. Also, many other applications which depend on WebView2 may need this mechanism to run correctly.

For the second, I saw the uninstaller will try to restart apps that were shutdown. Perhaps we don't need to differential between uninstall and system shutdown?

**Closed** 2022-11-21 22:42 UTC
