### ISSUE TITLE
[WinUI3][C++/WinRT] WebView2 menu issues

### ISSUE THREAD

**Issue by IVVOVVI** [MicrosoftEdge/WebView2Feedback#2351] opened 2022-04-09 11:09 UTC
### Describe the bug

After opening a PDF file with WebView2, the controlbar button menu and context menu don't close after losing focus. The menu cannot be closed by clicking the pdf content area, controlbar buttons, or dragging the scrollbar. The menu can only be closed by clicking the menu item, or by deactivating the window (make the window lose focus).

### Steps to reproduce the bug

1. Create a blank C++/WinRT WinUI3 project.

2. Xaml

`<WebView2 Source="d:\test.pdf"/>`
 
### NuGet package version

WinUI 3 - Windows App SDK 1.0.2

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

[AB#39070699](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39070699)

**Comment by champnic** [comment] 2022-04-12 23:08
Hey @IVVOVVI - When you say "controlbar button menu" do you mean the toolbar at the top of the page? I believe it's By Design that it stays visible. What's the behavior you see if you navigate to your test pdf in the Microsoft Edge browser?

**Comment by IVVOVVI** [comment] 2022-04-14 03:06
Yes and no, it's the toolbar at the top, but not the bar, I mean the popup menu of the buttons, and the context menu (right click). Microsoft Edge browser doesn't have this issue.

**Comment by IVVOVVI** [comment] 2022-04-14 07:45
![screenshot](https://user-images.githubusercontent.com/50931497/163338439-84677f26-c3a8-46e6-9231-87080f58f642.gif)

**Comment by IVVOVVI** [comment] 2022-04-14 07:49
As you can see, it's not just that it can't auto hide, there are also some issues with the location of menu and tooltip.

**Comment by champnic** [comment] 2022-04-14 21:06
Thanks for that gif, it really demonstrates the issue well. I've opened this as a bug on our backlog to dig into.

**Comment by johna-ms** [comment] 2022-06-10 22:23
I'm resolving this as a duplicate of #2290. Fix for that is pending

**Closed by johna-ms** 2022-06-10 22:23 UTC
Labels: bug, tracked
