### ISSUE TITLE
UWP app crashes on pressing F12 twice

### ISSUE THREAD

**Issue by Take-A-Byte** [MicrosoftEdge/WebView2Feedback#3198] opened 2023-02-07 12:09 UTC
**Description**
UWP app crashes on pressing F12 twice in Debug mode

**Version**
SDK: 1.0.1518.46
Framework: UWP
OS: Win11

**Repro Steps**
1. Create a minimalistic UWP app with WebView2 (can use[sample app](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp) as well).
2. Run the app in **Debug mode** and press F12 twice

Based on the information on - https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opendevtoolswindow?view=webview2-dotnet-1.0.1518.46
![image](https://user-images.githubusercontent.com/29909785/217241825-1ac1969a-a682-45a6-b511-9f58494168ad.png)

Expected result - Dev tools are opened on first press and second press does nothing
Actual result - Dev tools are opened on first press and app crashes on second press 

[AB#43383604](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43383604)

**Comment by novac42** [comment] 2023-02-09 11:16
Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by champnic** [comment] 2023-02-28 23:06
Hey @Take-A-Byte - This behavior is By Design. F12 can invoke the native debugger when using Visual Studio. This is not due to WebView2. We have this documented here: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio#open-devtools-using-an-approach-other-than-f12

**Closed by champnic** 2023-02-28 23:06 UTC
Labels: bug, tracked
