### ISSUE TITLE
Setting "CreationProperties" property give exception

### ISSUE THREAD

**Issue by haiduong87** [MicrosoftEdge/WebView2Feedback#2804] opened 2022-09-16 10:09 UTC
**Description**
I used "CreationProperties" to set "UserDataFolder" in version "1.0.902.49".
After upgrading to latest version "1.0.1343.22", I can't use it.
       `   at Microsoft.Web.WebView2.WinForms.CoreWebView2CreationProperties.CreateEnvironmentAsync()
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DefaultCreation1343_22.Form1.<Form1_Load>d__1.MoveNext() in C:\Users\duongngh\source\repos\DefaultCreation1343_22\DefaultCreation1343_22\Form1.cs:line 22`

**Version**
SDK: 1.0.1343.22
Runtime: WebView2 Runtime 105.0.1343.42
Framework: WinForms (4.6.2)
OS: Win 11 21H2 (OS BUILD 22000.978)

**Repro Steps**
- Create a "MyWebview2" class extend "Webview2"
- In the constructor assign the "CreationProperties" property (to set "UserDataFolder")
- The webview won't work anymore
-- If we don't have a EnsureCoreWebView2Async it won't show exception (but it doesn't show anything)
-- If we add EnsureCoreWebView2Async it will give above exception

Screenshot: ![image](https://user-images.githubusercontent.com/22165935/190614538-3d3f81f9-8503-40c3-825a-233fdf4bb796.png)
SourceCode: [DefaultCreation1343_22.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9582962/DefaultCreation1343_22.zip)

Thanks,

Duong Nguyen

[AB#41393357](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41393357)

**Comment by Worldwidebrine** [comment] 2022-09-16 15:02
Me too
```cs
using System;
using System.Windows.Forms;
using Microsoft.Web.WebView2.WinForms;
using System.Drawing;

namespace Main
{
    public class Cls
    {
        [STAThread]
        public static void Main()
        {
            Form f = new Form
            {
                Size = new Size(500, 500)
            };


            WebView2 webview = new WebView2
            {
                // CreationProperties = new CoreWebView2CreationProperties(),
                Location = new Point(20, 20),
                Size = new Size(400, 400),
                Source = new Uri("https://www.bing.com")
            };
            var promise = webview.EnsureCoreWebView2Async().GetAwaiter();
            promise.OnCompleted(() =>
            {
                try
                {
                    promise.GetResult();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            });

            f.Controls.Add(webview);
            f.ShowDialog();
        }
    }
}
```

**Comment by Worldwidebrine** [comment] 2022-09-16 16:42
Workaround:
Use `webview2.EnsureCoreWebView2Async(env);` to set the directory **right after** `webview2 = new WebView2();`.
You must await `env` **before** `new WebView2()`.

Example:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2435#issuecomment-1249550167

**Comment by champnic** [comment] 2022-09-16 22:04
It's possible these are separate issues. @Worldwidebrine yours looks like an expected issue when setting Source (which does implicit initialization) and then calling Ensure (which tries to do initialization again).

@haiduong87 What runtime version are you using? If you try using a preview version, do you still see this failure?

**Comment by haiduong87** [comment] 2022-09-17 01:31
@champnic I'm using WebView2 Runtime 105.0.1343.42
I've just tried with beta and canary (I uninstalled the runtime) and the problem is still there

**Comment by Worldwidebrine** [comment] 2022-09-18 16:51
> It's possible these are separate issues. @Worldwidebrine yours looks like an expected issue when setting Source (which does implicit initialization) and then calling Ensure (which tries to do initialization again).
No [that](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2804#issuecomment-1249572696)'s the workaround.
[This](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2804#issuecomment-1249478318) is the same issue with minimized reproduce

**Comment by champnic** [comment] 2022-09-19 18:59
Thanks for the info. We'll dig into this. It seems there may have been a binary incompatibility introduced with a new optional param in the function.

**Comment by champnic** [comment] 2022-11-21 23:33
This is fixed in the latest SDK releases. Thanks!

**Closed by champnic** 2022-11-21 23:33 UTC
Labels: bug, tracked
