### ISSUE TITLE
[Problem/Bug]: New windows open when it shouldn't

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#4224] opened 2023-12-11 01:52 UTC
### What happened?

I'm not sure what happens, we been running the same custom built app for months with no code changes and now our logic that tells webview2 to ignore any requests to open a new browser window isn't working.

```
		private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
		{
			if (e.Uri.Contains("powerapps"))
			{
				e.NewWindow = WebView.CoreWebView2;
			}
			else
			{
				e.Handled = false;
			}
		}

```

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.61

### SDK Version

1.0.2151.40

### Framework

WPF

### Operating System

Windows 10

### Repro steps

Use the following code (change URL etc as need be:

```
		private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
		{
			if (e.Uri.Contains("powerapps"))
			{
				e.NewWindow = WebView.CoreWebView2;
			}
			else
			{
				e.Handled = false;
			}
		}

```

And attach it to the `WebView.CoreWebView2.NewWindowRequested` event.

### Repros in Edge Browser

Not Applicable

### Regression

Regression in newer Runtime

### Last working version (if regression)

Runtime 119.0.2151.97 (I think)

**Comment by litski18** [comment] 2023-12-12 04:21
We are also facing the same issue. Please help.

**Comment by victorhuangwq** [comment] 2023-12-12 18:38
We are currently looking into this issue

**Comment by Danielx64** [comment] 2023-12-12 18:41
Thank you :)

**Comment by Danielx64** [comment] 2023-12-14 13:04
@victorhuangwq is this considered a regression or is it still being looked into?

**Comment by Danielx64** [comment] 2023-12-18 00:26
@victorhuangwq just reporting that this is still happening on runtime 120.0.2210.77

**Comment by iGThomas** [comment] 2023-12-19 10:26
Same issue here suddenly due to some update on Edge since 120.0.2210.61 the new window events aren't cancelled with e.NewWindow = webView21.CoreWebView2;. I've been running the code for 2 years already without issues until now.

**Comment by Danielx64** [comment] 2023-12-19 10:48
For now, I have been forced to turn my 2mb install size into close to 500mb install while I include the runtime to fix the issue.

**Comment by monica-ch** [comment] 2024-01-05 21:03
Closing the issue as duplicate of #4250

**Comment by yildirimcagri-msft** [comment] 2024-01-06 13:41
Hi, From the bug description, this seems to be a distinct issue from the one that was fixed. Could you explain what you expected the behavior to be here? `Handled` set to false would mean that the app is not handling the event and [the default behavior of opening a popup window should apply](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.handled?view=webview2-dotnet-1.0.2210.55#microsoft-web-webview2-core-corewebview2newwindowrequestedeventargs-handled). If you'd like to block the webview from opening new windows you would need to set the Handled property to `true`

**Comment by yildirimcagri-msft** [comment] 2024-01-06 13:54
From the issue description, this may potentially be a distinct issue from #4250 as IIUC you are expecting WebView to ignore the NewWindowRequest with this code snippet so I'm reopening this issue to clarify.

In the snippet, if the URL is a specific URL(contains `powerapps`) then it seems you are setting the NewWindow to be the origin WebView, which would run into the issue manifested in #4250 (and would be fixed) and the new window request would simply be a navigation of the origin WebView. 

However, in other cases, you are setting `Handled` to false and it sounds like you are expecting that this should cause WebView to ignore the request to new window. When `Handled` set to false, this would mean that the app is not handling the event and [the default behavior of opening a popup window should apply](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.handled?view=webview2-dotnet-1.0.2210.55#microsoft-web-webview2-core-corewebview2newwindowrequestedeventargs-handled). If you'd like to block the webview from opening new windows you would actually need to set the Handled property to `true`.  If it was not opening the window before Edge 119 with this same code, it would mean the old behavior was wrong.

Does this match your expectation?

**Comment by Danielx64** [comment] 2024-01-15 03:06
@yildirimcagri-msft I'm back on deck after having 3 weeks off.

So in a nutshell if the url contains powerapps I do not want a new window to open while for all other requests, open a new window. 

I just checked with runtime 120.0.2210.133 and it's working the way it should now.

**Closed** 2024-01-27 04:02 UTC
Labels: bug
