### ISSUE TITLE
Old file explorer options2

### ISSUE THREAD

**Issue by LeoGlobe** [MicrosoftEdge/WebView2Feedback#1528] opened 2021-07-14 04:35 UTC
Hey chamnic,

Thanks for responding.
Maybe my reguest will be clearer with the picture.

Regards Leo
![IE11 versus EDGE](https://user-images.githubusercontent.com/87391457/125558323-b2936a92-8353-4848-993d-0c716fda8175.JPG)

Can the functionality of the old file explorer (IE11) come back within the webview2.
We now miss:

The options to preview the icons.
The right click functions to be able to copy, paste, rename, etc.
Compact display.
Options to customize columns.
Clicking on files without downloading them directly. 
Typing letters to jump to the first item starting with the typed letter.

_Originally posted by @LeoGlobe in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1527#issuecomment-879564592_

**Comment by champnic** [comment] 2021-07-14 16:56
Closing as dupe of #1527.

**Closed by champnic** 2021-07-14 16:56 UTC
