### ISSUE TITLE
WebView2 becomes transparent after minimizing then activating in some local machines and VMs

### ISSUE THREAD

**Issue by orrindeng** [MicrosoftEdge/WebView2Feedback#1130] opened 2021-03-30 02:33 UTC
**Description**
We found in some devices, the WebView2 content will became empty(after deeper investigating, it actually shows the control behind WebView2) when you minimize and then activate the window. The content renders after mouse moves on the WebView2 control. Please see the gif below.

![WebView2Issue1](https://user-images.githubusercontent.com/25047407/112923468-f0463700-9140-11eb-854e-725b714be9ee.gif)

Their devices are some old devices with CPU i7-2600/i7-3632QM(all intel 2-gen or 3-gen core CPU) and 16G memory without dependent graphic cards (means they all uses integrated graphic cards like Intel HD Graphics 4000). 

But in my device, the issue doesn't happen. My device has CPU i7-7700HQ and 16G memory with independent Nvidia graphic card.

I guess the difference may be the graphic card's performance. But we try Microsoft Edge it doesn't have this issue. So would please tell us how to avoid this issue?

I have seen this issue #1115 , But this issue not only happens on our RDP environment but also in our local machines.

**Version**
SDK: 1.0.790-prerelease
Runtime: 89.0.774.45
Framework: .NET Framework 4.7.2
OS: both Win10 and Win7

[AB#32335798](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32335798)

**Comment by champnic** [comment] 2021-04-02 00:50
Thanks for the bug report @orrindeng! I've added it to our backlog to take a look.

**Comment by littyjoseph** [comment] 2021-05-07 11:20
Hi,
Can you please let us know the expected date of this fix as it is blocking use of webview2.

**Comment by Florin-blz** [comment] 2021-05-07 16:48
Hi,
Yes, can you let us know the expected date? the issue is related with the runtime or the SDK itself ? if it's the runtime I believe it should update itself if using the evergreen one, but if it's in the SDK, an update of the app is required and for that we require an expected date to arrange a "deployment" for the app affected by this, as it's blocking and confusing a lot of users with this issue.

**Comment by gnanamu** [comment] 2021-06-01 13:15
This is blocker for us also. Problem is for development we all use VMs, we cannot release if we see this issue in developemtn and testing. We do not have vGup in all the VMs. Looks like problem is when WebView2 is running under software rendering this occurring.  Though our application is medical Imaging application, it is designed to work well with software rendering. We cannot put restrictions on Gpu in our product system requirements. Customers are moving towards VMs and Citrix. Since Edge Browser does not have symptoms of this issue , this should be problem with only WebView2 control. For us it is critical to get it fixed. For our internal testing currently I have applied a workaround to set focus the WebView2 control when application is maximized. 

`	private void Control_Loaded(object sender, RoutedEventArgs e)
        {
            var window = Window.GetWindow(this);
            if (window == null)
                return;
            window.StateChanged += Window_StateChanged;
        }

        private void Window_StateChanged(object sender, EventArgs e)
        {
            var wind = (Window)sender;
            if (wind.WindowState == WindowState.Normal || wind.WindowState == WindowState.Maximized)
            {
                ActivateWebView();
            }

        }

        private void ActivateWebView()
        {
            Task.Factory.StartNew(() =>
            {
                try
                {
                    System.Threading.Thread.Sleep(1000);

                    this.Dispatcher.InvokeAsync(() =>
                    {

                        _webView2.Focus();

                        Log.Information(ModuleType.StudyList, "Activating WebView2 window..");

                    }, DispatcherPriority.Background);

                }
                catch
                { }
            });

        }`

**Comment by gnanamu** [comment] 2021-06-01 13:17
Since issue is already been taken into work, is it possible to tell the expected date when it will be fixed?

**Comment by champnic** [comment] 2021-06-02 06:10
We believe this is a runtime issue. We haven't had time to specifically look at this issue, but I'll bump the priority as it's clearly pretty important/blocking. We did recently checkin a change that affected software rendering - can you let me know what WebView2 runtime version you are using on the machine/VM where you are seeing this problem?

**Comment by littyjoseph** [comment] 2021-06-02 06:23
Hi All,

We are not seeing this issue now. We are also not sure how this got fixed. May be windows auto update fixed this issue.

**Comment by gnanamu** [comment] 2021-06-03 10:44
@champnic  currently we have integrated 89.0.774.48 into our product where we see the issue. Now I have tried to reproduce the issue with 90.0.818.51 and 90.0.818.62. 
90.0.818.51 is still has issue ,  I could not reproduce the issue in 90.0.818.62. Iooks like it is fixed in 90.0.818.62.  I need to integrate this Runtime with our product package to fully test in all environment . After that I can confirm it is problem in all the VMs.

**Comment by champnic** [comment] 2021-06-03 18:19
This is great to hear, and suggests the fix we did for the other issue is likely also fixing this issue.

**Comment by champnic** [comment] 2021-08-06 23:28
We are still able to repro some behavior like this on our end, so we're keeping this bug open to continue investigation.

**Comment by champnic** [comment] 2023-06-07 23:04
We believe the only remaining issue here was happening on Windows 7, which we no longer support. If you are still seeing this issue on Windows 10 or 11 please let me know and I'll reactivate. Thanks!

**Closed by champnic** 2023-06-07 23:04 UTC
Labels: bug, tracked
