### ISSUE TITLE
Mouse gestures are enabled by default and seriously interfere with business logic

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#3737] opened 2023-08-24 09:08 UTC
**Description**

We found that when WebView2 was upgraded to version 116.0.1938.54 from August 23. We found that this version turned on mouse gestures by default.

However, mouse gestures seriously interfered with our business logic, causing our related businesses to fail to work. We need to fix this problem urgently and urgently need help. we want to know:
**How to turn off mouse gestures?**

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/48123998/15131127-c4ba-4a6e-b1f9-5115a16f8531)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/48123998/ca915a4c-0c3e-475b-a010-3c36c5d3ace1)

[AB#46142844](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46142844)

**Comment by champnic** [comment] 2023-08-24 18:03
Hey @ztextplus - Could you provide us with a bit more info about your business logic and how this is interfering? For example, where do you expect to be handling the mouse input - on the web content, or in the host app? Any information about what SDK version, UI framework, etc. about your app would also be helpful to know.

**Comment by champnic** [comment] 2023-08-24 18:31
You should be able to turn this off in you app by setting additional browser arguments:
`--disable-features=msEdgeMouseGestureSupported,msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN`
Can you give that a try?

**Comment by ztextplus** [comment] 2023-08-25 02:51
@champnic  @novac42  @liminzhu  @peiche-jessica 

We have some drawing applications, which are a bit like whiteboards and figma applications. When users use the mouse to draw, the mouse operation is interpreted as mouse gestures, which seriously interferes with user operations.

Even though we can use the command line parameters` --disable-features=msEdgeMouseGestureSupported, msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN` to turn off the mouse gestures, but it will only take effect in the latest version we push to users. We have many users who should have some reasons ( Such as group policy control) will stay in the historical version client, which is inconvenient for them to use.

I don’t think the need for mouse gestures is so obvious in WebView2. Can we keep the status quo and make this feature off by default, and it can only be turned on by the user calling a certain setting function.

**Comment by champnic** [comment] 2023-08-25 03:19
We're working on disabling this feature for WebView2 by default. It will probably be available in the next release sometime next week. It will be available in a Canary build tomorrow for testing.

1. Are any of the broken experiences available to test through the browser? Are you able to share a link? I'm wondering if those will be broken in the regular Edge browser now, which will have gestures enabled by default.
2. Just confirming, but is the drawing action done using the right mouse button? Left mouse button shouldn't initiate a gesture.

**Comment by ztextplus** [comment] 2023-08-25 03:44
@champnic 
Sorry, we are currently embedding webview2 in the client, so we cannot share a link.

We have just confirmed that when we are drawing, we press and hold the right button to drag a shape to achieve the purpose of moving the shape, and figma does the same. The result is that the drag operation of our right mouse button conflicts with the mouse gesture of webview2.

**Comment by Aostas** [comment] 2023-08-26 02:01
`--disable-features=msEdgeMouseGestureSupported, msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN` is not working for me.
I tried pass these args to edge's shortcut, tauri's additionalBrowserArgs option, but either works.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/1fe86945-4636-48c1-a64f-aa967544c770)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/f34aa682-9c09-4599-9b5e-addd3a2fd46e)
I tried turn off the "Microsoft Edge Mouse Gesture(#edge-mouse-gesture)" flag and restart the browser, not work.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/31f7f03f-b3ae-4fa8-b058-3a3857057ba9)
The only way to disable this feature is turn off `Enable Mouse Gesture` option in edge://settings/mouseGesture.

My application is based on tauri and use three.js to show and operate point cloud, the left button controls rotation, and the right controls movement, the mouse gesture feature must be off.

**Comment by peiche-jessica** [comment] 2023-08-29 15:43
Hi @Aostas, if your app is using WebView2, the additional browser arguments will need to be passed to the WebView2 Runtime, not the Edge Browser, for them to be effective. You can configure the additional browser arguments using [environment options](https://learn.microsoft.com/microsoft-edge/webview2/reference/win32/webview2-idl#createcorewebview2environmentwithoptions), environment variable, or registry key.

Also, could you please confirm whether passing `--disable-features=msEdgeMouseGestureSupported,msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN` to the _browser_ is sufficient for turning the feature off in the _browser_? Or do you still need to go to `edge://settings/mouseGesture` in the browser to turn it off?

**Comment by Aostas** [comment] 2023-08-29 17:17
I tired pass the args to the WebView2 Runtime on my tauri app, but not work:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/fe47cfeb-ad3d-425c-a5dc-5290c2e21012)

Then I tried pass the args to browser to confirm if it was a tauri issue.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/e6c400cc-5919-49a7-9a18-c0382591e683)
I don't know if this is the correct way to pass it to the browser. The feature can not be turned off by these args.

If I want to turn it off in the browser, I need to go to edge://settings/mouseGesture to turn it off.

If I want to turn it off in my tauri app, I can only wait for this issue to be fixed... https://github.com/tauri-apps/tauri/issues/7692

**Comment by peiche-jessica** [comment] 2023-08-30 21:30
I'm not sure how tauri handles the additionalBrowserArguments from users, but could you try setting the `WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS` environment variable on your machine?

<img width="326" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/55165503/e9bf7276-ff2d-404e-b20f-7af8768a2d88">

**Comment by Aostas** [comment] 2023-08-31 01:53
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31911231/a7609b58-ec9b-44ea-9a60-51c1a21f4870)
Not work for the Edge or my tauri app. Does this variable effective for the Edge browser? Maybe the setting in edge://settings/mouseGesture will overwrite the additional arguments.

The tauri pass additionalBrowserArgs directly to webview2.https://tauri.app/v1/api/config#windowconfig.additionalbrowserargs

**Comment by GalensGan** [comment] 2023-08-31 01:57
@champnic I also encountered the same problem. I tried setting AdditionalBrowserArguments in the code

```
var env = await CoreWebView2Environment.CreateAsync(null,null,new CoreWebView2EnvironmentOptions()
 {
    AdditionalBrowserArguments = "--disable-features=msEdgeMouseGestureSupported,msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN"
    });        
 await webView2.EnsureCoreWebView2Async(env);
```

and environment variables, but I couldn't disable the mouse gesture function. I am looking forward to an official solution.

**Comment by Aostas** [comment] 2023-08-31 02:18
Actually, I don't care how to disable the feature temporary, this feature should be disabed by default.
Enable this feature by default for Edge browser is fine.
But for webview2, Every single application based on it will be effected or even be destoryed. 
I can change right click to Ctrl+left click for drag, but this will seriously affect the user experience.

**Comment by dev-3mensio** [comment] 2023-08-31 07:29
Just wanted to chime in that this has broken our app as well. It turns out it is only our chinese users that run into this, the rest of the world appears unaffected. For graphics applications, it is quite common to attach features to the right mouse buttons. Of course webview2 is my primary concern, but it really should be possible to disable from javascript in a web page.

**Comment by peiche-jessica** [comment] 2023-08-31 15:25
@Aostas @GalensGan @dev-3mensio I understand and we are working on disabling this feature for WebView2 by default. The change is available in Canary 118.0.2061.0 and will be in the next Stable 116.0.1938.X (X is TBD but is scheduled for full rollout at the end of week). Could you please confirm the fix in Canary is effective for you? Related instruction about testing using a preview channel can be found [here](https://learn.microsoft.com/microsoft-edge/webview2/how-to/set-preview-channel).

**Comment by dev-3mensio** [comment] 2023-08-31 20:15
Thanks @peiche-jessica. Ideally I would like to reproduce on our own test infrastructure, but we are not seeing it there currently (we're in Europe). Are the gestures hardcoded in a special build for china? Or are they switched on based on the configured locale? 
I can only verify that it is removed after I can reproduce it here.

**Comment by GalensGan** [comment] 2023-09-01 00:46
> 

Yes,  After I installed Edge-Canary 118.0.2073.0, the mouse gesture are disabled，it works well on my computer，thanks!

**Comment by peiche-jessica** [comment] 2023-09-02 01:16
@dev-3mensio The switch `kEdgeMouseGestureDisabledInCN` was disabled by default, which resulted in the Mouse Gesture effectively being turned on by default in CN locale. The change, which disables Mouse Gesture in WebView2, should be in the latest WebView2 Runtime 116.0.1938.69 and such update is being rolled out at the moment.

@GalensGan Thanks for confirming!

**Closed** 2023-09-07 23:04 UTC
Labels: bug, tracked

**Comment by wang-345** [comment] 2024-02-26 08:31
Mouse gestures are enabled by default again.

**Comment by wang-345** [comment] 2024-02-26 08:48
@peiche-jessica @champnic   Mouse gestures are enabled by default again on latest edge. Does the default change again?

OS: windows 10
browser: edge canary 124.0.2424.0

**Comment by wang-345** [comment] 2024-02-27 02:43
@champnic using the Microsoft Edge browser

**Comment by champnic** [comment] 2024-02-27 23:35
@wang-345 That's out of scope for this WebView2 feeedback repo. You should be able to change the mouse gesture settings for Edge here:
edge://settings/mouseGesture
