### ISSUE TITLE
Webview PDF view is blurred when scrolling horizontally

### ISSUE THREAD

**Issue by rozeboosje** [MicrosoftEdge/WebView2Feedback#2306] opened 2022-03-23 16:56 UTC
**Description**
We're using a WebView2 in a "Previewer" in which the user can "preview" documents. We convert documents to PDF and load them into the previewer. As we need space for a list on the left, and having the document zoomed out too much makes the text illegible the zoom level is such that not all of the document will fit horizontally, causing a horizontal scroll bar to appear. When the user scrolls to the right to see the right hand side of the document it sometimes comes out all blurry.

**Version**
SDK: 1.0.1150.38
Runtime: 
![image](https://user-images.githubusercontent.com/223879/159755066-858ea216-1fa5-4ede-91cb-94ef7f680901.png)

Framework: WPF, .NET Framework 4.8
OS: Observed in Windows 10 as well as Windows 11

**Repro Steps**
Load a PDF into a WebView2 and make sure it's zoomed to a level where the document is wider than the available viewing area. Scroll to the right to see the right hand side of the document. Sometimes - not always - the part of the document that scrolls into view is blurry.

![BlurryPreview](https://user-images.githubusercontent.com/223879/159754185-de99e077-6311-49a9-9ad0-80bf786fa6b0.gif)

[AB#38653264](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38653264)

**Comment by champnic** [comment] 2022-03-24 00:27
Hey @rozeboosje - thanks for the bug report, and sorry you are running into this. I see a similar behavior in the browser with blurry text when scrolling into view, although it very quickly resolves into the correct rendered result. I wonder if something is blocking a needed call to Paint. I've added this bug to our backlog to take a closer look.

**Comment by rozeboosje** [comment] 2022-03-24 09:23
Thank you @champnic - as I show in the gif there is a very easy workaround for this anyway...

**Comment by rozeboosje** [comment] 2022-04-14 15:08
Hello @champnic 

Ok not sure whether I'm imagining it or whether I have just not come across it but recently through Windows Updates I appear to have been updated to Microsoft Edge 100.0.1185.39 and Microsoft Edge WebView2 Runtime 100.0.1185.39 and so far I have not seen the blurring happening. Do you know whether any changes were made in this area?

**Comment by rozeboosje** [comment] 2022-04-14 15:27
(also: nuGet package 1.0.1185.39)

**Comment by champnic** [comment] 2022-04-14 21:30
It's possible this got resolved. Apparently it was an issue also affecting the PDF experience in the browser and was a relatively high priority, so may have gotten fixed recently. I'll see what I can find out.

**Comment by animalis007** [comment] 2022-05-16 14:30
This is happening to us on WebView2 runtime 101.0.1210.47. Workaround of clicking Fit to Page seems to resolve the issue, but asking a user to have to click that every time they view a PDF seems a bit of an ask.

**Comment by rozeboosje** [comment] 2022-05-17 11:40
I'm on Edge and WebView2 Runtime both 101.0.1210.47 and I haven't seen this happening yet. Well, to be precise, once I noticed blurring while scrolling through a large PDF *but* it resolved to normal as soon as I stopped scrolling.

@champnic any chance something may have regressed?

**Comment by animalis007** [comment] 2022-05-17 15:59
Some more information from my side, in code we are using Microsoft.Web.WebView2 package 1.0.1185.39. Also, the web page is accessing the PDF via byte[]/FileStreamResult in html <object> instead of directly accessing a PDF file. I know this may be less common. 

I am able to reproduce the issue from our web app previewing with Edge Beta or Canary. Normal MS Edge previews fine.
`<object style="object-fit: fill; height: 806.8px;" data="/Communications/Management/GetDocument?cacheKey=EfileStoreId_10268231&amp;documentIndex=1" type="application/pdf">PDF Content</object>`

**Comment by rozeboosje** [comment] 2022-05-17 16:08
And I am seeing something suspicious in https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes

In the release notes for "1.0.1248-prerelease"

"Fixed an issue where WebView2 content can become blurry when moving between monitors with different scaling."

I suspect that in the process of fixing that, they may have regressed in other issues relating to "blurry content"

**Comment by champnic** [comment] 2022-05-17 20:11
I'll reach out to the PDF team with these updated details. Sorry you are hitting this again!

> I suspect that in the process of fixing that, they may have regressed in other issues relating to "blurry content"

Good eye, but I think these are separate issues. The PDF scrolling blurriness will be handled completely within the PDF control, whereas this was a general problem with DPI and was only seen when dragging between monitors.

> I am able to reproduce the issue from our web app previewing with Edge Beta or Canary. Normal MS Edge previews fine.

@animalis007 If I understand correctly, you are only seeing this issue when the PDF is displayed in a WebView2? When you run the same code in the same version browser it appears fine?

**Comment by animalis007** [comment] 2022-05-17 21:30
@champnic I encounter the issue both within WebView2 (from a Winforms app) and hitting our web page directly with Edge Beta or Edge Canary. No issue encountered with plan Edge. Our users can only hit the web page from WebView2. 

However, if I navigate directly to the PDF in Edge Beta or Canary it displays fine, its only blurry when viewed embedded within the web page. Users do not have access to the original PDFs as they are on a separate server. Due to this we read the file bytes and deliver within the web page via a FileStreamResult to the html object element.

**Comment by rozeboosje** [comment] 2022-05-18 07:52
In our case it's in a WPF form. The PDF is a URL generated using an SAS from Azure Blob Storage

**Comment by animalis007** [comment] 2022-05-19 15:53
@rozeboosje do you happen to know what PDF version you are seeing this in? I found an interesting correlation this morning where PDFs were more likey to be blurry only scroll if they were version 1.4 compared to version 1.7
![image](https://user-images.githubusercontent.com/105655688/169343861-5937314e-f7e8-43f6-b2f1-30708a394b68.png)

**Comment by rozeboosje** [comment] 2022-05-25 14:33
Just wondering what the story is..... I note that my Edge and Webview2 Runtime are now on 101.0.1210.53

**Comment by rozeboosje** [comment] 2022-05-25 18:03
@champnic I'm not sure I'd be much use here right now. I haven't been able to reproduce (persistent) blur issues on my dev machine. What I *can* say is that we got a few complaints about blurring last week when client PCs were on Edge 101.0.1210.47, but this week I haven't heard of anyone complaining and it appears Edge and the WebView2 runtime are now on 101.0.1210.53. It could be a coincidence or maybe our friends on the Edge and WebView2 Runtime teams fixed something?

**Comment by rozeboosje** [comment] 2022-06-16 08:30
@champnic 

Hello Nic,

We still get some of our clients complaining about blurry previews. Now these are on a build that is now several weeks old, so they are stuck on a previous version of the nuGet package. Not too much I can do about that; with our next official release they'll get the most current package there will be at that time.

That aside....

I just checked my own machine and made an interesting observation. My Microsoft Edge is up to date on 102.0.1245.41, but my Microsoft Edge WebView2 Runtime is on 101.0.1210.53 .... Why is that? I installed the evergreen version?

**Comment by mikeduglas** [comment] 2022-06-16 09:16
I noticed the same: MS Edge 102.0.1245, WebView2 runtime 101.0.1210.53
until I manually upgraded it.

--
Mike


чт, 16 июн. 2022 г. в 11:30, rozeboosje ***@***.***>:

**Comment by rozeboosje** [comment] 2022-06-16 09:31
Yeah I'd be reluctant to manually upgrade it as I would expect the "Evergreen" version to take care of that; if it doesn't, I must assume that there is a reason for that, maybe that its developers are not happy to release it "into the wild" yet?

**Comment by rozeboosje** [comment] 2022-06-17 14:58
Ok... today both my Edge and my WebView2 Runtime appear to have been updated to 102.0.1245.44

@champnic do you know whether those builds include anything specific to deal with this issue?

**Comment by mikeduglas** [comment] 2022-06-18 08:21
@rozeboosje 
I don't see 102.0.45.44 in the list of Evergreen available versions:
![image](https://user-images.githubusercontent.com/12225093/174429379-7325a72f-6011-46dd-b1b3-4d0dddd85688.png)

**Comment by rozeboosje** [comment] 2022-06-18 08:40
I'm not entirely sure how it happened... we recently moved everyone to Azure AD. When the IT guy did my machine a lot of stuff stopped working. I reset my Windows 11. I was reinstalling the software that had been removed during the reset and that's when I noticed the new versions on my machine. Not a sequence of events that's easy or even desirable to reproduce

**Comment by rozeboosje** [comment] 2022-06-23 15:41
@champnic Ok I can now confirm that there are still issues with blur. Microsoft.Web.WebView2 nuget package build 1.0.1245.22
Microsoft Edge and Microsoft Edge WebView2 Runtime are both on 102.0.1245.44
![StillBlurryAfterAllThisTime](https://user-images.githubusercontent.com/223879/175339412-978bc6ad-a071-43b6-8a1b-8be7810d23ff.gif)

**Comment by rozeboosje** [comment] 2022-06-23 16:02
Ahhhhhhhh!!!!!! @champnic I think I have figured something out. When parts of the WebView2 are showing just the gray background (they're "empty"), then things blur when they scroll into those areas:
![BlurringWhenEmptySpacesAreFilled](https://user-images.githubusercontent.com/223879/175343828-1c8c73ee-619b-4111-be1e-38cd7b4cab3e.gif)

**Comment by champnic** [comment] 2022-06-23 18:26
Actually it looks like the PDF team may have just checked in a fix into versions 104.0.1267.0+. Can you try your scenario using the latest Canary/Dev runtime?

**Comment by rozeboosje** [comment] 2022-06-23 18:42
Hi @champnic - when I stop scrolling it stays blurred. It's the end of my working day here in Ireland, I may get a chance tomorrow.

**Comment by rozeboosje** [comment] 2022-07-07 08:24
Hello @champnic Just a quick catchup. I'm sorry we have a bereavement in the family so I wasn't able to do anything in this area.

I'm reluctant to install Canary/Dev runtimes as we would never release builds with those in them to our clients. Any idea when this fix will make it to a mainstream release?

**Comment by rozeboosje** [comment] 2022-07-07 12:29
In fact I think the problem is getting **worse** rather than better:
![CompletelyMissingNow](https://user-images.githubusercontent.com/223879/177773354-df379d8d-8da3-473a-b4c4-54fd671102e8.gif)

**Comment by champnic** [comment] 2022-07-08 19:56
> we have a bereavement in the family

I'm really sorry to hear that :(

> I'm reluctant to install Canary/Dev runtimes as we would never release builds with those in them to our clients. Any idea when this fix will make it to a mainstream release?

Using Canary/Dev would just be to verify that the work the PDF team is doing fixed the issue. Looks like 104 would ship around beginning of August.

> In fact I think the problem is getting worse rather than better:

Was this new testing done with version 104.0.1267.0+ I mentioned above? Or with the latest stable release (103)?

**Comment by champnic** [comment] 2022-07-18 21:03
@rozeboosje You can use the prerelease browser channels to use as prerelease runtimes:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Glad to hear the feature is working better. It's possible the PDF team pushed the feature into the latest 103 stable as well if it resolved the issue you mentioned, as that sounded pretty serious.

**Comment by rozeboosje** [comment] 2022-07-19 11:22
@champnic It looks like I spoke too soon. Looking at it today, and still on the same builds of Edge and WebView2 Runtime the blurring issue has returned

![image](https://user-images.githubusercontent.com/223879/179738694-7823208f-5d3d-42fa-a0dc-b7d27ce02fba.png)

**Comment by champnic** [comment] 2022-07-20 20:38
Any luck testing on the newer builds?

**Comment by rozeboosje** [comment] 2022-08-12 14:06
Microsoft Edge and Microsoft Edge WebView2 Runtime both 104.0.1293.47

Microsoft.Web.WebView2 nuget package 1.0.1293.44

Now this is where it gets interesting. I ran the software and it all seemed ok "blur" wise, **but**
 ... on one PDF I noticed text on the right hand side being chopped off as I scrolled horizontally. It was literally as if everything to the right of the ViewPort does not get rendered, and then even if you scroll the horizontal scrollbar to bring the right hand side into view, it's just blank.
 
The viewport appears to be determined regardless of the vertical scrollbar. Even though the vertical scrollbar was visible, the content that was at first covered by the vertical scrollbar still scrolls into view and looks fine, but as soon as you scroll more than the width of the vertical scrollbar into view, anything that should have been to the right of the vertical scrollbar is blank.

The document in the attached image is a pdf containing a screen capture so you're looking at an image, not actual text.

This is where it gets REALLY interesting....

We allow the user to set an initial "zoom" factor for their previews. By default this is 100 (100 Percent, so "actual size").

I noticed that I didn't seem to be having that problem when the zoom factor was set to 75. Or to 150.

As an experiment I then tweaked our application to use a zoom factor of 99 when the user picks a zoom factor of 100. The difference is so slight that the user won't notice, but the problem doesn't seem to occur with a zoom factor of 99.

I also tried a zoom factor of 101, which led to a strange "duplication" effect as if part of the rendered image was duplicated horizontally.
![ZoomFactors](https://user-images.githubusercontent.com/223879/184369842-6eac8c59-3013-47ab-9ceb-983789b86f43.gif)

We preview the PDF using an object tag, for example
`<!DOCTYPE html><html style=""overflow-y:hidden""><body style=""height:100vh; width:100vw; margin:0px""><object data=""file://some/location/somepdffile.pdf#zoom=100"" height=""100%"" width=""100%"" style=""min-height:100vh; margin-bottom:50px"" type=""application/pdf""></object></body></html>`

**Comment by rozeboosje** [comment] 2022-09-08 10:56
Hello @champnic

Just wondering what the status is of this issue. As far as I can tell there no longer is any issue with blurring. Looking at my dev PC I see:

Microsoft Edge and Microsoft Edge WebView2 Runtime: 105.0.1343.27
Microsoft.Web.WebView2 nuGet package: 1.0.1343.22

The issue I mentioned on the 12th of August 2022 is still there but it's pretty hard to make it happen. I even noticed once or twice that I would see the issue with a document, navigate to somewhere else in our application, go back to the document and then the issue not happening, and I still observe that changing the zoom factor to 99 makes the problem "go away".

Is this the right place to keep mentioning this or should I raise a new issue?

**Comment by champnic** [comment] 2022-09-08 19:38
It's probably helpful to raise the remaining bug as a new issue just to make it clearer to track. I'll close this one out as it sounds like the main issue has been resolved by the PDF team. Thanks!

**Closed by champnic** 2022-09-08 19:38 UTC
Labels: bug, tracked
