### ISSUE TITLE
Enabling debug logging shows console window

### ISSUE THREAD

**Issue by 2Late1** [MicrosoftEdge/WebView2Feedback#2195] opened 2022-02-18 05:26 UTC
**Description**
When chromium debug logging is enabled, either setting WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--enable-logging --v=1 --log-file=c:\temp\webview.log before running app with WebView2 or doing the same thing with CoreWebView2EnvironmentOptions.AdditionalBrowserArguments console window is shown with some errors in Windows 10. In Windows 7 this does not happen. And the problem/bug is the console window.

**Version**
SDK:  1.0.1108.44
Runtime: Evergeen 98.0.1108.50
Framework: WPF, .NET 4.7.2
OS: Win10/Win7

**Repro Steps**
Set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--enable-logging --v=1 --log-file=c:\temp\webview.log environment variable before running it.

I'd expect no console window is shown.

![image](https://user-images.githubusercontent.com/6552042/154622875-6b48d0f0-6a32-46a3-b648-a4ed5012ff13.png)

**Additional context**
Also when console window is shown and if user closes it, CoreWebView2_ProcessFailed event is raised. 

[AB#38227198](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38227198)

**Comment by champnic** [comment] 2022-02-18 20:30
Hey @2Late1 - thanks for the bug report! What's the behavior if you try this in the Edge browser? I've added this bug to our backlog.

**Comment by 2Late1** [comment] 2022-02-19 07:15
If I run Edge browser from command line (win10, Windows terminal), there is similar kind of debug output in the console window. When  I Run (windows key + r) "msedge --enable-logging --v=1 --log-file=c:\temp\edge.log", console window is opened.

**Comment by quietfanatic** [comment] 2022-03-28 23:37
I think if the browser opens a console window in this case, it's reasonable to expect that WebView2 will also open a console window.  Also, closing the console when running the browser does seem to make the browser exit ungracefully, so this behavior also matches the browser.

I'm pretty sure debug logging is intended to be for development purposes, not for normal usage, so I'm going to close this as "By Design".  Let us know if you have any more questions.

**Closed by quietfanatic** 2022-03-28 23:37 UTC
Labels: bug, tracked
