### ISSUE TITLE
TAB/SHIFT-TAB navigation issue

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#933] opened 2021-02-12 20:37 UTC
**Description**
When a keyboard focus is on first focusable element on web page and a user presses Shift-Tab, or
a keyboard focus is on last focusable element on web page and a user presses Tab, then WV2 control and entire program stops responding to any user interaction (keyboard, mouse), and the program must be killed thru Task manager.

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.63
Framework: WinForms, Win32
OS: Win10

**Additional context**
I'm using non standard environment: I have a WinForms dll that exports UserControl with WebView2 control. This control is embedded into Win32 window (using SetParent api). So far so good except this issue with TAB navigation.
.

[AB#31757154](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31757154)

**Comment by ShaunLoganOracle** [comment] 2021-02-16 23:39
I see a similar issue using shift+Tab then shift+F6 when I host a WebView2 control in an Excel Task Pane.  In my case, Excel goes into then Not Responding and uses 25% or so of my CPU.  The webview2 processes are idle.

**Comment by ShaunLoganOracle** [comment] 2021-02-17 18:55
Possibly related to #589 ?

**Comment by champnic** [comment] 2021-02-17 23:37
Yes these issues might be related. I think we probably have a bug around expecting the parent of the WebView2 control to be a Form or something, and are running into these issues when the parent is different - Win32 HWND and/or TaskPane. I've opened a bug on our backlog to track this and will link it to the #589 bug as well. Thanks!

**Comment by mikeduglas** [comment] 2021-02-24 15:35
Would be great to have FocusMoving event with a flag indicating "by tab key or by mouse" it is moving", and boolean "handled (or "cancel)" allowing to cancel the operation.

**Comment by mikeduglas** [comment] 2021-03-09 21:52
Just tested new v1.0.774.44, unfortunately nothing has been changed and WebView2 is still unusable for us.

**Comment by mikeduglas** [comment] 2021-05-04 14:17
With new updates the issue seems to gone away:

SDK: 1.0.865-prerelease
Runtime: 92.0.873.1 Dev

I will test more and close the issue if everything goes well.

**Comment by champnic** [comment] 2021-05-04 23:29
Yup this issue should be fixed in 1.0.865-prerelease SDK package. I'm going to close this issue now, but please let me know if you run into any issues around this. Thanks!

**Closed by champnic** 2021-05-04 23:29 UTC
Labels: bug, tracked

**Comment by alaincao** [comment] 2021-05-05 23:15
Hi,  

I am not sure if it is an issue with ExcelDNA or with WebView, but I still have an issue with the keyboard focus when used with ExcelDNA Custom Task Panes:  
When I click the WebView window so it get the focus and seems to keep it and the worksheet loses the controls with keyboard arrows/page up|down.  
Everything returns to normal after clicking on another window and going back to the worksheet.  
- Using "1.0.865-prerelease"
- WebView Runtime 90.0.818.51
- I have a demo project (based on the samples from ExcelDNA/CustomTaskPane) to demonstrate the issue there https://github.com/alaincao/ExcelDNASamples/tree/webview2_issue_933/CustomTaskPane

**Comment by champnic** [comment] 2021-05-06 00:12
Hey @alaincao - this sounds like a separate issue. Are you using Tab/Shift-Tab to move keyboard focus out of the WebView2? While focus is on the WebView2 it's expected that it will key the arrow up/down input until focus leaves the WebView2 control.

**Comment by alaincao** [comment] 2021-05-06 00:49
I tried to use the tab key to move the focus out of the WebView control, but the focus cycles through the controls inside the HTML and never goes out ; I guess this is expected behaviour.  
But clicking on a control/the worksheet outside the WebView does not release the focus from the WebView. The keyboard is still interacting with the WebView even if another cells in the worksheet is selected.

Sorry, I was not too sure what to do with that issue so I put it here since it looked like related to focus. Should I create a separate issue?

**Comment by champnic** [comment] 2021-05-06 20:36
@alaincao That sounds like #951. Can you take a look and see if you agree? Feel free to add extra info there if so.
