### ISSUE TITLE
[Problem/Bug]: sessionStorage is being blocked

### ISSUE THREAD

**Issue by BradCB** [MicrosoftEdge/WebView2Feedback#4864] opened 2024-10-17 19:05 UTC
### What happened?

Google maps is no longer working because its trying to set a sessionStorage variable but WebView2 seems to be blocking it.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2792.45

### Framework

Winforms

### Operating System

Windows 10

### OS Version

22H2

### Repro steps

I can reproduce the issue when I use the html from https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_sessionstorage
and NavigateToString. 

![image](https://github.com/user-attachments/assets/01ee55fe-1ae1-491c-88d8-4df0bc4e9a6e)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by charlessowers2024** [comment] 2024-10-17 20:33
We have the same issue with our application. We changed back to using google version 3.57 and it works; however, this version is going to be removed shortly.

**Comment by charlessowers2024** [comment] 2024-10-17 20:33
This is currently impacting thousands of our customers so a solution would be greatly appreciated. Not sure why this being blocked.

**Comment by victorhuangwq** [comment] 2024-10-17 22:37
What is `google version 3.57`?

**Comment by victorhuangwq** [comment] 2024-10-31 21:53
Looks like this might not be a regression on WebView2's side? Closing this issue unless you have a reason to believe otherwise

**Closed by victorhuangwq** 2024-10-31 21:53 UTC
Labels: bug

**Comment by BradCB** [comment] 2024-10-31 23:46
> Looks like this might not be a regression on WebView2's side? Closing this issue unless you have a reason to believe otherwise

I can reproduce the issue when I use the html from https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_sessionstorage
and NavigateToString. Its not just an issue with google maps.

Session storage is supported in most modern browsers. I believe it should be supported by WebView2 since it is a widely supported web storage structure.

**Comment by BradCB** [comment] 2024-11-05 20:08
I think it was an actual issue with google maps, they seemed to have fixed it here: https://developers.google.com/maps/documentation/javascript/releases#2024-10-24
