### ISSUE TITLE
Download event monitoring

### ISSUE THREAD

**Issue by wf-soft** [MicrosoftEdge/WebView2Feedback#671] opened 2020-11-24 15:39 UTC

**Comment by pagoe-msft** [comment] 2020-11-24 19:19
Could you provide more clarity on this scenario?

**Comment by wf-soft** [comment] 2020-11-25 01:37
Like DownloadHandler in CefSharp

**Comment by ukandrewc** [comment] 2020-11-25 09:01
If you just want to monitor dwnload, you can do that with DevTools Protocol, but there is a feature request for a download api here: 
#419

**Comment by wf-soft** [comment] 2020-11-25 11:58
Can't access download events and iframe's kernel, it will be just a browser, and can't do more.

**Comment by champnic** [comment] 2020-12-03 08:00
Closing this issue as I believe it's a dupe of #419. @wf-soft Feel free to add input and scenarios to #419. Thanks!

**Closed by champnic** 2020-12-03 08:00 UTC
Labels: feature request
