### ISSUE TITLE
WebView2 WPF Modeless EnsureCoreWebView2Async problem,Modal System.InvalidCastException 

### ISSUE THREAD

**Issue by arkadiuszkoltun** [MicrosoftEdge/WebView2Feedback#592] opened 2020-10-31 18:12 UTC
Hi,
I have tried new WebView2 prerelease to create WPF Library Project which uses WebView2 Control but it doesn't load CoreWebView when invoking in modeless state. I try to EnsureCoreWebView2Async but it stays null. I tried out the basic code proposed in documentation:

![image](https://user-images.githubusercontent.com/27006678/97786153-fb089a00-1ba9-11eb-85bc-670689d69ccf.png)

On the other hand when using modal state (with ShowDialog() method) i keep getting :

`System.InvalidCastException: 'Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'`

**Version**
SDK: 1.0.674-prerelease 
Runtime: Dev 88.0.680.1 
Framework: WPF
OS: Win10 

[AB#30161444](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30161444)

**Comment by Gerthart** [comment] 2020-11-02 09:19
getting the same type of exception when trying to create a evergreen webview2 environment. 

`var env = CoreWebView2Environment.CreateAsync().GetAwaiter().GetResult();
`

results in

```
   InvalidCastException:  bij System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bij System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   bij Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
```
Version
SDK: 1.0.674-prerelease
Runtime: Dev 88.0.680.1
Framework: WPF
OS: Win10

**Comment by champnic** [comment] 2020-11-03 23:04
@Gerthart Glad you got it working 👍 

@arkadiuszkoltun What is the stack when you are hitting these errors? Or where in your source code?

**Comment by arkadiuszkoltun** [comment] 2020-11-03 23:46
Here is the stack:

`System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.add_AcceleratorKeyPressed(ICoreWebView2AcceleratorKeyPressedEventHandler eventHandler, EventRegistrationToken& token)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.add_AcceleratorKeyPressed(EventHandler1 value)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass25_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SMARTUI.TestWPF.<InitializeAsync>d__2.MoveNext() in C:\Users\ArkadiuszKoltun\source\repos\SMARTUI\TestWindow.xaml.cs:line 40
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`


I am just trying to invoke ShowDialog() method on gathered form (desired Show() as mentioned before, doesn't load CoreWebView2 property object) from DLL (marshalled as IDispatch)

**Comment by champnic** [comment] 2020-11-04 01:07
Hm, Show() should be working as well. There seems to be some mismatch in the APIs/SDK you are using, and the runtime, as evidenced by the interface IID not being available. I confirmed that IID is the latest one for ICoreWebView2Controller, and should be available at least as far back as any runtime version 628+. Can you verify that you are loading 88.0.681.1? For example, by checking the properties of the msedgewebview2.exe being used by your app in Task Manager while it's running?
![image](https://user-images.githubusercontent.com/45700886/98057307-d9502280-1df6-11eb-95ae-84f9ef599d01.png)

**Comment by arkadiuszkoltun** [comment] 2020-11-05 17:26
So, I have also tried with new core environment from the latest release (88.0.690.0) but I am still getting the same exception:

![image](https://user-images.githubusercontent.com/27006678/98274289-8364b180-1f93-11eb-8aab-4af42215e110.png)

**Comment by champnic** [comment] 2020-11-06 20:25
@arkadiuszkoltun Thanks for verifying. I'm opening a bug on our backlog to dig in further.

**Comment by theRTC204** [comment] 2020-12-16 15:24
I am also seeing this exception when calling `EnsureCoreWebView2Async()` in WPF.

I've tested this in a variety of different configurations including:

```
SDK: 1.0.664.37
Runtime: 87.0.664.60
```
```
SDK: 1.0.664.37
Runtime: 89.0.734.0
```

```
SDK: 1.0.674-prerelease
Runtime: 87.0.664.60
```
```
SDK: 1.0.674-prerelease
Runtime: 89.0.734.0
```

```
SDK: 1.0.721-prerelease
Runtime: 87.0.664.60
```
```
SDK: 1.0.721-prerelease
Runtime: 89.0.734.0
```

Here's a copy of the full exception (taken from SDK 1.0.674-prerelease, Runtime 87.0.664.60)
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{B96D755E-0319-4E92-A296-23436F46A1FC}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment.CreateCoreWebView2Controller(IntPtr ParentWindow, ICoreWebView2CreateCoreWebView2ControllerCompletedHandler handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass25_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DungeonImporter.Views.LoginPageWebView2.<InitializeAsync>d__2.MoveNext() in F:\Workspace\dungeon-importer\DungeonImporter\Views\Login\LoginPageWebView2.xaml.cs:line 28
```

**Comment by darkguy2008** [comment] 2020-12-29 09:18
I'm experiencing this same issue on Microsoft.WebView2.FixedVersionRuntime.87.0.664.66.x64 . In my case, all I want to do is to call ExecuteScriptAsync through Reflection with some pretty standard code:
```
public T Call<T>(object obj, string methodName, params object[] args)
{
    MethodInfo method = null;
    var all = _type.GetMethods();
    var methods = _type.GetMethods().Where(x => x.Name == methodName && x.GetParameters().Length == args.Length);
    foreach (var m in methods)
    {
        int i = 0;
        var ps = m.GetParameters();
        for (i = 0; i < args.Length; i++)
            if (ps[i].ParameterType != args[i].GetType()) { i = -1; break; }
        if (i == -1) { continue; }
        method = m;
        break;
    }
    if (method == null && methods.Any()) { method = methods.Last(); } // I know Last() isn't good, but it's what I have now.
    return (T)method.Invoke(obj, args);
}
```
Error is: `"One or more errors occurred. (Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).)"`

**Comment by lungareakshay** [comment] 2021-04-05 02:36
Did we find any solution for this error?

**Comment by champnic** [comment] 2021-04-05 22:31
> The error message is quite cryptic though, classic Microsoft.

We like to keep you on your toes ;) We have a fix, currently in review, that will make this error and message much more obvious in the future. It will likely be available with the next prerelease SDK.

For those of you running into this, it might be caused by trying to use the WebView2 on the wrong thread. WebView2 is not thread safe, and needs to be accessed on the same thread that created it (usually the UI thread). https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

**Comment by theRTC204** [comment] 2021-04-06 02:36
> For those of you running into this, it might be caused by trying to use the WebView2 on the wrong thread. WebView2 is not thread safe, and needs to be accessed on the same thread that created it (usually the UI thread). https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

I can confirm that this was my issue. Turns out reading the API documentation to the end was the solution. Simply dispatching the initialization back to the UI thread was all I needed to do.

**Comment by nanaliulei** [comment] 2022-12-08 08:04
Can't repro it in latest stable 1.0.1462.37 or latest prerelease 1.0.1466-prerelease. Seems like it is already fixed. I will close this issue as no fix needed, and feel free to reopen with more info so we can investigate further, thanks.

**Closed by nanaliulei** 2022-12-08 08:04 UTC
Labels: bug, tracked
