### ISSUE TITLE
Failure to locate/load 'WebView2Loader.dll' when '#' or non-english characters in the path

### ISSUE THREAD

**Issue by leodin61** [MicrosoftEdge/WebView2Feedback#1236] opened 2021-04-28 14:11 UTC
**Description**

When client app is running in a folder containing "#" character in its name, i.e. "C:\Projects\Temp\Debug #317\test.exe"
invoking CoreWebView2Environment.GetAvailableBrowserVersionString() throws:

{"Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233052
    HelpLink: null
    InnerException: null
    Message: "Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"
    Source: "Microsoft.Web.WebView2.Core"
    StackTrace: "   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableCoreWebView2BrowserVersionString(String browserExecutableFolder, String& versionInfo)\r\n   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(String browserExecutableFolder)\r\n   at Nuance.Dma.View.WebView2Ext.IsRuntimeInstalled() in C:\\.....\\WebView2Ext.cs:line 63"
    TargetSite: {Int32 GetAvailableCoreWebView2BrowserVersionString(System.String, System.String ByRef)}
    TypeName: ""

Loader lib confirmed to be in place ( C:\Projects\Temp\Debug #317\x86\WebView2Loader.dll )

Removing "#" from the folder name works fine.

**Version**
SDK: WebView2 v1.0.705.50 (WPF)
Runtime: evergreen runtime "90.0.818.49"
Framework: WPF
OS: Win10

**Repro Steps**

[AB#37110283](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37110283)

**Comment by champnic** [comment] 2021-04-29 23:54
Hey @leodin61 - thanks for the bug report! There have been some minor changes to where and how the WebView2Loader.dll is loaded - would you mind trying a newer SDK package to see if that resolves the issue? If not I'm happy to put this bug on our backlog to take a closer look.

**Comment by gileli121** [comment] 2021-11-19 09:45
@champnic 
I found out that when the program path contains non-English characters, you will get this error
And the error is not fixed also in `1.0.1056-prerelease` when running the program under a folder with a path that contains non-English characters

**Comment by gileli121** [comment] 2021-11-19 10:10
@champnic 
This issue with non-English characters is very old and I was able to reproduce it even with `1.0.705.50`
I could not test older versions because my app will fail to build due to code compatibility issue

**Comment by champnic** [comment] 2021-11-20 00:48
Thanks for the pointer! If that's the issue then I expect this affects all of our SDKs. I've added this bug to our backlog to try and fix.

**Comment by gileli121** [comment] 2021-11-20 02:18
@champnic 
Thanks.
Any idea when it will be fixed?
I tried these workarounds:
`Win32Native.AddDllDirectory("\\");`
https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory

And also:
`Utils.AddEnvironmentPaths(new[] { "//" });`

```c#

        public static void AddEnvironmentPaths(IEnumerable<string> paths)
        {
            var path = new[] {Environment.GetEnvironmentVariable("PATH") ?? string.Empty};

            string newPath = string.Join(Path.PathSeparator.ToString(), path.Concat(paths));

            Environment.SetEnvironmentVariable("PATH", newPath);
        }
```

I hoped that somehow it will pick it using a relative path that does not depend on non-English chars.
it did not fix it

**Comment by champnic** [comment] 2021-11-23 01:31
Hey @gileli121 - Can you try using `SetDllDirectory` (also in kernel32.dll) instead of `AddDllDirectory`?

**Comment by champnic** [comment] 2021-11-23 23:22
I've got the fix getting checked in now - I'll let you know when it's available. Thanks!

**Comment by gileli121** [comment] 2021-11-24 03:48
@champnic 
Great!
I wanted to check if `SetDllDirectory` will work. I did not know that this function exists. I just did not have time last day to check it.
But even if it will work, it is a less good solution for my case because I use multiple DLL directories and not only one.
And I assume that this function will remove all other DLL directories and replace them to one directory.

How did you fixed it?

**Comment by champnic** [comment] 2021-11-24 20:50
When we were calculating the path to the WebView2Loader.dll in our code it was getting put through a `new Uri(<path>)` which was stripping out the `#` character from the path. The fix is to use the paths directly.

Ya, sounds like `SetDllDirectory` probably won't help you here. The other option is to manually LoadLibrary for WebView2Loader.dll yourself. but I would probably wait until the fix is available if you can.

**Comment by gileli121** [comment] 2021-12-04 17:27
@champnic 
When the fix will be available?
It is now 10 days since I reported about it

**Comment by champnic** [comment] 2021-12-07 01:12
Hey @gileli121 - The fix will ship with the next prerelease package (it unfortunately missed the recent prerelease), which will probably be in early January. Thanks!

**Comment by champnic** [comment] 2022-01-20 01:03
This is now fixed in the 1.0.1133-prerelease SDK. Thanks!

**Closed by champnic** 2022-01-20 01:03 UTC
Labels: bug, tracked

**Comment by Mecanik** [comment] 2022-07-28 06:43
I have the same issue. Once I moved the .exe out of the debug/release folder this message shows. Very weird since there is no such .dll in the first place in the debug/release folders. Any ideas where I can get it?

**Comment by Mecanik** [comment] 2022-07-28 06:45
I take one comment back, it seems the .dll is deployed to "runtimes\win-x86\native".

**Comment by champnic** [comment] 2022-08-04 21:05
Hey @Mecanik - Your app needs some WebView2 SDK files shipped with it to function properly. There should be some helpful details here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app
