### ISSUE TITLE
[Problem/Bug]: WebView2 Nuget packages don't support NativeAOT w/ WinAppSDK 1.6+

### ISSUE THREAD

**Issue by zhuman** [MicrosoftEdge/WebView2Feedback#4800] opened 2024-09-10 06:37 UTC
### What happened?

WinAppSDK 1.6+ and CsWinRT 2.1.1 have released in August and added major support for NativeAOT with .NET 8. This means that you can build WinAppSDK apps or apps using WinRT APIs and use the `<PublishAot>true</PublishAot>` property in your project to make the build process trim and compile your entire project down into one native DLL/EXE.

### How to fix it?
The Microsoft.Web.WebView2 Nuget package needs to be updated to build with CsWinRT 2.1.1 in order to get this benefit as well. I think literally just update your CsWinRT dependency and rebuild to get updated projections.

### What is broken?
Until this is fixed, you can build a WinAppSDK NativeAOT app that works fine until the WebView2 classes are called. They will fail with the message:

> Cannot create an RCW factory for implementation type 'Windows.Foundation.IAsyncOperation`1[Microsoft.Web.WebView2.Core.CoreWebView2Environment]'.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2783-prerelease

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

22635.4145

### Repro steps

1. Create a WinAppSDK 1.6 app with .NET 8 and include a WebView2 component.
2. Add `<PublishAot>true</PublishAot>` to your project file.
3. Publish the app (triggering the full compilation to native code) and try to run it.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by zhuman** [comment] 2024-09-10 06:42
Note internally this is tracked by bug 53191953.

This will work once a Nuget version >= 1.0.2798 drops. Just filed this publicly to ensure folks are aware this is already done and pending release.

**Comment by Gaoyifei1011** [comment] 2024-09-12 07:48
> ### What happened?
> WinAppSDK 1.6+ and CsWinRT 2.1.1 have released in August and added major support for NativeAOT with .NET 8. This means that you can build WinAppSDK apps or apps using WinRT APIs and use the `<PublishAot>true</PublishAot>` property in your project to make the build process trim and compile your entire project down into one native DLL/EXE.
> 
> ### How to fix it?
> The Microsoft.Web.WebView2 Nuget package needs to be updated to build with CsWinRT 2.1.1 in order to get this benefit as well. I think literally just update your CsWinRT dependency and rebuild to get updated projections.
> 
> ### What is broken?
> Until this is fixed, you can build a WinAppSDK NativeAOT app that works fine until the WebView2 classes are called. They will fail with the message:
> 
> > Cannot create an RCW factory for implementation type 'Windows.Foundation.IAsyncOperation`1[Microsoft.Web.WebView2.Core.CoreWebView2Environment]'.
> 
> ### Importance
> Blocking. My app's basic functions are not working due to this issue.
> 
> ### Runtime Channel
> Stable release (WebView2 Runtime)
> 
> ### Runtime Version
> _No response_
> 
> ### SDK Version
> 1.0.2783-prerelease
> 
> ### Framework
> WinUI3/WinAppSDK
> 
> ### Operating System
> Windows 11
> 
> ### OS Version
> 22635.4145
> 
> ### Repro steps
> 1. Create a WinAppSDK 1.6 app with .NET 8 and include a WebView2 component.
> 2. Add `<PublishAot>true</PublishAot>` to your project file.
> 3. Publish the app (triggering the full compilation to native code) and try to run it.
> 
> ### Repros in Edge Browser
> No, issue does not reproduce in the corresponding Edge version
> 
> ### Regression
> No, this never worked
> 
> ### Last working version (if regression)
> _No response_

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4783

**Comment by oggy22** [comment] 2024-09-15 05:31
This seems to be a duplicate of #4783 which has been fixed.

**Closed by oggy22** 2024-09-15 05:31 UTC
Labels: bug
