### ISSUE TITLE
Meschanism to add in new compression schemes/content types

### ISSUE THREAD

**Issue by hallambaker** [MicrosoftEdge/WebView2Feedback#2502] opened 2022-06-07 18:53 UTC
**Is your feature request related to a problem? Please describe.**

I need the ability to add new content types and (de)compression mechanisms to a WebView2 browser. 

I have developed a Threshold Key Infrastructure which makes it possible for a user to access Web content that is encrypted at rest. Thus Alice can encrypt a file 'secret.html' and upload it to her Web server and then grant/deny access to Bob and Carol independently.

This all works from the command line, I would like to show it in a browser.

**Describe the solution you'd like and alternatives you've considered**

The ideal would be to be able to trap CoreWebView2WebResourceResponse events and replace the headers and content. So my code does nothing unless content of type application/dare is returned in which case I can decrypt the envelope and return the corresponding content.

What I am planning to do for demonstration purposes is to intercept all CoreWebView2WebResourceRequested events, resolve them using the .NET HTTP stack and feed the result into the response, checking to see if they are of the types I want to process and if so, put it through my decryption filter and feeding that into the response.

The problem with this approach is of course that I have short circuited much of the WebView code completely. The entire HTTP stack is disengaged.

An alternative approach would be to provide access to the HTTP API 

So something like:

class CoreWebView2Environment {

CoreWebView2WebResourceResponse WebResourceRequest (
     CoreWebView2WebResourceRequest request, 
     CoreWebView2WebResourceContext resourceContext) {
     }
}

The same approach can then be used to do things such as surfing from a file archive like a zip file.

[AB#39922211](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39922211)

**Comment by victorthoang** [comment] 2022-06-08 15:56
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by champnic** [comment] 2022-07-16 00:12
@hallambaker I'm closing this as a duplicate of #2355. Feel free to add info/extra requirements to that issue. Thanks!

**Closed by champnic** 2022-07-16 00:12 UTC
Labels: feature request, tracked
