### ISSUE TITLE
Is it possible to share ArrayBuffer between host and webview? 

### ISSUE THREAD

**Issue by lubobill1990** [MicrosoftEdge/WebView2Feedback#885] opened 2021-02-02 07:24 UTC
I find host and script in webview can communicate through postMessage. But currently only json and string can be the payload.

My question is that is it possible to share ArrayBuffer between host and webview? I need the host code to handle the image data get from webview.

**Comment by lubobill1990** [comment] 2021-02-02 07:27
related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/89

**Comment by champnic** [comment] 2021-02-02 23:19
You can also look at using app Host Objects in your javascript:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_

But mostly I think the ask is a duplicate of #89 so I'm going to close this item. Please add more info to #89 or let me know if you have other questions. Thanks!

**Closed by champnic** 2021-02-02 23:19 UTC
Labels: question

**Comment by lubobill1990** [comment] 2021-02-03 03:07
Thanks
