### ISSUE TITLE
WebView2.KeyDown does not work correctly with modifiers

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#1216] opened 2021-04-23 13:31 UTC
**Description**
When you press Shift+F8 and the KeyDown event gets triggered it registers as F8 and not as Shift+F8

**Version**
SDK: 1.0.824-prerelease
Runtime: Stable Edge 90
Framework: WinForms
OS: Win10, 20H2

**Repro Steps**
Take the following project as example:

```
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

using Microsoft.Web.WebView2.WinForms;

namespace WebView2BugModifiers
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(CreateTestForm());
        }

        public static Form CreateTestForm()
        {
            var form = new Form
            {
                Size = new Size(1280, 1024)
            };

            var webView2 = new WebView2
            {
                Dock = DockStyle.Fill,
                Source = new Uri(@"https://github.com/MicrosoftEdge/WebView2Feedback/")
            };

            webView2.KeyDown += (sender, e) =>
            {
                return;
            };

            form.Controls.Add(webView2);

            return form;
        }
    }
}
```
When you set a breakpoint in the KeyDown event handler and then press Shift+F8 you will see that no modifier is listed. We expect that the shift is listed as a modifier.

[AB#34280866](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34280866)

**Comment by champnic** [comment] 2021-04-23 16:38
Thanks for catching this, I've confirmed on our end. I've added a bug to our backlog to get this fixed.

**Comment by fvanheeswijk** [comment] 2021-05-03 15:37
An extra addition to this: Ctrl does not seem to work correctly either, when I press Ctrl + W for example then KeyDown returns that the Control key has been pressed, my W has disappeared nor is Control set as modifier.

**Comment by JaseRandall** [comment] 2021-09-01 12:51
Would there be an update/ETA available please for the KeyDown bug fix?

I'm trying to handle some of the BrowserAcceleratorKeys, such as CTRL-T (new tab) however the KeyDown events always has Control = false and the Modifiers are always None.
As per the image below, I pressed the control key but the only values to reflect that is the KeyCode and KeyValue.
![image](https://user-images.githubusercontent.com/35100435/131673099-bfcf9f1b-7e18-42c7-b355-4d6858f630dd.png)
 
I can confirm other BrowserAcceleratorKeys, such as Ctrl-F and Ctrl-P are working correctly, so it's not as if BrowserAcceleratorKeys are set to false.

**Comment by champnic** [comment] 2021-09-08 23:18
No update here. The current workaround is to keep track of when keys are being pushed (through a map or similar) and check that way, because as you note the "control" and the "T" are coming in separate events. Devs have also been using script to catch and handle keyboard shortcuts more easily, for example: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1684#issuecomment-908251870

We know this is a pain point, and is one of the upcoming .NET scenarios we're going to look at improving.

**Comment by fvanheeswijk** [comment] 2023-06-21 09:34
Is there any news on this?

**Comment by champnic** [comment] 2023-06-21 18:25
@zhuhaichao518 Would this scenario be improved by your hit-transparent work? If so, can you share some details on how to enable that here?

**Comment by spencerb02** [comment] 2023-12-21 17:05
2 and a half years later, any update on this?

**Comment by wnayes** [comment] 2024-06-12 03:20
Another workaround option, in case it helps someone:

If you are working with a WinForms Control/Form, then you have access to the base [Control.ModifierKeys](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.modifierkeys) property, which is a property that holds the current modifier key state. This seems to be a straightforward alternative to trying to use the Modifiers on the KeyEventArgs.

**Comment by zhuhaichao518** [comment] 2024-06-19 05:11
@wnayes Thanks for your suggestion!
@spencerb02 We have fixed it on our side and I expect it to be fixed in the 128 release.

**Comment by champnic** [comment] 2024-08-02 00:18
This is resolved on the latest pre-release SDK and upcoming release SDK in about a week.

**Closed by champnic** 2024-08-02 00:18 UTC
Labels: bug, tracked
