### ISSUE TITLE
Excel Addin -> Custom Pane with Html -> Dragging between 2 screens with different resolutions misplaces the pane content

### ISSUE THREAD

**Issue by shlomizeevy** [MicrosoftEdge/WebView2Feedback#2386] opened 2022-04-24 06:58 UTC
In my Excel Addin project (c#) I created a custom pane, which uses winfrom control, which hosts an html page using WebView2.

When I drag the Excel app between 2 different screens, with different resolutions the pane html content seems to go out of place:

![image](https://user-images.githubusercontent.com/59958305/164960805-b73d1325-862c-4bd8-9eec-d4952342f3d4.png)

When I use a winform control without hosting an html page, this doesn't happen.

I tried hooking on the WebView2's OnResize, and also control's, and I see that size changes when content gets out of place, but don't know how to fix it. Tried various options like setting parent to null etc...

Any ideas?

**Comment by jamesoli** [comment] 2022-05-02 17:44
This was reported in an earlier issue that we are currently tracking. #820 describes two issues and this is one of them.

Duplicate of #820

**Closed by jamesoli** 2022-05-02 17:44 UTC
Labels: question

**Comment by jamesoli** [comment] 2022-05-02 17:45
Duplicate of #820
