### ISSUE TITLE
Cannot Use File Upload with Input ``type="file"``

### ISSUE THREAD

**Issue by KiddoV** [MicrosoftEdge/WebView2Feedback#2972] opened 2022-11-14 20:30 UTC
**Description**
I have a basic upload input in HTML:
```html
<input type="file" accept="image/png">
```
When I click on the ``Choose File`` button, nothing happen in the ``runtime`` environment.
I tried putting the application on the Edge browser, then it is working.

**Version**
Runtime: Webview2 107.0.1418.42
Framework: Svelte, Wails, Golang
OS: Windows 10 Enterprise LTSC , Version 21H2

**Additional context**
I have tried the old Webview2 Runtime version ``107.0.1418.35``. This version is still OK, no issue at all.
Thanks!

**Comment by victorthoang** [comment] 2022-11-18 19:16
Hello @KiddoV,

Thanks for your bug report. I've assigned this to a dev that might best try to replicate the issue and follow up on this.

**Comment by oggy22** [comment] 2022-11-18 19:32
Hi @KiddoV, can you please tell us what kind of app is it? Win32, dotnet or UWP? Also what is the nuget package version?

**Comment by KiddoV** [comment] 2022-11-19 02:29
I am building an application using this framework: [Wails](https://wails.io/) - Golang + Webview2
More details on the issue: https://github.com/wailsapp/wails/discussions/2075#discussioncomment-4137777
Also an issue was opened: https://github.com/wailsapp/wails/issues/1331#issuecomment-1318493195

This is hard to re-produce, because I found it happens not on every computer. Also it doesn't throws any ERROR in the DevTools so it is hard to track down what is going on.

Despite all, when I compile the app to bin (exe) file, then it works. 

I'm not using ``.NET``, so I don't know what nuget package version you are asking.

**Comment by jinleil** [comment] 2022-11-19 07:40
Hi @oggy22, I had the same problem too. But the problem occur only when you run app as an administrator.
My app type is the wpf application with .NET6.
I tried to use the nuget package version:1.0.705.50/1.0.1418.22 ...

**Comment by oggy22** [comment] 2022-11-21 23:11
@KiddoV can you also check if that only reproes when the app is run as an administrator?

**Comment by KiddoV** [comment] 2022-11-22 12:11
@oggy22 you are right, when running the app in ``administrator mode``, input file doesn't work. @@!

**Comment by oggy22** [comment] 2023-02-07 23:09
Hi @KiddoV ! Sorry for the late reply. I believe the issue is fixed in the latest 109 runtime so I am closing the issue. Please feel free to reopen it if it doesn't work for you after updating your runtime.

**Closed by oggy22** 2023-02-07 23:09 UTC
Labels: bug

**Comment by jinleil** [comment] 2023-02-08 01:53
![微信截图_20230208094510](https://user-images.githubusercontent.com/44106819/217408536-4d22f9d0-9010-4a76-9e92-dd35684d6080.png)
