### ISSUE TITLE
AddScriptToExecuteOnDocumentCreatedAsync does not inject into a child iframe created by script.

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2921] opened 2022-10-31 13:37 UTC
**Description**
I target an intranet site that is not public and it contains 4 frames when started.

I have the following code utilizing AddScriptToExecuteOnDocumentCreatedAsync to add JavaScript to all documents created

```
private string ReadProjectFile(string aName)
{
	return System.IO.File.ReadAllText(System.IO.Path.Combine(AppContext.BaseDirectory, aName));
}

private void WebView2Base_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
{
	this.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
	
	string script = ReadProjectFile(@"JavaScript\MyTopJavaScript.js");
	var res = await this.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(script);
	script = ReadProjectFile(@"JavaScript\MyFileFrameJavaScript.js");
	res = await this.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(script);
}
```

The javascript is injected into 3 of the 4 frames created.

To check I have also implemented CoreWebView2.FrameCreated and this event fires 4 times.

**Version**
SDK: 1.0.1369
Runtime: 1070.1418.24
Framework: WPF
OS: Win10

**Repro Steps**
Unfortunately this is an internal site I am targeting. I therefore am unable to give a reproducible site.

The iframe element itself is rather simple
`<iframe src="javascript:&quot;&quot;" id="com.app.AppCarl" tabindex="-1" style="position: absolute; width: 0px; height: 0px; border: none; left: -1000px; top: -1000px;"></iframe>`

Below is also a pic of the whole document within the frame which only has a script. 

![image](https://user-images.githubusercontent.com/3191525/199019004-d5bc73fd-5d96-49fd-bd33-c9fda0a29f54.png)

**Additional Comments**
I suppose creating a fake site with multiple frames like this one would be a way to reproduce it.

[AB#42470885](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42470885)

**Comment by victorthoang** [comment] 2022-11-02 20:41
Hello @darbid,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by darbid** [comment] 2022-11-06 18:23
@victorthoang Thank you 

@imicy sorry for posting the original bug without something to go on.  I have now got a reproachable example here [Example loading multiple frames](https://github.com/darbid/ExampleLoadingFrames)

The code will load a local html page which contains 3 iframes and 1 script tag. The JS that is loaded in the script tag creates a 4th iframe and loads it. It is this iframe which does not get webview2 "love" from  AddScriptToExecuteOnDocumentCreatedAsync

**Comment by yizhao5** [comment] 2022-11-24 11:43
@darbid. Hello, what are your problems and expectations?

![image](https://user-images.githubusercontent.com/109595412/203770035-a6b6e4d2-fc27-4783-862d-5f755de5cfe9.png)
firstly, there are indeed 4 frames here, which are consistent with what you wrote.

![image](https://user-images.githubusercontent.com/109595412/203776174-c961dade-4d07-402a-aaff-1e55fe993614.png)
In addition, the `javaSrcriptToLoad.js` you added by `AddScriptToExecuteOnDocumentCreatedAsync` are also executed by the 4 frames.

**Comment by yizhao5** [comment] 2022-11-24 12:35
Do you mean that `frame4` (same as `loadscript.js`) has not been created, which is `window.frameElement = null`?

![image](https://user-images.githubusercontent.com/109595412/203779728-b67c13c8-d4d7-4cdb-944a-88de3292808e.png)
Meanwhile, there is no "Testing multiple Top document" log of `MainHTMLPage.html`.

Debug shows that the running order is:
```js
"Window frameElement is nothing. This is the Top Doc." -- in javaSrcriptToLoad.js
↓
"Testing multiple Top document" -- in MainHTMLPage.html
↓
"Load Frame With Name: frame4" -- in CoreWebView2.FrameCreated event
"Load Frame With Name: Frame1" -- in CoreWebView2.FrameCreated event
"Load Frame With Name: Frame2" -- in CoreWebView2.FrameCreated event
"Load Frame With Name: Frame3" -- in CoreWebView2.FrameCreated event
↓
"Frame SRC: https://testframe.app/WebPage/Frame1HTML.html" -- in javaSrcriptToLoad.js
↓
"Frame SRC: https://testframe.app/WebPage/Frame2HTML.html" -- in javaSrcriptToLoad.js
↓
"Frame SRC: https://testframe.app/WebPage/Frame3HTML.html" -- in javaSrcriptToLoad.js
```

Your `frame4` (same as `loadscript.js`) is a script included by the HTML document. The MSDN said, `AddScriptToExecuteOnDocumentCreatedAsync` [adds the provided JavaScript to a list of scripts that should be run after the global object has been created, but before the HTML document has been parsed and before any other script included by the HTML document is run](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=webview2-dotnet-1.0.1418.22).

**Comment by darbid** [comment] 2022-11-24 17:29
Thank you for your candid responses.

1. I do not have any problems but I am happy to assist you with your problems (assuming you are responsible for the good working condition of this code)
2. my expectation is that the JS code added with AddScriptToExecuteOnDocumentCreatedAsync is injected into the frame with the name frame4
3. my test show that it is not.

**Comment by yizhao5** [comment] 2022-12-01 11:20
@darbid. Hello.
Some logic of the function `CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync` is Chrome DevTools Protocol (CDP) API [Page.addScriptToEvaluateOnNewDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument), which "Evaluates given script in every frame upon creation (before loading frame's scripts)".

I also tested Google Chrome Browser, which also has been injected 4 times, which are 1 mainframe (`MainHTMLPage.html`) and 3 iframes (`Frame1HTML.html`, `Frame2HTML.html`, and `Frame3HTML.html`), and the "frame4" dynamically generated by JS (`loadscript.js`) is also not injected. The results are the same. It should be by design.
You can also verify it by `{"command":"Page.addScriptToEvaluateOnNewDocument","parameters":{"source": "console.log('1234')"}}`.

![image](https://user-images.githubusercontent.com/109595412/205038752-3e3a64a1-ba4e-4e47-b72d-5315bd3c5484.png)

**Comment by darbid** [comment] 2022-12-01 20:05
Great that we are on the same page now. So in my limited understanding the webview2 method does not in fact inject the script into new documents where the new document is created by js code as in the repo above. 

If I'm correct that does not sound right to me.

May I suggest either explaining in the documentation the documents which will not get code injected or get the upstream bug that is relied on here fixed.

As the webview2 code is not open source nobody knows you are just wrapping other code nor that that other code has a bug.

**Comment by yizhao5** [comment] 2022-12-02 03:01
It has nothing to do with open source or not. Users only need to choose the corresponding API according to their needs, without knowing the implementation.

The description of API `CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync`on MSDN is [adds the provided JavaScript to a list of scripts that should be run after the global object has been created, but before the HTML document has been parsed and before any other script included by the HTML document is run](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=webview2-dotnet-1.0.1418.22). The API description is clear.

As I said in the [comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2921#issuecomment-1333611436), the behavior of webview2 and **Chrome Browser** is the same, and also the same as the API document description and target, which means it is by design. So you can't say it's a bug.

If you have the requirements that all are injected, you can select the corresponding API. You can refer to [Page.loadEventFired](https://groups.google.com/a/chromium.org/g/headless-dev/c/Gr3sgGch_mI) or others.

**Comment by darbid** [comment] 2022-12-02 06:03
1 step forward 10 steps back @yizhao5 I have no idea why you refer to other code then. Either it is used by Webview2 under the hood or not. I have no idea and you worded your answer so you did not say :-) but if Webview2 does not use it then some other persons code is irrelevant. Further and more importantly lets look at the description of Page.addScriptToEvaluateOnNewDocument, it has a nice description text which you did not copy paste. 

_**"Evaluates given script in every frame upon creation (before loading frame's scripts)."**_ 

A Nice clear description which I understand, do you understand this @yizhao5 


Now lets align on the facts - here is an image to help

![msImage](https://user-images.githubusercontent.com/3191525/205221141-39be2f42-3456-441e-8d56-dce6f21a3087.png)

1. Here is an image of html elements on a page.
2. The frame identified with an arrow and the number 1 which has the "name" frame4 (identified with a Number 2) is located in this page.
3. the framecreated event recognizes this frame4 as a new frame created and fires an event. (so WebView2 recognizes the frame)
4. frame4 has a document (identified with an arrow and has the number 3) which has been loaded and is on this page.
5. AddScriptToExecuteOnDocumentCreatedAsync does NOT add the provided Javascript to the document (identified with an arrow and has the number 3)

So these 5 points are in the repo and you have now confirmed you can repro it, and it is in fact the case that AddScriptToExecuteOnDocumentCreatedAsync does not add provided Javascript to the document contained in frame4.

**Now the rest is up to you, as I am just a dumb customer. **

As customer feedback here is what i think @victorthoang and @david-risney 

1. It is my expectation that when I see the elements of a page that if it contains a document or documents that AddScriptToExecuteOnDocumentCreatedAsync will add the provided javascript to **each and every document**. To be clear I should not have to worry about the method in which the document is added. In most cases a Webview2 has no control and is blind to how pages are built by third parties.
2. @yizhao5  twice now has copy pasted the AddScriptToExecuteOnDocumentCreatedAsync on MSDN text. I am just a dumb customer, however, this text does not help me to understand that there are in fact cases where AddScriptToExecuteOnDocumentCreatedAsync does not add javascript to a document on a page. May I respectfully suggest that if I do not understand it, but you want to maintain that AddScriptToExecuteOnDocumentCreatedAsync is working as intended that at least a few other people will not understand it either and there might be room for an amendment.

**Comment by yizhao5** [comment] 2022-12-02 08:36
OK. I'm sorry. Probably earlier I meant to say that this behavior is as expected. We will consider your suggestions. @david-risney, @LiangTheDev, @oggy22, What are your suggestions? Thanks.

![image](https://user-images.githubusercontent.com/109595412/205250121-4ed6aea6-e84a-4944-b5ac-dc406ff80753.png)

**Comment by david-risney** [comment] 2022-12-02 18:46
This behavior surprises me and offhand appears to be a bug. We intend for AddScriptToExecuteOnDocumentCreatedAsync to run the provided script for each document before running the document's script and I agree with the statement that the end developer shouldn't have to worry about how the document is added.

I've cloned your bug repro github project (thanks for making that, very helpful in investigating bugs!) and I try the following in the DevTools console:

```
function tryAddingFrame(src) { var frame = document.createElement("iframe"); frame.src=src; document.body.appendChild(frame); }

tryAddingFrame("./Frame2HTML.html"); // AddScriptToExecuteOnDocumentCreatedAsync script loads
tryAddingFrame("https://example.com"); // AddScriptToExecuteOnDocumentCreatedAsync script loads
tryAddingFrame("about:blank"); // AddScriptToExecuteOnDocumentCreatedAsync script loads
tryAddingFrame("javascript:\"<h1>h1</h1>\""); // AddScriptToExecuteOnDocumentCreatedAsync script loads
tryAddingFrame("javascript:\"\""); // AddScriptToExecuteOnDocumentCreatedAsync script loads
```

And all of the frames ran the AddScriptToExecuteOnDocumentCreatedAsync script so it doesn't seem like its related to dynamically creating the frame nor the javascript: URI. Instead it looks like its how loadscript.js calls `frameDoc.open() ... close()`. When I comment out those lines, the AddScriptToExecuteOnDocumentCreatedAsync script runs again. 

I'm going to look into the open call more and see if I can tell what's going on.

**Comment by david-risney** [comment] 2022-12-02 19:30
You can see for any frame or the top level document if you target it with DevTools and run `document.write("<h1>example</h1><script>console.log(1)</script>"); document.close();`, you can see the document in the frame is replaced with that new content (including its own clean JavaScript engine instance), the new script in that document runs, but the AddScriptToExecuteOnDocumentCreatedAsync script doesn't run. The intent of AddScriptToExecuteOnDocumentCreatedAsync is to add end developer provided script in every document before that document runs its own script and so this seems like a bug for AddScriptToExecuteOnDocumentCreatedAsync.

**Comment by yizhao5** [comment] 2022-12-09 13:54
Hello, your problem is that `frame4` will not execute the script added by AddScriptToExecuteOnDocumentCreatedAsync.

**1. Example of fixing:**

**(1) Method one: using setTimeout in loadscript.js.**
```js
console.log('Javascript File loaded which will load an iFrame - loadscript.js');
var scriptFrame = document.createElement('iframe');
scriptFrame.src = 'javascript:""';
scriptFrame.id = 'frame4';
scriptFrame.name = 'frame4'
scriptFrame.style.cssText = 'position:absolute; width:0; height:0; border:none; left: -1000px;' + ' top: -1000px;';
scriptFrame.tabIndex = -1;
document.body.appendChild(scriptFrame);
frameDoc = scriptFrame.contentDocument;
if (!frameDoc) {
    frameDoc = scriptFrame.contentWindow.document;
}
function overrideDocumentFunction() {
    frameDoc.open();
    var doctype = document.compatMode == 'CSS1Compat' ? '<!doctype html>' : '';
    frameDoc.write(doctype + '<html><head><\/head><body><p>dddd</p><\/body><\/html>'); // The identifier "dddd" is added here.
    frameDoc.close();
}
setTimeout(function () { overrideDocumentFunction(); }, 1000);
```
![image](https://user-images.githubusercontent.com/109595412/206706022-d9c18a73-cf9f-4971-95f3-cb69d405be11.png)
The frame4 can execute the added script after using setTimeout, but overwriting frameDoc document failed. The reason may be scriptFrame.src = 'javascript:""'. After further changing to scriptFrame.src = 'about:blank' or empty, both are ok.

**(2) Method two: using onload event in loadscript.js.**
```js
console.log('Javascript File loaded which will load an iFrame - loadscript.js');
var scriptFrame = document.createElement('iframe');
scriptFrame.src = 'javascript:""';
scriptFrame.id = 'frame4';
scriptFrame.name = 'frame4'
scriptFrame.style.cssText = 'position:absolute; width:0; height:0; border:none; left: -1000px;' + ' top: -1000px;';
scriptFrame.tabIndex = -1;
document.body.appendChild(scriptFrame);
frameDoc = scriptFrame.contentDocument;
if (!frameDoc) {
    frameDoc = scriptFrame.contentWindow.document;
}
function overrideDocumentFunction() {
    frameDoc.open();
    var doctype = document.compatMode == 'CSS1Compat' ? '<!doctype html>' : '';
    frameDoc.write(doctype + '<html><head><\/head><body><p>dddd</p><\/body><\/html>'); // The identifier "dddd" is added here.
    frameDoc.close();
}
document.getElementById("frame4").onload = function () { overrideDocumentFunction() };
```
![image](https://user-images.githubusercontent.com/109595412/206708945-4c8eb439-3ebc-4de0-b116-dcc4412eb8ea.png)
The frame4 can execute the added script after using onload event, but overwriting frameDoc document failed. After further changing to scriptFrame.src = 'about:blank' or empty, frameDoc document still cannot be overwritten. [The onload event occurs when an object has been loaded](https://www.w3schools.com/jsref/event_onload.asp).

**(3) Method three: changing to scriptFrame.src = 'about:blank' or empty in loadscript.js.**
```js
console.log('Javascript File loaded which will load an iFrame - loadscript.js');
var scriptFrame = document.createElement('iframe');
scriptFrame.src = 'about:blank';
scriptFrame.id = 'frame4';
scriptFrame.name = 'frame4'
scriptFrame.style.cssText = 'position:absolute; width:0; height:0; border:none; left: -1000px;' + ' top: -1000px;';
scriptFrame.tabIndex = -1;
document.body.appendChild(scriptFrame);
frameDoc = scriptFrame.contentDocument;
if (!frameDoc) {
    frameDoc = scriptFrame.contentWindow.document;
}
function overrideDocumentFunction() {
    frameDoc.open();
    var doctype = document.compatMode == 'CSS1Compat' ? '<!doctype html>' : '';
    frameDoc.write(doctype + '<html><head><\/head><body><p>dddd</p><\/body><\/html>'); // The identifier "dddd" is added here.
    frameDoc.close();
}
overrideDocumentFunction();

```
![image](https://user-images.githubusercontent.com/109595412/206714476-0019d793-95b6-4c6d-97f1-30fa85d9aac9.png)
The frame4 can execute the added script after changing to scriptFrame.src = 'about:blank' or empty, and overwriting frameDoc document takes effect.

There may be several reasons why the added script is not executed. I think it may be an unexpected input, or unexpected event order, or an internal exception. At this stage I would suggest customer if they can use "about:blank" or "" if it works. As mentioned earlier, we will also track and address this. Thanks.
Cc: @david-risney, @vbryh-msft.

**Comment by plantree** [comment] 2023-01-10 07:27
Hi @darbid,

I am keeping track of this issue, and I have one question: why will you set the source of frame and clear the document later?

**Comment by plantree** [comment] 2023-01-13 02:25
Hi @darbid,

Thanks again for your patience while we investigate this issue! 

For your use case, we have found a possible workaround with the example project you've shared.  

We've made the workaround in the `MainWindow.xaml.cs` file, with provided inline code comments from Step1 - Step3. Below is the code snippets, please find complete code in the `ExampleLoadingFrames_workaround.zip`. 
```c#
private async void InitializeAsync()
{
     ..........
    // Step1: add a DOMContentLoaded event handler
    this.Browser.CoreWebView2.DOMContentLoaded += WebView_DOMContentLoaded;
}

// Step2: event handler
async private void WebView_DOMContentLoaded(object sender, CoreWebView2DOMContentLoadedEventArgs e)
{
    // Step3: executeScript()
    await this.Browser.CoreWebView2.ExecuteScriptAsync("scriptFrame.src= 'javascript:\"\"';");
}
```

*Tested working in the Example solution for the injected script in the dynamically created iframe.*

Hope this can help unblock you while we continue to dive deep into this API bug. Please see attached example zip with our workaround in code and kindly let us know if this works for you.

[ExampleLoadingFrames_workaround.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10407351/ExampleLoadingFrames_workaround.zip)

**Comment by novac42** [comment] 2023-02-20 09:13
Hi @darbid, does the workaround provided in previous comment work for you?

**Comment by plantree** [comment] 2023-03-31 06:07
Hi @darbid,

I'll mark this issue as resolved temporarily. If you have any other issues, we will still follow up. Thanks.

**Closed by plantree** 2023-03-31 06:07 UTC
Labels: bug, tracked, status-unresolved
