### ISSUE TITLE
webView2 does not fire the Form mouse event properly

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3740] opened 2023-08-25 09:15 UTC
**Description**

I have a webVIew2 control loaded into the form, and I bind the mouse move event to the form, but when I move the mouse over the webView2 control, the mouse event does not trigger properly, and the form mouse event will not take effect again until the mouse moves out of the scope of the webView2 control

**Version**
SDK:  1.0.1901.177
Runtime: 115.0.1901.203
Framework: WinForms
OS: Win11

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by johna-ms** [comment] 2023-10-18 00:27
Hi, I'm closing this issue as a duplicate of issue #425. In short, because the WinForms WebView2 control handles the mouse input, the user cannot do further handling. You can work around this using javascript mouse event handlers.

**Closed by johna-ms** 2023-10-18 00:27 UTC
Labels: bug
