### ISSUE TITLE
WebView2 + WeifenLuo.WinFormsUI.Docking

### ISSUE THREAD

**Issue by reckon117** [MicrosoftEdge/WebView2Feedback#289] opened 2020-06-17 14:48 UTC
Hi,

I use Webview2 in WinForm in a dockpanel (with WeifenLuo.WinFormsUI.Docking) and my concern is that when I move my panel, an exception is launched:
`$exception	{"The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)"}	System.Runtime.InteropServices.COMException`

 and when I look into the StackTrace I have:
```
 at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rect value)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.ScrollableControl.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Form.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(IArrangedElement affectedElement, String affectedProperty)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Form.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

How can I get around this without rebuilding everything when I move my window ?

I'm using version 0.9.538-prerelease of Microsoft.Web.WebView2.
I tried to use the normal 0.9.538 release, but I couldn't get it to work... (He can't found Miscrosoft.Web)

[AB#27047002](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27047002)

**Comment by pagoe-msft** [comment] 2020-06-17 18:47
@reckon117,

Currently .NET binaries are in the pre-release package and will remain in the package while we are in preview. 

Thanks for bringing this to our attention, I've filed a bug and we will investigate this.

**Comment by cbra-caa** [comment] 2020-09-14 08:14
I have experienced the same problem in WPF with the following stacktrace:

```
Catching Unhandled exception:System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rect value)
at Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged(Rect rcBoundingBox)
at System.Windows.Interop.HwndHost.UpdateWindowPos()
at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
at System.Windows.ContextLayoutManager.UpdateLayout()
at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Setup**
- WPF application
-  .Net 4.7.2
-  0.9.579-prerelease package for WebView
-  Edge Dev installed

**Comment by jairbubbles** [comment] 2020-10-05 12:54
I'm experimenting the same error with my application. I've been working on getting a clear repro but with no luck.

Some information:
- We use multiple instances of `WebView2` in our application
- It seems to be related to letting the application in background and the `WebView2` unloaded

We've been seeing multiple crash callstack (without all the WPF lines):
```
System.Runtime.InteropServices.COMException:
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds (Microsoft.Web.WebView2.Core, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds (Microsoft.Web.WebView2.Core, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
   at Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged (Microsoft.Web.WebView2.Wpf, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
...
```

But also:
```
System.Runtime.InteropServices.COMException:
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_IsVisible (Microsoft.Web.WebView2.Core, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_IsVisible (Microsoft.Web.WebView2.Core, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
   at Microsoft.Web.WebView2.Wpf.WebView2.UIElement_IsVisibleChanged (Microsoft.Web.WebView2.Wpf, Version=0.9.628.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e)
...
```

These are triggered just because the `WebView2` control in the visual tree and we have no control on it. The main problem is that when it happens it leaves the application in a completely wrong state.

**Could the `COMexception` at least be try/catch'ed in the wrapper?** If we were getting a failure callback it would allow to relaunch the `WebView2` control / remove the control and display a message.

*Apart from that the control is really and a huge improvement over the previous one. Keep up the good work! 💪*

**Comment by jairbubbles** [comment] 2020-10-12 07:18
We're also getting it when disposing the control:
```
Microsoft.Web.WebView2.Core Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.remove_ContentLoading()                                                                                                                                 1/1/0001 12:00:00 AM 
Microsoft.Web.WebView2.Core Microsoft.Web.WebView2.Core.CoreWebView2.remove_ContentLoading()                                                                                                                                      1/1/0001 12:00:00 AM 
Microsoft.Web.WebView2.Wpf  Microsoft.Web.WebView2.Wpf.WebView2.Dispose()   
```

Regardind try/catch, it's possible to override  `Dispose` and `OnWindowPositionChanged` in a new control inheriting from `WebView2` but not `IsVisibleChanged`.

**Comment by jairbubbles** [comment] 2020-10-20 11:52
I just saw the WebView2 is now avalaible (https://blogs.windows.com/msedgedev/2020/10/19/edge-webview2-general-availability/). This is great news but I was wondering if there was progress on this issue. 

IMO the problem is quite severe and prevents to use it in production.

**Comment by TReKiE** [comment] 2020-10-20 19:36
I saw that yesterday too and then noticed it's GA for the non-managed version only.

One point to add, the control was working fine on this aspect originally, and then broke at some point.  I had added WebView2 as a secondary rendering option, then one day upgraded the control via nuget, and it broke as reported above.  No code changes.

**Comment by champnic** [comment] 2020-10-20 23:36
Is everyone on this thread trying to use WeifenLuo.WinFormsUI.Docking?

@cbra-caa That error message is usually indicative of the WebView2 control has not finished initializing. I would have to see your code to know why, but often related to not awaiting EnsureCoreWebView2Async, or not using the CoreWebView2Ready event to know that initialization is complete.

@jairbubbles/ @TReKiE: If you upgrade to the latest 1.0.674-prerelease package do you still see this? if so, could you please open a separate issue?

Thanks!

**Comment by TReKiE** [comment] 2020-10-21 07:13
My apologies @champnic, I really should've tried that before posting.   It is now working again for me on 1.0.674-prerelease.  My thanks to yourself and the rest of the team for your hard work 🙂.

To answer your question, I am not using WeifenLuo.WinFormsUI.Docking.  I am only adding the control to a Panel, with both set to DockStyle.Fill.
Also, the Dispose issue jair mentioned above isn't resolved, but that's [already been reported](https://github.com/MicrosoftEdge/WebView2Feedback/issues/442) and the described workaround (Visible=false before Dispose) resolves it.

**Comment by jairbubbles** [comment] 2020-10-21 07:26
@champnic No we don't use `WeifenLuo.WinFormsUI.Docking` but we have multiple tabs containing webviews (we're using Prism and classic WPF tab controls).

I'll test `1.0.674-prerelease` ASAP and keep you posted. Please note that in our case the issue appears randomly after using for a quite a time our application so it's complicated to test. As a workaround we're now disposing the control after 5 minutes when a tab is hidden. It's already a big improvement are we're seeing the exception a lot less, but we still have occurences from time to time.

@TReKiE I don't think it's the same issue as in our case it's always a `COMexception` and not a `NullReferenceException`.

**Comment by AbeniMatteo** [comment] 2020-11-17 00:35
Same problem here. Pure WPF TabControl that handles multiple webviews (one per tab).
This exception is thrown after an inactive tabs is restored (by clicking on the relative TabItem) but i'm not able to create a concrete repro.

@jairbubbles do you detach\attach the webview control from the tree?

**Comment by jairbubbles** [comment] 2020-11-17 08:27
Since we updated to `1.0.674-prerelease` we do not receive error reports anymore. And this is good news, great job!

But we still have the code which disposes the control after 5 minutes when not visible. This has the merit to reduce the memory usage. I don't know if somehitng is planned but it will be cool to have some "recycling" parameters that allow to fine tune that kind of behaviors. I guess Edge browser do that kind of things?

@AbeniMatteo Here is what our code looks like:

```csharp
// Listen to  IsVisibleChanged event
private void OnIsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
{
    _disposeTimer?.Dispose();
    _disposeTimer = null;

    if (IsVisible)
    {
            CreateWebView();
    }
    else
    {
        // Dispose after 5 minutes
        _disposeTimer = new Timer(_ => Dispatcher?.InvokeAsync(DisposeWebView), null, TimeSpan.FromMinutes(5), TimeSpan.FromMilliseconds(-1));
    }
}

private void CreateWebView()
{
    if (_webView != null) // The web view is still alive => nothind to do
        return;

    Dispatcher.InvokeAsync(() =>
    {
        _webView = new WebView(_logger);
        _webView.NavigationCompleted += WebViewOnNavigationCompleted;
        _webView.NavigationStarting += WebViewOnNavigationStarting;
        _webView.ContentLoading += WebViewOnContentLoading;
        _webView.Loaded += WebViewOnLoaded;

        WebViewContainer.Content = _webView;
    });
}

private void DisposeWebView()
{
    if (_webView == null)
        return;

    _webView.NavigationCompleted -= WebViewOnNavigationCompleted;
    _webView.NavigationStarting -= WebViewOnNavigationStarting;
    _webView.ContentLoading -= WebViewOnContentLoading;
    _webView.Loaded -= WebViewOnLoaded;

    if (_pendingUrl == null)
        _pendingUrl = _webView.Source;

    _webView.Dispose();
    _webView = null;
}


```

**Comment by AbeniMatteo** [comment] 2020-11-17 08:53
`1.0.674-prerelease` doesn't solve the problem for me and disposing the control is not an option.

I thought it was caused by some resize\fill logic fired by attaching\detaching the control (example below) but it seems time related (inactivity).
```cs
private void TabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
{
    var webView = ...;

    // detach the old webview
    container.Children.Clear();
    // attach the new view
    container.Children.Add(webView);
}
```

**Comment by AbeniMatteo** [comment] 2020-11-17 10:07
Finally! I was able to reliably repro the problem using `edge:\\discards` to manually control the tabs.
@champnic can you check this?

Steps:
1. Run the code below
2. Select `DISCARD ME tab`
3. Select `Active tab`
4. Click `[Urgent Discard]` for the tab named `DISCARD ME` (third row)
5. Select `DISCARD ME tab`
6. Exception is thrown 🥳 

Program.cs
```cs
using System;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Web.WebView2.Wpf;

namespace Repro0x8007139F
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            /********* UI SETUP *********/
            new Application();

            var window = new Window
            {
                Width = 1500,
                Height = 700,
            };

            var grid = new Grid();
            grid.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            grid.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            window.Content = grid;

            var tabControl = new TabControl();
            Grid.SetRow(tabControl, 0);
            grid.Children.Add(tabControl);

            var discardsWebView = new WebView2();
            Grid.SetRow(discardsWebView, 1);
            grid.Children.Add(discardsWebView);
            /********* UI SETUP *********/

            discardsWebView.EnsureCoreWebView2Async().ContinueWith(_ =>
            {
                Application.Current.Dispatcher.Invoke(() => discardsWebView.Source = new Uri("edge://discards"));
            });

            var activeWebView = new WebView2();
            activeWebView.EnsureCoreWebView2Async().ContinueWith(_ =>
            {
                Application.Current.Dispatcher.Invoke(() =>
                {
                    activeWebView.NavigateToString(@"
                        <html>
                            <head>
                                <title>ACTIVE TAB</title>
                            </head>
                            <body style='background:green'>ACTIVE TAB</body>
                        </html>
                    ");
                });
            });

            tabControl.Items.Add(new TabItem { Header = "Active tab", Content = activeWebView });
            tabControl.Items.Add(new TabItem { Header = "DISCARD ME tab", Content = null });
            tabControl.SelectionChanged += (sender, e) =>
            {
                var selectedTabItem = (TabItem)e.AddedItems[0];
                if (selectedTabItem.Content != null)
                    return;

                var discardMeWebView = new WebView2();
                discardMeWebView.EnsureCoreWebView2Async().ContinueWith(_ =>
                {
                    Application.Current.Dispatcher.Invoke(() =>
                    {
                        discardMeWebView.NavigateToString(@"
                            <html>
                                <head>
                                    <title>DISCARD ME</title>
                                </head>
                                <body style='background:red'>DISCARD ME</body>
                            </html>
                        ");
                    });
                });
                selectedTabItem.Content = discardMeWebView;
            };

            window.ShowDialog();
        }
    }
}
```

Repro.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.674-prerelease" />
  </ItemGroup>
</Project>
```

**Comment by champnic** [comment] 2020-11-18 19:16
I'm going to close this issue for now as it seems the original and other cases were fixed. @AbeniMatteo I've opened #637 to track you WPF issue.

**Closed by champnic** 2020-11-18 19:16 UTC
Labels: .NET, WinForms, bug
