### ISSUE TITLE
Right-clicking a link crashes WebView2 on 90.0.818.42 runtime

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#1081] opened 2021-03-17 08:32 UTC
**Description**

On some machines, right-clicking a link in WebView2 crashes the application.
I have three machines on the same version of Windows, one of them correctly shows the context menu, two of them experience a crash: `System.Runtime.InteropServices.COMException: 'The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)'`.

I can repro this on all machines when using the "Windows 10 dev environment" VM from Hyper-V's Quick Create.

Stack-trace screenshots added below.

**Version**
SDK: 1.0.824-prerelease
Runtime: Version 91.0.828.0 (Official build) canary (64-bit)
Framework: WPF
OS:  Windows 10 Pro 10.0.19041 x64

**Repro Steps**

- Create a new .NET 4.7.2 WPF Application
- Add WebView2 NuGet package
- Replace `<Grid>` in the `MainWindow.xaml` with:
```
    <DockPanel>
        <wpf:WebView2 Name="webView" Source="https://www.microsoft.com"
        />
    </DockPanel>
```
- Launch the app
- Right click any link in the page (e.g. the Microsoft logo)
- Expected: context menu opens
- Actual: crash
- If this does not crash on your machine, try this in the "Windows 10 dev environment" VM from Hyper-V's Quick Create.

**Screenshots**

x86:
![image](https://user-images.githubusercontent.com/4180387/111436995-48297a80-870b-11eb-9ea7-efb1a1a97dd0.png)

x64:
![image](https://user-images.githubusercontent.com/4180387/111437095-5f686800-870b-11eb-8b21-4eb64754b0b2.png)

Let me know if there's any additional info I can provide to help reproing this issue.

[AB#32213079](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32213079)

**Comment by LaraSQP** [comment] 2021-03-21 03:14
Same here but with `WinForms`.

**Comment by champnic** [comment] 2021-03-22 23:50
This is likely caused by the browser processes crashing in that scenario. Can you try listening for the [ProcessFailed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed?view=webview2-dotnet-1.0.774.44) event and see if that's getting hit?

**Comment by mrsteamfist** [comment] 2021-04-05 22:29
@LaraSQP and @RendijsSmukulis I just want to confirm, this is specific to Virtual Machines and the context menu itself, not a context menu item.

**Comment by LaraSQP** [comment] 2021-04-06 05:41
I did not use a VM and have work around the issue by providing my own context menu.

**Comment by mrsteamfist** [comment] 2021-04-06 16:25
@LaraSQP can you give me more information on your error. Is there a specific page you go to. Does it crash when the context menu pops up?

**Comment by LaraSQP** [comment] 2021-04-06 21:12
Like I said, no longer get an error since disabling the default context menu.

**Comment by cbra-caa** [comment] 2021-04-08 14:20
@mrsteamfist For me it crashes whenever right-click is used on a link, when the default context menu is enabled.

It also produces three different stacktraces, which are almost similar, from the same COM-exception:

1. `System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Undtagelse fra HRESULT: 0x8007139F)
ved Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
ved Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
ved Microsoft.Web.WebView2.Wpf.WebView2.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
ved System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
ved MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
2. `System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Undtagelse fra HRESULT: 0x8007139F)
ved Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
ved Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rectangle value)
ved Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged(Rect rcBoundingBox)
ved System.Windows.Interop.HwndHost.UpdateWindowPos()
ved System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
ved System.Windows.ContextLayoutManager.UpdateLayout()
ved System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
ved System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
ved System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
ved System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
3. `System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Undtagelse fra HRESULT: 0x8007139F)
ved Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_IsVisible(Int32 IsVisible)
ved Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_IsVisible(Boolean value)
ved Microsoft.Web.WebView2.Wpf.WebView2.UIElement_IsVisibleChanged(Object sender, DependencyPropertyChangedEventArgs e)
ved System.Windows.DependencyPropertyChangedEventHandler.Invoke(Object sender, DependencyPropertyChangedEventArgs e)
ved System.Windows.UIElement.RaiseDependencyPropertyChanged(EventPrivateKey key, DependencyPropertyChangedEventArgs args)`

**Comment by jfgimenezx** [comment] 2021-04-21 08:34
I've falled in this problem since evergreen runtime has been updated to 90.0.818.42. Previous versions work fine. The first post in this thread talks about version 91.0.828.0, so this problem exists for a while. And now, evergreen is automatically updated to a buggy version. Is it possible to revert to a previous version and block this new one?

It is really a big problem for me and my users.

In my case, I'm using webview in a 32 bit app compiled with mingw (plain C). It was working fine until now. I've tried several .dll versions with no success. It happens all computers with windows 10 that have been updated (4 computers for now).

**Comment by rllibby** [comment] 2021-04-21 14:54
I ran into this same issue starting on 04/19, when one of my four systems updated to the evergreen version of 90.0.818.41. Prior to that, my application had been running without errors since December of 2020. My other three systems were still on runtime version 89.0.774.77, and they did not exhibit this crash behavior. I uninstalled the WebView2 runtime on one of the systems that was still working correctly (89.0.774.77), and then ran the evergreen installer which placed down version 90.0.818.42, and the crash started occuring on that system as well. Anyways, to ensure this wasn't an issue caused by my application, I created a basic WinForm app; installed the WebView2 SDK nuget package 1.0.774.44, dropped the WebView2 component on the form, set the source to "https://www.google.com" and then tested right clicking on the page. The context menu works fine for the page, selected text, images, etc; everything but links. Right clicking *any* link causes the CoreWebView2.ProcessFailed event to be triggered, with the ProcessFailedKind == BrowserProcessExited. 

Detailed information on the OS / Framework / SDK / runtime versions tested.

Windows 10 version (all systems):
19042.928

.NET Framework version used:
4.7.2

WebView2 SDK version(s) tested:
1.0.774.44
1.0.705.50
1.0.664.37

Edge evergreen runtime version(s) tested:
90.0.818.42
90.0.818.41

Checking the default user folder for the WinForm test app, I navigated to the subfolder of "..\WindowsFormsApp1\bin\Debug\WindowsFormsApp1.exe.WebView2\EBWebView\Crashpad\reports" and found mini dump files for each crash I had generated. They appear to all be the same (0xC0000005), except for the faulting address:

Process Name:		msedgewebview2.exe : C:\Program Files (x86)\Microsoft\EdgeWebView\Application\90.0.818.42\msedgewebview2.exe
Process Architecture:	x64
Exception Code:		0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

Unhandled exception at 0x00007FFD2D834083 (msedge.dll) in 8e918cb0-8b9a-4e87-b5b0-3d22f3fd1bee.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FFAD7EC4083 (msedge.dll) in 015da7f4-0ac9-4505-ac2b-d7a2b84d8fe2.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FFD2D834083 (msedge.dll) in 27ca98b1-c8bb-43b1-9865-f2ada1ef4b01.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FFD2D834083 (msedge.dll) in 4196c2da-232b-42b6-9945-6ac38f95b746.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FFD20484083 (msedge.dll) in db459f17-a66a-4984-8053-591094a65b02.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.

Please let me know if further information is needed.

**Comment by champnic** [comment] 2021-04-22 03:44
Hey all - I appreciate all the extra info here. It's clear this is something we need to fix ASAP and get patched. I'll update when we have more info to share/fix ETA. Thanks!

**Comment by champnic** [comment] 2021-04-22 20:29
We've just pushed a fix into the 90 runtime branch, so the fix so go out with the next patch/runtime update, within a week. Apologies to everyone running into this!

**Comment by jfgimenezx** [comment] 2021-04-24 11:08
Hi @champnic,
thank you very much. However, I believe that you should provide a way to revert an update when these kinds problems happens.

**Comment by champnic** [comment] 2021-04-26 22:45
@jfgimenezx - Agreed! We are definitely looking into that moving forwards.

**Comment by Symbai** [comment] 2021-04-27 12:29
@champnic Can you please tell us the version number of the WebView2 runtime that contains the fix? I see the download page is already on 90.0.818.4**9** and this topic is about .4**2**

**Comment by rllibby** [comment] 2021-04-27 13:17
I forced an update to WebView2 this morning, and it pulled down version 90.0.818.49; I was previously on version 90.0.818.46. 

Control Panel | Programs | Uninstall a program | Microsoft Edge WebView2 Runtime | Right click | Change | Repair

Testing of my application shows that the issue has been corrected in version 90.0.818.49, and context menus for links are now working as expected. This was verified on my 4 systems that previously crashed the browser process when right clicking any links.

**Comment by Symbai** [comment] 2021-04-27 13:27
Thanks @rllibby I believe @champnic can close the issue then?

**Comment by jfgimenezx** [comment] 2021-04-27 16:49
I confirm. Version .49 is working fine!
Thanks!

**Comment by champnic** [comment] 2021-04-27 16:57
Yes 90.0.818.49 should have the fix - thanks for confirming everyone!

**Closed by champnic** 2021-04-27 16:57 UTC
Labels: bug, tracked
