### ISSUE TITLE
Mouse gets ignored after writing into a contenteditable element

### ISSUE THREAD

**Issue by dady8889** [MicrosoftEdge/WebView2Feedback#3118] opened 2023-01-11 02:25 UTC
**Description**

Moving the mouse at the same time as writing into a `contenteditable` element (such as div) causes all subsequent mouse events to get ignored (click, hover, ...).

**Version**
SDK: 1.2.221109.1
Runtime: 108.0.1462.76
Framework: .NET 7 MAUI Blazor
OS: Windows 11 Version 22H2 (Build 22621.963)

**Repro Steps**

- Create a new MAUI Blazor project for .NET 7
- Add the following code into any page
```razor
<div style="border: 1px solid black;" contenteditable="true">
    @text
</div>

<hr />

<button style="height: 2rem; width: 100%">Click Me</button>

@code {
    string text = "write something here and move mouse at the same time";
}
```
- Try writing into the editable text area and moving the mouse at the exact same time
- After finishing writing, try clicking on the button

Expected behaviour:
- Button is successfully clicked

Actual behaviour:
- It is not possible to click anything on the webpage

**Comment by champnic** [comment] 2023-01-12 00:25
@Eilon FYI

I was unable to reproduce this issue on a Windows Form or WinUI3/WindowsAppSDK app, so I think this may be specific to Maui. @dady8889 would you mind opening this issue on the Maui repo to have them take a first look?
https://github.com/dotnet/maui/issues/new/choose

Thanks!

**Comment by dady8889** [comment] 2023-01-12 00:52
Thank you for checking the issue. I opened a new one at MAUI.

**Comment by Eilon** [comment] 2023-01-23 19:21
Duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003. The same basic repro app I posted there also shows this bug.

**Closed** 2023-01-25 20:55 UTC
Labels: bug
