### ISSUE TITLE
Getting and displaying connection "is secure" and certificate validity - which API?

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#2642] opened 2022-08-02 13:56 UTC
I'd like to show my WebView2 users the equivalent of MS Edge's "Connection is secure" status and details.  You can see this by clicking the lock icon in the address bar of MS Edge, and then see the details by selecting the "Connection is secure" menu item.
![image](https://user-images.githubusercontent.com/17167099/182390321-203fb71a-f3b7-4c9f-86e9-38b77d62aae5.png)

I have found the [ClientCertificateRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.clientcertificaterequested?view=webview2-dotnet-1.0.1264.42) event and I see that I can get to the `SelectedCertificate` property. Is that the best (easiest) way to implement this, or am I missing a higher level API that would do much of what I need?  Ideally there'd be something that would yield the 4 states of connection security detailed [here](https://support.microsoft.com/en-us/microsoft-edge/securely-browse-the-web-in-microsoft-edge-c7beb47a-de9e-4aec-839d-28224a13a5d2).

**Comment by monica-ch** [comment] 2022-08-03 23:16
@ShaunLoganOracle ClientCertificateRequested event gets raised only when server request client certificate for authentication and I don't think you can use this event to display connection details to the user for all the webview requests. 

However, we have similar feature request recently which can be used for your case I believe #2602.

I am going to close this issue and please use tagged issue to track the status of request.

**Closed by monica-ch** 2022-08-03 23:16 UTC
Labels: question

**Comment by monica-ch** [comment] 2023-02-21 22:04
@ShaunLoganOracle You can use the Chromium Devtools Protocol (CDP) method to get server certificate details:
Win32 API: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.864.35#calldevtoolsprotocolmethod
.NET API: https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.864.35
CDP method (Network.getCertificate): https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getCertificate

Let me know if you run into any problems. Thanks!

**Comment by monica-ch** [comment] 2023-02-21 22:33
or use the ICoreWebView2DevToolsProtocolEventReceivedEventHandler interface and a "[Security.visibleSecurityStateChanged](https://chromedevtools.github.io/devtools-protocol/tot/Security/#event-visibleSecurityStateChanged)" eventName in the GetDevToolsProtocolEventReceiver.

**Comment by ShaunLoganOracle** [comment] 2023-02-23 17:01
Thank you. The latter approach to watch for Security.visibleSecurityStateChanged seems promising.  I have not found a .NET API for ICoreWebView2DevToolsProtocolEventReceivedEventHandler - is there one?

**Comment by monica-ch** [comment] 2023-02-23 17:28
This is the .net API [devtoolsprotocoleventreceived](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2devtoolsprotocoleventreceiver.devtoolsprotocoleventreceived?view=webview2-dotnet-1.0.1518.46)

**Comment by bostjane** [comment] 2023-05-15 07:47
I've tried CDP method (Network.getCertificate), but the result I got is empty ({"tableNames":[]}). I also tried WebView2ApiSample, menu Script->Call CDP method and the result is the same. When I open DevTools for that page, Security clearly shows valid server certificate.

Why it doesn't work?

**Comment by monica-ch** [comment] 2023-05-16 19:56
@bostjane You must navigate to the origin and try calling the CDP method to get the results. I navigated to bing.com in WebView2ApiSample and call the CDP method as `Network.getCertificate {"origin":"https://www.bing.com/"}` and got the server certificate details.

**Comment by bostjane** [comment] 2023-05-17 14:19
@monica-ch That's strange. I did exactly the same and I still get no certificate info. Version is 113.0.1774.42

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7306524/f06d1f37-e864-413b-ba88-0c04f9c446f5)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7306524/102a9094-a734-4753-8430-4b0c3465c610)

**Comment by monica-ch** [comment] 2023-05-19 21:43
@bostjane Have you tried the same with any other sites besides bing.com? How about [Security.visibleSecurityStateChanged](https://chromedevtools.github.io/devtools-protocol/tot/Security/#event-visibleSecurityStateChanged) that also gives to cert info? Does it work for your case?

**Comment by bostjane** [comment] 2023-05-24 07:40
@monica-ch My bad, now works and I can get server certificate. Sorry and thanks for helping.

**Comment by bostjane** [comment] 2023-10-06 12:06
I noticed one but using Security.visibleSecurityStateChanged. How to reproduce:
1. webview2 connects to server with valid certificate A, which consequently gets cached
2. time elapses so certificate A is no longer valid, but expired
3. install new valid certificate B on server
4. webview2 connects to server successfully, but certificate returned via Security.visibleSecurityStateChanged is A, instead of B ?!?

Therefore server certificate info presented to user is wrong, also manual certificate validation fails...

**Comment by monica-ch** [comment] 2023-10-13 17:28
@bostjane Looks like this is an upstream chromium CDP issue. Can you open a bug with them [here](https://bugs.chromium.org/p/chromium/issues/list)? Thanks

**Comment by bostjane** [comment] 2023-10-14 06:25
I did, thanks.
