### ISSUE TITLE
Bizarre Interop Dotnet Object Call Behavior with Methods not being found or invalid Parameter Signatures

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#731] opened 2020-12-10 22:56 UTC
I'm having a bizarre problem with Interop with hosted objects where some methods of my class are accessible and others are not. Not only that it seems that sometimes those methods can be called but at other times they cannot, all the while **the same Interop object** is accessible in JavaScript and other methods work fine.

To create the instance I use a hosted object reference:

```cs
 private void WebBrowser_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {

            DotnetInterop = new WebViewPreviewDotnetInterop(Model, WebBrowser);
            WebBrowser.CoreWebView2.AddHostObjectToScript("mm", DotnetInterop);
            DotnetInterop.JsInterop.InitializeInterop();   /
        }
```

The initializeInterop() method is used to init the browser interop - mainly to pass in the interop object if in other (IE WB) hosted scenarios. Here this isn't needed. But once initialized it immediately calls a method to determine a sync mode and that actually works:

```js
function initializeinterop(editor) {
    // WebView2
    if (window.chrome) {
      te.mmEditor = window.chrome.webview.hostObjects.sync.mm;   // WebView Proxy
      te.mmEditorAsync = window.chrome.webview.hostObjects.mm;
    }
    // CEF
    else if (window.dotnetProxy) {
      te.mmEditor = window.dotnetProxy;
    }   
    else {
      te.mmEditor = editor;
    }

 // THIS WORKS!

    if (te.mmEditor)
      te.isPreviewEditorSync = te.mmEditor.IsPreviewToEditor(false);

    scroll();
}
```

Then later I call a function that updates the content of the document by replacing the body, but not the header that loaded script etc. and I call **that same exact function again** and it fails:

```js
function updateDocumentContent(html, lineno) {

  if (te.mmEditor) {
    try {
      console.log(te.mmEditor.ToString());
      te.isPreviewEditorSync = te.mmEditor.IsPreviewToEditor(false);
    } catch (ex) {
      console.log(ex.message);
    }
  }

  ... // update doc content inside of <div#MainContent>.
```

This seems to work once, then never again. You might say: The reference probably gets destroyed in the update, but that doesn't appear to be so as I can access all other methods but not that one.

This screen shot demonstrates:

![image](https://user-images.githubusercontent.com/1374013/101841267-b1389b00-3ae9-11eb-8967-4ea9551fc804.png)

Notice that the object reference (`te.mmEditor`) is there and it works with various other methods. But calling the same `IsPreviewEditorToSync(false)` method fails **even though it worked during doc initialization** (I can see it firing in .NET in the debugger the first time). When running the ` console.log(te.mmEditor.ToString())` produces the class name so the instance is definitely there and working.

Anybody have any idea what the heck could be going on here?

[AB#31049439](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31049439)

**Comment by RickStrahl** [comment] 2020-12-10 23:18
Just updated with a fixed screen shot. I've been experimenting with different parameter signatures for the function that's failing (as well as renaming in case that the `Sync` had an impact. Made sure it fails with the right signatures.

To re-iterate the really weird thing to me is this: 

* Why does it work on initialization and not on the second call
* Why is the error 'Element not found'? Other interop errors tend to be more reflection accurate (ie. invalid parameter, or method not found)

**Comment by cgeier** [comment] 2020-12-10 23:21
@RickStrahl The error `Invalid number of parameters. (0x8002000E)` occurs when you try to access an object that's depth is > 3. Hostobjects only supports a depth of 3.

Ex:

**ComputerInfo.cs**

```
string Description { get; set; }

string Manufacturer { get; set; }

string Model { get; set; }

string SerialNumber { get; set; }
```

**CompanyAssetInfo.cs**

```
              ...
public List<ComputerInfo> Computers { get; set; } = new List<ComputerInfo>();

public void AddComputer(string description, string make, string model)
{
        //add to list
        Computers.Add(new ComputerInfo(description, make, model));
}

              ...
```

**EmployeeInfo.cs**

```
              ...
public CompanyAssetInfo CompanyAssets { get; set; } = new CompanyAssetInfo();

 public void AddAssetComputer(string description, string make, string model, string serialNumber)
{
        CompanyAssets.AddComputer(description, make, model, serialNumber);
}

              ...
```

Using the following code will cause error `Invalid number of parameters. (0x8002000E)`
     
`chrome.webview.hostObjects.sync.employee.AddAssetComputer('Laptop','HP','Pavilion','SN: 12345');`

**Comment by cgeier** [comment] 2020-12-10 23:26
I can't see your entire class, but make sure you have `[ComVisible(true)]` above the class name. See #517, where I showed how to use `[ClassInterface(ClassInterfaceType.None)]` and an interface.

**Comment by RickStrahl** [comment] 2020-12-10 23:53
Added the `[ComVisible(true)]` but that had no effect.  It works the same as when it's not there for this object. My object is pretty simple - single level with top level methods. There are internal properties but those aren't COM visible so shouldn't have an impact.

I'm in the middle of the commit that has this code in it - I'll post a link once it goes in so you can see the whole code along with the relevant files.


I figured hack that works sort of by basically duplicating that function and calling one during initialization and one from content update routine. For some unfathomable reason that now works. But it makes **zero** sense. Why is this the first method disappearing on me?

```cs
        public bool IsPreviewToEditor()
        {
            try
            {
                if (Model.ActiveEditor != null)
                    return Model.ActiveEditor.IsPreviewToEditorSync();

                return false;
            }
            catch
            {
                return false;
            }
        }

        public bool IsPreviewToEditor2()
        {
            try
            {
                if (Model.ActiveEditor != null)
                    return Model.ActiveEditor.IsPreviewToEditorSync();

                return false;
            }
            catch
            {
                return false;
            }
        }
```

**Comment by mrsteamfist** [comment] 2020-12-11 00:07
Thanks for the feedback @RickStrahl. My gut on this is your use of sync, https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.664.37
`
te.mmEditor = window.chrome.webview.hostObjects.sync.mm;
`
This may be why your C# code does not work as expected. Our documentation only states this:
`sync Asynchronous host object proxies expose a sync method which returns a promise for a synchronous host object proxy for the same host object. For example, chrome.webview.hostObjects.sample.methodCall() returns an asynchronous host object proxy. You can use the sync method to obtain a synchronous host object proxy instead: const syncProxy = await chrome.webview.hostObjects.sample.methodCall().sync()`

I am going to do some track this.

**Comment by mrsteamfist** [comment] 2020-12-11 01:09
@RickStrahl, it seems this is a known issue that was fixed and should be in the latest nuget package. https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.721-prerelease. Let me know if the issue is not fixed for you.

**Comment by RickStrahl** [comment] 2020-12-11 03:38
Part of my problem here is that I need this code to work in IE as well as in the Chromium due to the use of the WebBrowser control and Chromium as an alternative. So using Async is not an option as the classic COM interface can't make async calls. That's the reason I've been sticking with the Sync interface rather than just using async. 

As to using the newer pre-release - Can't use that because users can't download a runtime that matches that from the official source. So I've been using 644 (I think) until the runtimes are updated. 

Hmmm... actually how do I get the newer runtime since the download is older? I'm not even sure how the original runtime (which was higher) got onto my machine. Is it through the NuGet package?

**Comment by cgeier** [comment] 2020-12-11 15:26
InitializeAsync should be `Task` not `void` (the code won't execute in the expected order if it's void) `. Here are some suggestions:

**IPreviewBrowser.cs**

```
[ComVisible(true)]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface IPreviewBrowser
{
    //ToDo: remove any property, method, or function that doesn't 
    //          need to be COM visible from the interface
    //
    //           any parameter default values are set in the interface

    MainWindow Window { get; set; }

    AppModel Model { get; set; }

    bool IsVisible { get; set; }

    WebViewPreviewDotnetInterop DotnetInterop { get; set; }

    WebViewPreviewJavaScriptInterop JsInterop { get; set; }

    WebViewPreviewHandler(WebView2 webViewBrowser);

    Task InitializeAsync();

    void Dispose();

    void PreviewMarkdown(MarkdownDocumentEditor editor = null, bool keepScrollPosition = false, 
        bool showInBrowser = false, string renderedHtml = null, int editorLineNumber = -1);

    Task PreviewMarkdownAsync(MarkdownDocumentEditor editor = null, bool keepScrollPosition = false,
        string renderedHtml = null, int editorLineNumber = -1);

    void ScrollToEditorLine(int editorLineNumber = -1,
        bool updateCodeBlocks = false,
        bool noScrollTimeout = false,
        bool noScrollTopAdjustment = false);

    Task ScrollToEditorLineAsync(int editorLineNumber = -1, bool updateCodeBlocks = false,
        bool noScrollTimeout = false, bool noScrollTopAdjustment = false);

    void Navigate(string url);

    void Refresh(bool noCache);

    void ExecuteCommand(string command, params dynamic[] args);

    void ShowDeveloperTools();
}

```


**WebViewPreviewHandler.cs**


```
[ComVisible(true)]
[ClassInterface(ClassInterfaceType.None)]
public class WebViewPreviewHandler : IPreviewBrowser
{
                  ...
}
```

**WebViewPreviewHandler constructor**  (WebViewPreviewHandler.cs)

```
public WebViewPreviewHandler(WebView2 webViewBrowser)
{
              ...
  
    // ToDo: Call 'InitializeAsync' after this class has been created
    //       
    // ex: 
    //       WebViewPreviewHandler myWebViewPreviewHandler = new WebViewPreviewHandler();
    //       await myWebViewPreviewHandler.InitializeAsync();

}

```

InitializeAsync should be `Task` not `void` (the code won't execute in the expected order if it's void)

**InitializeAsync**  (WebViewPreviewHandler.cs)

```
public async Task InitializeAsync()
{
    var browserFolder = Path.Combine(mmApp.Configuration.CommonFolder, "WebView_Browser");
    // must create a data folder if running out of a secured folder that can't write like Program Files
    var env = await CoreWebView2Environment.CreateAsync(
        userDataFolder: browserFolder
    );

    await WebBrowser.EnsureCoreWebView2Async(env);

    if (Model.Configuration.System.ShowDeveloperToolsOnStartup)
        WebBrowser.CoreWebView2.OpenDevToolsWindow();
}

```

This one may need to be a Task as well.

** PreviewMarkdownAsync** (WebViewPreviewHandler.cs)

```
 //default values are set in interface
public async Task PreviewMarkdownAsync(MarkdownDocumentEditor editor, bool keepScrollPosition,
    string renderedHtml, int editorLineNumber)
{
              ...
}

```

**WebViewPreviewDotnetInterop.cs**

```
[ComVisible(true)]
[ClassInterface(ClassInterfaceType.None)]
public class WebViewPreviewDotnetInterop : IWebViewPreviewDotnetInterop
{
             ...
}

```

**IWebViewPreviewDotnetInterop.cs**

```
[ComVisible(true)]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface IWebViewPreviewDotnetInterop
{

      //ToDo: remove any property, method, or function that doesn't 
      //          need to be COM visible from the interface
     //
    //           any parameter default values are set in the interface

    WebViewPreviewJavaScriptInterop JsInterop { get; }

    void InitializeInterop();

    void gotoLine(object editorLine, object noRefresh);

    void GotoBottom(object noRefresh, object noSelection);


    void PreviewContextMenu(string positionAndElementType);

    bool PreviewLinkNavigation(string url, string src = null);

    bool IsPreviewToEditorSync();
}

```

**Comment by mrsteamfist** [comment] 2020-12-11 18:09
I have not checked out the example code. At one point someone on the team will take a look. Thanks @cgeier for checking out the code too.

**Comment by hunkydoryrepair** [comment] 2020-12-11 23:10
> Part of my problem here is that I need this code to work in IE as well as in the Chromium due to the use of the WebBrowser control and Chromium as an alternative. So using Async is not an option as the classic COM interface can't make async calls. That's the reason I've been sticking with the Sync interface rather than just using async.

I had this same issue. Finally bit the bullet and made them all work asynchronously, simulating callback behavior in the WebBrowser case (runs syncrhonously but returns value through a callback). A few simple interfaces that just return known values, I handled with injection and just insert the values into the javascript with each page load. A lot of changes but once it was done, WebView2 and CEF working asynchonously and WebBrowser works as well as it can.

**Comment by RickStrahl** [comment] 2020-12-13 08:09
@cgeier - thanks for the review. I think some of your suggestions may not be necessary since most of the functionality is actually working. Specifically calling **into JavaScript seems to work reliably**. What's not working is that that **calls from JavaScript into .NET using the Host object** will stop working after firing a few times (even after switching to async signatures).

To that changed the way the JS code calls into .NET via another abstract object that figures out which object instance to use so I can call async with the WebView and sync for the COM IE control. 

```javascript
dotnetInterop: {
    getEditor: function() {
      if (te.mmEditorAsync)
        return te.mmEditorAsync;
      if (te.mmEditor)
        return te.mmEditor;

      return null;
    },
    previewContextMenu: function(parm) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
          return;
      editor.PreviewContextMenu(JSON.stringify(parm));
    },
    previewLinkNavigation: function(url, rawHref) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return false;

      return editor.PreviewLinkNavigation(url, rawHref);
    },
    gotoBottom: function(updateEditor) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return;

      editor.GotoBottom(updateEditor || false);
    },
    gotoLine: function(line, updateEditor) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return;

      editor.GotoLine(line, updateEditor || false);
    },
    isPreviewEditorToSync: function() {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return false;
      te.isPreviewEditorSync = editor.IsPreviewToEditorSync();

      return te.isPreviewEditorSync;
    }
  }
};
```

With the .NET methods in the WebView handler being async:

```csharp
/// <summary>
        /// Navigates the Editor to a specified line
        /// </summary>
        /// <param name="editorLine"></param>
        /// <param name="noRefresh"></param>
        public async Task GotoLine(object editorLine, object noRefresh)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                Model.ActiveEditor?.GotoLine(Convert.ToInt32(editorLine), (bool)noRefresh);
            });
        }

        /// <summary>
        /// Goes to the bottom of the editor
        /// </summary>
        /// <param name="noRefresh"></param>
        /// <param name="noSelection"></param>
        public async Task GotoBottom(object noRefresh, object noSelection)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                Model.ActiveEditor?.GotoBottom((bool)noRefresh, (bool)noSelection);
            });
        }


        /// <summary>
        /// Shows the WPF Preview menu
        /// </summary>
        /// <param name="positionAndElementType"></param>
        public async Task PreviewContextMenu(string positionAndElementType)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                var pos = JsonSerializationUtils.Deserialize(positionAndElementType, typeof(PositionAndDocumentType));
                mmApp.Model.Window.PreviewBrowser.ExecuteCommand("PreviewContextMenu", pos);
            });
        }
...
```


These calls work about 3-4 times and then start failing. They also fail if hook up the debugger and stop in .NET for more than a brief moment. It seems  that the .NET object disconnects from the host even though the JavaScript code doesn't see a change in the .NET editor reference.

These methods presumably return promises and currently I'm not handling them, but most methods don't actually return a value and it does seem to actually work without promise logic (like the call to `isPreviewToEditorSync()`):

So this works in the JavaScript handler `initInterop()`:
```javascript
    if (te.mmEditor) {
      // te.mmEditor.IsPreviewToEditorSync();
      te.isPreviewEditorSync = te.dotnetInterop.isPreviewEditorToSync(); 
    }
```

The `te.isPreviewEditorSync` is getting set even through the editor in this case is making an async call.

Bottom line it seems that the interop in this case is very unstable. It seems to work for a bit then starts failing.

The behavior with these async calls is pretty much the same behavior I had with the sync calls, so don't think this is directly related to sync/async problems.

I understand that you're pointing out that some of my calls aren't async - that's because I can't get them async right now due to the dual operation between IE and WebView. In the cases where non-async calls are made however, I think that should still work - they just end up being fire and forget calls:

```csharp
       public void InitializeInterop()
        {
            // async - fire and forget we don't have to wait
            _ = JsInterop.InitializeInterop();
        }
```

Timing doesn't appear to be a problem here, because all the initial function calls work just fine (ie. ContextMenu/Link Nav/Editor Navigation) a few times.

If I can eventually make the switch to the WebView for both the editor and preview then I can re-think the top down async approach but it this time it's not really an option for me beyond the changes that I made up to this point. There are a few big blockers before I can make that jump unfortunately.

**Comment by RickStrahl** [comment] 2020-12-13 09:00
@cgeier - thanks for the review. I think some of your suggestions may not be necessary since most of the functionality is actually working. Specifically calling **into JavaScript seems to work reliably**. What's not working is that that **calls from JavaScript into .NET using the Host object** will stop working after firing a few times (even after switching to async signatures).

To that effect I changed the way the JS code calls into .NET via another abstract object that figures out which object instance to use so I can call async with the WebView and sync for the COM IE control. 

```javascript
dotnetInterop: {
    getEditor: function() {
      if (te.mmEditorAsync)
        return te.mmEditorAsync;
      if (te.mmEditor)
        return te.mmEditor;

      return null;
    },
    // TODO: Make all this work with Async/Await once IE is dropped
    // always return the sync instance for callbacks that return
    // values (2 funcs). All others use the async version.
    getEditorSync: function() {
      if (te.mmEditor)
        return te.mmEditor;

      return null;
    },
    previewContextMenu: function(parm) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
          return;
      editor.PreviewContextMenu(JSON.stringify(parm));
    },
    previewLinkNavigation: function(url, rawHref) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return false;

      return editor.PreviewLinkNavigation(url, rawHref);
    },
    gotoBottom: function(updateEditor) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return;

      editor.GotoBottom(updateEditor || false);
    },
    gotoLine: function(line, updateEditor) {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return;

      editor.GotoLine(line, updateEditor || false);
    },
    isPreviewEditorToSync: function() {
      var editor = te.dotnetInterop.getEditor();
      if (!editor)
        return false;
      te.isPreviewEditorSync = editor.IsPreviewToEditorSync();

      return te.isPreviewEditorSync;
    }
  }
};
```

With the .NET methods in the WebView handler being async:

```csharp
/// <summary>
        /// Navigates the Editor to a specified line
        /// </summary>
        /// <param name="editorLine"></param>
        /// <param name="noRefresh"></param>
        public async Task GotoLine(object editorLine, object noRefresh)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                Model.ActiveEditor?.GotoLine(Convert.ToInt32(editorLine), (bool)noRefresh);
            });
        }

        /// <summary>
        /// Goes to the bottom of the editor
        /// </summary>
        /// <param name="noRefresh"></param>
        /// <param name="noSelection"></param>
        public async Task GotoBottom(object noRefresh, object noSelection)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                Model.ActiveEditor?.GotoBottom((bool)noRefresh, (bool)noSelection);
            });
        }


        /// <summary>
        /// Shows the WPF Preview menu
        /// </summary>
        /// <param name="positionAndElementType"></param>
        public async Task PreviewContextMenu(string positionAndElementType)
        {
            await Model.Window.Dispatcher.InvokeAsync(() =>
            {
                var pos = JsonSerializationUtils.Deserialize(positionAndElementType, typeof(PositionAndDocumentType));
                mmApp.Model.Window.PreviewBrowser.ExecuteCommand("PreviewContextMenu", pos);
            });
        }
...
```

After a bunch of back and forth I've managed to get these to work somewhat reliably, but... it seems that anytime a failure occurs during any of the COM interop calls, the COM object completely disconnect and no longer works.

Initially I had one of the parameter signatures wrong for `GotoBottom` so effectively the call failed and I get a JavaScript Promise rejection message. After that happens none of the calls work any longer... Most of the Interop calls I make are fire and forget (with two low frequency call exceptions whcih for now I call synchronously). That seems to work much better, but it still bonks if anything at all goes wrong.

It seems that the Host object should be more resilient if a failure occurs and not disconnect everything (resulting in the dreaded `Element not Found` error on any method access after).

I suspect properly using promises/async/await and using proper exception/catch() handles might fare better here, but at this point I'm not in a position to make that code happen in my existing code base as I have to continue to support IE as the primary preview browser mechanism (cause it works reliably!).

**Comment by cgeier** [comment] 2020-12-13 13:12
I had issues with hostobjects initially too. I added exception handling (try-catch) in the JS. I also seemed to have issues when I tried to use `var` in JS. I refactored my code and now use `let`.

**Comment by RickStrahl** [comment] 2020-12-13 22:30
@cgeier - thanks. Added that too (for sync calls) but that didn't seem to make a difference. In my cases the page is fairly long lived with only the content getting updated and the failures seem to occur randomly. I see both with sync and async ops so I don' think the issue is the sync vs. async part.

I did update to Canary (again) and the latest Preview library - this seems to work much better than the current Release version, which fails fast. The Canary version is much better - still fails but it takes considerably longer.

I think the issue still is **if there is some sort of failure in calling the host object in any way - even if there's an exception handler on both ends - the binding to that specific method call gets wiped out.**  I have to do some more experimenting to really make sure that's the right conclusion but at a glance that's what it looks like. The good news is that in the latest pre-release at least there's no internal untrappable error but only my code that can blow it up 😆 - that's progress!

At minimum I hope a release update to the runtime can make it out soon as that would fix most of my pressing preview issues.

**Comment by champnic** [comment] 2021-01-09 00:05
@RickStrahl We have seen some errors in the past when the host object is cached in javascript in a variable. Can you try the full call each time (at least to verify this is the cause), for example:
`window.chrome.webview.hostObjects.sync.mm.IsPreviewToEditor(false);`

**Comment by RickStrahl** [comment] 2021-01-09 21:04
@champnic  Yes that seems to work well! Thank you - that gets me over the hump with one issue! 

Luckily I switched to an abstraction layer for making all the interop calls so this was a relatively easy change to make:

```js
dotnetInterop: {
  getEditor: function() {
      if (window.chrome) {
        // WebView interop instance  does not want to be cached
        return window.chrome.webview.hostObjects.mm || window.chrome.webview.hostObjects.sync.mm;
      }
      // this is the cached instance - don't use with WebView2
      return te.mmEditorAsync || te.mmEditor || null;
    },
    // TODO: Make all this work with Async/Await once IE is dropped
    // always return the sync instance for callbacks that return
    // values (2 funcs). All others use the async version.
    getEditorSync: function() {
      if (window.chrome) {
        // WebView instance does not want to be cached
        return window.chrome.webview.hostObjects.sync.mm;
      }
      return te.mmEditor || null;
    gotoLine: function(line, updateEditor) {
      let editor = te.dotnetInterop.getEditor();
      if (!editor)
        return;
      try {
        editor.GotoLine(line, updateEditor || false);
      } catch (ex) {}
    },
}
```

and:

```js
te.dotnetInterop.gotoLine(line, true);
```

The one that was giving me problems as it gets called from the scroll function, which often has overlapping calls from many scroll events. With the change it now doesn't hang up any more. Previously the scroll sync would work a few scrolls and then stop. Now it works.

While I'm glad this fixes the issue, is it possible to not have this behavior? This is likely to trip up a lot of people. I tend to store my objects and reuse them in abstractions usually. In this case it works because I have a factory function anyway due to the support for differences in IE and WV but normally I wouldn't and then making the change you suggest would be ugly as heck - especially given the long object hierarchy you have to drill into.

**Comment by champnic** [comment] 2021-01-12 17:45
Yes we intend to fix the caching problem. As noted this is a common and hard to diagnose error that people will be running into, and the workarounds, while not too complex, can be cumbersome and prone to breaking.

**Comment by vbryh-msft** [comment] 2021-10-20 23:07
@RickStrahl I'm trying to write simple repro for this issue. Here is the code:
```
   [ComVisible(true)]
    public class TestRemoteObject
    {
        // Sample function that takes a parameter.
        public string Func(int param)
        {
            return "TestRemoteObject.Func(" + param + ")";
        }
    }
```
JS console output:
```
var test = chrome.webview.hostObjects.testObject;
await test.Func("string");
 - Uncaught Error: No such interface supported (0x80004002)
await test.Func(1);
 - TestRemoteObject.Func(1)'
```
Do you have suggestion where I should go from there - how to simulate the failure which will wipe out the method binding which you have seen? Was issue happening intermittently or consistently for some flows?

**Comment by champnic** [comment] 2022-01-07 01:18
Unable to repro this issue, closing. Let me know if you have more info and we can potentially take another look. Thanks!

**Closed by champnic** 2022-01-07 01:18 UTC
Labels: bug, tracked

**Comment by RickStrahl** [comment] 2022-01-07 02:17
Frankly I haven't tried this in some time. 

The issue originally was that the host instance was not sticky - it would disconnect through different call contexts. if I always **explicitly** referenced the host object for each call context then there's no problem (ie. what .getEditor() does). I haven't checked if that's changed, since I now just make very sure I always access a current instance of the host object explicitly usually by re-capturing the host instance as part of the current call context explicitly. That works fairly reliably.

It's possible that by now the instance is not transient and can be accessed if stored, but I wouldn't know since I've reworked my code to not do that 😄

**Comment by champnic** [comment] 2022-01-07 18:42
No worries, thanks Rick! We'll take a look at this issue again if we hear it from other folks :)
