### ISSUE TITLE
Webview2 not loading in both UWP and Winui3

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftEdge/WebView2Feedback#3318] opened 2023-03-19 18:45 UTC
**Description**
The webview2 controls suddenly refuse to load in both Winui 2 Gallery and WinUI3 Gallery, with winui2 giving me the error message and winui3 showing a blank screen as in the screenshots. 
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/42881734/226199753-ced36eca-5774-4269-9d05-ed7cd23ef0cd.png">

**Version**
SDK: Don't know what version winui gallery uses, but both are the latest version downloaded from store.
Runtime: 111
Framework: UWP, WASDK 1.2
OS: Win11

**Repro Steps**

**Screenshots**

**Additional context**

[AB#44119262](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44119262)

**Comment by novac42** [comment] 2023-03-20 04:51
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by maurawinstanley** [comment] 2023-04-10 19:04
@HO-COOH thanks for reaching out, we were able to repro this bug and are tracking it internally.

**Comment by maurawinstanley** [comment] 2023-04-19 19:45
@HO-COOH we were able to repro this issue with WebView2 runtime 111, and when upgraded to 112 the issue did not repro.  Are you able to update your WebView2 runtime to 112 and confirm whether this fixes your issue?

**Comment by pieths-ms** [comment] 2023-04-19 21:00
Closing this bug since this does not appear to repro with 112. WebView2 version 112 should get automatically installed when Edge updates. @HO-COOH, if you are still seeing this issue with 112 please re-open the bug. Thanks.

**Comment by HO-COOH** [comment] 2023-04-20 02:28
Was still able to reproduce this, and still it shows an empty page on WinUI3. I was able to find out the injected dll, but I think the issue now becomes webview2 on WinUI3 shows an empty page which is really confusing to the user. (Like is it the page loading slow or the renderer process crashed?)

**Comment by pieths-ms** [comment] 2023-04-20 19:01
Hi @HO-COOH. Thanks for verifying that this issue is still occurring. A few questions:

1. Which dll is being injected?
2. Are you running any security/antivirus software? If so, which one and is it up to date?
3. Are you only seeing the issue in the WinUI3 gallery app or is the WinUI2 gallery app also still showing the error?
4. Which version of WebView2 is the app (where you see the issue) trying to use?

One way to find the version of WebView2 which an app is using is to open task manager, right click on the "Microsoft Edge WebView2" process and select "Properties". The version can be found in the "Location" item.

<img width="558" alt="WebView2_Location" src="https://user-images.githubusercontent.com/53836562/233461747-28750524-54c9-4995-ac40-1294b1c006ba.png">

**Comment by HO-COOH** [comment] 2023-04-21 10:12
> Hi @HO-COOH. Thanks for verifying that this issue is still occurring. A few questions:
> 
> 1. Which dll is being injected?
> 2. Are you running any security/antivirus software? If so, which one and is it up to date?
> 3. Are you only seeing the issue in the WinUI3 gallery app or is the WinUI2 gallery app also still showing the error?
> 4. Which version of WebView2 is the app (where you see the issue) trying to use?
> 
> One way to find the version of WebView2 which an app is using is to open task manager, right click on the "Microsoft Edge WebView2" process and select "Properties". The version can be found in the "Location" item.
> 
> <img alt="WebView2_Location" width="558" src="https://user-images.githubusercontent.com/53836562/233461747-28750524-54c9-4995-ac40-1294b1c006ba.png">

The inject dll in in the log. Winui2 gallery and winui3 gallery behaves the same as the screenshot in OP.
```
Code Integrity determined that a process (\Device\HarddiskVolume4\Program Files (x86)\Microsoft\EdgeWebView\Application\112.0.1722.39\msedgewebview2.exe) attempted to load \Device\HarddiskVolume4\Windows\System32\winhafnt64.dll that did not meet the Microsoft signing level requirements.
```

**Comment by pieths-ms** [comment] 2023-04-21 21:22
@HO-COOH this appears to be a duplicate of this bug: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2051

winhafnt64.dll appears to be a dll created by TEC Solutions as part of their Ocular Agent. Do you have this (or something similar) installed on your system?

There is a workaround mentioned in the other bug. Can you try setting these registry keys and see if it resolves the issue?

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"RendererCodeIntegrityEnabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2]
"RendererCodeIntegrityEnabled"=dword:00000000
```

**Comment by HO-COOH** [comment] 2023-04-23 02:22
@pieths-ms  This workaround works, but why does the webview2 renders the error page under winui2 but not under winui3?

**Comment by pieths-ms** [comment] 2023-04-27 22:47
> @pieths-ms This workaround works, but why does the webview2 renders the error page under winui2 but not under winui3?

I have created a bug for this and we will be tracking it internally.

Closing this bug since the original issue where WebView2 was not loading has been addressed.

**Closed by pieths-ms** 2023-04-27 22:47 UTC
Labels: bug, tracked
