### ISSUE TITLE
Version 1.0.1264.42 breaks csproj file and has impact on generated resource base name

### ISSUE THREAD

**Issue by OndrejVrsan** [MicrosoftEdge/WebView2Feedback#2621] opened 2022-07-25 16:37 UTC
**Description**
When referencing current latest version (1.0.1264.42), the C# project is "broken"
Symptoms:
 - Properties window in Visual Studio shows `SynthesizedEmpty` instead `Project properties` heading
 - No properties are shown (instead File Name, Full Path, Project folder)
 - In case there is Resource file, generated code is missing project name in its base name in `ResourceManager` constructor

**Version**
Nuget Package: 1.0.1264.42
Framework: NET 6
OS: Windows 11 21H2 OS Build 22000.832

**Repro Steps**
1. Create NET 6 Class library project in Visual Studio 2022 (17.2.6)
2. Reference Microsoft.Web.WebView2 version `1.0.1245.22`
3. Select project, press F4 to view properties
   - Expected: Project properties - File Name, Full Path, Project folder
   - Actual: No project properties 
4. Add Resource file, save it, view generated code
   - Expected: `ResourceManager` has in ctor `"<project_name>.<resource_name>"` base name
   - Actual: `ResourceManager` has in ctor `"<resource_name>"` base name
5. Reference older version `1.0.1245.22`
   - ✅ Expectations are met

**Screenshots**
VersionWithBug
![image](https://user-images.githubusercontent.com/17138864/180827523-97dd16af-ee1d-409d-87d8-74042baf6262.png)
![image](https://user-images.githubusercontent.com/17138864/180827091-7a154dfe-c3ee-4ef6-8d76-d50ccdbea298.png)

VersionWithoutBug
![image](https://user-images.githubusercontent.com/17138864/180827663-04bf182e-7ce8-488f-a850-b8c396d4a5b4.png)
![image](https://user-images.githubusercontent.com/17138864/180826863-9366bbba-9b39-45c4-8e6d-e9049e1e4bd5.png)

**Additional context**
[WebView2Repro.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9183148/WebView2Repro.zip)

**Comment by OndrejVrsan** [comment] 2022-07-25 16:40
Ahh, just found #2583

**Comment by nishitha-burman** [comment] 2022-07-25 20:34
Closing this issue since it is a duplicate of [#2583](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2583)

**Closed by nishitha-burman** 2022-07-25 20:34 UTC
Labels: bug
