### ISSUE TITLE
WebView2 isn't respecting the Profile.PreferredColorScheme for the scrollbars

### ISSUE THREAD

**Issue by zhuman** [MicrosoftEdge/WebView2Feedback#3696] opened 2023-08-08 22:05 UTC
**Description**
Setting the CoreWebView2.Profile.PreferredColorScheme to Dark doesn't affect the scrollbars in a WinUI3 app using WinAppSDK.

```csharp
await myWebView.EnsureCoreWebView2Async();
myWebView.CoreWebView2.Profile.PreferredColorScheme = (this.ActualTheme == ElementTheme.Dark) ? CoreWebView2PreferredColorScheme.Dark : CoreWebView2PreferredColorScheme.Light;
```

**Version**
SDK: Packaged in the WinAppSDK
WinAppSDK: 1.3.230724000
Runtime: Stable channel Edge I assume
Framework: WinUI3 using WinAppSDK
OS: Win11 Dev Channel build 23521

**Regression**
Was this working before but has regressed? no, this is the first version of the WinAppSDK that has the PreferredColorScheme available I think
If yes, what version did this last work on? N/A

**Repro Steps**
1. Create a WinAppSDK project using WinUI3
2. Create a WebView2 control
3. Use the code above to set the PreferredColorScheme based on the app theme, and use a dark theme.

**Screenshots**

**Additional context**

**Comment by novac42** [comment] 2023-08-09 03:52
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by johna-ms** [comment] 2023-10-18 00:01
@zhuman  I am seeing the theme color respected. Is there a website that is or isn't working for you or is it any website that normally honors theme color? If so have you tested on the normal edge browser?

**Comment by bojan-sala-igt-com** [comment] 2023-10-28 21:08
I can confirm this doesn't work in WinUI3 (using the latest version). 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/108935163/1df9946c-4538-4410-a158-3d25a02d63a9)
Basically, system default scrollbar is always in light mode, no matter what we do to it. Styling it in css results in another (much worse) bug where mouse capture stops as soon as the cursor goes off of control boundaries (described in detail here https://github.com/microsoft/microsoft-ui-xaml/issues/8677) so there isn't really any workaround.

**Comment by johna-ms** [comment] 2023-11-01 04:00
@bojan-sala-igt-com - thank you for the screenshot! I'm thinking this is a website issue. What website are you using in the screenshot? When I'm on youtube or github.com/features/codespaces, websites I know to respect OS theme, the scrollbar is dark with no other code.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/63807693/55c31d82-d88c-48a1-a122-7bfead857a2e)

**Comment by bojan-sala-igt-com** [comment] 2023-11-01 10:53
It was indeed a website issue, which I found out later and edited the comment but wasn't 100% sure if that's intended behavior 🙂

Doing something along the lines of:
```js
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
  document.documentElement.setAttribute('data-theme', 'dark');
} else {
  document.documentElement.setAttribute('data-theme', 'light');
}
```
Fixed it for me.

**Comment by gave92** [comment] 2023-11-01 11:48
Adding `<meta name="color-scheme" content="dark light">` also appears to be necessary for me to get dark mode scrollbars.

**Comment by dianaqu** [comment] 2024-01-23 01:52
Hi all folks in the thread. Yes, you need to make sure your page's `color-scheme` is set to `light dark` in order for the scrollbar to follow the webview2 color-scheme change. It's the same behavior as browser.

**Closed by dianaqu** 2024-01-23 01:52 UTC
Labels: bug
