### ISSUE TITLE
Very slow to load (15seconds, AV?) - Is there a way to reuse CoreWebView2 for multiple controls

### ISSUE THREAD

**Issue by SimonA84** [MicrosoftEdge/WebView2Feedback#522] opened 2020-10-12 13:20 UTC
Hi,
I'm using version 0.9.628-preview for a plugin in a third-party app. To make the plugin easier I use a fixed path for the browserExecutableFoler, which is used for creating the CoreWebView2Environment.
For some functional parts I need an additional Form with a WebView2 control.
The task for CoreWebView2Environment.CreateAsync resolves very fast, but the task for webView2Control.EnsureCoreWebView2Async takes currently 15 seconds. To make the plugin more responsable I want to reuse the CoreWebView2 instead of creating it for every webView2 control.
Is there a possible solution to reuse this for multiple controls?

[AB#29780123](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29780123)

**Comment by champnic** [comment] 2020-10-12 16:38
EnsureCoreWebView2Async shouldn't take anywhere near 15 seconds. I believe we received a similar report from another partner, and our current guess is Antivirus software is interfering with the binaries loading and running. Are you running any AV software?

You can't reuse a given CoreWebView2 object, but if you create a new WebView2 control with the same environment, it will reuse the same runtime processes (except for the renderer process, which is per site). This should avoid the 15 seconds the second time you call EnsureCoreWebView2Async.

I'm tracking this as a bug on our end for the slow loading though. Thanks!

**Comment by SimonA84** [comment] 2020-10-13 05:44
On my system is the AV from Sophos running. The company where I'm working decides to use this AV.

**Comment by champnic** [comment] 2020-10-13 06:27
Are you able to disable the AV temporarily to test if that is the cause?

**Comment by SimonA84** [comment] 2020-10-13 06:45
That's not possible. We aren't allowed to disable the AV. In the past we could do this.

**Comment by SimonA84** [comment] 2020-10-13 12:47
I changed my code to wait till the first EnsureCoreWebView2Async resolves. For making this more responsive I use AutoResetEvents.
What now happens is, that two different "EmbeddedBrowserWebView.dll" are included. One in a runtime-directory I defined and one from the Path where it's installed.

**Comment by SimonA84** [comment] 2020-10-13 15:01
What I found out is, that it only takes so long when the runtimepath is set in the CoreWebView2EnvironmentOptions.

**Comment by champnic** [comment] 2020-10-13 16:36
Oh interesting. Are you able to see what runtime/version it was using before and after the change to runtimepath? I'm curious if the slow loading is tied to a particular type of runtime (Edge Beta vs WV2 Runtime, for example).

**Comment by SimonA84** [comment] 2020-10-14 05:37
For the first initialized control is a copy used which is located in **%lcoalappdata%\Company\runtime\<runtime-version>**. For the other control is the runtime used which came with the installer from https://developer.microsoft.com/en-us/microsoft-edge/webview2/.
I copied it to the first location to have a stable runtime for our customers, which should not have to take care about updating the runtime.

**Comment by champnic** [comment] 2020-10-14 16:57
Gotcha. If you run and install the WebView2 Runtime, it will update automatically with no work necessary by you or the customer - it's what we call our Evergreen version. If you prefer to manage shipping new runtime bits at your own cadence and copying them yourself, you'll want to use our Fixed Version, which should be releasing in public preview in the next week or two.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

To confirm though, the version that you manually copied was the one that experienced the slow loading correct? My guess is that the AV software was scanning the files on disk and took a long time.

**Comment by SimonA84** [comment] 2020-10-15 06:25
I prefere to control the update. The reason is that I cannot say that if the customers update the plugin every time and so I cannot guarantee that it works with different versions.

Yes the copied version was the slow loading one. But as far as I know is the AV scanning the files only the first time, during the copy task very intensive.

**Comment by SimonA84** [comment] 2020-10-19 12:25
I was able to load the WebView2 in 3-4 seconds after the first initialization, which is better but for our usecase still to slow.

As a user it's ugly to wait, that the ui shows some changes in the new window after you clicked on a button.

**Comment by LiangTheDev** [comment] 2020-10-28 19:53
After first usage, creating a WebView2 when there is no other running WebView2 could be a little slow, creating another WebView2 if there is already a running WebView2 (sharing the same user data folder) should be fast.

We could also pre-create an invisible WebView2, and show it when user clicked the button.

For reuse CoreWebView2 for multiple controls, each control has to have its own CoreWebView2.
Multiple CoreWebView2s do sharing most of the WebView browser processes and creating additional CoreWebView2 should be fast while there is an existing CoreWebView2 running.
If we are navigating between forms, we could also try moving the whole WebView2 control from one form to another, like Controls.Remove(webview2Control) from one form and Controls.Add(webview2Control) to another form.

**Comment by LiangTheDev** [comment] 2020-11-12 20:06
Closing this issue. Please reopen if there is further feedback.

**Closed by LiangTheDev** 2020-11-12 20:06 UTC
Labels: bug, question, tracked
