### ISSUE TITLE
[Problem/Bug]: WebView2 crashes when accessing entire page "edge://wallet/"

### ISSUE THREAD

**Issue by naldobr** [MicrosoftEdge/WebView2Feedback#4782] opened 2024-08-30 22:35 UTC
### What happened?

After a recent update of WebView2, when I access the internal URL "edge://wallet/" in my WPF/C# project, WebView2 in my project crashes, showing the following error when I try to update the page or load another URL any:

**System.InvalidOperationException:** 'The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed'

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

128.0.2739.42

### SDK Version

1.0.2739.15

### Framework

WPF

### Operating System

Windows 10

### OS Version

19045.4170

### Repro steps

Accessing the internal URL "edge://wallet/", or "chrome://wallet/", WebView2 in the project immediately crashes.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

[AB#53589930](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/53589930)

**Comment by vbryh-msft** [comment] 2024-08-30 22:38
Do you have crash dumps?

**Comment by naldobr** [comment] 2024-08-30 22:40
> Você tem despejos de memória?

No

**Comment by naldobr** [comment] 2024-08-30 22:44
Even old projects that use WebView2 are showing this error, so I believe the problem is in the current Runtime.

**Comment by jls28** [comment] 2024-08-31 06:45
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4710

**Comment by aluhrs13** [comment] 2024-09-04 00:01
Yep, dupe of #4710

**Closed by aluhrs13** 2024-09-04 00:01 UTC
Labels: bug, tracked, regression

**Comment by naldobr** [comment] 2024-09-25 00:04
The problem has been resolved and when accessing "edge://wallet/" the program no longer dies.

I understand that Wallet is a feature of Microsoft Edge and it may not make sense to use it in WebView2, however, there are some settings regarding automatic filling (passwords, addresses and cards) that you can only control there, and depending on the context of the application, are useful features. Two of my apps would miss Wallet if I had to block access to it. Therefore, I thank you for solving the problem and not deactivating it.

**Comment by vbryh-msft** [comment] 2024-09-25 00:22
as mentioned in linked thread wallet feature is not supported by wv2 and will be completely blocked in next releases - you should not depend on it. Thanks
