### ISSUE TITLE
UWP with WebView2 won't launch or uninstall

### ISSUE THREAD

**Issue by aliu-interpro** [MicrosoftEdge/WebView2Feedback#2079] opened 2022-01-14 20:17 UTC
**Description**
If I open a UWP app for about 10 minutes, after I close the app, I won't be able to open it again. The app will stuck at the logo screen. In term of app lifecycle, I don't think the app is started at all. There isn't any process running in the background, and there isn't any error prompted. 

Sometimes, after the first or second times this behavior has shown up, I can still close the app while it stuck, then try to launch it again and it will launch properly. However, after the third or forth time, the app will always stuck at the logo screen and I won't be able to launch or uninstall it until I have restarted my computer. The only way for this behavior to not show up is to always run the app through visual studio debugger session.

The app I have written only has a WebView2 control. I have tried to import WebView2 into a UWP app with WinUI2 and WinUI3. I also tried installed through VS studio, sideload installation, debug build and release build. They all have this issue.

There isn't any error log shown in the Event Viewer. I have tried to uninstall the app with command line `Remove-AppxPackage`, the process is initialized but stuck initialized. If I installed through visual studio, I won't be able to launch with visual studio. If I installed through sideload build, I won't be able to reinstall with the installation wizard.

**Version**
SDK: Microsoft.WindowsAppSDK (1.0.0-experimental1) or Microsoft.UI.Xaml (2.8.0-prerelease.210927001)
Runtime: Dev 99.0.1131.3
Framework: UWP
OS: Win10

**Repro Steps**
1. Create UWP with WebView2 package through WinUI3 or WinUI2
2. Install the app through Visual Studio 19 or sideload build
3. Open the app through Start Menu, and let the app run for at least 10 minutes
4. Close the app, and try to launch it gain. If app launch successfully, repeat step 3.
*Expected:*
The app will launch.
*Actual:*
Stuck at logo screen, and closes itself after a while. Cannot uninstall app.

**Screenshots**
Here is the logo screen I am talking about:
![image](https://user-images.githubusercontent.com/85906261/149572011-c453986c-de11-4392-b548-013d7e5c93c1.png)

[AB#37309012](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37309012)

**Comment by champnic** [comment] 2022-01-18 22:32
Thanks for the bug report @aliu-interpro! We are currently investigating this bug, and I've linked it to this GH issue.

**Comment by champnic** [comment] 2022-02-14 21:33
The root cause is understood now, and is caused by a bug in the OS. We are working on a faster workaround in WebView2 and are implementing it now. Tentatively this should be fixed in the upcoming stable release in early March. Thanks!

**Comment by champnic** [comment] 2022-02-19 01:07
This is fixed in runtime versions 100.0.1168.0+ and will be in the next Edge 99 Beta release (around 2/21). Thanks!

**Closed by champnic** 2022-02-19 01:07 UTC
Labels: bug
