### ISSUE TITLE
Make WPF WebView2 CanGoBack and CanGoForward bindable dependency properties.

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#1146] opened 2021-04-04 12:48 UTC
**Is your feature request related to a problem? Please describe.**
WebView2 has 2 dependency properties for CanGoBack and CanGoForward which are readonly.
It is my understanding that you cannot bind to Readonly dependency properties in WPF.

[OneWayToSource binding from readonly property in XAML](https://stackoverflow.com/questions/4904300/databind-a-read-only-dependency-property-to-viewmodel-in-xaml)
[Databind a read only dependency property to ViewModel in Xaml](https://stackoverflow.com/questions/658170/onewaytosource-binding-from-readonly-property-in-xaml)

These 2 properties are already on CoreWebView2 as your reference material states; eg

> Returns true if the WebView can navigate to a previous page in the navigation history. Wrapper around the CanGoBack property of CoreWebView2. If CoreWebView2 isn't initialized yet then returns false.

Therefore what is the purpose of exposing Dependency Properties if you cannot bind to them? If I just want to use code behind I simply use "WebView2.CoreWebView2.CanGoBack "

**Describe the solution you'd like and alternatives you've considered**
I would suggest that it be made possible to bind to these Dependency Properties. Please create some WPF love to your control.

**Comment by Symbai** [comment] 2021-04-05 05:48
Dupe #434

**Comment by darbid** [comment] 2021-04-05 06:33
Nice. I assume as they are read only that this is the reason they don't notify a change.

**Comment by Symbai** [comment] 2021-04-06 16:39
The reason is more likely that they are implemented to work everywhere including Winforms and the developers of WebView2 aren't WPF developers. Like @champnic said in the issue I've linked, he suggested to listen to events instead. Doing so you can raise the propertychanged event yourself. And like he said also binding to these properties should work (I can confirm it does). 

I completely agree with you that for WPF it should be work properly but it's already tracked in the issue I've linked. Creating another issue isn't anything useful. Please upvote the existing issue and close this one.

**Closed** 2021-04-07 06:21 UTC
Labels: feature request
