### ISSUE TITLE
Too many runtimes installed

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2926] opened 2022-11-02 08:57 UTC
The following error message is confusing our users:
**System.Runtime.InteropServices.COMException HRESULT: 0x80070070 (Disk Full)**

In the last two months at least 10 customers run into that problem. The application crashed and it took too long to see the real reason, because the exception message is confusing.

I don't know which applications are holding references to older runtimes. But couldn't you make your installer smarter? Probably scheduling a task for cleanup? If not, please change the error message to display the real reason.

I can't solve the problem, because even if I catch the exception with HRESULT 0x80070070 and ignore it, the webview2 has failed during initialization and it's not usable, right?

_Originally posted by @fdzatdtv in https://github.com/MicrosoftEdge/WebView2Feedback/issues/2136#issuecomment-1286513250_
      

[AB#42531903](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42531903)

**Comment by victorthoang** [comment] 2022-11-02 21:51
Hello @fdzatdtv,

Thanks for your bug report. I've included @champnic whom you've spoken to previously regarding this. 

Are the customers who are experiencing this issue able to fully close the applications that are seeing the crash? Are they still using the evergreen runtime? My only guess is that the application might not be fully closing or needs a reset for the update to occur and remove older runtime instances?

**Comment by fdzatdtv** [comment] 2022-11-03 07:12
Hi @victorthoang,

Yes, we are using the evergreen runtime. But we can't tell you which application is or was holding a reference to the runtime.
Since the exception report is sent automatically to us, we don't have spoken to our customers. We even don't know whether all users close the application(s) before they leave office or whether some of them leave the application open until next day or for several days.

When does the evergreen runtime update itself? After a reboot or at the same time or randomly? And how often does it retry to uninstall the older runtimes? I'm asking because this probably could interfere with the usage time of the applications.

**Comment by champnic** [comment] 2022-12-06 21:25
Hey @fdzatdtv - The evergreen runtime tries to update about once a week for the stable version (and much more often for Canary). The update timing depends on when an update is available to the machine, which depends on the specific machine - our runtimes are rolled out over the course of 3 days for a new version. This update is not blocked by running WebView2 instances, and will install side-by-side. Cleanup will run at some frequent cadence, but won't delete versions that are actively in use by a running WebView2 application. We do this so that apps that are relying on WebView2 aren't randomly being force-quit when an update comes in.

When a WebView2 is created it will attempt to use the latest installed version, so seeing this error would mean that there are WebView2's holding onto many different versions of the runtime, which is pretty rare, as anytime that WebView2 is destroyed it should release that version. @LiangTheDev Do you know what the "uninstall" cadence is? And any idea if our telemetry is showing a spike in the number of concurrent WebView2 versions?

**Comment by LiangTheDev** [comment] 2022-12-06 23:49
The cleanup is attempted after every installation of the new version, and upon user login/reboot. To help confirm the issue, is it possible for you to collect the number of folders inside "C:\Program Files (x86)\Microsoft\EdgeWebView\Application" when this happens?
As a workaround, you can try to update your app to set environment variable COREWEBVIEW2_MAX_INSTANCES with a very large number like 200 and see whether that makes your app work better.

**Comment by sln162** [comment] 2022-12-07 03:28
@LiangTheDev  (https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1072.54#createcorewebview2environmentwithoptions)
The environment variable written in this document is WEBVIEW2_ MAX_ INSTANCES, COREWEBVIEW2_ MAX_ INSTANCES? For c # programs, which should be set exactly?

**Comment by LiangTheDev** [comment] 2022-12-07 18:18
It should be COREWEBVIEW2_MAX_INSTANCES. I could not find WEBVIEW2_ MAX_ INSTANCES in the page you linked.

**Comment by sln162** [comment] 2022-12-07 18:29
@LiangTheDev   
<img width="747" alt="未命名1670437713" src="https://user-images.githubusercontent.com/11196986/206265863-fde3a788-3b78-4d8b-90cd-bd4ce75006c4.png">

**Comment by LiangTheDev** [comment] 2022-12-07 18:54
That's a doc bug. Will track it internally to either update the doc or implementation. The current implementation is COREWEBVIEW2_MAX_INSTANCES.

**Comment by sln162** [comment] 2023-01-01 17:12
@LiangTheDev   Setting COREWEBVIEW2_MAX_INSTANCES is invalid, and we found that 15 IPs from different regions have the same OS Version: 10.0.14393.0

**Comment by LiangTheDev** [comment] 2023-01-03 18:41
Is it possible to collect more info? Like, available disk space, and "dir "c:\Program Files (x86)\Microsoft\EdgeWebView" /s > EdgeFiles.txt" and collect the EdgeFiles.txt, so that we can confirm whether it is too many left over old WebView2 Runtime versions, or real running out of disk space? Setting COREWEBVIEW2_MAX_INSTANCES would only work for too many old WebView2 Runtime versions.

**Comment by sln162** [comment] 2023-01-04 10:35
@LiangTheDev  EdgeFiles.txt has a lot of content and cannot be collected and reported from the software. Waiting for the user to contact me actively. In addition to these two reasons, there may be other possibilities.

**Comment by sln162** [comment] 2023-01-06 08:02
@LiangTheDev    I found the problematic environment, and generated EdgeFiles.txt, 
[EdgeFiles.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/10358514/EdgeFiles.txt)
and debugging found that the COREWEBVIEW2_MAX_INSTANCES setting is invalid. Manually setting the environment variable will take effect only when it is set to the system environment variable, and it is also invalid when it is set to the user.

Environment.SetEnvironmentVariable("COREWEBVIEW2_MAX_INSTANCES", "1000") - has no effect
Environment.SetEnvironmentVariable("COREWEBVIEW2_MAX_INSTANCES", "1000",EnvironmentVariableTarget.User) - has no effect
Environment.SetEnvironmentVariable("COREWEBVIEW2_MAX_INSTANCES", "1000",EnvironmentVariableTarget.Machine) - works
This should be a BUG, take another variable as an example，Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1"); This code is valid, it will modify the environment variables related to the process, it will not modify the user and system, the test is valid, and Edge Dev will be used first.
[EnvironmentVariableTarget](https://learn.microsoft.com/en-us/dotnet/api/system.environmentvariabletarget?view=netframework-4.5.2)
Although modifying user system variables can solve the problem, it is not a good solution.

**Comment by LiangTheDev** [comment] 2023-01-06 17:59
The machine is in an unexpected state and having too many old versions of WebViews. If you could collect Edge installer logs from the machine, that would help us a lot? The logs to collect are listed at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md#installer-logs.

We use the same ReadEnvironmentVariable for all environment variables and it should not make a difference whether it is set for process, user, or machine. When/how did you set that? Set it before any webview creation happens in the application, outside the app before running the app? If setting it outside the app, make sure that the process that launches the app is also getting the new environment variable.

**Comment by sln162** [comment] 2023-01-07 02:26
@LiangTheDev  Logs fetched:
[InstallerLogs.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10365332/InstallerLogs.zip)

I failed the first initialization and returned 0x80070070. At this time, the environment variable `COREWEBVIEW2_MAX_INSTANCES` was set, and `WEBVIEW2_RELEASE_CHANNEL_PREFERENCE` was before the first initialization, so it is valid? As long as it is initialized once, it is impossible to set the environment variable? But I don't initialize it for the first time, and I don't know that I encountered an error.

**Comment by LiangTheDev** [comment] 2023-01-09 18:06
It is by design that COREWEBVIEW2_MAX_INSTANCES is read only once. So, what you observed is expected.

The most important logs are the following logs, could you try to collect those? If not found (like on Win7 machine), could you simply do a "dir /s msedge_installer.log" for C: drive and collect all the installer logs found?
```
C:\Windows\Temp\msedge_installer.log
%systemroot%\Temp\msedge_installer.log
```

The real solution for this problem is to ensure that the old versions that are not used by any app are deleted automatically and the msedge_installer.log would help us figure out why that is not the case.
For recovery, you can simply ask the user to delete the old versions.

**Comment by sln162** [comment] 2023-01-10 06:22
@LiangTheDev At that time, I searched for these two locations, but could not find the msedge_installer.log file. The user has not responded yet, and may not be willing to cooperate. This is a screenshot I used to have. 
![QQ图片20230110141735](https://user-images.githubusercontent.com/11196986/211476259-234e0a8a-7c26-422c-8e5b-06dfb798a577.jpg)
![QQ图片20230110141753](https://user-images.githubusercontent.com/11196986/211476290-0020879e-ef58-438f-86dc-695993ab552b.jpg)
All those who encountered this problem (currently 20), the operating system is all 10.0.14393, which may be related to the operating system.
> It is by design that COREWEBVIEW2_MAX_INSTANCES is read only once. So, what you observed is expected.

I think it is unreasonable, COREWEBVIEW2_MAX_INSTANCES is either placed in the AdditionalBrowserArguments parameter, or it cannot be read only once, and it will be invalid if the initialization fails and then set.

**Comment by champnic** [comment] 2023-03-06 16:47
@sln162 We cache the value, which is why it has to be set before the first initialization. Subsequent initializations only use the cached value. In practice this won't make a difference for your app - the effect you are trying to achieve is that for your app you want to ignore the max value. It doesn't matter if you set that for your app right away, or only after an error.

The docs bug has been resolved and there isn't more specific info from the actual customers hitting this, so I'm going to resolve for now.

**Closed by champnic** 2023-03-06 16:47 UTC
Labels: bug, tracked
