### ISSUE TITLE
CTA to install Chrome extensions is visible

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3312] opened 2023-03-16 15:05 UTC
**Description**
When visiting Chrome extension store Edge related banner is displayed with CTA to allow extensions from Chrome store. 

**Version**
SDK: 1.0.1671-prerelease
Runtime: Evergreen, 110.0.1587.69
Framework: WPF
OS: Win11

**Repro Steps**
1. Navigate to https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

**Expected:** No CTA banner is displayed.
**Actual:** CTA banner to allow extensions from Chrome store is displayed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8770144/225660456-9054b669-938b-408e-a702-b2eeec9c3611.png)
![image](https://user-images.githubusercontent.com/8770144/225660574-94e59a0e-c09c-499f-9de2-9c4e64526997.png)

**Additional context**
`Allow extensions from other stores` button can be clicked which opens a native popup.

[AB#49821879](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/49821879)

**Comment by champnic** [comment] 2023-03-30 22:08
Thanks for the bug report @q71114! We'll get this fixed, I've opened it as a bug on our backlog.

**Comment by champnic** [comment] 2023-04-24 23:59
Fix is in WebView2 runtimes 114.0.1784.0+. Thanks!

**Comment by deanmalone** [comment] 2023-11-17 05:40
@champnic @Master-Ukulele Can this issue be re-opened please? 

We are seeing a regression of this issue in version `119.0.2151.44`. Noting that the regression may have occurred earlier as we only just recently noticed it.

**Comment by pdolanjski** [comment] 2023-11-24 18:23
@Master-Ukulele , there are a few issues here:

1. A user can click to install an extension which will bring up the "allow extension from other stores" dialog. We wouldn't expect that dialog come up at all.
2. If the user clicks Allow, then they get another dialog to confirm the addition of the add-on. This refers to Edge, which isn't relevant here and the dialog doesn't make sense because it won't actually do anything. 

Because of the above, this is highly confusing for our app's users since it erroneously uses an Edge dialog and makes them believe that they will be able to install and use these extensions, but they can't.

**Comment by sivMSFT** [comment] 2024-11-21 07:25
Hi @q71114,

The issue has been resolved in [1.0.1829-prerelease](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/archive?tabs=dotnetcsharp). Please let us know if you continue to experience any problems.

Thank you!

**Closed by sivMSFT** 2024-11-21 07:25 UTC
Labels: bug, tracked
