### ISSUE TITLE
WebView2 Renders over its parent

### ISSUE THREAD

**Issue by KristerAtFatshark** [MicrosoftEdge/WebView2Feedback#2579] opened 2022-07-08 08:07 UTC
I have the latest ms update and latest version of WV2 and it is happening again.. Any ideas

In the picture I have just scrolled in the scrollviewer, after resizing the window (making it smaller vertically so content do not fit)

![image](https://user-images.githubusercontent.com/98453620/177946587-dfe46fb4-ce93-41a5-bf84-18062ec12a6b.png)
![image](https://user-images.githubusercontent.com/98453620/177946526-fbe226f3-b81e-4fd6-bb39-77d81bc1da2f.png)

Framework: WPF
OS: Win10
VS2019

**Comment by KristerAtFatshark** [comment] 2022-07-11 06:40
Good to note that above is simply an example using your own application. The real case is when you have a browser surrounded by other parts of a tool set, which of course is a very common concept when making tools needing a browser and not just a standlone browser window.

**Comment by jaybuckman** [comment] 2022-07-11 11:08
I have Win 10 19044.1806 and I don't think KB5011543 applies to my build.  But I do not have the issue you describe.

**Comment by KristerAtFatshark** [comment] 2022-07-11 12:17
@jaybuckman it is not connected to KB5011543, I posted in that thread but I have removed it this is a different issue, the old one render on top of windows etc this is internal between hierarchy inside wpf. 100% repro with the code above. I have tested on several machines no idea if we are missing another windows update that fixed this but we are on KB5014699

also another image of the issue, basically when scrolling the browser renders on top:
wpf is basically a scrollviewer + stackpanel
![image](https://user-images.githubusercontent.com/98453620/178262029-0822e0de-af12-4ac7-8bb1-1d31268e0bff.png)

**Comment by KristerAtFatshark** [comment] 2022-07-11 12:21
I have set the ClipToBounds="True" in the webview control but it only clips on the window

**Comment by champnic** [comment] 2022-07-11 22:04
Ah - this feels like it's probably an extension of the Airspace issue in WPF: #286. Basically the WebView2 will always render on top, so when the scrollviewer is trying to clip/hide the portion of the WebView2 that should not be visible, it can't. @KristerAtFatshark I'm going to close this as a dupe of #286, but if you think these might be separate please let me know. Thanks!

**Closed by champnic** 2022-07-11 22:04 UTC
Labels: bug

**Comment by KristerAtFatshark** [comment] 2022-07-13 07:56
I cant say for sure that this is the same case but they might absolutely be related
