### ISSUE TITLE
[Problem/Bug]: new winui3 black app can not drag file from explorer to webview2 ,please fix this bug.

### ISSUE THREAD

**Issue by caoruipeng123** [MicrosoftEdge/WebView2Feedback#4908] opened 2024-11-07 09:21 UTC
### What happened?

we use vs2022 create an black winui3 app with webview2. app can't drag file from explorder to webview2

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

130.0.2849.56

### SDK Version

1.6.240923002

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

Windows Feature Experience Pack 1000.22700.1041.0

### Repro steps

1.create new winui3 app
2.run new winui3 app.
3.drap an txt file from desktop to wenview2 .show a red disabled icon.

https://github.com/user-attachments/assets/f095c4de-05b3-435a-9801-c7fc7e50c4a1

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by caoruipeng123** [comment] 2024-11-07 09:39
we have set AllowDrop=true

**Comment by sandeepchads** [comment] 2024-11-15 07:24
@caoruipeng123 - I believe this issue is duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/discussions/3973

We have this on our backlog. If you are fine, then we can close this one as a dupe and you can follow updates on the above bug. Closing this for now. Kindly re-activate if you feel otherwise.

**Closed by sandeepchads** 2024-11-15 07:24 UTC
Labels: bug

**Comment by wood4099** [comment] 2025-02-20 01:51
Hello,@sandeepchads 
Perhaps there is a misunderstanding in this description.
We need to allow users to drag and drop any file into webview2 after launching the application using the administrator.
We use the winui3+webview2 architecture, but we found that if the app is launched in administrator mode, users cannot drag files into webview2.
