### ISSUE TITLE
WebView2 control is not reflecting the correct point when the System Scale is not set to 100%

### ISSUE THREAD

**Issue by cgits14** [MicrosoftEdge/WebView2Feedback#2683] opened 2022-08-15 10:40 UTC
This is at least happening with the 'ZoomText 2022' accessibility application by Freedom Scientific. Can be experienced on all Windows OS using the latest stable release of WebView2 104.0.1293.54.

To recreate:
1. Download ZoomText 2022 (free version - https://support.freedomscientific.com/Downloads/ZoomText)
2. Set your device to scale > 100% (common setting for surface pro)
3. Launch a WebView2 application pointed to an accessible web page 
4. Launch ZoomText and use the control to read text at a certain point on the page

What happens is that the accessibility application starts reading text from an offset point that varies based on the Windows Scale Setting that is selected.

The issue is not experienced when using Edge, only the WebView2 control.

[AB#41987620](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41987620)

**Comment by bradp0721** [comment] 2022-08-15 23:07
What WebView2 control are you using? Are you using the WPF WebView2 element? WinForms WebView2 element? WinUI3 WebView2 element? Or the Win32 CoreWebView2Controller directly?

Are you able to repro the issue using the [WebView2APISample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample)?

**Comment by cglacken** [comment] 2022-08-16 01:32
@bradp0721 using in32 CoreWebView2Controller directly. I am able to repro using the WebView2WindowsFormsBrowser sample app, but the WebView2wpfBrowser app does not have the issue and is working as I would expect.

**Comment by tochukwuIbeEkeocha** [comment] 2023-01-12 00:57
Hey all. So while we are working on resolving the root cause, we have also found a workaround for your own WPF or WinForms app. If your app is targeting .NET 4.2.6  see ([here](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)) otherwise see [here](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8).

**Comment by cglacken** [comment] 2023-03-08 18:24
@tochukwuIbeEkeocha thank you. We were successful with the win32 SetThreadDpiAwarenessContext call and will run with that. We also support 8.1 and all versions of 10, and this has a limitation Windows 10, version 1607. While support on those platforms would be nice, I am not expecting Microsoft to apply anything to platforms that are no longer supported.

**Comment by champnic** [comment] 2023-08-03 23:47
This has been resolved in runtime versions 117.0.1978.0+. Thanks!

**Closed by champnic** 2023-08-03 23:47 UTC
Labels: bug, tracked
