### ISSUE TITLE
The browser crashes unexpectedly while working with it

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#2086] opened 2022-01-18 15:56 UTC
**Description**
The browser crashes unexpectedly while working with it. This does not appear to be reproducible, however it seems to occur daily, reports have been heavily increased over the last few days.

**Version**
SDK: 1.0.1054.31
Runtime: Stable 97.0.1072.62
Framework: WinForms
OS: Windows 10 Enterprise Version 21H2

**Repro Steps**
Work with the browser, and observe it crash for an unknown reason after some time.
We have also received a minidump, [670ce50e-4a8a-485d-a904-ab8a5a051cae.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7890468/670ce50e-4a8a-485d-a904-ab8a5a051cae.zip), it also mentions the following:
```
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(5348.3ab0): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!NtDelayExecution+0x14:
00007ffc`9670d3f4 c3              ret
```

So I suspect this is an error in the browser engine itself.

[AB#34658419](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34658419)

**Comment by champnic** [comment] 2022-01-19 20:17
Hey @fvanheeswijk - Thanks for the bug report! When you say "the browser" do you mean the browser/WebView2 runtime processes?

**Comment by champnic** [comment] 2022-01-19 23:56
I've confirmed from the crash dump that this is indeed the WebView2 processes. I've found the issue in our backlog and linked to this item. It's currently not a very high hitter overall, so we won't be looking at it right away. Please let me know if this is affecting your specific scenario too much, but I suspect other crash dumps would be caused by other things as well. Thanks!

**Comment by fvanheeswijk** [comment] 2022-01-20 08:59
This is a very serious issue for us, our customers are hitting this issue every day since recently, we would very much like a fix as soon as possible. When they hit this issue then the whole application is unusable as well..

**Comment by champnic** [comment] 2022-01-20 19:03
A WebView2 crash shouldn't bring down the whole application (at least not the one described in the crash dump). You can listen to the "ProcessFailed" event on the environment and recreate the WebView2 control when this happens for a renderer or main browser process.

**Comment by champnic** [comment] 2022-04-11 18:57
We haven't seen this particular crash since runtime 97 (no hits on 98+). Closing this item.

**Closed by champnic** 2022-04-11 18:57 UTC
Labels: bug
