### ISSUE TITLE
WebView2 issues when SetWindowDisplayAffinity set to WDA_MONITOR in Windows 11

### ISSUE THREAD

**Issue by np14** [MicrosoftEdge/WebView2Feedback#841] opened 2021-01-21 14:32 UTC
My requirement is to disable screen capture for a WPF application and I was trying to do the same with winapi (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity). My app also hosts a webview2 control and this control generates an exception when the website is navigated from one url to another url. Kindly advise if there is a way to get the webview2 control working with the above setting and if this is something that will be supported in a future version.

If i try it by setting SetWindowDisplayAffinity to WDA_NONE, the app works.

Webview2 Nuget Package version : 1.0.664.37
WPF app target : .net core 3.1
Exception details : An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in Microsoft.Web.WebView2.Core.dll
The group or resource is not in the correct state to perform the requested operation. (0x8007139F)

System.Runtime.InteropServices.COMException
  HResult=0x8007139F
  Message=The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

[AB#41248050](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41248050)

**Comment by champnic** [comment] 2021-01-29 00:46
Hey @np14 - thanks for the report! I've added this bug to our backlog to take a look.

**Comment by BugKiller-tech** [comment] 2021-02-04 01:14
> My requirement is to disable screen capture for a WPF application and I was trying to do the same with winapi (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity). My app also hosts a webview2 control and this control generates an exception when the website is navigated from one url to another url. Kindly advise if there is a way to get the webview2 control working with the above setting and if this is something that will be supported in a future version.
> 
> If i try it by setting SetWindowDisplayAffinity to WDA_NONE, the app works.
> 
> Webview2 Nuget Package version : 1.0.664.37
> WPF app target : .net core 3.1
> Exception details : An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in Microsoft.Web.WebView2.Core.dll
> The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
> 
> System.Runtime.InteropServices.COMException
> HResult=0x8007139F
> Message=The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
> Source=
> StackTrace:
> [AB#31477272](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31477272)

Same issue for me

**Comment by cglacken** [comment] 2021-02-22 02:00
We are having this issue as well. We recently upgraded our application to the new WebView2 from the previous WebView control. 

We have 2 scenarios in which setting SetWindowDisplayAffinity to WDA_MONITOR will crash our application. The first is when we have an http to https redirect, such as a http vanity resolving to an https long url. The second scenario is when a new window is opened, such as a print dialog.

We do not have any crashes with the older WebView control. The issue is specific to using the new WebView2.

This is an important requirement for our application.

**Comment by jamesoli** [comment] 2021-03-04 22:47
@np14 @BugKiller-tech @cglacken We found the issue of the crash and are fixing it right now.

However, I had an additional question for you. How would you expect Print and Save for the page to work when SetWindowDisplayAffinity is called with WDA_MONITOR or WDA_EXCLUDEFROMCAPTURE? Currently, printing and saving works under this scenario.

Do you expect that printing and/or saving the page to be automatically disabled with SetWindowDisplayAffinity or do you expect another API to control that functionality?

![image](https://user-images.githubusercontent.com/20053282/110041034-87fa6600-7cf8-11eb-879c-402c2876bf77.png)

**Comment by cglacken** [comment] 2021-03-05 00:32
@jamesoli That is great news, thank you for the update. Do you have an idea of when we can expect the fix?

With regards to your question, I would expect printing/saving to be automatically disabled.

**Comment by np14** [comment] 2021-03-05 07:27
Hey @jamesoli, thanks for the update. I would expect printing and saving to be disabled. In fact, we are disabling right click for our application.

**Comment by cglacken** [comment] 2021-03-09 14:43
Hi @jamesoli, can you tell me if something was recently released with the latest round of updates? 

We have now shifted from only crashing on a redirect or new widow to crashing 100% of the time. We are unable to use SetWindowDisplayAffinity at all now. I've tried canary and was unsuccessful there as well. Our app has not changed, the only thing that has changed is the underlying runtime. Would you be able to share any information on what the bug was that you found and what was done to "fix" it?

**Comment by jamesoli** [comment] 2021-03-10 19:51
@cglacken The bug fix hasn't gone in yet. I'm confirming a few things before putting it in so it doesn't break later on. As to why it seems to be failing more scenarios for you now is unclear. As far as I know, it would break on all navigations in my test scenario so that is actually expected for me right now.

**Comment by cglacken** [comment] 2021-03-10 19:56
ok, that is good to hear! Thank you for the response. We are looking forward to have this one working fully. 

Would you be able to share any information on what the actual issue is? only asking because I am curious as it seems odd webview2 would be impacted by this. Regardless, do you have an estimate of when we could look for this fix in production?

**Comment by cglacken** [comment] 2021-03-18 12:34
Hi @jamesoli, I wanted to see if there was any update on this one. I do not see a milestone assigned to this so it is not clear to me when your fix can be expected. This feature is very important to us and this is a show stopper for moving more of our clients onto the version of our app using the new WebView2 control

**Comment by jamesoli** [comment] 2021-03-18 17:26
@cglacken Hey, sorry for the delayed response. We were making sure the fix wasn't going to be broken by any Windows changes. We are pretty confident that the change will be available in the next Canary browser release. This won't need any new SDK changes.

**Comment by jamesoli** [comment] 2021-03-18 17:28
For further clarification, this fix doesn't come with automatic disabling of printing and saving. That is a separate issue we are tracking.

**Comment by cglacken** [comment] 2021-03-18 17:28
@jamesoli Great news, thank you! I will keep an eye out for it.

**Comment by champnic** [comment] 2021-05-04 23:26
This should be fixed in all runtimes 91.0.836.0+. Thanks!

**Comment by shiv455** [comment] 2022-05-19 10:23
is this broken again?

**Comment by Slapbox** [comment] 2022-08-31 20:07
Doesn't work in Windows 11.

**Comment by champnic** [comment] 2022-09-07 23:13
@Slapbox same questions as above: Does your app work as expected without change if deployed to Win10? Can you share what WV2 Runtime and SDK you are using?

**Comment by Slapbox** [comment] 2022-09-07 23:57
It did work on Windows 10 but I don't have the other details available.

**Comment by champnic** [comment] 2022-09-08 19:16
Thanks for confirming that this appears limited to Win11. I'll reactivate the bug and scope to Win11.

**Comment by cglacken** [comment] 2022-09-08 22:05
@champnic - do you know the runtime/Win11/webview2 control where this is an issue? We use this in our applications but I am unable to recreate this issue and am trying to figure out what scenario(s) are not covered.

**Comment by champnic** [comment] 2022-09-09 00:08
We have not tried to repro this issue ourselves yet (on Win11 or elsewhere), so I'm not able to say with certainty where this will occur. The only reason this is open again is because of the reports from @shiv455 and @Slapbox above.

**Comment by shiv455** [comment] 2022-09-09 12:05
We were not able to duplicate it after updating the runtimes. I believe this is not an issue any more. Sorry for not doing that earlier.

**Comment by tochukwuIbeEkeocha** [comment] 2022-09-30 20:43
Hello,

As @champnic  mentioned we have tried to repro this bug on Windows 11, and it looks like it is not present. Please try what @shiva445 did and update the runtime.

**Closed by tochukwuIbeEkeocha** 2022-09-30 20:43 UTC
Labels: bug, tracked
