### ISSUE TITLE
This browser or app may not be secure. Webview2

### ISSUE THREAD

**Issue by markismail7** [MicrosoftEdge/WebView2Feedback#1584] opened 2021-07-29 21:43 UTC
Hi @david_risney,
All of the sudden, google are not allowing our users to login to their Gmail thru Webview2. It was fine yesterday. Here is the error message i get from google:

Couldn’t sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

What do we do in this situation. I'm ready to throw up about anything that is related to google. They always making us look bad in front of our customers. They act like they care about our privacy, but the reality they don't. All they care about is steering people away from Microsoft.
Microsoft please create a better Gmail service so we can run for our lives from their dictatorship.
Any help would be appreciated. 
![Screenshot 2021-07-29 223320](https://user-images.githubusercontent.com/6565139/127591196-c914da81-d38c-4c74-8e7d-766d628a43af.png)

**Comment by amaitland** [comment] 2021-07-30 07:29
Duplicate of #1578

**Closed** 2021-07-30 11:59 UTC
Labels: question
