### ISSUE TITLE
[Problem/Bug]: FluentUI ComboBox/Select don't accept selected option in WinUI WebView2

### ISSUE THREAD

**Issue by Eilon** [MicrosoftEdge/WebView2Feedback#4545] opened 2024-05-08 17:33 UTC
### What happened?

Original reports:

* https://github.com/microsoft/fluentui-blazor/issues/1741
* https://github.com/dotnet/maui/issues/22297

But the bug seems specific to WinUI WebView2 (doesn't repro on WPF WebView2).

Details: The FluentUI ComboBox (which internally uses an HTML `<input>` + some other HTML UI) doesn't accept selection in the WinUI WebView2. It works in regular Edge (just browsing the web), and it works in WPF WebView2.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.80

### SDK Version

WinAppSDK 1.5.240428000

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

10.0.22631.3447

### Repro steps

1. Create new WinUI3 Packaged App
2. Change XAML to be just `<WebView2 Source="https://learn.microsoft.com/en-us/fluent-ui/web-components/components/combobox?pivots=typescript"></WebView2>`
3. Run the app
4. Scroll down to the bottom of the page and in the **Example** section make sure the **Result** tab is enabled, and in the dropdowns you see try to pick a 'graphics card' option. But it won't let you

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/202643/3ffea050-86e5-45bc-99df-6b404d06fe0a)

If you try the same repro in a WPF WebView2 app it works fine (the graphics card is selected). And if you browser in regular Edge browser to https://learn.microsoft.com/en-us/fluent-ui/web-components/components/combobox?pivots=typescript then it also works fine.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

[AB#50879689](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50879689)

**Comment by johna-ms** [comment] 2024-05-13 22:55
Thank you for reporting this! I was able to repro this and will track this on our side

**Comment by Peppe426** [comment] 2024-06-07 08:57
I can confirm this. When debugging on a Windows machine, I can navigate and select options in FluentSelect using the **keyboard**. However, **mouse clicks** don't work; it seems to click on the area behind the dropdown/options instead.

**Comment by johna-ms** [comment] 2024-06-10 18:51
I believe this is a dupe of an older issue #4394 so I'll close this. Discussion should continue on the other issue

**Closed by johna-ms** 2024-06-10 18:51 UTC
Labels: bug, tracked
