### ISSUE TITLE
[Problem/Bug]:  WebVew2 plugin for Unity does not work along side MRTK3 (possible compatibility issue with com.unity.inputsystem@1.6.1)

### ISSUE THREAD

**Issue by AMollis** [MicrosoftEdge/WebView2Feedback#4386] opened 2024-02-21 17:12 UTC
### What happened?

This issue was originally reported by @ArDevKarl at the MRTK3 repository.  However, this is a WebView2 issue.   So copying here.  

## Original Issue:

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/650

--------------------

## Issue:

We recently updated our HoloLens 2 project from MRTK2.8.3 to MRTK3. Unfortunately I just found out, that the WebView2 (from MRFeatureTool) seems to be not supported by MRTK3 (https://github.com/MicrosoftEdge/WebView2Feedback/issues/3516). I tried this and the app just crashes without notifications or errors. Everything seems to work fine, until I try to initialize a WebView.

This would be a major setback for our development. Are there any plans for this or known workarounds, to run WebVew2 with a MRTK3 application for HoloLens 2?

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Unity Plugin

### Operating System

Hololens

## Steps to reproduce the behavior:

Setup the MRTK3 DevTemplate and implement the WebView2 package. Put the WebView Prefab inside a scene, build and run it on the HoloLens. App will crash as soon the WebView is initialized.

## Expected behavior
- The application does not crash
- Logs give me information about any occuring errors or incompadibilities

## Your setup (please complete the following information)
- Unity 2022.3.7f1
- MRTK3 
- WebView2 (0.17.1-pre.5)
(FYI: Works fine in UnityEditor)

## Target platform:
- HoloLens 2

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

**Comment by victorhuangwq** [comment] 2024-02-21 18:57
This is a duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/4380 , so I will close this and we will follow up on it there.

**Closed by victorhuangwq** 2024-02-21 18:57 UTC
Labels: bug
