### ISSUE TITLE
COMException HRESULT: 0x80004004 (E_ABORT)) during Dispose

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2384] opened 2022-04-22 09:52 UTC
**Description**
We observe increasing exceptions like this one at customer side.
The callstacks are obviously different, but they have all the following part together:

**Callstack**
   bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   bei Microsoft.Web.WebView2.Core.CoreWebView2CreateCoreWebView2ControllerCompletedHandler.Invoke(Int32 errCode, ICoreWebView2Controller createdController)
   bei System.Windows.Forms.UnsafeNativeMethods.IntDestroyWindow(HandleRef hWnd)
   bei System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(HandleRef hWnd)
   bei System.Windows.Forms.NativeWindow.DestroyHandle()
   bei System.Windows.Forms.Control.DestroyHandle()
   bei System.Windows.Forms.Control.Dispose(Boolean disposing)

**Version**
SDK: 1.0.1054.31
Runtime: Evergreen 100.0.1185.*, 99.0.1150.*, 98.0.1108.*
Framework: WinForms (x86)
OS: Windows Server 2016 and 2019

**Additional context**
If the root cause is calling Dispose multiple times, then you should implement a guard in your code. Why? Because we have lots of forms with the auto-generated Dispose method from the Windows Forms Designer:
```
protected override void Dispose(bool disposing)
{
    if (disposing && (components != null))
    {
        components.Dispose();
    }
    base.Dispose(disposing);
}
```
And this code doesn't have a guard. It would be a great effort for us to change all that parts. But you could do it at a single place.

If the root cause is anything else, let us know. So, we can investigate further.

[AB#39266250](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39266250)

**Comment by oggy22** [comment] 2022-04-26 04:41
Thank you for reporting the issue @fdzatdtv! Few questions for you:
- Is there any meaning of `bei` for each line in your callstack?
- Do your customers also run `x64` and it didn't repro there, or your customers are exclusively on `x86`?
We are looking into the issue and it seems as regression introduced recently. We'll keep you posted.

**Comment by liulichen0603** [comment] 2022-04-28 08:23
Hi @fdzatdtv , I'm investigating about this bug but cannot repro it even when call `Dispose` multiple times, and seems the crash callstack you provided is a little bit strange that the `Dispose` method can finally trigger `CoreWebView2CreateCoreWebView2ControllerCompletedHandler.Invoke`. Could you help provide some more info about how to repro this bug? Thanks!

**Comment by fdzatdtv** [comment] 2022-05-04 05:55
Hi @oggy22, `bei` is the same as `at`. The callstacks were logged with german culture.
The customers are **exclusively** running on **x86** because our **application** is build for x86. **But** we only install the **x64 evergreen runtime** of WebView2. Maybe this helps for your investigation.

Hi @liulichen0603, unfortunately I can't tell you how to reproduce. The exception logs were sent automatically to us when they happen. Maybe the following full callstack (omitting our typenames) can help you. Tell me if you miss some other information.

**Callstack**
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.Web.WebView2.Core.CoreWebView2CreateCoreWebView2ControllerCompletedHandler.Invoke(Int32 errCode, ICoreWebView2Controller createdController)
   at System.Windows.Forms.UnsafeNativeMethods.IntDestroyWindow(HandleRef hWnd)
   at System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(HandleRef hWnd)
   at System.Windows.Forms.NativeWindow.DestroyHandle()
   at System.Windows.Forms.Control.DestroyHandle()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at Our code Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Our code Dispose(Boolean disposing)
   at Our code Dispose()
   at Our code Dispose(Boolean disposing)
   at Our code Dispose()
   at Our code Dispose(Boolean disposing)
   at Our code Dispose(Boolean disposing)
   at Our code Dispose()
   at Our code Dispose(Boolean disposing)
   at Our code Dispose()
   at Our code Dispose(Boolean disposing)
   at Our code Dispose(Boolean disposing)
   at Our code 
   at Our code 
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Our code 
   at Our code OnWindowFormClosed(Object sender, WorkspaceEventArgs e)
   at Our code OnClosed(EventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Our code WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, Int32 wParam, Int32 lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)
   at System.Windows.Forms.Form.Close()
   at Infragistics.Win.UltraWinTabbedMdi.MdiTab.Close()
   at Infragistics.Win.UltraWinTabbedMdi.MdiTab.Close(MdiTabCloseReason closeReason)
   at Infragistics.Win.UltraWinTabbedMdi.MdiTabGroup.MdiTabGroupManager.CloseButtonClick(ITabItem tab, TabCloseReason reason)
   at Infragistics.Win.UltraWinTabs.TabCloseButtonUIElement.ButtonClick()
   at Infragistics.Win.ButtonUIElementBase.OnClick()
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUpHelper(Object sender, MouseEventArgs e)
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUp(Object sender, MouseEventArgs e)
   at Infragistics.Win.Utilities.ProcessEvent(Control control, ProcessEvent eventToProcess, EventArgs e)
   at Infragistics.Win.UltraWinTabbedMdi.MdiTabGroupControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at Infragistics.Win.UIAutomation.UiaProviderControlNativeWindow.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at Infragistics.Win.DpiUtilities.DpiUtilitiesNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Our code 
   at Our code 
   at Our code 
   at Our code Main(String[] args)

**Comment by yunate** [comment] 2022-05-18 07:31
Hi @fdzatdtv,  I'm investigating about this bug. The CoreWebView2CreateCoreWebView2ControllerCompletedHandler is async. I guess the webview2 control has been deconstructed when the async function call continuation(the code after await). In other words, the the webview2 control has been deconstructed before it's callback handle been called, this may cause crash. This may be caused by the user closing the interface manually before the webview2 control finish init. So could you help provide the process running time, or confirm whether the running time is very short?

**Comment by yunate** [comment] 2022-05-19 08:35
Hi @fdzatdtv, 
I test that: 
    Create a WebView2 control and init it.
    And then call it's Dispose() immediately.
It will always throw 0x80004004 exception.

It is by designed: if the control call Dispose(), windows will receive WM_NCDESTROY message, in it's WndProc we will tell app the **failure(the windows has been destroyed)** now.

So could you test it in your app, and to check if this happens.

**Closed** 2022-08-16 21:47 UTC
Labels: bug, tracked
