### ISSUE TITLE
[Feature]: Make WebView2 compadible with MRTK3

### ISSUE THREAD

**Issue by ArDevKarl** [MicrosoftEdge/WebView2Feedback#4588] opened 2024-05-27 06:04 UTC
### Describe the feature/enhancement you need

The MRTK - Feature Tool lets you install WebView2 aswell as MRTK3, allthough they do not work together. The reason is propably mostly this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4380

I strongly hope, this is already being worked on, since this is a major show stopper for MRTK3 in many future HoloLens/MRTK projects.

### The scenario/use case where you would use this feature

Any application that requires access to Web content during runtime using MRTK3

### How important is this request to you?

Critical. My app's basic functions wouldn't work without it.

### Suggested implementation

See: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4380
Basicly: WebView2 requres "D3D" as build type while MRTK3 requires "XAML". Initializing a WebView in a XAML application crashes it.

### What does your app do? Is there a pending deadline for this request?

Display data, videos, texts etc.

Deadline is ASAP. We cannot use MRTK3 until this is fixed. We already had to roll back to MRTK2.8.2 for our first release.

**Comment by champnic** [comment] 2024-05-29 04:59
Closing as a duplicate of #4380.

**Closed by champnic** 2024-05-29 04:59 UTC
Labels: feature request

**Comment by ArDevKarl** [comment] 2024-05-29 05:09
@champnic "Not planned" does this mean, this issue will never be adressed?
