### ISSUE TITLE
RemoveHostObjectFromScript Object not released until navigation

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#502] opened 2020-10-04 13:51 UTC
Not sure if this is a bug or by design, but any object added is not released until next navigation:

```
'Test class to see when it's released
Public Class TestThis
  Protected Overrides Sub Finalize()
    'Not raised until navigate
    MyBase.Finalize()
  End Sub
End Class

Dim Test As New TestThis
CoreWebView2.AddHostObjectToScript("Test", Test)
CoreWebView2.RemoveHostObjectFromScript("Test")
Test = Nothing
GC.Collect()
'Not released
```

[AB#29826148](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29826148)

**Comment by pagoe-msft** [comment] 2020-10-06 17:20
@ukandrewc ,

Thanks for drawing attention to this - it is not by design and appears to be a bug.

**Comment by ukandrewc** [comment] 2020-10-06 17:34
@pagoe-msft that's good news, I was hoping that was the case ;-)

**Comment by vbryh-msft** [comment] 2020-11-13 18:26
@ukandrewc The behavior which you observe could happen to objects with or without adding them to WebView2. Test object in your sample is not released after GC.Collect() because it is finalizable and requires additional finalization step which is done separately from garbage collection.
If you need more control over clean up it is suggested to use IDisposable interface: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

Also more info about Finalization and overall memory management in .NET can be found here: https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#finalizers

**Comment by vbryh-msft** [comment] 2020-11-13 19:05
@ukandrewc I have tested two objects: one with adding to WebView2 and another without adding to WebView2 in different scenarios: calling GC.Collect() and without calling it. Both objects are always release at the same time. Sometimes without calling GC.Collect() finalizer is called almost immediately. Sometimes after calling GC.Collect() finalizer is called after 5-10 min without navigation.
Are you using Microsoft WebView2 .NET wrapper?

**Comment by ukandrewc** [comment] 2020-11-13 19:44
@vbryh-msft Yes, I'm using .Net version. I did test this several times, in different ways. The code I posted was the simplest that I tried. I didn't wait as long as 5-10 mins, but I'll try it again and leave it longer, to see if I get the same.

**Comment by champnic** [comment] 2021-01-30 02:14
@ukandrewc Did you happen to test this and find the same thing? I'm going to close this for now, but if you see the same behavior let me know and I can reopen. Thanks!

**Closed by champnic** 2021-01-30 02:14 UTC
Labels: bug, question, tracked
