### ISSUE TITLE
WPF Sample + AddHostObjectToScript fails with ArgumentException

### ISSUE THREAD

**Issue by lostobject** [MicrosoftEdge/WebView2Feedback#494] opened 2020-09-30 01:59 UTC
I have been trying to get AddHostObjectToScript working in my WPF application following #175 and the newly added documentation. But it keeps failing with ArgumentException. I now tried with the WPF sample browser and it fails with the same exception.

Versions
SDK: 0.9.628-prerelease
Runtime: Tried both Dev (87.0.654.0) and Canary (87.0.655.0)
Framework: WPF
Visual Studio: 2019 version 16.7.4
OS: Win10 (tried 1607 Build 14393.3866 and 1803 Build 17134.1726)

**Repro Steps**
1. `git clone https://github.com/MicrosoftEdge/WebView2Samples.git`
2. Open WebView2WpfBrowser.sln in VS2019
3. Create BrowserHostObject.cs and paste:
```csharp
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace WebView2WpfBrowser
{
	[ClassInterface(ClassInterfaceType.AutoDual)]
	[ComVisible(true)]
	class BrowserHostObject
	{

		public bool Test(string something)
		{
			string message = $"***Test({something}) Called***";
			Debug.Print(message);
			return true;
		}
	}
}
```
4. Edit MainWindow.xaml.cs and paste (overwriting WebView_NavigationStarting):
```csharp
        private bool _hostObjectAdded = false;
        private void AddHostObject()
        {
			if (!_hostObjectAdded)
			{
				_hostObjectAdded = true;
				webView.CoreWebView2.AddHostObjectToScript("external", new BrowserHostObject());
			}
		}

        async void WebView_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            _isNavigating = true;
            RequeryCommands();

            await webView.EnsureCoreWebView2Async();
            AddHostObject();
        }
```
5. Debug the app (either .net core or framework) and upon initial navigation you will see:
```
Exception thrown: 'System.ArgumentException' in Microsoft.Web.WebView2.Core.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
Value does not fall within the expected range.
```
Stack trace:
```
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.AddHostObjectToScript(String name, Object& object)
   at Microsoft.Web.WebView2.Core.CoreWebView2.AddHostObjectToScript(String name, Object rawObject)
   at WebView2WpfBrowser.MainWindow.AddHostObject() in X:\TestProjects\WebView2Samples\SampleApps\WebView2WpfBrowser\MainWindow.xaml.cs:line 162
   at WebView2WpfBrowser.MainWindow.<WebView_NavigationStarting>d__24.MoveNext() in X:\TestProjects\WebView2Samples\SampleApps\WebView2WpfBrowser\MainWindow.xaml.cs:line 170
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at WebView2WpfBrowser.App.Main()
```

I also tried the C++ app WebView2APISample, and the AddHostObjectToScript scenario works.

[AB#29651142](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29651142)

**Comment by champnic** [comment] 2020-10-01 00:07
Thanks for letting us know, I've filed a bug internally and we'll take a look. Thanks!

**Comment by champnic** [comment] 2020-10-03 00:00
I gave this a try and was able to repro. Looks like it's related to trying to add the host object during the NavigationStarting event handler. If you move it to initialization or somewhere else then it works fine for me. Want to try that for now? I'm following up to try and figure out whether this is expected behavior (and why) or if this is a bug. Thanks!

**Comment by lostobject** [comment] 2020-10-06 01:39
Thanks for the update Nic. I tried a few different places but still get the same error:
- MainWindow_OnInitialized
- MainWindow_OnLoaded
- WebView_OnInitialized
- WebView_OnLoaded

Would you mind posting the code you have where it works?

**Comment by dorofino** [comment] 2020-10-08 15:03
I'm getting the same error, did you managed to find a way around?

> Thanks for the update Nic. I tried a few different places but still get the same error:
> 
> * MainWindow_OnInitialized
> * MainWindow_OnLoaded
> * WebView_OnInitialized
> * WebView_OnLoaded
> 
> Would you mind posting the code you have where it works?

**Comment by champnic** [comment] 2020-10-08 17:05
The workaround was putting the call after "await EnsureCoreWebView2Async()" in the sample, rather than an event handler:
```
             // Setting webView.Source will not trigger a navigation if the Source is the same
             // as the previous Source.  CoreWebView.Navigate() will always trigger a navigation.
            await webView.EnsureCoreWebView2Async();
            webView.CoreWebView2.Navigate((string)e.Parameter);
            webView.CoreWebView2.AddHostObjectToScript("external", new BrowserHostObject());
```

**Comment by dorofino** [comment] 2020-10-08 17:20
Under webView_NavigationStarting?

> The workaround was putting the call after "await EnsureCoreWebView2Async()" in the sample, rather than an event handler:
> 
> ```
>              // Setting webView.Source will not trigger a navigation if the Source is the same
>              // as the previous Source.  CoreWebView.Navigate() will always trigger a navigation.
>             await webView.EnsureCoreWebView2Async();
>             webView.CoreWebView2.Navigate((string)e.Parameter);
>             webView.CoreWebView2.AddHostObjectToScript("external", new BrowserHostObject());
> ```

**Comment by champnic** [comment] 2020-10-08 17:34
Ah apologies - the place I was moving it to wasn't getting hit. Looks like the function is just busted for .NET. I'm escalating the issue on our side.

**Comment by dorofino** [comment] 2020-10-08 17:36
> Ah apologies - the place I was moving it to wasn't getting hit. Looks like the function is just busted for .NET. I'm escalating the issue on our side.

Sounds good, If you heard of a solution let me know. 
Thank you

**Comment by champnic** [comment] 2020-10-09 00:26
Aha - the class needs to be **public**:
`class BrowserHostObject`

That fixed it for me (and double checked I'm actually hitting the code :P). Can you give that a try?

**Comment by lostobject** [comment] 2020-10-09 03:22
Yes that's it! I missed that detail when creating the class. I have a basic method call working from Javascript to the WPF code now.

Thanks for getting to the bottom of this!

**Comment by champnic** [comment] 2020-10-09 03:55
Glad it's working! 
I'm going to close this issue for now. If you'd like me to reopen please let me know with extra details, or open a new issue if you run into something else. Thanks!

**Closed by champnic** 2020-10-09 03:55 UTC
Labels: bug, tracked

**Comment by dorofino** [comment] 2020-10-12 15:31
> Yes that's it! I missed that detail when creating the class. I have a basic method call working from Javascript to the WPF code now.
> 
> Thanks for getting to the bottom of this!

Hi, sorry for my lack of knowledge, but how are you calling the method on javascript?

like this?

external.Text('this is a test');

**Comment by dorofino** [comment] 2020-10-12 15:40
Nevermind I found the way to get it working
```
using System.Diagnostics;
using System.Runtime.InteropServices;

        private bool _hostObjectAdded = false;
        private void AddHostObject()
        {
			if (!_hostObjectAdded)
			{
				_hostObjectAdded = true;
				webView.CoreWebView2.AddHostObjectToScript("external", new BrowserHostObject());
			}
		}

        async void WebView_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            _isNavigating = true;
            RequeryCommands();

            await webView.EnsureCoreWebView2Async();
            AddHostObject();
        }

	[ClassInterface(ClassInterfaceType.AutoDual)]
	[ComVisible(true)]
	public class BrowserHostObject
	{ 
		public bool Test(string something)
		{
			string message = $"***Test({something}) Called***";
			Debug.Print(message);
			return true;
		}
	} 
```
 
JS Script
```
const external= chrome.webview.hostObjects.external;
external.Test('This is a test');
```
