### ISSUE TITLE
Base64 string returned from ExecuteScriptAsync decode error and shorter than the original string

### ISSUE THREAD

**Issue by evolcano** [MicrosoftEdge/WebView2Feedback#3555] opened 2023-06-10 16:05 UTC
**Description**
I want to get image from web, so I call ExecuteScriptAsync to return the Base64 string encoded from image. The image data string changed in three steps:

**(1)The original Base64 string is:**
[1 Original Base64 image data in WebView2.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11712793/1.Original.Base64.image.data.in.WebView2.txt)

**(3)The string from ExecuteScriptAsync is:**
[2 Json from call ExecuteScriptAsync .txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11712794/2.Json.from.call.ExecuteScriptAsync.txt)

**(3)The string after decode by JsonConvert.DeserializeObject().ToString() is:**
[3 Base64 after DeserializeObject of Json data from WebView2.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11712795/3.Base64.after.DeserializeObject.of.Json.data.from.WebView2.txt)

**ERROR 1: The string return from ExecuteScriptAsync is too much shorter than the original one;
ERROR 2: The image from Convert.FromBase64String is totally BLACK**

**Version**
SDK: Microsoft.NET.Sdk
Runtime:  1.0.1823.32
Framework: net6.0-windows
OS: win11

**Repro Steps**
1. Call ExecuteScriptAsync to get Base64 encoded image data started with "data:image/png;base64,";
2. Call  JsonConvert.DeserializeObject().ToString() to get Base64 encoded image data;
3. Convert.FromBase64String to get image date of byte[] just use the Base64 substring after "data:image/png;base64,";
4. Create Image from MemoryStream of byte[];
5. Show Image on WinForm.

The jpg saved from Image which convented form Base64 string:

![text](https://github.com/MicrosoftEdge/WebView2Feedback/assets/18514981/849e69ca-439f-493a-a583-9f71d785a33d)

**Additional context**

**Comment by ElyssaJyu** [comment] 2023-06-15 08:53
Hi @evolcano, I'm trying to reproduce your scenario. It will help for investigating if a sample project can be provided. Will sync the update later. Thanks

**Comment by ElyssaJyu** [comment] 2023-06-27 07:58
Hi @evolcano, 
I change the input in URL box from JPG source link to HTML file link. It works. The Base64 string of html and WinForms are the same; Image is shown as expected. 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/111425758/fbe72eb0-cac1-4ab1-99ec-4a8712ca7a39)
Base64 string textbox is shown as blank since the content is large, then the page is frozen. so I comment out the code.
```
//show decoded base64 image data
//txtScriptData.Text = ImgData;
```
Hope this will unblock your work. Could you give some details why you would like to get Base64 encoded image data, then convert Base64 string to create the image? Thanks

**Comment by evolcano** [comment] 2023-06-29 01:56
Thank you @ElyssaJyu !
I repeated your operation ,change to local file is fine.  But it still failed if change url to any on-line location.

In my scenario, I want to get the image data of any **ON-LINE** page which displayed in WebView embeded in WinForm. 

Yes, I'm still blocked. Would you please do some test using on-line URL(not local file) and give me some feedback? 

Thanks again.

**Comment by ElyssaJyu** [comment] 2023-06-29 05:46
Hi @evolcano, 

I have tried to replace from `webView.Source = new Uri()` to `webView.CoreWebView2.Navigate()`. Triger it second time, then the image can show as expected.  

I would guess when the image data isn't complete in the first navigation, due to async task.  The data I got will convert to a white blank image, when testing. You can check [HTMLImageElement: loading property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading) test whether the image is loaded.

After second navigation, the image shows, but the Base64 string is different comparing with that from web page. That might be because the image source directly from web page and the image source from html embedded in html are different. 

Also please try [AddWebResourceRequestedFilter](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addwebresourcerequestedfilter?view=webview2-dotnet-1.0.1823.32) method and raise [WebResourceResponseReceived ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourceresponsereceived?view=webview2-dotnet-1.0.1722.45) event to get webcontent data . Thanks.

**Comment by evolcano** [comment] 2023-06-30 14:46
@ElyssaJyu , you are really awsome! Have a nice weekend. 

Finally I got the image data according to your solution. Thanks a lot!

And I noticed after webView_NavigationCompleted trigged,  the "complete" status of image is "True", but the image data is also bad. 

It is still a mystery to me.

**Comment by ElyssaJyu** [comment] 2023-07-03 03:25
Hi @evolcano, What does "bad" image data refer to?

**Comment by ElyssaJyu** [comment] 2023-08-08 07:51
Closing as answered but feel free to reactivate if you have more questions. Thanks

**Closed by ElyssaJyu** 2023-08-08 07:51 UTC
Labels: bug
