### ISSUE TITLE
(sometimes) control not fully fill window at first loaded

### ISSUE THREAD

**Issue by cuiliang** [MicrosoftEdge/WebView2Feedback#432] opened 2020-09-12 03:02 UTC
**Description**
When window first show, some time it will show on only part of window.
After mouse move over webview or move/resize window, it will be stretched to full window.
code:
```
<DockPanel>
        <wv2:WebView2 Name="webView"
                          Source="https://www.microsoft.com"
            />
        </DockPanel>
```
![image](https://user-images.githubusercontent.com/1972649/92984893-5ee2e080-f4e0-11ea-9a4e-9091c56e90e5.png)

**Version**
SDK: 0.9.628-prerelease
Runtime:   87.0.637.0
Framework: WPF with .Net 4.6.2
OS: Windows 10 2004(19041.450) , Windows 10 1909
Display: 3840*2160, display ratio: 150%

**Repro Steps**

**Screenshots**
![image](https://user-images.githubusercontent.com/1972649/92985547-38c03f00-f4e6-11ea-83e6-f94e595150e5.png)

It also happend with my own application.
![problem](https://user-images.githubusercontent.com/1972649/92985566-6f965500-f4e6-11ea-8d32-8b5323a81273.gif)

**Additional context**
This not always happen, only some times.
It seems like something related to dpi scale.

[AB#28658107](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28658107)

**Comment by cuiliang** [comment] 2020-09-12 03:22
Here is a sample project. 
Execute "\bin\x64\Debug\WpfApp2.exe"  window will like this:
![image](https://user-images.githubusercontent.com/1972649/92985963-e4b75980-f4e9-11ea-8fdc-e3a8cfcfa109.png)

When debuging in visual studio, it works normally.


[WpfApp2.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5212114/WpfApp2.zip)

**Comment by champnic** [comment] 2020-09-12 05:04
Thanks for filing this @cuiliang! This is a known issue (but didn't have a GitHub issue yet), and we'll take a look next sprint.

**Comment by cuiliang** [comment] 2020-09-13 23:59
Any workground on this issue? 
Adding  'window.UpdateLayout()' to Loaded event handler has no effect.

**Comment by champnic** [comment] 2020-09-14 20:18
No, we haven't started taking a look at this yet. I'll update you when we have more info. Thanks!

**Comment by cgeier** [comment] 2020-09-21 01:11
@cuiliang The issue didn't occur when I tried your project. Have you tried setting `HorizontalAlignment="Stretch"` and `VerticalAlignment="Stretch"` ?

```
<wv2:WebView2 Name = "webView"
              Source = "https://www.microsoft.com"
              HorizontalAlignment="Stretch"
              VerticalAlignment="Stretch" />
```

There does seem to be a little bit of a delay when starting one's program when the web cache files/folders don't exist yet. Not sure if it would make a difference or not, but you could try programmatically initializing "CoreWebView2" by calling `EnsureCoreWebView2Async`.

Subscribe to the Window "Loaded" event by adding `Loaded="Window_Loaded"`

**MainWindow.xaml**
```
<Window x:Class="WebView2Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:WebView2Test"
        mc:Ignorable="d"
        Loaded="Window_Loaded"
        Title="MainWindow" Height="450" Width="800">
```

Don't set Source property, as this causes initialization to occur.
```
<wv2:WebView2 Name = "webView21"
              CoreWebView2Ready="webView21_CoreWebView2Ready"
              HorizontalAlignment="Stretch"
              VerticalAlignment="Stretch" />
```

Then in MainWindow.xaml.cs, add the following code:

MainWindow.xaml.cs

```
public MainWindow()
{
    InitializeComponent();
}

private async void Window_Loaded(object sender, RoutedEventArgs e)
{
    //initialize CoreWebView2
    await webView21.EnsureCoreWebView2Async();

    //set Source property - navigate to URL
    webView21.Source = new Uri("https://www.microsoft.com", UriKind.Absolute);
}

private void webView21_CoreWebView2Ready(object sender, EventArgs e)
{
    //ToDo: subscribe to desired events (add event handlers) - CoreWebView2

}
```

**Comment by cuiliang** [comment] 2020-09-21 01:16
@cgeier 
It only happens on high dpi screen.

Run program directly from output folder, not from visual studio.
I use `await webView21.EnsureCoreWebView2Async();` in another program, It also have this problem.

I have also tried call 'UpdateLayout()' from window Loaded event handler, but have no effect.

**Comment by champnic** [comment] 2020-09-21 04:22
We've got a fix for this, and it should be available next release (around mid October). In the meantime, you should be able to workaround the issue by calling webView.UpdateWindowPos() after EnsureCoreWebViewAsync is completed (or in CoreWebView2Ready event handler). This will cause a WindowPosChanging event in our control which will correctly update the window bounds.

**Comment by cuiliang** [comment] 2020-09-21 05:07
@champnic webView.UpdateWindowPos()  works, thank you!

**Comment by champnic** [comment] 2020-10-19 23:28
This should now be fixed in WebView2 SDK 1.0.674-prerelease. If this is still an issue please let us know. Thanks!

**Comment by ukandrewc** [comment] 2020-11-29 20:02
Looks like this one is back in V1.0.707.0

**Comment by champnic** [comment] 2020-12-03 08:22
Thanks for the heads up. We'll take another look...

**Comment by champnic** [comment] 2020-12-07 17:03
@ukandrewc We've been unable to repro this bug. Do you have a repro sample you could share, or other machine setup info?

**Comment by ukandrewc** [comment] 2020-12-07 18:59
@champnic Sorry, I'm not seeing it all the time, it's while resizing during initialisation. Will try and get a repro together.

**Comment by champnic** [comment] 2020-12-08 22:38
Ah, I don't think we've been trying to test other explicit resizing during initialization - the original bug was with just a default "Create a webview" behavior we would see the broken resizing. My guess is the control takes the current expected bounds when it begins initialization and uses those, and then misses the updated size until it's done initializing, at which point it starts listening for changes. The fix may be something like having the control re-check bounds when it hooks up to size listening.

Let me know if you do get a repro sample/app, as that will make verifying this much easier. Thanks!

**Comment by ukandrewc** [comment] 2020-12-09 09:00
@champnic Will do, just a bit up against with my day job at the moment ;-)

**Comment by ukandrewc** [comment] 2020-12-10 12:16
@champnic I think this is me, possibly due to a WebView2 change, I'm not sure.

I was enabling **DevTools Protocol** events in **CoreWebView2InitializationCompleted**:

`CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}")`

This is deadlocking. I don't think it was prior to 1.0.707.0, but not sure. Has the CoreWebView2 event changed from Async to Sync? because I'm sure this used to work.

Anyway, I've moved "Page.enable" now, and I can't reproduce the issue any more.

**Comment by champnic** [comment] 2020-12-10 22:34
@ukandrewc The events are still async in general, though there are parts of it that are sync (setup for the CDP call). Where did you move the call to that's working? If you move it back, do you hit the same deadlock issue (it's reproducible)?

**Comment by ukandrewc** [comment] 2020-12-11 08:25
@champnic This is me, because I'm waiting for the result of the call. It is a little odd, because using PushFrame prevents the task completing. I don't know you need to know, but this is what I've found:

```
Sub CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs)

  'Task doesn't complete
  Dim Task = CoreWeb.CallDevToolsProtocolMethodAsync("Page.enabled", "{}")
  Task.ContinueWith(Sub() Frame.Continue = False)

  Frame.Continue = True
  Dispatcher.PushFrame(Frame)

End Sub
```
```
Sub CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs)

  'Task completes but is faulted
  Dim Task = CoreWeb.CallDevToolsProtocolMethodAsync("Page.enabled", "{}")
  Task.ContinueWith(Sub() 'Task.IsFaulted True here)

End Sub
```

**Comment by johna-ms** [comment] 2021-01-27 23:04
@ukandrewc any luck on a repro? I haven't been able to repro anything.

**Comment by ukandrewc** [comment] 2021-01-28 09:37
@johna-ms Sorry, should have closed this, as it was my fault.

**Comment by champnic** [comment] 2021-01-28 17:26
Thanks for the follow-up - closing this for now. Let us know if you see this again!

**Closed** 2021-01-28 17:25 UTC
Labels: bug, tracked
