### ISSUE TITLE
CoreWebView2_ProcessFailed event ExitCode: '259'  Reason: 'Unexpected'

### ISSUE THREAD

**Issue by Elisa-Adela** [MicrosoftEdge/WebView2Feedback#2793] opened 2022-09-15 13:48 UTC
**Description**
I have a WinForms application using WebView2 and WebView Runtime fixed version.
There are several windows that are initialized.
After upgrade sometimes the application crashes. at startup.

CoreWebView2_ProcessFailed event ExitCode: '259', Reason: 'Unexpected', ProcessDescription: '', ProcessFailedKind: 'BrowserProcessExited', FrameInfosForFailedProcess: ''

Previous version(1.0.961.33) did not have this issue.
Is is solved on versions later than 1.0.1185.39?or How to prevent it?

The documentation states about exitcode 259 but with different reason.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedeventargs.exitcode?view=webview2-dotnet-1.0.1185.39

**Version**
SDK: 1.0.1185.39
Runtime: 100.0.1185.50
Framework: WinForms
OS:Win10

**Repro Steps**

149280814355 06/06/22 05:28:00.232 t@15848 dus WebView2Window.cs(229){CoreWebView2Ready}: Object ID 2 Thread7
149280837689 06/06/22 05:28:00.248 t@15848 dus WebView2Window.cs(191){SetBrowserSettings}: Object ID 2 Thread 7 
149280881077 06/06/22 05:28:00.295 t@15848 dus WebView2Window.cs(211){AddBrowserEventHandlers}: Object ID 2 Thread 7 
149280884739 06/06/22 05:28:00.295 t@15848 dus WebView2Window.cs(247){CoreWebView2Ready}: 
149281002204 06/06/22 05:28:00.420 t@15848 dus WebView2Window.cs(457){attachExternalToWindow}: 
149281002242 06/06/22 05:28:00.420 t@15848 dus WebView2Window.cs(253){CoreWebView2Ready}: Object ID 2 Thread 7
149283719077 06/06/22 05:28:03.128 t@15848 dus WebView2Window.cs(218){ExecuteEventLater}: Object ID 2 Thread 7
149283732555 06/06/22 05:28:03.144 t@15848 dus WebView2Window.cs(540){CoreWebView2_ProcessFailed}: Object ID 2 Thread 7 - Gaudi LUI: CoreWebView2_ProcessFailed
149283759485 06/06/22 05:28:03.175 t@15848 dus WebView2Window.cs(541){CoreWebView2_ProcessFailed}: SDS error 11504: CoreWebView2_ProcessFailed event ExitCode: '259', Reason: 'Unexpected', ProcessDescription: '', ProcessFailedKind: 'BrowserProcessExited', FrameInfosForFailedProcess: ''
149283759518
 
**Screenshots**

**Additional context**

**Comment by Elisa-Adela** [comment] 2022-12-20 07:55
@oggy22 Hello, are there any updates on this issue?

**Comment by sln162** [comment] 2022-12-25 05:43
So far, 108.0.1462.54 still encounters the problem of 259, and the data collected by our background error still exists.

**Comment by novac42** [comment] 2023-02-16 04:53
@Elisa-Adela @sln162 Thanks for the update. I've assigned the issue to a dev to look into it.

**Comment by ElyssaJyu** [comment] 2023-02-20 09:00
Hi @Elisa-Adela @sln162, does this issue still exist on your side? If does, could you give some details about your scenario, like how you use webview2 in your app? Thanks.

**Comment by sln162** [comment] 2023-02-21 10:07
@ElyssaJyu We have ignored this error, and will reinitialize in case of process crash, so don't know if it will still happen.

**Comment by ElyssaJyu** [comment] 2023-02-21 10:21
@sln162 Hi, if the crash will still block you later, you could open a new issue with description of your scenario and mention there. Thanks.

**Comment by ElyssaJyu** [comment] 2023-03-30 10:25
We're making this issue as unconfirmed because it has not had recent activity and we weren't able to confirm it yet.

**Comment by ElyssaJyu** [comment] 2023-05-12 02:53
I will close this issue as we didn't hear back for several days, feel free to reopen with more info so we can investigate further, thanks.

**Closed by ElyssaJyu** 2023-05-12 02:53 UTC
Labels: bug, status-unresolved

**Comment by XinZhangBBL** [comment] 2025-04-27 01:17
@sln162 Excuse me, do you know what version this issue is fixed? I'd like to make sure this is fixed

> [@ElyssaJyu](https://github.com/ElyssaJyu) We have ignored this error, and will reinitialize in case of process crash, so don't know if it will still happen.
