### ISSUE TITLE
Hovering over images triggers visual search

### ISSUE THREAD

**Issue by RichardSteele** [MicrosoftEdge/WebView2Feedback#2345] opened 2022-04-07 07:27 UTC
**Description**

Hovering over an image causes the visual search feature to appear. This shouldn't happen or be made configurable. Can the feature be disabled by an additional browser argument (--disable-feature=ABC)?

**Version**

SDK: 1.0.1150.38
Runtime: 100.0.1185.29
Framework: Win32
OS: Win10

**Repro Steps**

Launch WebView2APISample, navigate to a site with images (e.g. https://developer.microsoft.com/en-us/microsoft-edge/webview2/) and hover over an image.

**Screenshots**

![image](https://user-images.githubusercontent.com/2310381/162142452-66f567f6-fdbf-44c1-8ebc-2427422cb58a.png)

[AB#38478100](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38478100)

**Comment by champnic** [comment] 2022-04-12 04:54
Hey @RichardSteele - Thanks for the bug report and sorry you're hitting this. I've added this to our backlog. We plan to give a flag to disable this soon.

**Comment by champnic** [comment] 2022-06-24 22:03
@simeyla This sounds like you are talking about the browser behavior in general? You can open feedback in the browser using the "Send feedback" tool (alt + shift + i). The flag I was suggesting would only apply to WebView2 (or I guess if a user chose to launch the browser with that specific command-line arg).

**Comment by nickw3154** [comment] 2022-07-06 14:53
This is most definitely NOT a welcome feature.  As a e-commerce company that spends alot of money driving customers to our site, the last thing we want is for the browser to offer them a semi-automated reverse image search to go and find a product elsewhere.  

Fine have the feature, but it should be disabled on websites by default, and allow the site within the html to determine to enable the feature or not!

**Comment by colincdean** [comment] 2022-07-11 17:36
This feature should be off by default or removed altogether.

We develop web apps for children with learning disabilities such as Autism.  Using pointer-events:none isn't an option if you want the child to click an image, and having them distracted by visual search is hugely disruptive to their concentration and learning.  We cannot convey to every parent and teacher of a disabled child that they can turn it off in Edge settings.

If it must be on by default, then there has to be a meta tag that can be used to disable it.  Please will someone in the WebView2 team convey this to the Edge team as well (yes I have fed back there, but am not optimistic that I will have had any effect).

**Comment by champnic** [comment] 2022-07-11 22:45
@colincdean I've forwarded this thread to the right team to look at this feedback. Thanks!

**Comment by champnic** [comment] 2022-07-12 16:55
Hey folks - I've heard back from the owning team and they are considering improvements here. In the meantime, we may be able to disable the feature for domains under certain circumstances. If you'd like to do this, please email me at `champnic@microsoft.com` with information about the domains you would want to disable this behavior for. Thanks!

**Comment by morganwdavis** [comment] 2022-07-16 09:33
Browser user agents should never change the visual design or UX of a page without the user opting into it (e.g., by settings they themselves enable or by installing an extension where that behavior is then expected). UAs have one job: faithfully render the page as it was designed and developed!

This is definitely undesirable for ecommerce site owners. Visual search, as implemented now, sends customer traffic off to competitor sites. Worse, the manner in which it presents this to the user makes it look like its part of the website's own UX as it is basically changing site's visual elements, behaviors, and all done within the viewport (sort of).

**If this must be turned on by default, then consider this alternative: restrict visual search within the site in which the client is browsing.  If the user wants to expand the results beyond the site, they can do that via Settings.**

History repeating? Please don't make web developers hate Microsoft's browser ... again.

**Comment by tochukwuIbeEkeocha** [comment] 2022-10-11 21:11
Hello,

A PR which disables Visual Search on WebView2 has just been checked in. The update should be a part of the next release. Please feel free to reopen if the issue persists after that.

**Closed by tochukwuIbeEkeocha** 2022-10-11 21:11 UTC
Labels: bug, tracked

**Comment by alexanderkladov** [comment] 2023-03-02 21:54
The issue is still here! I am on macOS Version 12.6.3 and Edge Version 110.0.1587.63.

I consider this nothing less than malware injection! You are hijacking website UX to get the user to do something we do not want them to do. Absolutely unacceptable.

Do you want us to start banning Edge again like what we used to do with something like https://browser-update.org/? Because that's how you get developers to start doing that again.

**Comment by champnic** [comment] 2023-03-02 23:18
@alexanderkladov This repo is for the WebView2 control. For browser feedback, please use the Send Feedback tool in the browser under '...' > 'Help and Feedback', or Shift+alt+i.

**Comment by alexanderkladov** [comment] 2023-03-03 02:13
@champnic There needs to be a public forum where we can openly shame Microsoft Edge for this kind of stuff. My singular complaint is not going to do anything without outside exposure.

**Comment by champnic** [comment] 2023-05-09 22:12
@robsyc I don't think there's a tag for this. What site are you seeing it on the map tiles?

**Comment by robsyc** [comment] 2023-05-12 13:06
@champnic I am creating a dynamic site utilizing the [opendatasoft map widget](https://help.opendatasoft.com/widgets/#/api/ods-widgets.directive:odsMap) and had this issue when viewing the site on edge. After some investigation, I found out the problem is more strange... viewing the map on a static site doesn't trigger the visual search. However, when viewing the exact same HTML content but served through Django, it does trigger it.

**Comment by champnic** [comment] 2023-05-12 18:25
Weird, thanks for confirming. I wonder what heuristic they are using to show it. I've forwarded this to the owner team to follow-up.

**Comment by champnic** [comment] 2023-05-24 22:28
@sandstrom Can you share the hosts or domains that are getting affected by this in your case? You can email me at `champnic@microsoft.com` if you prefer.

**Comment by morganwdavis** [comment] 2023-05-26 21:48
@champnic: Why just @sandstrom's case? Apparently, all ecommerce sites can be affected by this.  See https://www.jeromes.com.  Hover over the hero banner and the image search icon appears, effectively modifying the presentation of the website in a visually intrusive way that breaks the design trust we have with our browsers.

Click on that icon and you get a complete content layout shift of the primary viewport (terrible!) with a Bing search result sidebar flyout that has links to dozens of competitor websites. Navigate to a product listing page and then hover over the product tiles:
https://www.jeromes.com/furniture/living-room/sets

There it is again, just below our favorite (heart) icon! This obscures product view and introduces an icon design and color that doesn't even match our site. Honestly, who at Microsoft has **lost their mind** on this?

As I said earlier in this now _closed_ ticket, this is a great way to piss off web developers who, only a couple years ago were thrilled at Microsoft's direction with Edge, encouraged its use over Chrome for the improvements over it, and now we are starting to hate it, just like we began to hate Internet Explorer after Microsoft screwed that up, too.  All the crap being loaded into it is bloat nobody asked for. Turns out its just as bad with privacy as Chrome.  And now it is becoming a competitive disadvantage to support it if it offers any way for shoppers to get redirected away from a commerce site that has a huge investment in attracting and maintaining visitors.  It's getting harder to recommend Edge anymore, all due to Microsoft mucking up what was originally an excellent alternative browser.

Visual search aids like this should be a user-installed extension, or a default-to-off setting they can enable, a right-click menu option (which already exists), and/or a meta tag that can be controlled by the website author.  It SHOULD NOT be a default-to-on feature that affects the visual appearance of a site or adds what seems like some kind of site-implemented functionality.

**Comment by champnic** [comment] 2023-05-26 22:40
@morganwdavis I hear you. Unfortunately I only own WebView2, where we turned this feature off by default, and not the Edge browser version or behavior of this feature. This issue is closed because this is the WebView2Feedback repo, not general feedback for Edge, and there's no more work on WebView2 here.. I've been trying to be helpful by forwarding requests to the right team to have domains added to the block-list.

There is a browser setting to disable visual search if you don't want to see it when navigating to jeromes.com. If you own that domain and want it disabled everywhere I can forward the request to the right team.

**Comment by morganwdavis** [comment] 2023-05-30 19:14
@champnic Nic, thanks for the clarity here, especially with respect to your role, and your interest to help make Edge better (which we all want and is why we care enough to complain about it).

That anyone can request a whitelisting for a domain in Edge visual search bothers me almost as much as the feature itself. This either means that production builds of Edge include lists of domains to disable the feature, or there is some real-time network check taking place to look up a domain to see if it's in an exclusion list. Both are terrible, unscalable patterns.

I'd rather see a universal user option based on sensible design that defaults to off with a settings override, or make it part of the Edge feature onboarding walkthrough. 

Further, I'm sure I'm not alone in preferring that Microsoft focused on improving the core browsing experience over these kinds of add-ons.

**Comment by sandstrom** [comment] 2023-05-30 19:22
@morganwdavis A list of domains is actually pretty scaleable. For example, the HSTS preload list (https://hstspreload.org/) is implement as such, in several browsers.

I agree that this feature is bad, but I think @champnic is being very helpful here, and the domain approach actually isn't too bad.

**Comment by webdev69420** [comment] 2023-06-23 08:08
Please reconsider and **just let us add a meta tag on our pages that would disable the feature** on those pages. This would benefit both parties :

- Developers have a PROPER solution to disable this "Visual search" feature on their sites
- Microsoft can still show this "Visual search" menu on a lot of websites, because most websites probably won't disable this as they won't be aware of this meta tag, or just won't care, especially if they're not e-commerce websites : the feature won't bother them as much as it is not directly hurting their business (the reverse image search one click away isn't exactly great news for an e-commerce site)

Using `pointer-events: none;`, on top of probably breaking accessibility features and preventing some screen-readers to detect the `alt` text of an image also prevents regular users to just right-click an image to download it. So it really is not a good solution at all. This feels super hacky and just reminds me of the days of Internet Explorer quirks...

**Comment by mrkalchemy** [comment] 2023-09-22 10:07
This is giving me flashbacks to the launch of IE6 with its "Image Toolbar" feature. I would suggest that if someone has <meta http-equiv="imagetoolbar" content="no"> in their <head> section then they probably don't what this version of it ether. Maybe you could add a check for that and not show the new toolbar if present. 🤬

**Comment by simeyla** [comment] 2023-11-11 02:33
Did this ever get resolved? (i.e. killed) I saw a couple comments saying they'd backtracked but I can't quickly confirm if there are new defaults. It's been over a year since a comment here so fingers crossed...?

**Comment by morganwdavis** [comment] 2023-11-12 05:09
No. Edge still does this. I gave it a chance. It started out as a great alternative to Chrome. I really liked it and recommended it to everyone then. :-(  Personally, I solved this issue (and the other annoying ones that were added since then) by switching to Firefox. Seems the only way to get something to improve these days is to simply abandon it, which is a shame.

**Comment by champnic** [comment] 2023-11-14 18:35
FYI - Not expecting to change your mind, but for personal usage there is a setting to disable the hover search button:
edge://settings/appearance/hoverMenu

**Comment by morganwdavis** [comment] 2023-11-14 22:22
:-) Thanks, Nic. Again, no shade on you for any of this. I actually want to keep that setting on just so I know it still impacts "normals" by default. I'm sure we'll never know, but curious about the engagement with this. If it was really low, I wonder if Microsoft would decide to drop it at some point.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4434533/788e7cf3-9b39-4e1a-90e5-f7e60bce8497)

**Comment by bezborodow** [comment] 2024-02-16 00:08
The visual search can also interfere with user interface elements on the page. For example, when using an iamge gallery such as [dimsemenov/photoswipe](https://github.com/dimsemenov/photoswipe), the close button is obscured by the visual search, making it unusuable, and thus breaking the user interface experience.

<img width="147" alt="Screenshot 2024-02-16 103442" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/950634/db9f0b3f-a7a5-4c23-9e5b-b9de1e5bfbad">

<img width="134" alt="Screenshot 2024-02-16 103525" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/950634/d32255b9-f4c7-461c-b563-6ebb37e5c291">

**Comment by ASchmidt1** [comment] 2024-07-12 02:16
> the close button is obscured by the visual search, making it unusable, and thus breaking the user experience

Precisely. 
Unbelievable the continued ignorance of MS staff vs. the real world.

**Comment by 12t13g3aga3tga3** [comment] 2024-08-14 14:27
The issue is not still fixed/made easy for developers?
@champnic can you add my website https://hemp-infusion.com to the list that doesnt show image search?
