### ISSUE TITLE
ICoreWebView2HttpRequestHeaders::RemoveHeader() doesn't work on "Origin"

### ISSUE THREAD

**Issue by RayIon** [MicrosoftEdge/WebView2Feedback#839] opened 2021-01-21 11:19 UTC
Hello,

I have a native application that uses IWebCoreView2 (pre-release 774 I think). I'm trying to do OAuth2 against login.live.com, using Navigate() and NavigateWithWebResourceRequest():

First step -- getting a code -- works fine. This is what I'm trying to use for the second step (swapping a code for a token):

hr = Environment2->CreateWebResourceRequest(
						LiveTokenRedeemUri.c_str(),
						L"POST",
						PostDataStream.get(),
						L"Content-Type: application/x-www-form-urlencoded\r\n",
						&Request
					);

In that second step where I try to swap the code for a token, the request fails with an error:

{
     "error":"invalid_request",
     "error_description":"Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.",
     "correlation_id":"e4defc60-9e57-4306-b46f-0e4d2dc99839"
}

The first step (getting the code), works fine. This is all being done from the same app on the same machine, it doesn't "feel" right to change the settings in Live to make my native app a "single page application", when there's already native settings. 

As far as I can tell, the only difference is in the second API call the header below is added automagically by IWebCoreView2:

     Origin: null

The other call (via IWebCoreView2 Navigate()) doesn't seem to add "Origin: null", and works. I've tried using SetHeader() and RemoveHeader() to effectively remove "Origin: null" but it doesn't work.

 - Firstly, can I use IWebCoreView2/WebView2 to do OAuth against Live/Onedrive?
 - Secondly, is the "Origin: null" thing correct, and you just can't use WebView2 for this?
 - Thirdly, should I be able to change "Origin" from my code?

Or am I barking up the wrong tree entirely?

Thanks,
-R

[AB#31425010](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31425010)

**Comment by RayIon** [comment] 2021-01-21 17:10
(Just tried submitting the same request via Fiddler to the endpoint with "Origin: null" removed, and it works)

**Comment by champnic** [comment] 2021-01-22 00:29
Hey @RayIon - just to confirm, you don't need to specify an origin, because you confirmed in fiddler if you remove it then it works. If that's not working with RemoveHeader then it's possible the origin null is being added later on by WebView2 code. I'll open a bug on our backlog to take a closer look. Thanks!

**Comment by RayIon** [comment] 2021-01-22 05:33
Just to summarise:
 - Fiddler is showing no Origin set via Navigate() calls, just the CreateWebResourceRequest()/NavigateWithWebResourceRequest() combination (POST method, if that's relevant)
 - SetHeader() and RemoveHeader() won't affect the "Origin: null" that gets added, even if you specify a "nullptr" value.
 - Setting Origin via CreateWebResourceRequest() header parameter also has no affect.

**Comment by quietfanatic** [comment] 2021-07-16 03:43
Hi @Reylon.  After doing some investigation, I've found that the browser process requires an origin header to exist whenever the request method is POST.  This behavior is specified by the CORS standards, and since it's a security feature, it might not be best for us to diverge from the browser's behavior in this case.  You can find documentation for the Origin header at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin.

Can you try manually adding an Origin header with an origin the server will accept?  I don't know how to find out all the origins it'll accept, but it should at least accept its own origin of "https://login.live.com".

**Comment by quietfanatic** [comment] 2021-09-14 19:39
Since we aren't going to make any changes regarding this issue and it's been two months, I'm going to close this.  @RayIon if you have any more input, feel free to reopen this issue.

**Closed by quietfanatic** 2021-09-14 19:39 UTC
Labels: bug, tracked
