### ISSUE TITLE
Version 95.0.1020.30 causes CoreWebView2.Settings.UserAgent to intermittently fail

### ISSUE THREAD

**Issue by joshmcorreia** [MicrosoftEdge/WebView2Feedback#1861] opened 2021-10-22 18:57 UTC
**Description**
After updating to Version 95.0.1020.30, the `CoreWebView2.Settings.UserAgent` property is intermittently failing. When accessing a webpage through WebView2 it sometimes uses the value that I set it to, and sometimes it ignores this value and acts as if it was never set. Previous versions always use the value that `UserAgent` is set to. No code in my product was changed.

**Version**
Runtime: Version 95.0.1020.30 64-bit
OS: Win10 (untested on others)

**Repro Steps**

1. Open software that uses WebView2
2. Right click on your webpage and click "Inspect"
3. Go to the "Network" tab and click the "Preserve log" checkbox
4. Click around on the webpage (being sure to click new links to generate new traffic)
5. Click on the network traffic requests and view the "User-Agent" Request Header (should be at the bottom of the "Headers" tab). Note that it changes between whatever you set it to and the default Request Header sent by WebView2.

[AB#36914861](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36914861)

**Comment by joshmcorreia** [comment] 2021-11-02 17:19
There doesn't seem to be any pattern to the requests unfortunately. I just tried again on version `Microsoft WebView2 95.0.1020.40 64-bit` and the issue still persists.

**Comment by joshmcorreia** [comment] 2021-11-02 20:49
Unfortunately I'm unable to provide network traffic logs due to the nature of the secure environment that I'm working in, but I'll keep an out eye to see if I can find consistency in the failures.

**Comment by champnic** [comment] 2021-11-03 03:36
Thanks for confirming this isn't #1860. I've added this bug on our backlog.

**Comment by jarno9981** [comment] 2021-11-03 11:57
@joshmcorreia  try this works for me

  private void newWeb_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
              

            if (new Uri(e.Uri).Host.Contains("accounts.google.com"))
            {
                if (newWeb.CoreWebView2 != null)
                {
                    var settings = newWeb.CoreWebView2.Settings;
                    if (settings.UserAgent != "Chrome")
                        originalUserAgent = settings.UserAgent;

                    settings.UserAgent = "Chrome";
                }
            }
            else
            {
                if (newWeb.CoreWebView2 != null)
                {
                    var settings = newWeb.CoreWebView2.Settings;
                    if (settings.UserAgent == "Chrome")
                        settings.UserAgent = originalUserAgent;
                }
            }
            // Note: Oversimplified test. Need to support idn, case-insensitivity, etc.
          
         
          
        }

**Comment by champnic** [comment] 2022-03-16 18:04
Thanks for the info! We have a set of issues we think are stemming from redirect failures and inconsistencies, so I'll add this one to investigate with those.

**Comment by yildirimcagri** [comment] 2022-05-20 18:57
Hi @joshmcorreia, we have root caused an issue that seems to be causing this. A workaround is to set the --disable-domain-action-user-agent-override browser argument in WebView2, please let us know if this works for you. Thanks!

**Comment by Kay-Burchardt** [comment] 2022-07-08 15:24
Hi Microsoft,

we also experienced issues with the useragent in Webview2. Our embedding product - SAP Business Client - is patching the useragent to contain the term "SAP NetWeaverBusinessClient". We noticed that the patched useragent is not applied to frames that have a different origin than the root document. Additionally, we only receive the NavigationStarting and WebresourceRequested events for such frames. For frames that have the same origin as the root document we receive the full set of events, and the patched useragent is also applied!

@joshmcorreia I also tested your suggested "--disable-domain-action-user-agent-override" browser argument. Unfortunately, it didn't change the described behaviour.

Best regards,
Kay

**Comment by yildirimcagri** [comment] 2022-07-08 20:27
I will look into this and get back to you. For the WebResourceRequested event not firing on out of process iframes, we have a fix in the works (from an initial guess the user agent issue could be related to this and may need a similar fix). For navigation events, which events are you subscribing to? Frame events should only come to FrameNavigation events (i.e. FrameNavigationStarting) or CoreWebview2Frame navigation events (i.e. [CoreWebView2Frame.NavigationStarting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.navigationstarting?view=webview2-dotnet-1.0.1264.42)).

**Comment by ghorowski** [comment] 2022-07-15 06:50
Hi, I started getting this issue, altough I'm not sure if it's still related to WebView2 itself.
In PowerBI Desktop (January 2022) RS, I get this error since about a week or so: 
![image](https://user-images.githubusercontent.com/109335205/179166275-4cd7680d-f741-45b4-84ed-2453a429e847.png)

When I click sign-in I can see a login window (empty but has ms office login link in the title) blink quickly and then I receive the above message. 

The exact same thing is working fine PowerBI Deskop (from MS store) but I need to use the RS version. 

I tried the following:
- completely reinstall PowerBI and WebView2
- fixes from the #1860 but only the env variable part as BrowserSignIn policy on my PC was already set to 0 - I tried it with 1 and 2 as well

I have WebView2 v. 103.0.1264.62 installed
I'd try the --disable-domain-action-user-agent-override argument, but since WebView is being started by PowerBI, I'm not sure how I can do that.

**Comment by champnic** [comment] 2022-07-15 23:18
@ghorowski It sounds like there was a bug in PowerBI that got resolved between Jan and May releases. I'm not sure there's anything we can do on the WebView2 side for that issue. Thanks!

**Comment by Kay-Burchardt** [comment] 2022-08-01 13:54
> I will look into this and get back to you. For the WebResourceRequested event not firing on out of process iframes, we have a fix in the works (from an initial guess the user agent issue could be related to this and may need a similar fix). For navigation events, which events are you subscribing to? Frame events should only come to FrameNavigation events (i.e. FrameNavigationStarting) or CoreWebview2Frame navigation events (i.e. [CoreWebView2Frame.NavigationStarting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.navigationstarting?view=webview2-dotnet-1.0.1264.42)).

Currently we only register to FrameNavigationStarting. We are not using the new events of CoreWebview2Frame yet, so I don't know if they are working or not.
Additional observation: for frames of different domain, the WebResourceRequested event is only firing for the document, not for embedded resources like images or scripts. We also don't receive a corresponding WebResourceResponseReceived event for the document.

**Comment by yildirimcagri-msft** [comment] 2023-08-01 16:47
Hi, lately I cannot repro this issue, could you provide some repro steps if this still happens for you?

**Comment by joshmcorreia** [comment] 2023-08-01 18:41
> Hi, lately I cannot repro this issue, could you provide some repro steps if this still happens for you?

I no longer work at the company that I worked at when I encountered this issue so I no longer have the code to reproduce. Feel free to close this since I can't confirm or deny.

**Comment by yildirimcagri-msft** [comment] 2023-08-07 13:42
Closing for now, please reopen with repro steps if this issue persists.

**Closed by yildirimcagri-msft** 2023-08-07 13:42 UTC
Labels: bug, tracked
