### ISSUE TITLE
.Net Core Console Application Supporting

### ISSUE THREAD

**Issue by jameslin0312** [MicrosoftEdge/WebView2Feedback#202] opened 2020-05-23 06:48 UTC
Does WebView2 support .Net Core 3.1 Console Application? I am trying to use WebView2 as the codes below.

      var ev  = await CoreWebView2Environment.CreateAsync();
      var wc = await ev.CreateCoreWebView2ControllerAsync(IntPtr.Zero);

But it doesn't work.

Thanks for your help!

[AB#26584480](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26584480)

**Comment by david-risney** [comment] 2020-05-26 18:52
You can use CoreWebView2 directly in a .NET application as long as you can create an HWND to use as the parent to pass in in the CreateCoreWebView2ControllerAsync call. You could create a hidden HWND to use there. We don't currently support passing in null/0 for the parent window.

**Comment by jameslin0312** [comment] 2020-05-27 06:16
Hi David,

Thanks a lot for your reply. Can you please give me sample code of how to create a hidden HWND? Is it only supported on Windows platform or cross-platform?

**Comment by jameslin0312** [comment] 2020-06-05 03:03
Hi David,

I have tried a couple of ways to make .net core console application working with WebView2, such as the codes below.

      var ev  = await CoreWebView2Environment.CreateAsync();
      var form = new Form();
      var wb = new Microsoft.Web.WebView2.WinForms.WebView2();
      form.Controls.Add(wb);
      await wb.EnsureCoreWebView2Async(ev);

But the process stuck at EnsureCoreWebView2Async.

Any help would be appreciated.

**Comment by devttebayo** [comment] 2020-08-13 21:40
I went ahead and tried to use CreateWindowsEx() + CreateCoreWebView2ControllerAsync() to throw together a simple .Net Core console app that would host WebView2 in a hidden window:

```csharp
using System;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

using Microsoft.Web.WebView2.Core;

namespace WebViewTest
{
    class Program
    {

        private static readonly IntPtr HWND_MESSAGE = new IntPtr(-3);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr CreateWindowEx(
           uint dwExStyle, string lpClassName, string lpWindowName, uint dwStyle, int x, int y,
           int nWidth, int nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInstance, IntPtr lpParam);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern Boolean DestroyWindow(IntPtr hWnd);

        static async Task Main(string[] args)
        {
            Console.WriteLine("Starting WebView2 browser...");

            IntPtr dummy = CreateWindowEx(0, "Message", null, 0, 0, 0, 0, 0,
                HWND_MESSAGE, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);

            var browserEnv = await CoreWebView2Environment.CreateAsync(@"C:\Program Files (x86)\Microsoft\Edge Dev\Application\86.0.601.1");

            var browserController = await browserEnv.CreateCoreWebView2ControllerAsync(dummy);

            // This never executes
            Console.ReadKey();

            DestroyWindow(dummy);
        }
    }
}
```

What's interesting is, when I run this I see msedgewebview2.exe in my task list, but execution never moves past CreateCoreWebView2ControllerAsync():

<img width="482" alt="webview2-taskman" src="https://user-images.githubusercontent.com/59602202/90189534-39907480-dd72-11ea-8115-dcc6438fbf8a.png">

This example was put together using Microsoft.Web.WebView2 NuGet version 0.9.579-prerelease.
(I also won't rule out the possibility that my HWND creation code is bad - I'm not too good with Win32)

**Comment by MatthewBeardmore** [comment] 2021-02-12 22:07
Any update on this? It would be useful for me as well.

**Comment by champnic** [comment] 2021-03-04 01:05
One of our devs took a look and it seems the problem is stemming from HWND_MESSAGE which causes an ERROR_INVALID_WINDOW_HANDLE. We have the work to fix that and allow HWND_MESSAGE on our backlog, but I'll try to get the priority bumped up.

**Comment by RobertoBaruffa** [comment] 2021-03-04 08:41
Thank You @champnic
this is a very important feature to enable the adoption of the WebView2 control in my project.

Bye :-)

**Comment by fvanheeswijk** [comment] 2021-04-16 14:12
We have a similar case here where `environment.CreateCoreWebView2ControllerAsync` does not seem to ever complete.

Our code:
```
public static Form CreateTestForm()
{
	var form = new Form
	{
		Size = new Size(1280, 1024)
	};

	var control = new Control
	{
		Dock = DockStyle.Fill
	};

	control.CreateControl();

	var environment = CoreWebView2Environment.CreateAsync().GetAwaiter().GetResult();
	var controller = environment.CreateCoreWebView2ControllerAsync(control.Handle).GetAwaiter().GetResult();

	controller.CoreWebView2.AddHostObjectToScript("handler", new Handler());
	controller.CoreWebView2.NavigateToString(
@"<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <button onclick='window.chrome.webview.hostObjects.sync.handler.openForm();'><h1>Open new form</h1></button>
    </body>
</html>");

	form.Controls.Add(control);

	return form;
}
```

Also, we are not completely sure if we are using it correctly like this, we haven't been able to find an example on how to use `CreateCoreWebView2ControllerAsync`, more clarification would be useful.

Could you take a look at it, hopefully soon?

**Comment by RobertoBaruffa** [comment] 2021-06-07 08:51
Hi guys,
 any update on this feature?

**Comment by champnic** [comment] 2021-06-08 04:21
We have it currently assigned to a dev, and I hope they are able to begin work on it shortly. Thanks!

**Comment by daniatic** [comment] 2022-01-13 12:20
@champnic could you please give an update on the state?

**Comment by champnic** [comment] 2022-01-13 19:50
Hey @daniatic - Unfortunately our priorities had shifted and so we haven't begun this work yet.

**Comment by champnic** [comment] 2022-01-14 18:44
Yes we still want to do this work. It's currently listed in this upcoming quarter, but it's at the bottom of the list for this quarter so is the most likely to be dropped if other work comes in.

In the meantime, I did come across a different user who seems to have gotten it working. I haven't tried this myself though:
https://stackoverflow.com/questions/66699811/how-do-i-use-webview2-in-a-console-application

**Comment by daniatic** [comment] 2022-01-26 09:21
@champnic thx for the workaround. Unfortunately it didn't help. Our use case is that we need to render browser content on windows servers in a service. First we wanted to use puppeteer, but didn't want to deploy chromium to every client. 

We would have waited for this feature but the uncertaintity on the completion date is drawing us away from it.

**Comment by jennifer-jacobs** [comment] 2022-03-11 23:36
Hi @daniatic  - I've started investigating this issue. Can you give me a concrete example of what scenario you're trying to accomplish? Would you ever want to show the hidden WebView you create?

**Comment by daniatic** [comment] 2022-03-13 15:32
@jennifer-jacobs thx for reaching out. 

> Can you give me a concrete example of what scenario you're trying to accomplish?

We have an application that needs to render dashboards, charts and other content which is created by users based on browser rendered charts and other content. As long as the user actively creates charts and so on, the browser can just display what he/she created, but we also need to render automatic generated reports with dynamic data on the server with the user interacting. 
That is why we need a service which we can instruct to render the desired content, without any user interaction, and we don't want any of this to be visible on the executing server. 
> Would you ever want to show the hidden WebView you create?

No.

I hope I described it clearly. If not please contact me and I'll provide more details.

**Comment by devttebayo** [comment] 2022-03-13 20:09
> Hi @daniatic - I've started investigating this issue. Can you give me a concrete example of what scenario you're trying to accomplish? Would you ever want to show the hidden WebView you create?

I know I wasn’t tagged but I was hoping I could add my thoughts 😊 My scenario involves showing a user web content in-game via WebView2. I won’t need to display the WebView UI chrome but I am hoping to have the ability to render the browser to a texture and scroll/navigate it programmatically.

**Comment by RobertoBaruffa** [comment] 2022-06-28 08:08
Hi guys,
any update on this feature?

**Comment by champnic** [comment] 2022-06-28 18:02
Hey @RobertoBaruffa - Can you try using a newer runtime, version 103.0.1260.0+? We've been adding support for HWND_MESSAGE, and it should ship in stable soon.

**Comment by champnic** [comment] 2022-08-16 20:53
As mentioned above, the work has been done to allow having HWND_MESSAGE be the parent to WebView2 in runtime versions 103.0.1260.0+.

**Closed by champnic** 2022-08-16 20:53 UTC
Labels: feature request, tracked

**Comment by devttebayo** [comment] 2022-08-16 21:49
@champnic I tried a simplified version of my example above with CreateCoreWebView2ControllerAsync(HWND_MESSAGE) but still can't seem to get the await to return:

```cs
class Program
{

    private static readonly IntPtr HWND_MESSAGE = new IntPtr(-3);

    [STAThread]
    static void Main(string[] args)
    {
        Console.WriteLine("Starting WebView2 browser...");

        CreateWebView2();

        Console.ReadKey();
    }

    static async void CreateWebView2()
    {
        var environment = await CoreWebView2Environment.CreateAsync(null, null, null);

        var controller = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);

        // Never hits
        Debugger.Break();
    }
}
```

I'm using the following WebView2 packages in my project:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1340-prerelease" />
    <PackageReference Include="WebView2.Runtime.X64" Version="104.0.1293.54" />
</ItemGroup>
```

**Comment by champnic** [comment] 2022-08-16 22:21
@jennifer-jacobs or @yizhao5 - Any idea why the Controller is not finishing creation here?

**Comment by champnic** [comment] 2022-08-16 22:22
@devttebayo Can you confirm what version of the runtime your app is using? When you create the CoreWebView2Environment you need to specify the BrowserExecutableFolder to have it point to the WebView2.Runtime.x64 version, otherwise it will use the evergreen version installed on your machine. The author of that Nuget package has example usage here: https://www.nuget.org/packages/WebView2.Runtime.X64#readme-body-tab

**Comment by devttebayo** [comment] 2022-08-16 22:50
@champnic Happy to confirm - the only version of Edge installed on my PC is currently:

```
Version 104.0.1293.54 (Official build) (64-bit)
```

I also attempted an updated version that uses the instructions from the runtime readme (thanks for the pointer there!) and still find myself blocked:

```cs
static async void CreateWebView2()
{
    var runtimePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "WebView2");
    var environment = await CoreWebView2Environment.CreateAsync(runtimePath, null, null);

    var browserController = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);

    // Never hits
    Debugger.Break();
}
```

I checked task manager and verified that processes are indeed being created.

**Comment by champnic** [comment] 2022-08-17 20:22
@devttebayo It sounds like the browser processes are getting spun up correctly and not causing an error, so it may be that the async "await" is just failing to get the result back to continue. I wonder if it could be related to the issue (and potential workaround) mentioned here:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2318#issuecomment-1192527041

**Comment by devttebayo** [comment] 2022-08-17 20:36
That did the trick! The linked comment is exactly right - there was no UI thread in my application, causing the await to hang. The following updated function works:

```cs
static void CreateWebView2()
{
    var uiThread = new Thread(() =>
    {
        Dispatcher.CurrentDispatcher.Invoke(async () =>
        {
            var runtimePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "WebView2");
            var environment = await CoreWebView2Environment.CreateAsync(runtimePath, null, null);

            var browserController = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);

            Console.WriteLine("Success!");
        });

        Dispatcher.Run();
    });

    uiThread.SetApartmentState(ApartmentState.STA);
    uiThread.Start();
    uiThread.Join();
}
```

Thanks for all the help!

**Comment by devttebayo** [comment] 2022-08-17 20:50
@champnic One more thing (though this may be its own thread?): It appears CreateCoreWebView2CompositionControllerAsync() isn't happy when you try and construct it with HWND_MESSAGE:

```cs
try
{
    var compositionController =
        await environment.CreateCoreWebView2CompositionControllerAsync(HWND_MESSAGE);
}
catch (Exception ex)
{
    // COMException:
    // {"Invalid window handle. (0x80070578)"}
}
```

Not sure if this is expected behavior but I figured I'd flag it while the topic had eyeballs on it 😄

**Comment by champnic** [comment] 2022-08-17 21:05
@devttebayo Glad it's working!!

@bradp0721 Any idea if we would expect HWND_MESSAGE to work for the parent of the visual tree using CompositionController?

**Comment by georg-eckert-zeiss** [comment] 2022-09-02 09:23
We have seen many examples on how to do this with `environment.CreateCoreWebView2CompositionControllerAsync`. But how is it done with

`WebView2::EnsureCoreWebView2Async`?

Best regards.

**Comment by bradp0721** [comment] 2022-09-02 16:25
> @champnic One more thing (though this may be its own thread?): It appears CreateCoreWebView2CompositionControllerAsync() isn't happy when you try and construct it with HWND_MESSAGE:
> 
> ```cs
> try
> {
>     var compositionController =
>         await environment.CreateCoreWebView2CompositionControllerAsync(HWND_MESSAGE);
> }
> catch (Exception ex)
> {
>     // COMException:
>     // {"Invalid window handle. (0x80070578)"}
> }
> ```
> 
> Not sure if this is expected behavior but I figured I'd flag it while the topic had eyeballs on it 😄

This behavior is expected. If you want to create a WebView2 that never needs to display content, use CreateCoreWebView2Controller with HWND_MESSAGE. The reason to use CreateCoreWebView2CompositionController over CreateCoreWebView2Controller is that you want the WebView2 to render its content into a visual instead of an HWND. When using the CompositionController, even though the main html content is rendered to a visual, WebView2 still needs the parentWindow to correctly position popups (i.e. context menus, status bubbles, tool tips) and to correctly report screen coordinates to UIA (so accessibility tools can show the highlight rect in the correct location). Having CreateCoreWebView2CompositionController accept HWND_MESSAGE would have let apps render the WebView2 content using the visual, but would have caused issues with popups and accessibility. For that reason, we decided to not support HWND_MESSAGE on the CompositionController.

**Comment by yizhao5** [comment] 2022-11-08 09:45
@Marcelluszebra. Hello, you can use WPF (.net framework) with Webview2. If you want to create a webview2 and execute JavaScript/HTML, you can learn about [AddHostObjectToScript](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.1418.22).

Here are some examples:
https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/BridgeAddRemoteObject.cs
https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/assets/hostObject.html

**Comment by Marcelluszebra** [comment] 2022-11-08 09:52
Hi yizhao,

nope, as the topic, I want to load web content in a console application, or in a dll that work as a services, or in IIS dll. In general in a program that not have an UI.

marc.

**Comment by Manka-Muakido** [comment] 2022-11-28 15:05
i also need to use webview2 in projects that don't has UI, but no matter what CoreWebView2 never is initialized without UI showing up, any fix?

**Comment by Screaminlean** [comment] 2022-12-08 12:25
> That did the trick! The linked comment is exactly right - there was no UI thread in my application, causing the await to hang. The following updated function works:
> 
> ```cs
> static void CreateWebView2()
> {
>     var uiThread = new Thread(() =>
>     {
>         Dispatcher.CurrentDispatcher.Invoke(async () =>
>         {
>             var runtimePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "WebView2");
>             var environment = await CoreWebView2Environment.CreateAsync(runtimePath, null, null);
> 
>             var browserController = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);
> 
>             Console.WriteLine("Success!");
>         });
> 
>         Dispatcher.Run();
>     });
> 
>     uiThread.SetApartmentState(ApartmentState.STA);
>     uiThread.Start();
>     uiThread.Join();
> }
> ```
> 
> Thanks for all the help!

In a worker service (net7.0) as @devttebayo example, it works on my dev pc in debug perfectly but once published and the service installed it gets stuck at `await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);`

**Comment by lucaswhob** [comment] 2024-04-16 12:40
> That did the trick! The linked comment is exactly right - there was no UI thread in my application, causing the await to hang. The following updated function works:
> 
> ```cs
> static void CreateWebView2()
> {
>     var uiThread = new Thread(() =>
>     {
>         Dispatcher.CurrentDispatcher.Invoke(async () =>
>         {
>             var runtimePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "WebView2");
>             var environment = await CoreWebView2Environment.CreateAsync(runtimePath, null, null);
> 
>             var browserController = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);
> 
>             Console.WriteLine("Success!");
>         });
> 
>         Dispatcher.Run();
>     });
> 
>     uiThread.SetApartmentState(ApartmentState.STA);
>     uiThread.Start();
>     uiThread.Join();
> }
> ```
> 
> Thanks for all the help!

I Use This Code But Same Excpetion throw
