### ISSUE TITLE
WebView2 freezes after logging in to facebook.

### ISSUE THREAD

**Issue by NicatQaraxanov** [MicrosoftEdge/WebView2Feedback#3488] opened 2023-05-16 07:19 UTC
**Description**
When I try to log in to Facebook, WebView2 occasionally freezes. I can't determine the exact cause, but I've noticed a possible correlation with requests for notification permissions; when a website requests these permissions, it tends to freeze. Conversely, when the website does not request notification permissions, it operates normally. While I'm not entirely certain that this is the cause, it's a potential lead. Moreover, this issue only occurs when I'm logging into Facebook. Everything works normally on the login page.

**Version**
WebView2: 1.0.1774.30
Framework: WinForms.
OS: Win10.

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/109304730/c1a816d5-7410-4f48-8d50-c12e747dd93a)
Here you can see that this happens and after this WebView just stops working.

[AB#44688481](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44688481)

**Comment by novac42** [comment] 2023-05-16 09:50
Thanks for reporting the issue. I've assigned this to a dev who can help follow up on this.

**Comment by hazem-it** [comment] 2023-05-16 10:31
same error

**Comment by ElyssaJyu** [comment] 2023-05-17 06:19
Hi @NicatQaraxanov @hazem-it, I simply navigate to Facebook website in our WinForms sample app. I successfully logged in and receive notification on my test. Could you give more details about your scenario? so I can address the root cause. Thanks.

**Comment by NicatQaraxanov** [comment] 2023-05-17 07:06
An error occurs every time Facebook attempts to display a white overlay with a popup, which I suspect is caused by a certain JavaScript call. This popup and overlay don't appear every time you log in, only the very first time and if you have cleaned your cache and cookies. You might see this popup in Edge browser's private mode.

By popup i mean this
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/109304730/ddbb08dc-50f8-4fb6-95fc-8867e862a468)

And here additional video about what happens.
https://github.com/MicrosoftEdge/WebView2Feedback/assets/109304730/ce48d59c-c69d-4644-ad05-a23d6caf78f9

**Comment by hazem-it** [comment] 2023-05-17 12:16
> Hi @NicatQaraxanov @hazem-it, I simply navigate to Facebook website in our WinForms sample app. I successfully logged in and receive notification on my test. Could you give more details about your scenario? so I can address the root cause. Thanks.

You need to delete all files created by the browser before trying again
I will take a video of the problem and send it to you

**Comment by hazem-it** [comment] 2023-05-17 13:11
https://github.com/MicrosoftEdge/WebView2Feedback/assets/115902713/1db7da4b-4f4f-4b10-8257-4782a973a8de

**Comment by RK-BAKU** [comment] 2023-05-17 13:33
> > Hi @NicatQaraxanov @hazem-it, I simply navigate to Facebook website in our WinForms sample app. I successfully logged in and receive notification on my test. Could you give more details about your scenario? so I can address the root cause. Thanks.
> 
> You need to delete all files created by the browser before trying again I will take a video of the problem and send it to you

I've got the same error. Looks like a bug.

**Comment by ElyssaJyu** [comment] 2023-05-18 02:03
Thanks for provided details. I tracked as a bug internally and investigate it. I will async with you when there is a fix. Thanks.

**Comment by ElyssaJyu** [comment] 2023-05-26 05:09
Hi, I haven't been able to completely reproduce the issue based on your scenario, but I have encountered a similar freeze situation on my end. I would like to confirm a few details:

1. It appears that the freeze leads to WebView2 disposal. Could you confirm whether the WebView2 process is still initialized when the freeze occurs? 
2. Is there any exception thrown? Could you check the crash dumps? It can usually be found in the app's user data folder. <user-data-folder>\EBWebView\Crashpad\reports
3. Currently, notifications are disabled in WinForms. Have you triggered the  [PermissionRequested event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=webview2-dotnet-1.0.1774.30) to re-enable them?

Thanks for the incoming feedbacks.

**Comment by johnasebok** [comment] 2023-05-26 12:55
I have the same issue when trying using it in a WPF application.  First time logging into facebook it crashes the entire program.   After log in is cached, subsequent loading of the page cause only the control to stop working.  The webview2 does not appear to be disposed but does become invalid. I can still access it via code.  When trying to set a new source for it, it throws the following error.


System.InvalidOperationException: 'The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed'


The CoreWebView2.ProcessFailed event returns the following:

<HTML>
<head>
<title>Document</title></head>
<body>



  | Name | Value | Type
-- | -- | -- | --
◢ | e | {Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedEventArgs} | Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedEventArgs
  | ExitCode | -1073741819 | int
  | FrameInfosForFailedProcess | null | System.Collections.Generic.IReadOnlyList<Microsoft.Web.WebView2.Core.CoreWebView2FrameInfo>
  | ProcessDescription | "" | string
  | ProcessFailedKind | BrowserProcessExited | Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedKind
  | Reason | Unexpected | Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedReason



</body>
</HTML>

**Comment by NicatQaraxanov** [comment] 2023-05-30 07:15
Hi @ElyssaJyu,

Thank you for your detailed feedback and observations. I'll attempt to address your queries as concisely as possible:

1. For your first question, the runtime version being utilized in my project is 4.7.2 and the SDK version is 7.0.101.
2. As for the second question, it appears that the WebView2 instance is not getting disposed when the freeze occurs. The freeze seems to only affect the view while leaving the underlying processes intact. I can confirm this as I can still perform operations on the WebView2 object via code.
3. Yes, I have noticed exceptions being thrown, which are logged in the Crashpad/reports. Specifically, I am seeing an exception with Code: 0xc0000005. The information attached with this exception states, "The thread tried to read from or write to a virtual address for which it does not have the appropriate access." This seems to occur post the freezing of WebView2.
4. With respect to your fourth question, indeed, it appears that WebView2 occasionally freezes after a request for notification permission. When the request isn't made, I don't experience such freezes. However, I must clarify that I cannot assert with absolute certainty that the request for notification permission is the sole trigger for this freeze.
5. Finally, addressing your last question, I have indeed tried handling the PermissionRequested event by returning true/false for each permission request. Unfortunately, this approach did not yield any improvement to the situation.

I hope this information proves helpful in understanding the issue at hand better, and I look forward to any insights or solutions you might be able to suggest.

**Comment by ElyssaJyu** [comment] 2023-05-30 08:11
Hi @NicatQaraxanov,


1. > For your first question, the runtime version being utilized in my project is 4.7.2 and the SDK version is 7.0.101.

this seems your .net version and framework. I'd like to clarify your WebView2 runtime and SDK version. Your can find SDK version from NuGet package manager in your project and using [CoreWebView2Environment.GetAvailableBrowserVersionString(String) Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.774.44#exceptions) to find runtime version.

2. When a WV2 process fails, it fires a ProcessFailed event. You can define what actions to take when such a failure occurs, e.g., logging the error or attempting to recover from the failure.

3. To be confirmed, it seems, in your scenario, webview2 browser process doesn't crash, but freezes. WebView2 sometimes freezes when a request for notification permission is made. If you didn't request the notification permission, the freeze won't happen.

**Comment by NicatQaraxanov** [comment] 2023-05-30 08:20
@ElyssaJyu the SDK version is mentioned on my very first message in this issue (WebView2: 1.0.1774.30). It is latest.
Runtime: 113.0.1774.57

**Comment by NicatQaraxanov** [comment] 2023-05-30 08:28
@ElyssaJyu The ProcessFailed event has been triggered, providing the same information as @johnasebok mentioned. However, once the process has failed, how can I recover from it?

**Comment by ElyssaJyu** [comment] 2023-05-30 09:18
@NicatQaraxanov. I'm trying to find a workaround, will post it ASAP. Sorry for that inconvenience.

**Comment by NicatQaraxanov** [comment] 2023-05-30 10:24
@ElyssaJyu Thank you for your response. I appreciate your effort in finding a workaround and your commitment to resolving the issue. Take your time. I look forward to hearing from you as soon as possible.

**Comment by ElyssaJyu** [comment] 2023-05-30 10:33
Hi @NicatQaraxanov. I find a potential workaround. Please try to disable this Edge [Web App Widgets](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/widgets). Could you confirm whether it will work? I'm still working on finding the root cause. Thanks.
e.g. [CoreWebView2EnvironmentOptions.AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1774.30)= "--disable-features=msWebAppWidgets"

**Comment by NicatQaraxanov** [comment] 2023-05-30 10:38
@ElyssaJyu Thank you for providing the workaround! I appreciate your efforts in finding a solution. I have tried disabling the Web App Widgets as you suggested, and I'm happy to inform you that it has successfully resolved the problem.

**Comment by johnasebok** [comment] 2023-05-30 23:58
Thanks @ElyssaJyu that works for me.  The WPF control doesn't seem to have an option to set  CoreWebView2EnvironmentOptions.AdditionalBrowserArguments.  So just used:
 Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-features=msWebAppWidgets");

**Comment by NicatQaraxanov** [comment] 2023-06-02 06:05
Hi @ElyssaJyu! I have a quick question. Does disabling Web App Widgets affect WebView2 performance? I'm not entirely certain, but I believe I might experience some performance loss after disabling the Web App Widgets. For example, when visiting YouTube and so on.

**Comment by ElyssaJyu** [comment] 2023-06-02 06:43
Hi @NicatQaraxanov, I don't think disabling this feature should affect WebView2 performance, could you provide some details about performance loss you faced? Thanks

**Comment by NicatQaraxanov** [comment] 2023-06-02 12:19
@ElyssaJyu I cant say 100% if its happening because of Web App Widgets. I will ping you after i gain much more information about this problem. Thank you for your response :)

**Comment by ElyssaJyu** [comment] 2023-06-05 02:50
Hi, the issue has been fixed in webview2 runtime 114+, and new version has been released.

@NicatQaraxanov, I will close this issue since webview2 freeze has been fixed. If any further issue with webview2 performance, please either reopen this case or open a new one, and notify me, thank you.

**Comment by NicatQaraxanov** [comment] 2023-06-06 08:29
Hi @ElyssaJyu! When I disable Web App Widgets and try to enter YouTube, it freezes. Could you please check it?

**Comment by ElyssaJyu** [comment] 2023-06-06 08:45
@NicatQaraxanov Hi, have you upgraded the runtime to 114 version? In the latest version, you don't need to disable the Widgets feature to avoid webview2 freezing. Please let me know if WebView2 still freezes occasionally in the 114+ without disabling behavior. Thanks

Also, I have reached out the feature team, currently, the crash when manually disabling widgets is an understood behavior that should not be impacting any users who are not manually passing command line flags. The team will make some change on this feature in the near future.

**Comment by NicatQaraxanov** [comment] 2023-06-06 08:52
Do you mean installing the latest version on WebView2 from nuget package manager @ElyssaJyu? The latest is 1.0.1823.32

**Comment by ElyssaJyu** [comment] 2023-06-06 09:47
NuGet package is for WebView2 SDK. If you use [Evergreen distribution mode](https://developer.microsoft.com/en-us/microsoft-edge/webview2/), it's automatically up to date; if fixed version mode, please try to manually upgrade it. 
You can use `webView.CoreWebView2.BrowserVersionString` to check the version. Or check the webview2 process property in Task Manager.

**Comment by Ychyi1** [comment] 2024-01-08 16:22
I also encounter the same issue; when I try to open the Facebook website, it becomes unresponsive.

WebView2 Runtime Evergreen Bootstrapper
120.0.2210.121
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\120.0.2210.121\msedgewebview2.exe

**Comment by tekmun** [comment] 2024-01-09 02:07
Hi, I encounter a WebView2 freezing in my app when I open the Facebook website for authentication.

WebView2 Runtime version is 120.0.2210.121, taken from Settings -> Apps -> Installed Apps.

Now, I am no longer able to sign into Facebook from my app.

**Comment by ixiaokang** [comment] 2024-01-09 02:16
I also encounter the same issue; when I try to open the Facebook website, it becomes unresponsive.

WebView2 Runtime Evergreen Bootstrapper
120.0.2210.121
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\120.0.2210.121\msedgewebview2.exe

**Comment by HoangPhiHung0618** [comment] 2024-01-09 10:56
I am experiencing a similar issue

**Comment by didess27** [comment] 2024-01-09 15:01
Hi, I have the same issue. My app worked in December 2023, now it stopped showing the facebook site, other sites are working so far. I also tried to use the code from the WebView2Samples but the same problem there with facebook.
Our clients use the app so a workaround or a solution would be very helpful. Thank

**Comment by victorhuangwq** [comment] 2024-01-09 23:52
Hi @Ychyi1 @HoangPhiHung0618 @didess27 @ixiaokang @tekmun, the issue you are facing is actually a new / different bug, tracked in the following GitHub issue.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4281

The issue is fixed in Edge Canary 122.0.2330.0+. Could you please test with [Canary channel](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel) and validate the fix?

**Comment by victorhuangwq** [comment] 2024-01-09 23:52
In the meantime, I am closing this issue as it's tracked in #4281

**Closed by victorhuangwq** 2024-01-09 23:52 UTC
Labels: bug, tracked
