### ISSUE TITLE
UWP reports "file not found"

### ISSUE THREAD

**Issue by ramondeklein** [MicrosoftEdge/WebView2Feedback#2640] opened 2022-08-02 08:59 UTC
I have an UWP application to works fine on all our developer machines that have Visual Studio 2022 installed. Unfortunately, it doesn't work for machines that don't have VS installed. I try to obtain the installed WebView2 version using `CoreWebView2Environment.GetAvailableBrowserVersionString()`. This call succeeds on the VS-enabled machines, but fails with a "file not found" exception on other machines.

We did install the WebView2 runtime using this link: https://go.microsoft.com/fwlink/p/?LinkId=2124703. But even after rebooting the machine the error persists, even though WebView2 runtime v103.0.1264.77 is listed in the list of installed software.

The registry key lists both v1.3.165.21 in both registry locations (HKLM and HKCU), but that's the same as on my development box. The documentation about deploying this is extremely confusing, because it seems to have changed several times. Please help. It already took me several hours to sort this out, but no luck...

I am using the following versions:
* Microsoft.NETCore.UniversalWindowsPlatform: 6.2.13
* Microsoft.UI.Xaml: 2.8.0
* Microsoft.Web.WebView2: 1.0.1264.42

[AB#41075416](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41075416)

**Comment by ramondeklein** [comment] 2022-08-08 09:19
I am now debugging for a week and got nowhere. I have never been so frustrated about deploying an application. The Microsoft Store should make things easier, but WebView2 makes it a terrible experience. Can someone point me to an example that can be installed on a Windows 10/11 installation that has nothing else installed?

**Comment by ramondeklein** [comment] 2022-08-08 10:19
I ran [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to determine where it fails. I think I have found the root-cause:
1. It tries to open `HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}`, but this key doesn't exist (WebView2 runtime is installed by the end-user, so a local-user installation).
2. It tries to open `HKCU\Software\Microsoft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` and it reports `ACCESS DENIED` (read-only access).
3. It tries some other keys too, but these all do not exist.

When I open the key with the registry editor, then the key exists and the local user has *full access* permission to this key. For some reason the UWP application doesn't have access to this key.

I have been developing Windows desktop applications since 1994, but it never has been such a mess as currently. We have Win32, UWP, WinUI2, WinUI3, ... and it's almost impossible to know what to use. I cannot move to MAUI yet (no decent Bluetooth support and also cannot use Kestrel), so I'm stuck on Xamarin. What are my options and why does it work on machines with VS2022 installed?

**Comment by ramondeklein** [comment] 2022-08-08 11:08
It's not my software. Even the official example on https://github.com/MicrosoftEdge/WebView2Samples doesn't run on the non-VS2022 machines.

**Comment by ramondeklein** [comment] 2022-08-08 11:30
When I uninstalled WebView2 and re-installed it again (with elevated privileges) then it worked. It seems that WebView2 must be installed in per-machine mode instead of per-user mode to allow it to run in a UWP app.

**Comment by ramondeklein** [comment] 2022-08-08 12:04
It seems to be mentioned here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2030#issuecomment-1150272893.

**Comment by DavidShoe** [comment] 2022-08-25 20:50
We have a change in PR now that will resolve this issue.  It will allow UWP to work in both install types.

**Comment by LiangTheDev** [comment] 2022-08-25 21:08
It is a known issue that UWP app cannot access per user installed Edge WebView2 Runtime. The workaround is to install Edge WebView2 runtime as admin so that it will be installed for the machine. You can do this by right click on the downloaded MicrosoftEdgeWebview2Setup.exe and choose Run as administrator.

FWIW, 
- If the device has per machine installed Edge browser, the per user installed WebView2 Runtime will be migrated to per machine installation later, like after a day and UWP apps will then be able to work.
- The registry in question for per user install is supposed to be readable from UWP app, but we know that in some machine it is not accessible. Root cause unknown. Even if it is accessible, UWP app will later have problem accessing the installed files. So, the per user install would still not be usable by UWP app. There is a change coming in Edge version 105 where we will ensure that the installed files are accessible from UWP app so that per user installed WebView2 runtime can be used by UWP apps, if there is no registry key access issue. Anyway, the best way is to install WebView2 Runtime per machine.

**Comment by champnic** [comment] 2023-03-04 05:57
This should be fixed now - let me know if you run into something similar and for what versions. Thanks!

**Closed by champnic** 2023-03-04 05:57 UTC
Labels: bug, tracked
