### ISSUE TITLE
Web Share API does not work in WebView2

### ISSUE THREAD

**Issue by AshleyScirra** [MicrosoftEdge/WebView2Feedback#1038] opened 2021-03-05 11:29 UTC
**Description**
The Web Share API is supported in Edge/Chrome 89, but it does not work in WebView2.

**Version**
SDK: 1.0.705.50
Runtime: Stable 89.0.774.45
Framework: Win32
OS: Win10 x64 20H2

**Repro Steps**
I just took the getting started guide: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32
And set the navigation URL to this repro page: https://w3c.github.io/web-share/demos/share-files.html

Click the 'Share' button.

In the browser, it starts a share. In WebView2, nothing happens.

[AB#32078806](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32078806)

**Comment by champnic** [comment] 2021-03-11 01:13
Thanks for the report @AshleyScirra - I've added this to our backlog and we'll take a look.

**Comment by jasonstephen15** [comment] 2021-04-23 03:11
Hi @AshleyScirra thanks for submitting this issue. I've repro'd it as well, and confirmed the web-share works in the browser, but not webview2. Would you mind providing more detail on your app's scenario that might use this feature?

**Comment by AshleyScirra** [comment] 2021-04-23 10:38
If you use a Cordova-style app development approach, the entire app is web content, wrapped in a native app with a webview, possibly with a few minor bits of native communication added in. In this scenario, a high degree of web compatibility is necessary so that content in the webview works the same as in the browser. So in principle, WebView2 should support everything the browser does, in order to support this app development approach.

This is what we do with our game engine Construct (www.construct.net) - all games made in our software are published in this manner. Our games use a wide range of browser APIs that ought to be available inside webview to maintain web compatibility. Games want to share things, so we use the Web Share API.

**Comment by mlynch** [comment] 2021-08-31 13:49
Just to add to this, in #1696 it seems the Share API *is* supported, but doesn’t launch properly from a user event. If you trigger it manually from the console, for example, it does work.

And yes, approaches like Cordova or the modern Capacitor[Capacitor](https://capacitorjs.com) benefit from support for APIs like this.

**Comment by mrsteamfist** [comment] 2022-04-14 17:20
To clarify, I have validated that this was fixed in the latest OS build, not WebView 2 update. I am not sure which version of Windows you are on. If there is a specific version of the OS which is broken, please file a new issue.

**Closed by mrsteamfist** 2022-04-14 17:20 UTC
Labels: bug, tracked

**Comment by AshleyScirra** [comment] 2022-04-19 10:29
The problem still reproduces for me on Windows 10 21H2 (OS Build 19044.1645), which is AFAIK fully up-to-date and Windows Update is not showing any further updates available. @mrsteamfist - which version did you test? Are you sure this is working correctly? It's important for us and if the issue was closed prematurely it might not get any further attention.

**Comment by champnic** [comment] 2022-04-27 03:33
Hey @AshleyScirra - I believe "latest OS build" would refer to Windows 11. It's unlikely that the OS fix needed for this to work will be backported to Windows 10 and lower.

**Comment by AshleyScirra** [comment] 2022-04-27 10:10
So this will never be supported on Windows 10? 🙁 That will be quite a big omission for the many years that Windows 10 will still be in broad use.

**Comment by champnic** [comment] 2022-04-27 20:55
I'm following up with the Windows team to get the actual build number this will be available in. But yes, unfortunately for most OS related fixes they will be made in the next release of Windows and won't be backported.

**Comment by champnic** [comment] 2022-04-27 21:10
Looks like it's available in build 22581, which you can test out through the insiders program using Beta:
https://blogs.windows.com/windows-insider/2022/03/23/announcing-windows-11-insider-preview-build-22581/
