### ISSUE TITLE
Issues with WebView2 not being recognized after 109.0.1518.52 update from various applications.

### ISSUE THREAD

**Issue by brent20** [MicrosoftEdge/WebView2Feedback#3138] opened 2023-01-18 16:17 UTC
Is anyone else noticing pop-ups from apps that use the Microsoft Edge WebView2 Runtime about needing to install it or an error with it in the past few days? Looks like MSFT pushed build 109.0.1518.52 on 1/16/2023 and we're now seeing pop-ups in at least 2 of our applications- Webex and Citrix Workspace. See here:

https://freeimage.host/i/HaPYAHF 

https://freeimage.host/i/HaP1Z9S

WebView2 still shows as installed, but the apps aren't seeing it, tried all of the usual steps, restarting, re-installing, re-installing the applications, etc. nothing. Seems like a bug in this build? We were looking at some of the past releases and it seems like MSFT has released three updates in 3 days on this too... 

109.0.1518.52 - released on 1/16/2023 at 6:01am
109.0.1518.55 - released on 1/15/2023 at 7:18am
109.0.1518.49 - released on 1/13/2023 at 4:16am

Is this a new bug? We're starting to have many users reach out to our Service Desk about this... Please advise..

**Comment by champnic** [comment] 2023-01-18 17:46
Thanks for catching this @cremor. I've transferred this issue to the WebView2Feedback repo.

**Comment by bhe-gtk** [comment] 2023-01-18 18:03
We are facing the same issue!
Please have q lock at this.

**Comment by ShaunLoganOracle** [comment] 2023-01-18 21:07
Duplicate of #3136 (which has more traffic now). Please close this one, @champnic

**Comment by brent20** [comment] 2023-01-18 21:08
@cremor @champnic @ShaunLoganOracle - thank you, it's been tricky to navigate these repos for reporting. This is causing a lot of headaches across our user base and we're hoping for some guidance or acknowledgment of a bug. Thank you.

**Comment by champnic** [comment] 2023-01-18 22:10
> Duplicate of #3136 (which has more traffic now). Please close this one, @champnic

Done. Please see #3136.

**Closed by champnic** 2023-01-18 22:10 UTC
