### ISSUE TITLE
WebView2 runtime creates a black screen or black band when closing a PWA when a notification is given in response for closing the app.

### ISSUE THREAD

**Issue by PCRacer** [MicrosoftEdge/WebView2Feedback#4349] opened 2024-02-06 12:16 UTC
### What happened?

WebView2 displays black background after Notification popup when closing a PWA app that gives a response notification when closing the app.

On a secondary monitor the whole screen goes black with the notification not centered!

[WebView2 Display render In Main Screen Not Working.webm](https://github.com/MicrosoftEdge/WebView2Feedback/assets/96520393/ac74503a-2a6f-48b9-9c62-100c49eda8c9)

When reproducing the error on my main monitor, the WebView2 display moves down the height of the notification and the stays there without moving when navigating to another website.

[WebView2 Display Render Not Working.webm](https://github.com/MicrosoftEdge/WebView2Feedback/assets/96520393/77cde2e2-4d87-4b86-bf7c-9e32070faef1)

**This error cannot be reproduced in Edge or Chrome, so it is the WebView2 runtime itself that is to blame.**

_**When opening a new tab, WebView2 is working correctly again.**_

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.106

### SDK Version

1.0.2277.86

### Framework

Win32

### Operating System

Windows 10

### OS Version

19045.3996

### Repro steps

1. Start the browser application.
2. Navigate to https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
3. Enter any value into the form in the middle of the page
4. Press the Reload button
5. The WebView2 windows moves down and to the right inside of the bounds of the parent window (empty borders are created on the top and on the left side)
6. If you cancel the following dialog and press Reload again the WebView2 window even moves further downwards each time (also the following dialog)

Watch the two videos to reproduce the error... One is the main monitor and the other is from a second monitor which gives two different errors.

One video shows when using the app on a second monitor and one error is shown on the main monitor, which gives two different display errors!

Navigate to any website that has a notification response when closing... e.g. [https://desktop.ssuiteoffice.com](https://desktop.ssuiteoffice.com)

An app or any must be opened to activate the notification when closing or navigating to Home page.

[WebView2 Display Render Not Working.webm](https://github.com/MicrosoftEdge/WebView2Feedback/assets/96520393/d08b405d-289c-44ad-938d-74ec87e7a9bb)

 This error is given when used on the main monitor...

[WebView2 Display render In Main Screen Not Working.webm](https://github.com/MicrosoftEdge/WebView2Feedback/assets/96520393/37108190-126d-4aef-b967-ddd49838d135)

This error cannot be reproduced in Edge or Chrome, so it is the WebView2 runtime itself that is to blame.

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

SDK 1.0.2210.55  Runtime 121.0.2210.55

**Comment by PCRacer** [comment] 2024-02-06 12:43
Please download the [application](https://www.ssuiteoffice.com/downloads/apps/SetupSSuiteNetSurfer64X.exe) for testing purposes...

Download Link in text:
   https://www.ssuiteoffice.com/downloads/apps/SetupSSuiteNetSurfer64X.exe

**Comment by champnic** [comment] 2024-02-06 19:12
Thanks for the bug report @PCRacer! We are able to reproduce this issue locally, and are currently tracking it in #4350, so closing this one as a dupe (apologies they are technically out of order).

**Closed by champnic** 2024-02-06 19:12 UTC
Labels: bug, regression
