### ISSUE TITLE
Application with fixed WebView2 deployed with MSIX cannot be started as admin user

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3082] opened 2022-12-20 15:03 UTC
**Description**
The app fails to start when running with the built-in `Administrator` user or when using `Run as administrator` with standard user.

**Version**
SDK: 1.0.1369-prerelease
Runtime: Any fixed WebView2 version package, eg. latest 108.0.1462.46
Framework: WPF
OS: Win11 22H2 (OS Build 22621.521)

**Repro Steps**
1. Use a fixed WebView2 version to integrate with a sample app
2. Create a MSIX installer for the app
3. Install and start the app either with
   - the built-in `Administrator` user
   - OR a standard user but start it using `Run as administrator`

**Expected**: The app is running properly with WebView2 de-elevated
**Actual**: The app fails to start with the below error (check screenshots)

The app starts fine
- when running with standard user without elevation
- if evergreen WebView2 is used, in this case running with elevation works as well

**Screenshots**
Error when starting the app as admin
![error](https://user-images.githubusercontent.com/8770144/208695904-3e6b5c35-072d-42cf-98c7-c959d71fab97.png)

Errors in Process Monitor when monitoring the installed folder of the installed MSIX package
![error2](https://user-images.githubusercontent.com/8770144/208695911-7eb3f8a6-668a-40c7-a503-d04ab7abc181.png)

**Additional context**

Code used for testing where `WebViewContainer` is a `Grid`:
```cs
      var options = new CoreWebView2EnvironmentOptions();
      var webView2Location = Path.Combine(Path.GetDirectoryName(typeof(MainWindow).Assembly.Location), "WebView2");
      var environment = await CoreWebView2Environment.CreateAsync(browserExecutableFolder: webView2Location);
      WebView2 webView2 = new WebView2();
      webView2.HorizontalAlignment = HorizontalAlignment.Stretch;
      webView2.VerticalAlignment = VerticalAlignment.Stretch;
      WebViewContainer.Children.Add(webView2);

      await webView2.EnsureCoreWebView2Async(environment);
      webView2.Source = new Uri("https://developer.microsoft.com/en-us/microsoft-edge/webview2/");
```

**Comment by johnnylq** [comment] 2022-12-21 05:57
We happened experienced the same issue before.   
instead of using "windowsapp\pfn folder\webview2" as the wv2 folder,   we copy the wv2 runtime to another folder under Environment.SpecialFolder.CommonApplicationData for the admin scenarios which solved the problem.

**Comment by victorthoang** [comment] 2022-12-27 08:32
Hello @johnnylq,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this. With holidays over and new year's approaching, I appreciate your patience!

**Comment by novac42** [comment] 2022-12-29 04:39
@q71114 Thanks for the comprehensive report and thanks @johnnylq for providing a solution. Meanwhile our team are looking into this to check if there's an underlying bug.

**Comment by Shangminx** [comment] 2023-01-06 14:02
Hi @q71114, I have reproduced this issue. This permission error occurred in my env too. 

This error is because administrators doesn't have the Read & execute permission of the runtime exe(**msedgewebview2.exe**).
If you want to run this exe as administrators, you can grant this permission to administrators.
https://www.makeuseof.com/windows-access-windowsapps-folder/
![image](https://user-images.githubusercontent.com/119831188/211023699-d2b80b1c-2d64-4049-a384-c3035f26e66d.png)
**And don't forget to grant permission for the parent folder (Windowsapps).**

Actually, there are no admin mode for store apps. https://social.technet.microsoft.com/Forums/en-US/a525d01f-1755-481d-98ab-2cd33127a142/how-do-i-run-the-win-10-app-store-in-admin-mode?forum=win10itprosetup
So this is a general issue of the Windowsapps folder.

tips:
1. The evergreen webview2 runtime is not in this folder. So it won't meet this permission issue. thanks @johnnylq for providing a solution.
2. standard user can use another role to execute msedgewebview2.exe. You can find a role for user that has a condition like (Win://SYSAPPID Contains xxxID). In my opinion, it use this role to execute the runtime exe.

**Comment by q71114** [comment] 2023-01-06 15:46
Thanks @Shangminx for the explanation. 

How does the host application start if the administrators doesn't have the Read & execute permission?

**Comment by Shangminx** [comment] 2023-01-09 16:59
Hi @q71114 

It depends on the way you execute this exe.  If you use an administrator cmd to run, or menu bar run it as an app, you will see a blank window without any runtime exe.   If you select the .exe and run it as administrator, you won't see even the blank window.

There are complex secure mechanisms of windows. I think it is not related to webview2. It's a general issue of windows so you can discover in other app(e.g Microsoft.ZuneMusic) Maybe difference ways use different token or role to execute exe. It's complex. You can delete some roles for app folder to check which one it uses.

**Comment by novac42** [comment] 2023-02-14 10:13
Hi @q71114  We will close this issue for now, if you have more question please let us know :)

**Closed by novac42** 2023-02-14 10:13 UTC
Labels: question
