### ISSUE TITLE
I cannot change the size of WebView2

### ISSUE THREAD

**Issue by q7164518** [MicrosoftEdge/WebView2Feedback#2411] opened 2022-04-29 07:27 UTC
**Description**
我无法通过代码动态改变WebView的大小. 列如我在调整窗口大小的时候, WebView的大小无法改变
WebView.Size = new Size(width, height);

**Version**
SDK: 1.0.1185.39
Runtime: 100.0.1185.44 (正式版本)
Framework: WinForms
OS: Win 11

**Comment by champnic** [comment] 2022-05-04 17:31
Hey @q7164518 - thanks for the bug report! I just gave this a try in my Winforms control and it worked fine. Do you have a sample app you can share that demonstrates your issue?

**Comment by q7164518** [comment] 2022-05-05 02:58
> Hey @q7164518 - thanks for the bug report! I just gave this a try in my Winforms control and it worked fine. Do you have a sample app you can share that demonstrates your issue?

 this.webView21.Dock = System.Windows.Forms.DockStyle.Fill;

![image](https://user-images.githubusercontent.com/22828478/166857574-a7648005-53bf-4c00-9e49-a469ae2e2f5d.png)
![image](https://user-images.githubusercontent.com/22828478/166857591-479c4356-23e5-42d4-b90a-3b0a2a40c336.png)
I changed the form size, but the webView2 size did not change
@champnic  tkanks

**Comment by champnic** [comment] 2022-05-05 18:54
I'm not sure why, but I'm still unable to reproduce this issue. When I set to DockStyle.Fill in my Winforms app and try resizing the form, the WebView2 is automatically resized to fill.

Is your WebView2 added directly to the Form.Controls? Or do you have another layout/collection class it's being added to? WebView2 relies on it's Size property getting changed to properly tell the web content what size to be.

**Comment by q7164518** [comment] 2022-05-06 02:57
> I'm not sure why, but I'm still unable to reproduce this issue. When I set to DockStyle.Fill in my Winforms app and try resizing the form, the WebView2 is automatically resized to fill.
> 
> Is your WebView2 added directly to the Form.Controls? Or do you have another layout/collection class it's being added to? WebView2 relies on it's Size property getting changed to properly tell the web content what size to be.

I added it directly to Form.Controls
What version of SDK are you using, My SDK version is 1.0.1185.39
![image](https://user-images.githubusercontent.com/22828478/167059523-4e305da4-17c3-4b5d-b179-672d65478d3f.png)

@champnic thanks

**Comment by champnic** [comment] 2022-05-06 17:27
Same, SDK 1.0.1185.39. 
```cs
            // 
            // webView22
            // 
            this.webView22.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.webView22.CreationProperties = null;
            this.webView22.DefaultBackgroundColor = System.Drawing.Color.White;
            this.webView22.Location = new System.Drawing.Point(12, 52);
            this.webView22.Name = "webView22";
            this.webView22.Size = new System.Drawing.Size(1024, 768);
            this.webView22.Dock = DockStyle.Fill;
            this.webView22.TabIndex = 1;
            this.webView22.ZoomFactor = 1D;

...

            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.ClientSize = new System.Drawing.Size(1078, 860);
            this.Controls.Add(this.webView22);
            this.Name = "Form1";
            this.Text = "Form1";
```

Can you send me a sample app which reproduces the issue on your machine?

**Comment by q7164518** [comment] 2022-05-07 03:13
> Same, SDK 1.0.1185.39.
> 
> ```cs
>             // 
>             // webView22
>             // 
>             this.webView22.BackColor = System.Drawing.SystemColors.ActiveCaption;
>             this.webView22.CreationProperties = null;
>             this.webView22.DefaultBackgroundColor = System.Drawing.Color.White;
>             this.webView22.Location = new System.Drawing.Point(12, 52);
>             this.webView22.Name = "webView22";
>             this.webView22.Size = new System.Drawing.Size(1024, 768);
>             this.webView22.Dock = DockStyle.Fill;
>             this.webView22.TabIndex = 1;
>             this.webView22.ZoomFactor = 1D;
> 
> ...
> 
>             // 
>             // Form1
>             // 
>             this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
>             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
>             this.BackColor = System.Drawing.Color.Black;
>             this.ClientSize = new System.Drawing.Size(1078, 860);
>             this.Controls.Add(this.webView22);
>             this.Name = "Form1";
>             this.Text = "Form1";
> ```
> 
> Can you send me a sample app which reproduces the issue on your machine?
[WinFormsApp2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8644344/WinFormsApp2.zip)

@champnic thanks

**Comment by champnic** [comment] 2022-05-09 18:06
Unfortunately even with this sample app I'm able to resize the window and see the WebView2 resize as well. 
OS: Windows 11 21H2

Are you on a VM, or anything else particular about your setup?

**Comment by champnic** [comment] 2022-05-10 17:16
Still no luck. I've tried multiple monitors, switching between the monitors, and also changing the DPI and resolution of the monitors. Resizing with your sample app works as expected.

I'm going to close this bug for now because we can't repro it, but if you can think of anything else you'd like me to try please let me know and I'll try to repro it again!

**Closed by champnic** 2022-05-10 17:16 UTC
Labels: bug
