### ISSUE TITLE
Hangs up as soon as a host function with a return value is called

### ISSUE THREAD

**Issue by clhln** [MicrosoftEdge/WebView2Feedback#1322] opened 2021-05-26 02:36 UTC
Description
we have a ocx class as host object ,it can call all function without return value, but hangs up as soon as a function with a return value is called.(eg OCX.subBridge.Value() in mini case)

Version
SDK: 1.0.824-prerelease
Runtime: WebView2 runtime 90.0.818.42
Framework: WinForms, Win32
OS: Win10, Win7

Repro Steps
1.build MFCActiveXEdgeTest then regedit it
2.build EdgeTestFormsApp
3.run EdgeTestFormsApp.exe (auto load testEdge.html)
then click "GetValue" button, you can see OCX.subBridge.ClearData() just be executed once.

you can reproduce it by attach.
[EdgeTestFormsApp.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6543495/EdgeTestFormsApp.zip)

[AB#33613516](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33613516)

**Comment by champnic** [comment] 2021-06-03 23:10
Thanks for the bug report @clhln - I've added it to our backlog.

**Comment by champnic** [comment] 2021-11-25 01:36
Closing as dupe of #1210

**Closed by champnic** 2021-11-25 01:36 UTC
Labels: bug, tracked
