### ISSUE TITLE
COMException when calling method on host object

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#2840] opened 2022-09-30 15:53 UTC
**Description**
There is an exception thrown when calling a method on a host object:
```Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.Web.WebView2.Core.dll```
It is thrown from: 
```Microsoft.Web.WebView2.Core.dll!Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.GetMethodInfo(System.Type type, string methodName, int? parameterCount)```

The exception is handled, the running app can continue.

**Version**
SDK: 1.0.1343.22
Runtime: Canary 105.0.1343.27
Framework: WPF
OS: Win10

**Repro Steps**
Create a host object in .NET C#:
```c#
    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.AutoDual)]
    public class TestHandler
    {
        public void DoSomething()
        {
            Debug.WriteLine("something");
        }
    }
```

Add this host object to WebView2:
```c#
            await webView.EnsureCoreWebView2Async();
            webView.CoreWebView2.AddHostObjectToScript("test", new TestHandler());
```

Call the `DoSomething` method from JavaScript:
```html
<script type="text/javascript">
	function doSomething() {
	  window.chrome.webview.hostObjects.sync.test.doSomething();
	}
</script>
</head>
<body>
<button onclick="doSomething()">do something</button>
```

I also noticed that if I also add an empty `doSomething()` method to the C# host object the exception is gone.

[AB#41814829](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41814829)

**Comment by victorthoang** [comment] 2022-10-03 07:06
Hello @ztanczos,

I have assigned this to @imicy, who will help figure out how to approach the bug you're seeing. Thanks for your find!

**Comment by plantree** [comment] 2022-10-14 03:20
Hi @ztanczos,

I don't get your point. Did you mean that calling a method in js which is not defined in C# will cause exception?

**Comment by ztanczos** [comment] 2022-10-14 04:05
Hi @plantree,
No, the method _is_ defined, but there is still an exception which is handled internally by WebView2, so there is no crash, just performance penalty.

However if I define another method with camelCasing then there is no exception and the originally defined PascalCased method is called. This is why I think this is a bug in WebView2.

**Comment by plantree** [comment] 2022-10-14 06:02
> **Description** There is an exception thrown when calling a method on a host object: `Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.Web.WebView2.Core.dll` It is thrown from: `Microsoft.Web.WebView2.Core.dll!Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.GetMethodInfo(System.Type type, string methodName, int? parameterCount)`
> 
> The exception is handled, the running app can continue.
> 
> **Version** SDK: 1.0.1343.22 Runtime: Canary 105.0.1343.27 Framework: WPF OS: Win10
> 
> **Repro Steps** Create a host object in .NET C#:
> 
> ```cs
>     [ComVisible(true)]
>     [ClassInterface(ClassInterfaceType.AutoDual)]
>     public class TestHandler
>     {
>         public void DoSomething()
>         {
>             Debug.WriteLine("something");
>         }
>     }
> ```
> 
> Add this host object to WebView2:
> 
> ```cs
>             await webView.EnsureCoreWebView2Async();
>             webView.CoreWebView2.AddHostObjectToScript("test", new TestHandler());
> ```
> 
> Call the `DoSomething` method from JavaScript:
> 
> ```
> <script type="text/javascript">
> 	function doSomething() {
> 	  window.chrome.webview.hostObjects.sync.test.doSomething();
> 	}
> </script>
> </head>
> <body>
> <button onclick="doSomething()">do something</button>
> ```
> 
> I also noticed that if I also add an empty `doSomething()` method to the C# host object the exception is gone.

I saw you define `DoSomething()` in C# and call `doSomething()` in JS, will there be any problem?

**Comment by ztanczos** [comment] 2022-10-14 06:10
As I said in the original description: if I add two C# methods with both casing: doSomething and DoSomething then there is no exception HOWEVER DoSomething is called even though I called doSomething() from Javascript.

**Comment by plantree** [comment] 2022-10-17 07:30
Hi @ztanczos,

Thanks for your feedback. It seems that it is a implementation issue and I have already added it to our internal backlog. The current workaround might be **matching the definition and usage of the methods**.

The reason could be found in this [IDispatch::GetIDsOfNames method (oaidl.h)](https://learn.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-getidsofnames):
> The implementation of GetIDsOfNames is case insensitive.

I'll sync with you as soon as the problem is fixed.

**Comment by LiangTheDev** [comment] 2022-10-19 17:28
The current behavior is expected. The host object is based on IDispatch. As GetIDsOfNames is case insensitive, the behavior of which method will be invoked depends on how .NET handles GetIDsOfNames, which might not be deterministic.

Some explanation about the internal exception.
.NET core doesn't have type info built in and its return value for using a method as property does not help us, we have to build our own helper to figure out whether a "property" on project host object in JS is a method or property. When this works (naming matches), things are actually faster. When this helper doesn't work, we fallback to get type info and return error code, which works well with .NET framework.

**Closed** 2022-11-22 00:07 UTC
Labels: bug, tracked
