### ISSUE TITLE
[Problem/Bug]: WebView2CompositionControl Not Displayed Correctly with Multiple TabItems

### ISSUE THREAD

**Issue by cmiles** [MicrosoftEdge/WebView2Feedback#4941] opened 2024-11-20 17:19 UTC
### What happened?

The WebView2CompositionControl works as expected when in the first TabItem of a WPF TabControl but in other tabs it does not display anything.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

130.0.2849.80

### SDK Version

2950.0

### Framework

WPF

### Operating System

Windows 11

### OS Version

10.0.22631 Build 22631

### Repro steps

I have attached a small solution that shows that problem - the WebView2CompositionControl in the first tab works without issue - the WebView2CompositionControls in the 2nd and 3rd tab fail to display anything. Here are some things I noticed:
 - Events/Code for the WebView2CompositionControls in the 2nd and 3rd tab continue to work - in a more complicated application all events seemed to fire, but nothing was displayed
 - There is no exception thrown
 - In this application if you swap all of the WebView2CompositionControls for WebView2 controls the app works as expected

I've been following #286 but haven't noticed any problems/work arounds/limitations mentioned that indicate in WPF this scenario should work with WebView2 but not WebView2CompositionControl.

[WebView2CompositionControlInTabs.zip](https://github.com/user-attachments/files/17834445/WebView2CompositionControlInTabs.zip)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#55205081](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/55205081)

**Comment by champnic** [comment] 2024-11-22 23:46
@cmiles Thanks for opening this bug and for the repro app. I'm able to repro the issue on my end and will begin investigating.

**Comment by champnic** [comment] 2024-11-25 23:54
@cmiles Found the root cause and I've got a fix getting checked in shortly.

**Comment by cmiles** [comment] 2024-11-28 16:47
Thanks @champnic - before finding this bug swapping WebView2 for the WebView2CompositionControl was going smoothly and I'm looking forward to your fix getting into preview!

**Comment by champnic** [comment] 2024-12-02 21:14
@cmiles Glad to hear it! The fix is in and will be available in the next prerelease SDK. If you would like to, you can use this package to verify the fixed behavior (rename ".zip" to ".nupkg"):
[Microsoft.Web.WebView2.1.0.2980.zip](https://github.com/user-attachments/files/17984064/Microsoft.Web.WebView2.1.0.2980.zip)

**Closed** 2024-12-02 21:14 UTC
Labels: bug, tracked

**Comment by cmiles** [comment] 2024-12-04 14:43
@champnic I used the package you attached to update the code in https://github.com/cmiles/PointlessWaymarksProject and can confirm this issue is fixed - Thank You. My project makes reasonably simple use of the WebView2 but fwiw I was able to convert all my usages of WebView2 to WebView2CompositionControl so far without any issues!

**Comment by champnic** [comment] 2024-12-04 21:02
@cmiles That's really great news, and thanks for confirming the fix! Please do reach out if you end up finding any more issues with the new control :)
