### ISSUE TITLE
Invalid window handle. (Exception from HRESULT: 0x80070578)

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3097] opened 2023-01-03 10:22 UTC
Some win7 users have this error, unable to complete the initialization, error message: Invalid window handle. (Exception from HRESULT: 0x80070578)
![QQ截图20230103180904](https://user-images.githubusercontent.com/11196986/210339100-3a2fa30e-4037-4fe0-835e-9d33b953572b.png)

I used Windbg.exe to collect error information.
[Windbg.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/10335780/1.txt)

**Version**
SDK: 1.0.1462.37
Runtime: 108.0.1462.54
Framework: .NET 4.5.2
OS: Win7

[AB#42868992](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42868992)

**Comment by novac42** [comment] 2023-01-04 09:59
Thanks for the report. We will take a look into it.

**Comment by ElyssaJyu** [comment] 2023-01-04 11:17
Hi @sln162, 

> Framework: .NET 4.5.2
Do you mean .net framework 4.5.2? 
Could you try our [WinForms sample code](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/GettingStartedGuides/WinForms_GettingStarted) to see the webview2 runtime can be launched? [Get started with WebView2 in WinForms apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)

Also could we get some call track and share code where you are setting up the WebView2?

**Comment by sln162** [comment] 2023-01-04 11:41
@ElyssaJyu   I think the official example is the same, this is the code of the test program I used at the time, few lines of code.
![QQ截图20230104193842](https://user-images.githubusercontent.com/11196986/210547561-94b57384-0691-4f17-ac66-d44f1a127e35.png)

**Comment by ElyssaJyu** [comment] 2023-01-05 08:28
Hi @sln162, 
from txt file, it seems Microsoft.Web.WebView2.Core.dll isn't loaded. The project is not built successfully.
A value of type 'void' may not be assigned for `button1_Click` . Could you try this code?
![image](https://user-images.githubusercontent.com/111425758/210734641-f29427bb-2b72-40ed-ad68-333469b4525e.png)


It works for me.
![image](https://user-images.githubusercontent.com/111425758/210733406-de195633-1b4f-48ec-9d95-8749785f1878.png)

**Comment by sln162** [comment] 2023-01-05 11:31
@ElyssaJyu  This is all the source code, and the Debug directory also has the generated program. I don't think this error has anything to do with the code.
It seems that restarting the computer can solve the 0x80070578 problem, we are still tracking
[WebView2Feedback.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10351717/WebView2Feedback.zip)

**Comment by ElyssaJyu** [comment] 2023-01-06 02:29
Hi @sln162, I has cloned your project, and it works as expected. Could you give me some details and your workarounds that I can repro the 0x80070578 problem? Thanks

**Comment by ElyssaJyu** [comment] 2023-01-06 03:24
Also, does it only happen on Win7, or other Win versions else?

**Comment by sln162** [comment] 2023-01-06 04:49
@ElyssaJyu   Yes, it only happens on Win7. It can be initialized normally on normal Win7 machines. Only a few machines will appear 0x80070578, and the proportion is not high. It may be that our user base is large, so various strange things will appear.
When encountering this error, our software will give a prompt to restart the computer. At present, no new feedback of this error has been received.

**Comment by ElyssaJyu** [comment] 2023-01-06 05:26
@sln162 

- Microsoft Edge 110 and WebView2 110 will end support for Windows 7 and Windows 8/8.1, [microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1](https://blogs.windows.com/msedgedev/2022/12/09/microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1/), so your software might consider a fixed version(https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) for win7 users.
- The WebView adds a child window to the provided window during WebView creation. HWND_MESSAGE is a valid parameter for ParentWindow for an invisible WebView for Windows 8 and above.  In this case the window will never become visible. You are not able to reparent the window after you have created the WebView. This is not supported in Windows 7 or below. Passing this parameter in Windows 7 or below will return **ERROR_INVALID_WINDOW_HANDLE** in the controller callback. [createcorewebview2controllerasync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createcorewebview2controllerasync?view=webview2-dotnet-1.0.1462.37#microsoft-web-webview2-core-corewebview2environment-createcorewebview2controllerasync(system-intptr))

> Only a few machines will appear 0x80070578, and the proportion is not high.
Since it happens by chance, could you confirm what workaround this error will happen when you repro?

**Comment by sln162** [comment] 2023-01-06 08:32
@ElyssaJyu   I didn't use HWND_MESSAGE, and I didn't set the parent window, just as there is no such related thing in the source code of the test program, but on the machine with the problem, the test program also reported this error, maybe it is the reason of some software in the system? Since win7 does not support this method, can you directly add a rule inside WebVie2, when the user is a win7 machine, even if HWND_MESSAGE is set, this parameter will be deleted actively to prevent this kind of error.

This error was encountered by several IP users on January 2, 3, and 4, but it did not reappear in these two days. 108.0.1462.76 was released on January 5. Has this problem been fixed?
Due to the lack of new reports, it's unclear whether restarting the computer will fix it, so I can't give you a definitive answer.

**Comment by ElyssaJyu** [comment] 2023-01-06 09:16
@sln162
> Since win7 does not support this method, can you directly add a rule inside WebVie2, when the user is a win7 machine, even if HWND_MESSAGE is set, this parameter will be deleted actively to prevent this kind of error.

Thanks for your suggestion. We will discuss it internally with the team. 

 I don't think this issue has been resolved in 108.0.1462.76. I'm trying to repro this issue on Win7 now, but unfortunately, not repro yet. Still need investigate further.

I add this issue in our backlogs, so we will continue to track internally. Will update when it has been fixed. Please also let us know if there is any new report for this issue. Thanks.

**Comment by ElyssaJyu** [comment] 2023-01-06 09:27
> on the machine with the problem, the test program also reported this error, maybe it is the reason of some software in the system? 

When testing the test system, does the issue only also happen on these "problem" machine? Or it also happens on normal machine. I doubt the issue happens with machine-base (not confirm, just guess).

**Comment by sln162** [comment] 2023-01-07 12:23
@ElyssaJyu  
` [webview2]12-29-21|无效的窗口句柄。 (异常来自 HRESULT:0x80070578)|108.0.1462.54|10.0.19044.0`
This error was also found in Win10 19044. There was also a Win10 19044 on January 4th. The IP addresses of these two are not in the same area. They should be two machines.
This seems to break the original cognition that "only Win7 has this error". But the customer doesn't take the initiative to contact me, I can't contact him, and I can't collect more logs

**Comment by sln162** [comment] 2023-01-07 14:32
`[webview2]12-29-21|无效的窗口句柄。 (异常来自 HRESULT:0x80070578)|106.0.1370.47|10.0.19045.0`
Newly discovered Win10 19045

**Comment by ElyssaJyu** [comment] 2023-01-09 02:30
@sln162 Does those machines continually occur this error? Or after restarting the computer, it hasn't occurred again until now. Cuz this issue seems happens randomly and unexpectedly. There is not enough information to locate the issue.  It might take a while to repro this issue and analyze it.

**Comment by sln162** [comment] 2023-01-10 04:44
@ElyssaJyu  The user found me, and I sent it to the test program and operated it remotely. It was true that the initialization could not be completed, but the user did not find me in the subsequent error report, so I am not sure whether it happened randomly.

**Comment by ElyssaJyu** [comment] 2023-01-10 06:00
@sln162 Thanks for reaching out. 

>  The first user found me, and I sent it to the test program and operated it remotely. It was true that the initialization could not be completed,

Does the initialization fail to create every time? Does it work after restarting the test program?  Or you have to restart the computer (restarting the computer then it will work normally. It's kind of odd)

**Comment by sln162** [comment] 2023-01-10 06:04
> Does the initialization fail to create every time?
Yes.
> Does it work after restarting the test program?
No.
> Or you have to restart the computer
This is just my guess, because I checked the server log and found that his IP was initialized normally the next day, but the IP cannot be used as the only basis for the machine.

**Comment by ElyssaJyu** [comment] 2023-01-11 10:13
@sln162 Could you try to catch this exception to avoid crashing the app process? Please let me whether it works.

**Comment by sln162** [comment] 2023-01-11 15:22
@ElyssaJyu   > Could you try to catch this exception to avoid crashing the app process?

I don't understand what you mean. The exception of initialization failure has been screenshotted. Windbg.exe is used to capture the exception. ETW does not support Win7.
Our users are not the only ones who choose our software. If it is unavailable, they may have already used other software and will not use us anymore.

**Comment by ElyssaJyu** [comment] 2023-01-12 02:39
Sorry for that. We are working on it and will bump the priority. Will update soon.

**Comment by ElyssaJyu** [comment] 2023-01-30 02:30
@sln162 Is there any update from your customer? Does this error still exist?

**Comment by ElyssaJyu** [comment] 2023-01-31 02:29
@sln162 Thanks for the following update. Could you contact your customers to get trace? It will be helpful to find the root cause and resolve it.  
Also, could you confirm that whether errors mentioned in windbg file have been resolved? 
Other guess: does your project make any change related to SYSTEM? I might need more details. Thanks.

**Comment by sln162** [comment] 2023-01-31 03:01
> Could you contact your customers to get trace? 
No, users need to take the initiative to contact us, we do not have user contact information.

> Could you confirm that whether errors mentioned in windbg file have been resolved?
I tried to contact him, but the user didn't respond later, so I can't be sure.

> Does your project make any change related to SYSTEM?
Check and modify time zone, synchronize system time.

Sorry for not being able to give you enough information.

**Comment by ElyssaJyu** [comment] 2023-01-31 06:20
> Check and modify time zone, synchronize system time.

Could you give a description for your project workaround?  For example, the change related to the SYSTEM.  
Although "the frequency of occurrence seems to be decreasing", we can troubleshoot the possible root cause to prevent it, if you want.

**Comment by sln162** [comment] 2023-01-31 11:00
@ElyssaJyu   

> Could you give a description for your project workaround? For example, the change related to the SYSTEM.

Check whether the user system time zone is: China-Beijing (UTC+8), if not, modify it to this time zone, and use NTP to synchronize the accurate system time.

**Comment by ElyssaJyu** [comment] 2023-02-01 08:24
I will further investigate. Please let me know if you have update from your customers or more troubleshooting details you find. Thanks a lot.

**Comment by sln162** [comment] 2023-02-01 11:00
@ElyssaJyu  I don't think it has anything to do with this, modify the code for the time zone:
``` 
                string timeZoneId = "China Standard Time";
                var process = Process.Start(new ProcessStartInfo
                {
                    FileName = "tzutil.exe",
                    Arguments = "/s \"" + timeZoneId + "\"",
                    UseShellExecute = false,
                    CreateNoWindow = true
                });

                if (process != null)
                {
                    process.EnableRaisingEvents = true;
                    process.Exited += (sender, e) => { TimeZoneInfo.ClearCachedData(); }; 
                }
```
[NTP  Synchronize system time](https://github.com/vevi1982/TestGIT/blob/210fc1688c1e11fbf39366d18a84d69ec97ffe99/Vevisoft/WindowsAPI/SNTPTime.cs)

**Comment by novac42** [comment] 2023-05-29 09:37
Closing this issue as we cannot repro it on Win11 and Win7/Win8 are no longer supported. Please let us know if it can be reproduced on Win11 and reopen the issue if that's the case.

**Closed by novac42** 2023-05-29 09:37 UTC
Labels: bug, tracked, status-circle back

**Comment by JingeOnline** [comment] 2025-05-08 19:53
This problem occor on my windows11 machine.

Let me explain the problem, it is very tricky. I am develping a WPF screen saver app, use WebView2 control to show some HTML garget. It works all good on my windows 10 machine, then I copy the project bin folder to my windows 11 machine A and B. As a screen saver app, I need to change the .exe file extension to .scr so that windows screensaver can recognize it as a screen saver app and allow it be triggered when system idle. On my windows 11 machine A, this app can run correctly with the .scr extension, I can test, install and preview the screen saver app manually, the WebView2 contorl is loaded correctly. **BUT**, if the app be triggerd by system screensaver (leave machine 3 minutes idle for example), it cannot display the WebView2 control anymore, and throw this error every time. On my windows 11 machine B, when I first time run this app, the app throw the same error, but after that, it never throw this error anymore and works as a screensaver all good.

Since this error is very hard to reproduce on other machine, I don't think there is any problem in my code. But if you want to see the code, I leave the link in here: https://github.com/JingeOnline/WPF_WebScreenSaver_Project

Other potential reason could be:
1> In my computer A, I login as Administrator, while on other computer I login using Microsoft account.
2> In my computer A, the Windows version is not common, it is "Windows 11 Enterprise multi-session" some default setting inherit from Windows Server.
3> This problem only happend in some specific language system, like Chinese - Simplified (zh-CN)

Here is the device information about my computer A:
  设备名称(Device name)	HW-PC
  处理器(CPU)	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
  机带 RAM	8.00 GB (7.85 GB 可用)
  设备 ID (Device ID)	866D6982-AE16-4625-90AE-41C40020C215
  产品 ID (Product ID)	00389-20000-00001-AA885
  系统类型 (System Type)	64 位操作系统, 基于 x64 的处理器
  笔和触控 (Pen And Touch)	没有可用于此显示器的笔或触控输入
  
  版本	Windows 11 企业版多会话  -> Version       Windows 11 Enterprise multi-session
  版本号	24H2  -> Version Number        24H2
  安装日期	‎2025/‎4/‎17  -> Installation Date          2025/04/17
  操作系统版本	26100.3775   -> Operation System Version        26100.3775

Here is the Exception:
  System.Runtime.InteropServices.COMException (0x80070578): 无效的窗口句柄。 (异常来自 HRESULT:0x80070578)
     在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
     在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__15.MoveNext()
  --- 引发异常的上一位置中堆栈跟踪的末尾 ---
     在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     在 Microsoft.Web.WebView2.Wpf.WebView2.<Microsoft-Web-WebView2-Wpf-IWebView2Private-InitializeController>d__19.MoveNext()
  --- 引发异常的上一位置中堆栈跟踪的末尾 ---
     在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     在 Microsoft.Web.WebView2.Wpf.WebView2Base.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
  --- 引发异常的上一位置中堆栈跟踪的末尾 ---
     在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     在 WPF_WebScreenSaver_Project.MainWindow.<Run>d__14.MoveNext() 位置 C:\Users\jinge\source\repos\WPF_WebScreenSaver_Project\WPF_WebScreenSaver_Project\MainWindow.xaml.cs:行号 88
