### ISSUE TITLE
How do we get CoreWebView2Controller instance after WebView2 is created?

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#984] opened 2021-02-25 12:15 UTC
Can we not get `CoreWebView2Controller` instance after WebView2 is created?

I cam across this API in [CoreWebView2Environment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createcorewebview2controllerasync?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2Environment_CreateCoreWebView2ControllerAsync_System_IntPtr_) for creating `CoreWebView2Controller`. 

Is this the only way like, first we should create `CoreWebView2Controller` using async API and then navigate to create `CoreWebView2` instance inside `WebView2`?

I dint get examples regarding this. Any sample app with usage of this API will be greatly helpful.

**Comment by david-risney** [comment] 2021-02-25 18:47
The CoreWebView2Controller is used to manually manage hosting of a CoreWebView2. If you are using a WebView2 WPF/WinForms/WinUI control then you don't have access to the CoreWebView2Controller because the WebView2 control has its own reference to the CoreWebView2Controller and is responsible for integrating that with its UI framework. That is, rather than manually managing hosting of the CoreWebView2, you're using the WebView2 control which does it for you.

All of the CoreWebView2Controller functionality should either be integrated with the UI framework, for example the size of the control is set appropriately based on control's parent and so on, or should be exposed as APIs on the WebView2 if the UI framework doesn't support such integration, for example the [AcceleratorKeyPressed event on the WinForms WebView2 control](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.acceleratorkeypressed?view=webview2-dotnet-1.0.705.50).

Which WebView2 control are you using and what is it missing that you want to use from CoreWebView2Controller?

**Comment by chaitanyajun12** [comment] 2021-02-26 03:04
I'm using 1.0.705.50 version of WebView2 SDK.

The reasons to access controller,
1. I wanted to access the Close() method in CoreWebView2Controller. The reason was, I wanted to check if it would address the [browser-webview kill](https://github.com/MicrosoftEdge/WebView2Feedback/issues/974) issue. Was thinking if calling Close() will wipe out the instance fully. Does it do this?
2. Based on the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createcorewebview2controllerasync?view=webview2-dotnet-1.0.705.50), I see controller provides better handling when the WebView2 runtime changes happen when the app is open. Is it really the case or creating WebView2 directly will also offer the same benefits?

Few doubts I have, 
1. Is it possible to inflate the CoreWebView2 instance from CoreWebView2Controller on a WPF component?
  - If so how?
  - If not, then I'm assuming CoreWebView2Controller is not usable API for the apps. Please correct me on this.
2. So, the only approach I see to create WebView2 is directly creating its instance and assigning it to WPF component. From CoreWebView2Environment, there is no way to create WebView2. Please correct me on this as well.

**Comment by david-risney** [comment] 2021-02-26 19:04
1. The WebView2 controls are disposable and will call Close on their CoreWebView2Controllers. Closing a WebView2 will close down that WebView2 instance. If you have other WebView2s running at the same time using the same user data folder they share the same browser process and perhaps share some renderer and other processes and so closing one webview2 doesn't necessarily close down all the processes. If its the only WebView2 though it will close down all its associated processes. Note that calling Close starts this closing down process but doesn't wait for it to complete.
2. For noting when a new version is available you can use the [CoreWebView2Environment.NewBrowserVersionAvailable event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.newbrowserversionavailable?view=webview2-dotnet-1.0.705.50).

> Is it possible to inflate the CoreWebView2 instance from CoreWebView2Controller on a WPF component?

If you are using a WPF WebView2 control you cannot get to the corresponding CoreWebView2Controller.

> So, the only approach I see to create WebView2 is directly creating its instance and assigning it to WPF component. From CoreWebView2Environment, there is no way to create WebView2. Please correct me on this as well.

You directly create a WebView2 control. Its CoreWebView2 is created asynchronously and you can use the  EnsureCoreWebView2Async method to explicitly create the CoreWebView2 and optionally pass in the CoreWebView2Environment you want to use. You can read more about that in the [WebView2 documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.705.50#remarks).

**Comment by chaitanyajun12** [comment] 2021-02-28 17:01
Got it. So, the summary is if we are using WebView2 for browser creation, we cannot access CoreWebView2Controller instance and those APIs are unusable in that scenario.

One more doubt, regardless of which way (CoreWebView2Controller/WebView2) we use to create WebView2, the behaviour of browsers in each of these scenarios (in terms of restart/dispose) will be same or different during WebView2 runtime updates?

**Comment by david-risney** [comment] 2021-03-01 17:55
> So, the summary is if we are using WebView2 for browser creation, we cannot access CoreWebView2Controller instance and those APIs are unusable in that scenario.

Yes, you can use WebView2 or CoreWebView2Controller but not both. I wouldn't say the CoreWebView2Controller APIs are unusable. They should be exposed via the WebView2 control class or the WebView2 control class should hook them up correctly to WPF for you. If you find there is an API or something on CoreWebView2Controller missing from the WebView2 control please let us know.

> One more doubt, regardless of which way (CoreWebView2Controller/WebView2) we use to create WebView2, the behaviour of browsers in each of these scenarios (in terms of restart/dispose) will be same or different during WebView2 runtime updates?

The behavior is the same once Dispose/Close has been called. Obviously with the WebView2 control WPF may Dispose your control for you which won't happen with CoreWebView2Controller. But other than how Dispose/Close is called, the behavior once it is called is the same. Generally you'd expect the behavior to be the same. The CoreWebView2Controller/CoreWebView2 have no knowledge of what is hosting them, WPF, WinUI, custom hosting and so on. So the behavior of the CoreWebView2* doesn't vary based on that.

**Comment by champnic** [comment] 2021-03-03 00:09
I'm going to close this issue as there isn't work to be done here, but please continue the discussion and ask more questions if needed. Thanks!

**Closed by champnic** 2021-03-03 00:09 UTC
Labels: question

**Comment by Suchitra-s** [comment] 2021-12-02 12:28
I want to use CoreWebView2Controller.AllowExternalDrop as given in https://github.com/MicrosoftEdge/WebView2Feedback/issues/278. I am using WPF WebView2 Control. can you suggest how to access CoreWebView2Controller instance?

**Comment by champnic** [comment] 2021-12-02 23:48
Hey @Suchitra-s - the .NET controls don't give explicit access to the Controller or it's properties. Instead that behavior will be implemented and exposed on the .NET controls themselves. I'll follow-up with the dev implementing this feature to see what the plan is there. Thanks!

**Comment by BrightWind** [comment] 2022-08-16 15:59
> Hi @david-risney, 
I am using the Microsoft.Web.WebView2.Wpf.WebView2 from Microsoft.Web.WebView2 v1.0.1293.44 in wpf project. I found in UWP sample, when minimized/maximinzed the app, the document:visibilitychange event will be triggered. But in wpf project, it will not. And the IsVisible proper in WebView instance exposes only GET method, but in the CoreWebViewController,    the IsVisible proper exposes both GET and SET method. Could you give some tips how can I trigger the the document:visibilitychange event in wpf project?

**Comment by champnic** [comment] 2022-08-16 18:43
@BrightWind Sounds like that might be a bug in WPF. Can you open it as a new GitHub issue? If you have a sample app that reproduces this issue that would also be helpful. Thanks!

**Comment by duncangroenewald** [comment] 2023-01-04 10:07
I am trying to trap a key stroke combination while the WebView2 has the focus but there seems to be no way to do that.  None of the OnKeyDown/Up API's get called when using Windows App SDK.  Lots of references to AcceleratorKeyPressed etc. but not a single working example to be found.  Seems extraordinarily difficult to do something as simple as have a hot key that is accessible regardless of what child control has the focus.

**Comment by nickrandolph** [comment] 2023-04-26 15:22
> The CoreWebView2Controller is used to manually manage hosting of a CoreWebView2. If you are using a WebView2 WPF/WinForms/WinUI control then you don't have access to the CoreWebView2Controller because the WebView2 control has its own reference to the CoreWebView2Controller and is responsible for integrating that with its UI framework. That is, rather than manually managing hosting of the CoreWebView2, you're using the WebView2 control which does it for you.
> 
> All of the CoreWebView2Controller functionality should either be integrated with the UI framework, for example the size of the control is set appropriately based on control's parent and so on, or should be exposed as APIs on the WebView2 if the UI framework doesn't support such integration, for example the [AcceleratorKeyPressed event on the WinForms WebView2 control](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.acceleratorkeypressed?view=webview2-dotnet-1.0.705.50).
> 
> Which WebView2 control are you using and what is it missing that you want to use from CoreWebView2Controller?

Is there an equivalent to the WPF WebView2 AcceleratorKeyPressed method on the WinUI3 WebView2? I can't seem to find it, only a references to https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.acceleratorkeypressed?view=webview2-dotnet-1.0.1722.45

**Comment by champnic** [comment] 2023-04-27 21:07
@nickrandolph the equivalent would be a similar "KeyDown" event in WinUI, which seems to be broken according to @duncangroenewald above. If those events don't work for you in WinUI for the accelerator related keypresses (ctrl, shift, alt, etc.) can you open a new issue on our GitHub?

**Comment by UweKeim** [comment] 2023-05-17 07:27
Using WinForms WebView2 in latest available version **1.0.1774.30**, I tried to follow the link "[AcceleratorKeyPressed event on the WinForms WebView2 control](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.acceleratorkeypressed?view=webview2-dotnet-1.0.705.50)".

It seems that my (newer) version, there is no `AcceleratorKeyPressed` event available (anymore?).

Am I doing it wrong? Did the event get renamed?

**Comment by champnic** [comment] 2023-05-17 18:33
@UweKeim There isn't an AcceleratorKeyPressed event on the Winforms WebView2 control. The event is on the CoreWebView2Controller, and isn't meant to be exposed directly to WPF or Winforms controls. Instead please use the WebView2.KeyDown event.

(We had a bug in one SDK version from a while back that accidentally added it, so if you are using it then that could explain why you used to see it but don't anymore)

**Comment by Sandu119** [comment] 2025-02-04 06:53
I'm trying to use the `CoreWebView2Controller.IsVisible` property on a WebView2 instance (winforms project) but apparently it does not expose it. Am I missing something?

**Comment by Sandu119** [comment] 2025-02-04 06:54
I'm trying to use the CoreWebView2Controller.IsVisible property on a WebView2 instance (winforms project) but apparently it does not expose it. Am I missing something?

**Comment by Sandu119** [comment] 2025-02-04 06:54
I'm trying to use the CoreWebView2Controller.IsVisible property on a WebView2 instance (winforms project) but apparently it does not expose it. Am I missing something?
