### ISSUE TITLE
[file api 4 desktop application] allow conditional enable file path of file api like electronjs

### ISSUE THREAD

**Issue by congzhangzh** [MicrosoftEdge/WebView2Feedback#2497] opened 2022-06-06 13:52 UTC
**Is your feature request related to a problem? Please describe.**

I want to add native file drag and drop to my application, which needs the access to the file path

**Describe the solution you'd like and alternatives you've considered**

be confirm with electron js like https://www.electronjs.org/docs/latest/api/file-object

**make this an optional sandbox switch that allows control by the developer when init the webview2**

Refs:
1. https://www.electronjs.org/docs/latest/api/file-object
2. https://github.com/electron/electron/blob/main/patches/chromium/.patches
3. https://github.com/electron/electron/blob/main/patches/chromium/blink_file_path.patch
4. https://github.com/congzhangzh/desktoploveblazorweb

[AB#39922218](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39922218)

**Comment by champnic** [comment] 2022-07-16 00:14
@congzhangzh I'm closing this as a duplicate of #501. Feel free to add extra scenarios/requirements to that issue. Thanks!

**Closed by champnic** 2022-07-16 00:14 UTC
Labels: feature request, tracked
