### ISSUE TITLE
NavigationCompleted regression for certain websites

### ISSUE THREAD

**Issue by lezzi** [MicrosoftEdge/WebView2Feedback#3801] opened 2023-09-20 18:39 UTC
**Description**
The [`CoreWebView2.NavigationCompleted`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigationcompleted?view=webview2-dotnet-1.0.1901.177) event stopped raising for some websites. It can be reproduced by navigating to https://www.tradingview.com/.

**Version**
SDK: 1.0.1722.45, 1.0.1988-prerelease
Runtime: 117.0.2045.31, 117.0.2045.36.
Framework: WPF
OS: Windows 11 Pro 22H2 22621.1992

**Regression**
* Last time it worked properly on the 116.0.1938.81 runtime.
* It works on the latest Canary 119.0.2111.0 runtime.

**Repro Steps**
1. Download and install the Evergreen 117.0.2045.36 runtime ([link](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)).
2. Clone the official [WebView2WpfBrowser]( https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser).
3. Start the browser and navigate to https://www.tradingview.com/.

Expected: The "Reload" button gets enabled after the site has loaded.
Actual: The "Reload" button stays disabled forever and "Waiting for {url}..." can be visible in the left bottom corner. 

<img width="223" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/5619119/9dea7f7d-af93-4010-b376-52fc28eb23ff">

**Additional context**
* There are no pending requests on the Dev Tools Network page
* The issue does not exist on the 116.0.1938.81 runtime and older versions.
* The issue looks to be fixed in the latest Canary.

[AB#46853226](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46853226)

**Comment by RendijsSmukulis** [comment] 2023-09-22 13:28
I've just checked that it's not just WebView2 that presents this regression, but Edge also never finishes loading the page:

- It repros on latest Edge (117.0.2045.36)
- It repros on latest Edge Canary (119.0.2115.0)
- Chrome or Firefox finish loading the page as expected.

**Comment by monica-ch** [comment] 2023-10-13 00:01
@lezzi Looks like this site is using AV1 encoding to play the video and Edge requires AV1 Video Extension to play AV1(In Edge 117, we stopped to support AV1) which might be causing the issue. Can you make sure you install AV1 video extension for it to work? Also be sure to clear the browser /wv2 cache after the installation.

**Comment by MarkIngramUK** [comment] 2023-10-18 14:30
> Can you make sure you install AV1 video extension for it to work?

@monica-ch , we are building a browser, and aren't in control of the websites that our users navigate to.

**Comment by RendijsSmukulis** [comment] 2023-10-18 14:49
@monica-ch It does indeed look like the AV1 support, I see AV1 videos no longer work in our app. 

Can you please clarify the "install AV1 video extension" step, as I've installed the https://apps.microsoft.com/detail/av1-video-extension/9MVZQVXJBQ9V?hl=en-gb&gl=LV extension and it did not resolve the issue for Edge _or_ our app. The page still never finishes loading, and the videos don't play. Even after clearing out the WV2 profile folders.

**Comment by monica-ch** [comment] 2023-10-18 17:57
@RendijsSmukulis Can you send the logs from about://media-internals both from browser and wv2 app, please close microsoft edge and wv2 app first then repro it and send the logs

**Comment by monica-ch** [comment] 2023-10-24 20:15
@MarkIngramUK Edge and WebView2 have never broadly support AV1. The ability to leverage the Windows codec pack version of AV1 has been considered experimental and many users have never had the AV1 codec pack installed on their device. The experimental support was impacted due to upstream re-architecture for video decoding on Windows but, since it’s considered experimental and never broadly available, it was not noted in release notes. We are exploring options to re-enable the experimental codec pack support and can share updates if and when we have them.

cc @nishitha-burman

**Comment by monica-ch** [comment] 2023-10-24 20:17
@lezzi @RendijsSmukulis See above comment, we are exploring options to re-enable the experimental codec pack support to play av1 videos and I'll update the thread once we have info.

**Comment by monica-ch** [comment] 2024-01-16 19:35
AV1 encoding is now supported in [Edge 121+](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdeployedge%2Fmicrosoft-edge-relnote-beta-channel&data=05%7C02%7Cmonicach%40microsoft.com%7C48927b4764d8401cf2f808dc16c60399%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638410286983444203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r4pO1r5JqvoEz%2FPCQSskZLJQfl1PQ%2FJYt2iu1s4izcA%3D&reserved=0) which also fixed the navigation issue in WebView2. Please test in WebView2 app using Edge Beta binaries and let us know if you still see any issues.

Closing the thread, feel free to re-open if you see any issues

**Closed by monica-ch** 2024-01-16 19:35 UTC
Labels: bug, tracked
