### ISSUE TITLE
CoreWebView2_NewWindowRequested not raised

### ISSUE THREAD

**Issue by noxe** [MicrosoftEdge/WebView2Feedback#653] opened 2020-11-22 14:41 UTC
Hi,

is there any reaason why CoreWebView2_NewWindowRequested is not raised when clicking an Link and holding the SHIFT key ?

[AB#30813340](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30813340)

**Comment by pagoe-msft** [comment] 2020-11-23 18:22
@noxe 

This is definitely a bug - thanks for bringing this up!

**Comment by Symbai** [comment] 2020-11-23 18:32
Tried to reproduce this on `1.0.707-prerelease` but I cannot. @noxe Can you try this version and see if it solves the issue? According to the changelog, it should have: https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#features since it's pointing to the existing issue #168

**Comment by noxe** [comment] 2020-11-23 18:35
oh ok - thx. i see it uses minimum Microsoft Edge version 89.0.707.0. - since we only uses Fixed Distribution - how would i could get this fixed version to donwload?

**Comment by pagoe-msft** [comment] 2020-11-23 21:40
@noxe Apologies, yes this was fixed in the 1.0.7070-prerelease version of the SDK. If you are using the Fixed Distribution, you will need to update to 89.0.707.0 version.

**Comment by noxe** [comment] 2020-11-23 21:41
ok thx - can you post where to download fixed version 89.0.707.0 ? cannot find it ?

**Comment by noxe** [comment] 2020-11-30 06:16
@pagoe-msft so no more feedback here at all?

**Comment by champnic** [comment] 2020-12-03 08:45
Quick correction of what pagoe said above - we don't yet have a Fixed Version release that will support the 1.0.707-prerelease SDK. In general, the Fixed Version releases match the stable WebView2 Runtime, and support the latest release SDK (rather than prerelease). It's a known gap that developing against the prerelease SDKs isn't easy using Fixed Version.

Looking closer at this bug fix though, it should only require an updated runtime, rather than an SDK update. Any runtime version 88.0.693.0+ should have the fix. You can use the Canary/Dev channels, or wait until the next Fixed Version is released.

**Closed by champnic** 2020-12-03 08:45 UTC
Labels: bug, question, tracked
