### ISSUE TITLE
No scrolling possible at HTML input fields of type "time" and HTML Select

### ISSUE THREAD

**Issue by weaslyko** [MicrosoftEdge/WebView2Feedback#3512] opened 2023-05-25 10:03 UTC
Hello,
we are actually experiencing an issue with the HTML input field of type "time". When using in Webview2 there is no possibility to scroll the values with the mouse wheel. 
I will show u the issue in an attached video. As u can see there, changing the value with the keyboard is no problem. But with the mouse wheel..
(Unfortunately, the dropdown menu is not displayed correctly in the video. Therefore i attached a screenshot of it.)

Framework: UWP
We are using WebView2 1.0.1264.42 with Microsoft.UI.Xaml 2.8.2

If u need any other information please contact me. 

I hope for your support!

Best regards!

https://github.com/MicrosoftEdge/WebView2Feedback/assets/130778226/f6dd2067-a5e3-45fb-9cdc-8cd33e6494e7

![Screenshot 2023-05-25 120203](https://github.com/MicrosoftEdge/WebView2Feedback/assets/130778226/3add31a9-ff2b-43ca-81c2-f195a0b56af3)

[AB#44895924](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44895924)

**Comment by david-risney** [comment] 2023-05-26 17:24
@weaslyko Do I understand correctly that the issue is solely about the mouse wheel not working with the `<input type=time`'s dropdown menu? It does make it difficult to use the dropdown menu using the mouse since it seems like the mouse wheel is the only way to get to the time values that aren't first visible in the dropdown (it has 7 rows for choosing hours and minutes).

I tried the [MDN type=time doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) with the following results:

| App | Runtime | SDK | Works |
| --- | --- | --- | --- |
| Win32 Sample App | 113.0.1774.50 | 1.0.1777.0 | ✔️ |
| Win32 Sample App | 115.0.1880.0 | 1.0.1777.0 | ✔️ |
| WinUI 2 Sample App | 113.0.1774.50 | 1.0.1619.0 | ❌ |
| WinUI 2 Sample App | 115.0.1880.0 | 1.0.1619.0 | ❌ |
| WinUI 3 Gallery | 113.0.1774.50 | 1.0.1661.34 | ✔️ |
| WinUI 3 Gallery | 115.0.1880.0 | 1.0.1661.34 | ✔️ |


@champnic @bradp0721 is this a known issue? Seems like a bug with WinUI2 / UWP where mouse wheel isn't getting to the time picker flyout?

**Comment by bradp0721** [comment] 2023-05-26 17:27
@johna-ms, sounds like an issue with owned windows in UWP. Are you aware of this?

**Comment by weaslyko** [comment] 2023-05-30 06:18
@david-risney Thank you for your quick answer. Yes, thats absolutely right. It is just about the mouse wheel not working with the input type=time dropdown menu!
I look forward to further insights.
Best regards.

**Comment by applefanbois** [comment] 2023-06-02 14:13
Dropdown (select list) do not scroll with the mouse wheel.

Cannot scroll dropdown list in WebView2 with the mouse wheel under WinUI3.

**Comment by johna-ms** [comment] 2023-06-02 17:31
@bradp0721 confirming this is an issue with owned windows. I can take this over

**Comment by applefanbois** [comment] 2023-06-02 17:37
I created another ticket because I don't know if they are related.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3534

**Comment by johna-ms** [comment] 2023-06-02 20:47
@applefanbois thanks for that, though I think they are the same underlying bug

**Comment by weaslyko** [comment] 2023-06-19 09:42
Hello @johna-ms,

i just wanted to ask if u got an update on this issue for me?

Best regards!

**Comment by johna-ms** [comment] 2023-06-19 18:57
@weaslyko and others, the fix for this should be in Canary and will likely be in stable in mid August. Please try it out and verify it is fixed!

**Comment by champnic** [comment] 2023-06-20 19:55
Fixed in runtimes 116.0.1917.0+. Thanks!

**Closed by champnic** 2023-06-20 19:55 UTC
Labels: bug, tracked
