### ISSUE TITLE
How can I disabled javascript for content, but allow internal application scripts?

### ISSUE THREAD

**Issue by Huseriato** [MicrosoftEdge/WebView2Feedback#466] opened 2020-09-22 11:59 UTC
I use some extra scripts to manipulate the context menu and add some other features. But I do not want to allow external scripts. Is it possible to allow own scripts but disallow external scripts?

[AB#29558507](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29558507)

**Comment by champnic** [comment] 2020-09-23 21:00
This should be the behavior when you set ICoreWebView2Settings::put_IsScriptEnabled to false.
https://github.com/MicrosoftEdge/WebViewFeedback/issues/new?assignees=&labels=feature+request&template=feature---api-request.md&title=

Can you give that a try and see if it works for you?

**Comment by Huseriato** [comment] 2020-09-24 05:44
If I use `ICoreWebView2Settings::put_IsScriptEnabled` with value `false`, all scripts are disabled. Scripts added with `AddScriptToExecuteOnDocumentCreated` are not working, too. So I can have scripts on or off, but not distinguish between the source and allow my own, but disallow the scripts loaded by the content. So writing an email client for example is not possible, if you want to workaround with javascript around some issues of WebView2. So there is no other option?

**Comment by champnic** [comment] 2020-09-24 05:55
Can you try using `ICoreWebView2::ExecuteScript`? Sounds like we have a bug if `AddScriptToExecuteOnDocumentCreated` isn't working - we're tracking this internally and we'll look into it. Thanks!

**Comment by Huseriato** [comment] 2020-09-24 06:05
Thanks for tracking this as an issue. `ExecuteScript` is not working, too. I'm disabled the script using `ICoreWebView2Settings::put_IsScriptEnabled` in the activation event (is this correct?). I tried to add and execute scripts **before** and **after** this event. I also tried to add and execute scripts in `NavigationCompletedEventHandler` and also on button press in my application. Neither of this works.

**Comment by david-risney** [comment] 2021-01-19 23:02
I'm unable to reproduce the behavior described in this bug. I've performed the following steps in our [Win32 WebView2 sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample) and everything appears to work as intended. That is, after calling `put_IsScriptEnabled(FALSE)` and then reloading or navigating the page is unable to run script, but you can call ExecuteScript or AddScriptToExecuteOnDocumentCreated and have that script run in the page.

I tried the following out:
0. Wait for the sample app to start. It uses JavaScript to fill in the SDK build and Runtime version values. You can see that it does, JavaScript in the page is running.
1. Go to, Script | Inject Script, enter `alert("script")`, press OK
2. An alert dialog displays
3. Go to, Script | Add Initialize Script, enter `if (window.parent === window.top) { alert("init script 1") }`, press OK
4. Reload the page
5. Page's script runs, and an alert dialog displays "init script 1"
6. Go to, Settings | Toggle JavaScript
7. Reload the page
8. The page's script does not run, and an alert dialog displays "init script 1"
9. Go to, Script | Inject Script, enter `alert("script")`, press OK
10. An alert dialog displays

SDK build 772.0
Runtime version 89.0.772.0

Accordingly, I'm closing this bug. Perhaps the issue existed but has been fixed in a more recent runtime version than what you tried. But if you are still experiencing this issue on the latest runtime version please let us know. If you can reproduce the issue using the Win32 WebView2 sample app or using the simple script I used above it would be helpful to know about that. Thanks!

**Closed by david-risney** 2021-01-19 23:02 UTC
Labels: bug, question, tracked
