### ISSUE TITLE
MSEdgeWebView crash

### ISSUE THREAD

**Issue by PradeepKLCitrix** [MicrosoftEdge/WebView2Feedback#1882] opened 2021-10-27 08:31 UTC
MSEdgeWebView which is used to render, crashes in few systems resulting in White screen which is hosting this rendering process.

We recently released an update to the Citrix Workspace app. 

Workspace app 2109 for Windows switched to MSEdgeWebView as its rendering process. We have many customers  complaining about "white screen" in the UI. Users just see a white screen in the app and cannot take any further action. Upon debugging, it is found that MSEdgeWebView is just crashing in these machines. 
 
To try this out further and remove any Citrix components aspect, we used sample MSEdgeWebView Win32 app from https://github.com/MicrosoftEdge/WebView2Samples and this app as well resulted in MSEdgeWebView crash in the system. Essentially this is blocking the customer to use the app and the only fall back is to go to older version of the Citrix Workspace app which uses CEF based renderer. 

Could we please request your help to address these issues at the earliest? Please do let us know what further information we can help with. 

[AB#36857289](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36857289)

**Comment by Syul968** [comment] 2022-09-23 03:03
The root cause of this issue was fixed in the WebView2 Runtime back in February/March. Closing incident.

**Closed by Syul968** 2022-09-23 03:03 UTC
Labels: bug, tracked
