### ISSUE TITLE
Context Menu in WebView2 PDF Viewer when selecting text

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#1345] opened 2021-06-02 08:52 UTC
UseCase:

In an sample WPF window application i hosted a single instance of WebView2 as below ( In MainWindow.xaml ) and passed source url to load a sample PDF.
In addition to that I added a settings to CoreWebView2 to disable default context menu as below ( In MainWindow.xaml.cs )

MainWindow.xaml

![image](https://user-images.githubusercontent.com/25306014/120449906-7c791280-c3ad-11eb-9d0c-94eb704a6ea3.png)

MainWindow.xaml.cs

![image](https://user-images.githubusercontent.com/25306014/120449760-58b5cc80-c3ad-11eb-8bc8-e2a98c233095.png)

Current Behavior:

Upon RMB click on selected text we could see context menu as shown in below screenshot.

Is this expected behavior ?

![MiniContextMenu](https://user-images.githubusercontent.com/25306014/120449657-42a80c00-c3ad-11eb-9903-ad348ebe9b40.png)

Version Information

Nuget - Microsoft.Web.WebView2 => 1.0.818.41
Fixed Version: Microsoft.WebView2.FixedVersionRuntime.91.0.864.37.x64

[AB#33623058](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33623058)

**Comment by champnic** [comment] 2021-06-04 04:22
Hey @VijayanRamachandran - thanks for the report. The settings typically require a navigation to take effect. If you reload the page or try navigating somewhere else first, do you still see this behavior?

**Comment by VijayanRamachandran** [comment] 2021-06-04 07:04
@champnic 
Yes i still see the same behavior even after settings takes effect.

Ex:

I tried as below in MainWindow.xaml.cs ( in addition to instead of setting Source in MainWindow.xaml to pdf )

        async void InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async(null);

            webView.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
            webView.CoreWebView2.Settings.IsWebMessageEnabled = false;
            webView.CoreWebView2.Settings.IsStatusBarEnabled = false;
            webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
            webView.CoreWebView2.Settings.AreHostObjectsAllowed = false;
            webView.CoreWebView2.Settings.IsZoomControlEnabled = false;
            webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;
            webView.CoreWebView2.Settings.AreDevToolsEnabled = false;
            webView.CoreWebView2.Settings.IsScriptEnabled = false;

            webView.CoreWebView2.Navigate(@"D:\WebView2-Preview-MS-PrivateMSI\12_WebView2Preview-Pdf\WebView2Preview\SamplePdf.pdf");
        }

**Comment by champnic** [comment] 2021-06-04 18:09
I was able to repro the problem, and it looks like that menu shows up just by selecting text, not by using the right-mouse button. I don't think this is by design, so I've opened this bug on our backlog. Thanks!

**Comment by champnic** [comment] 2022-01-07 01:23
This should be fixed in runtimes 99.0.1112.0+. Thanks!

**Closed by champnic** 2022-01-07 01:23 UTC
Labels: bug, tracked

**Comment by sergimos** [comment] 2024-03-15 15:53
Hello,

I have the same issue on a touchpanel where a webview2 element is used to display a pdf. When selecting text with the touch control I get the same context menu as shown from @VijayanRamachandran. If I select text using my mouse I dont get the context menu.

**MainWindow.xaml.cs**
`using System.Windows;


namespace PDFViewer
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            InitializeAsync();
        }

        async void InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async(null); // Initialize the control
            webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
        }

    }
}`

MainWindow.xaml
`<Window x:Class="PDFViewer.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:PDFViewer"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <wv2:WebView2 Name="webView" Source="file:///D:/test.pdf#toolbar=0"/>
    </Grid>
</Window>`

Context menu that shows when selecting text with the  touch control:
![ContextMenu](https://github.com/MicrosoftEdge/WebView2Feedback/assets/94528357/690aded2-40b8-4fd8-97e1-4decf6af29f9)

Webview Version:
![WebView2Version](https://github.com/MicrosoftEdge/WebView2Feedback/assets/94528357/763fc308-a219-4c99-9cb4-e3d68ba849f3)

**Comment by champnic** [comment] 2024-03-20 20:21
@sergimos This is a pretty old issue. Can you open a new one for the issue you are seeing?
