### ISSUE TITLE
EnsureCoreWebView2Async throws Exception: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### ISSUE THREAD

**Issue by ukalhapu** [MicrosoftEdge/WebView2Feedback#3590] opened 2023-06-22 10:25 UTC
**Description**
EnsureCoreWebView2Async throws Exception: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
 EnsureCoreWebView2Async error: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) 
[29444] 03.32.54.748 PM [wtDesktop-WTWindows.5: Request Worker] BrowserForm_Load - EnsureCoreWebView2Async stack trace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler) 
[29444]    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext() 
[29444] --- End of stack trace from previous location where exception was thrown --- 
[29444]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
[29444]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
[29444]    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext() 
[29444] --- End of stack trace from previous location where exception was thrown --- 
[29444]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
[29444]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
[29444]    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 

**Version**
SDK: 1.0.1832.32
Runtime: 114.0.1823.51
Framework: WinForms
OS: Windows 11

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**
Application thread is creating a instance of Windows Form which has WebView2 control added.

**Comment by ElyssaJyu** [comment] 2023-06-26 09:10
Hi @ukalhapu, in general, "0x8007000B" indicates a mismatch between the platform target of your application and the library you are trying to use.  Could you check the platform target of your application, x86 or x64? 

Also, could you describe about your scenario when this issue happens? It will help for investigating if related sample code can be provided. Thanks.

**Comment by ukalhapu** [comment] 2023-06-26 09:34
Thanks ElyssaJyu for the response. 
It is VB.NET application with target AnyCPU and referring .NET 4.5 version of WebView2 SDK DLLs.
The application creates WinForm instance on thread with WebView2 control.

Private Sub TestButton_Click(sender As Object, e As EventArgs) Handles TestButton.Click
        LogMsg("TestButton_Click - > Creating new MyBackgroundThread....")
        Dim thread As New Thread(AddressOf MyBackgroundThread)
        thread.SetApartmentState(Threading.ApartmentState.STA)
        thread.IsBackground = True
        thread.Start()
    End Sub

    Private Async Sub MyBackgroundThread()
        LogMsg("TestWebView2OnThread -> Inside MyBackgroundThread...")

        Dim browser As New BrowserForm

        browser.WebView21 = New Microsoft.Web.WebView2.WinForms.WebView2()
        browser.WebView21.AllowExternalDrop = False
        browser.WebView21.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        browser.WebView21.CreationProperties = Nothing
        browser.WebView21.Location = New System.Drawing.Point(0, 0)
        browser.WebView21.Margin = New System.Windows.Forms.Padding(0)
        browser.WebView21.Name = "WebView21"
        browser.WebView21.Size = New System.Drawing.Size(512, 389)
        browser.WebView21.Source = New System.Uri("about:blank", System.UriKind.Absolute)
        browser.WebView21.TabIndex = 0
        browser.WebView21.ZoomFactor = 1.0R
        browser.WebView21.Enabled = True
        browser.WebView21.Visible = True
        browser.Controls.Add(browser.WebView21)

        'browser.Owner = Launch.ActiveForm
        browser.Enabled = True
        browser.Visible = True
        browser.ShowInTaskbar = True
        Application.Run(browser)


        Try
            Await browser.WebView21.EnsureCoreWebView2Async()
  
        Catch ex As Exception
            LogMsg("TestWebView2OnThread -> MyBackgroundThread - EnsureCoreWebView2Async error: " + ex.Message)
        End Try
        LogMsg("TestWebView2OnThread -> MyBackgroundThread compeleted")


    End Sub

**Comment by ElyssaJyu** [comment] 2023-06-27 06:23
Hi @ukalhapu, 
it seems you create a new thread and running the `MyBackgroundThread` method to create WebView2 and BrowserForm on it when the `TestButton` is clicked.

WebView2 control is creating on the backgroundThread in your code, however, WebView2 is single-threaded and must be created on a UI thread that uses a message pump. All callbacks occur on that thread, and requests into the WebView2 must be done on that thread. That may be why you encounter issue. 

You use [Control.Invoke ](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.invoke?view=windowsdesktop-7.0)to run the method on the UI thread, then create and manipulate webview2. Hope this will help you. Thanks

**Comment by ukalhapu** [comment] 2023-07-04 09:01
Hi @ElyssaJyu
Issue is resolved after I added WebVew2 dll in application bin folder. 
\runtimes
        \win-arm64\native\WebView2Loader.dll (arm64)
        \win-x64\native\WebView2Loader.dll (x64)
        \win-x86\native\WebView2Loader.dll (x86) 
Also WebView2 is working fine even though it is created on background thread (STA).

One more question - We have legacy VB.NET application using IE WebBrowser control. We have extended/customized/wrapped the existing WebBrowser control for application specific needs. 
Now we want  to migrate to WebView2. 
Is there standard migration guide/white paper published by Microsoft to ease migration from  Web Browser control to WebView2 ?
Please share the link.

**Comment by ElyssaJyu** [comment] 2023-07-05 02:59
Hi @ukalhapu, 
A comprehensive guide for migrating from Web Browser to WebView2 is not available yet. You can find more information on how to get started with WebView2 [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/), and [sample projects](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/get-started) to start building a WebView2 app in Win32, WPF and WinForms.

If you encounter any issues with WebView2 during the migration process, feel free to open an issue on [this GitHub page](https://github.com/MicrosoftEdge/WebView2Feedback/issues). We are here to help. Thanks

**Comment by ElyssaJyu** [comment] 2023-07-05 06:26
I'm closing it since the issue is resolved. Migration related issue will be followed up in #3616. Thanks

**Closed by ElyssaJyu** 2023-07-05 06:26 UTC
Labels: bug
