### ISSUE TITLE
[Problem/Bug]: CoreWebView2PrintSettings.ScaleFactor is not working when Windows's Microsoft WebView2 Runtime automatically upgade to 118.0.2088.46 verson

### ISSUE THREAD

**Issue by kekoke** [MicrosoftEdge/WebView2Feedback#4091] opened 2023-10-23 08:18 UTC
### What happened?

**Development Environment：**
Windows 11

.net core 3.1 Winform 
Microsoft.Web.WebView2 nuget version is  [1.0.2088.41](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2088.41)

**My code as below：**
```
private async Task<CoreWebView2PrintSettings> GetPrintSettingsAsync(WebView2 webView)
{
    CoreWebView2PrintSettings settings = webView.CoreWebView2.Environment.CreatePrintSettings();
    try
    {
        await webView.EnsureCoreWebView2Async();
        settings.MarginTop = _printSettings.MarginTop;
        settings.MarginLeft = _printSettings.MarginLeft;
        settings.MarginRight = _printSettings.MarginRight;
        settings.ScaleFactor = 0.4;//设置打印缩放
        //settings.Copies = 2;
        settings.Orientation = _printSettings.Orientation; //CoreWebView2PrintOrientation.Landscape; //横向
    }
    catch (Exception ex)
    {
        LogHelper.Error($"打印机配置错误，错误信息：{ex.Message}");
    }
    return settings;
}
```

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

118.0.2088.46

### SDK Version

1.0.2088.41

### Framework

Winforms

### Operating System

Windows 10, Windows 11

### Repro steps

1. load url
```
webBrowser.CoreWebView2.Navigate(newUrl);
```
2. in WebBrowser1_NavigationCompleted event, call Print function
```
private async Task<CoreWebView2PrintSettings> GetPrintSettingsAsync(WebView2 webView)
{
    CoreWebView2PrintSettings settings = webView.CoreWebView2.Environment.CreatePrintSettings();
    try
    {
        await webView.EnsureCoreWebView2Async();
        settings.MarginTop = _printSettings.MarginTop;
        settings.MarginLeft = _printSettings.MarginLeft;
        settings.MarginRight = _printSettings.MarginRight;
        settings.ScaleFactor = 0.4;//设置打印缩放
        //settings.Copies = 2;
        settings.Orientation = _printSettings.Orientation; //CoreWebView2PrintOrientation.Landscape; //横向
    }
    catch (Exception ex)
    {
        LogHelper.Error($"打印机配置错误，错误信息：{ex.Message}");
    }
    return settings;
}

 private async Task SendToPrinter()
        {
            //等待界面渲染完成
            CoreWebView2PrintSettings coreWebView2PrintSettings = await GetPrintSettingsAsync(_webBrowser);
            try
            {
                LogHelper.Info($"Step3 - 开始 - 调用浏览器打印");
                Thread.Sleep(_cmesConfig.ThreadSleep);//等待浏览器渲染
                var printResult = await _webBrowser.CoreWebView2.PrintAsync(coreWebView2PrintSettings);
                LogHelper.Info($"Step4 - 结束 - 调用浏览器打印，打印结果：【{JsonConvert.SerializeObject(printResult.ToString())}】");
            }
            catch (Exception ex)
            {
                LogHelper.Error($"连接打印机错误，错误信息：{ex.Message}");
            }
        }
```

### Regression

Regression in newer Runtime

### Last working version (if regression)

SDK 1.0.1722.45, Runtime 115.0.1901.203

[AB#47211445](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47211445)

**Comment by kekoke** [comment] 2023-10-23 08:40
_printSettings.ScaleFactor = 0.4;

**Comment by sln162** [comment] 2023-10-23 12:17
#4082  Is it the same problem?

**Comment by kekoke** [comment] 2023-10-23 12:34
> #4082 Is it the same problem?

The problem is similar, but not the same.

**Comment by lflores-ms** [comment] 2023-10-23 20:32
Thanks for the report @kekoke. Can you clarify what you mean by "setting is invalid"?

@monica-ch will this be addressed by the fix to #4082?

**Comment by monica-ch** [comment] 2023-10-23 20:39
If the issue is related to improper scaling in the print output, other bug should solve the problem. I have a fix which is in review, I'll let you know when it is Edge canary for validation.

**Comment by kekoke** [comment] 2023-10-24 00:19
> Thanks for the report @kekoke. Can you clarify what you mean by "setting is invalid"?
> 
> @monica-ch will this be addressed by the fix to #4082?

Sorry, it means that CoreWebView2PrintSettings.ScaleFactor does not work, thanks @lflores-ms.

**Comment by kekoke** [comment] 2023-10-24 00:28
> If the issue is related to improper scaling in the print output, other bug should solve the problem. I have a fix which is in review, I'll let you know when it is Edge canary for validation.

Thank you for letting me know. I appreciate your efforts in finding a fix for the improper scaling issue in the print output. Please keep me updated on the progress of the fix and let me know when it is available in Edge Canary for validation. I look forward to testing it out.

**Comment by monica-ch** [comment] 2023-10-26 16:39
@kekoke This is now fixed in Edge canary channel 120.0.2184.0+. Please test and let us know if you still see issues.

**Closed** 2023-10-30 20:07 UTC
Labels: bug, tracked

**Comment by jagrut-patel** [comment] 2023-11-07 21:56
When would this fix be distributed for production usage of WebView2 Runtime.  We cannot use canary channel in production.

Evergreen Runtime distribution mode has updated to latest version that has introduced this bug for us. We need an option to either go back to previous version of WebView2 Runtime or an official Microsoft Update is available with this fix.

**Comment by monica-ch** [comment] 2023-11-07 22:03
@jagrut-patel WebView2 next stable version is scheduled for 12/7 that has a fix. Sorry, there isn't a way to go back to previous evergreen versions.
