### ISSUE TITLE
Dropdowns on a topmost window appear behind the window ..

### ISSUE THREAD

**Issue by lekj** [MicrosoftEdge/WebView2Feedback#411] opened 2020-08-27 09:44 UTC
Dropdowns on a topmost window appear behind the window

![image](https://user-images.githubusercontent.com/2289981/91424807-dd0e7880-e88c-11ea-9a8a-4ef008b4a55d.png)

The same reason pop-up window is behind

[AB#33392715](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33392715)

**Comment by champnic** [comment] 2020-08-27 14:50
Thanks for filing this issue! Could you help me by letting me know what framework are you using? And could you expand on the details of your scenario a bit more? Thanks!

**Comment by OJapes** [comment] 2021-05-20 06:48
I'm experiencing the same issue. It's the very same application as described #460 
Maybe it's the same root cause?

![Clipboard01](https://user-images.githubusercontent.com/75669197/118932202-1077c280-b948-11eb-810e-e3faaed6ad4c.jpg)

**Comment by champnic** [comment] 2021-05-21 03:40
@OJapes Certainly looks to be the same - are you setting your window to TopMost as well? If so, that's probably why the popup window is displaying below. I believe this also happens with admin hosts, where the popup window doesn't have permissions to draw on top.

I've changed this from a question to a bug and added it to our backlog. Thanks!

**Comment by OJapes** [comment] 2021-05-21 05:47
Yes, the window is `Topmost` (see screenshot-snippet). The application itself is not executed with admin permissions.
When setting it to `false`, it works as expected.

**Comment by nikitavirg** [comment] 2021-07-12 09:05
I have the same issue on my side https://github.com/MicrosoftEdge/WebView2Feedback/issues/1495
Do you have any workaround for this issue? For us it is really a issue as we have our main window as top MOST.
Do you know when it will be corrected? 
I have a simple project that reproduce the issue in C++.

**Comment by champnic** [comment] 2021-08-03 17:30
This should be fixed in the latest Canary (runtime version 94.0.972.0+). Please give that a try and let us know if you are still seeing this issue. Thanks!

**Closed by champnic** 2021-08-03 17:30 UTC
Labels: bug, tracked

**Comment by OJapes** [comment] 2021-08-04 07:34
> This should be fixed in the latest Canary (runtime version 94.0.972.0+). 

Could you please give a hint where to download this version? I can't find it on https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by nikitavirg** [comment] 2021-09-08 07:41
And so is it included on version
release 1.0.902.49
or pre-release 1.0.955 ?
I supposed we need to wait for a release 1.0.972 or upper?

**Comment by champnic** [comment] 2021-09-09 23:34
@nikitavirg Answered in the linked #1718 issue. Thanks!

**Comment by OJapes** [comment] 2021-09-10 06:21
I finally gt around to test that and I can confirm that it seems to be working now
![image](https://user-images.githubusercontent.com/75669197/132808842-97579c23-a022-4b9e-95aa-d8bd148014d6.png)

Further testing needs to be done though. 
Can we perhaps get a date at which this fix is available in the public stable versions?

**Comment by nikitavirg** [comment] 2021-09-10 08:27
On my side I do not reproduce the issue on edge version 93.0.961.44 so I wonder if part of fix are on it?
Moreover, what I understand is that runtime 94.0.992.9 should contains the fix and it is available in Beta version. Moreover Release will be available on 23 september. Is it correct? We should wait for this version to have the complete correction?
![image](https://user-images.githubusercontent.com/24527619/132824243-6cae882b-dc51-42d3-8f5d-0897f707a437.png)

**Comment by champnic** [comment] 2021-09-10 23:32
Correct - the fix should be available in stable around 9/23. Thanks!

**Comment by nikitavirg** [comment] 2021-09-29 08:00
I have another question about this version, I see that I have now the webview2 runtime installed by default on my computer, I have the following repository C:\Program Files (x86)\Microsoft\EdgeWebView\Application\94.0.992.31
I wonder:
1- Is it installed at same time that edge?
2- Is it installed by another application as office?
3- Can I considere that with this version of edge we have also edgeWebView installed?
4- Is there a registry key to know the version of webview2 installed?

**Comment by ysc3839** [comment] 2021-09-29 09:02
@nikitavirg
1. No.
2. Yes. IIRC MS Office now installs Edge WebView2.
3. No.
4. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment
