### ISSUE TITLE
WebView2 And memory management (in .net app)

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#799] opened 2021-01-09 09:30 UTC
WebView2 And memory management 

Please share practices that you use internally in Microsoft.
1)	How many WebView2 control could and should I have in Single Form (WPF/WinForm)
2)	What is the cost of each WebView2 (In terms of memory)
3)	What happening to WebView2 when Form is Closed (and Garbage Collected : ) )
4)	What is memory Management Practice in .NET Application when using multiple WebView2 (Multiple Forms has WebView2 and some of them have more than one in the single form)

Thank you in advance.

[AB#31680804](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31680804)

**Comment by RickStrahl** [comment] 2021-01-09 21:40
I don't have official answers for you, but having added to my application here's what I see in general terms:

* Biggest memory hit comes from first instance of WV
* I show 5 external msedgewebview2 processes regardless of browser instance
* Subsequent  browser instances don't substantially increase memory usage (depending on content though)
* If you close all WV instances, 5 base processes remain and memory usage doesn't seem to go down
There may be explicit APIs that can be called to release though - haven't checked.

To give an idea of Mem usage:

![image](https://user-images.githubusercontent.com/1374013/104109164-51135100-526f-11eb-9c3f-d5c20a01a0c1.png)

Interesting that there's so much decreprency between TaskMan and ProcessManager?

**Comment by champnic** [comment] 2021-01-13 00:20
@RickStrahl Your findings are mostly consistent with what we'd expect. For process cleanup, we would expect all process to get shutdown when the WebView2 instances get cleaned up, so perhaps there's a handle sticking around somewhere or Dispose() hasn't been called on the controls or something. 

Process will be shared when using the same UserDataFolder. This is why you see 5 processes initially (browser, renderer, GPU, network, etc.). When starting new WebView2 instances, most will be shared except for a new renderer process. The discrepancy between Task Manager and ProcExp is in how they display memory that is shared between browser processes. One of them (I think ProcExp) double-counts memory that in actuality is first used in one process and then also used in another process.

To answer the original questions:
1. This is up to you. Sharing processes except for renderer means that each additional WebView2 is similar to opening a new browser tab (which in Chromium and Microsoft Edge also create a new renderer process). These do take up a fair bit of memory over time though, so you can choose to put a limit if you want, close WebView2 instances for older tabs and recreate the page when the user goes to that WV2. We also have a new suspension API that should be available in prerelease package soon.
2. We expect around 250MB for the first WV2, and 100+MB for each subsequent WV2. These are dependent on a range of factors though, including the page you are displaying, etc.
3. When disposing a WebView2 it should shutdown at least the renderer process associated with that WV2, and potentially the other processes (browser, GPU, network) as well if it's the last WV2 open for a given UserDataFolder.
4. See 1. They will share processes so new WV2 should be cheaper, but ultimately management is what you decide to do with it. Something we've seen other folks do is to prerender a WV2 (start one up in the background hidden) so that when they need to show it to the user it displays faster because it's already warmed up/navigated to a website and just needs to be made visible. This is a tradeoff between runtime and memory usage.

**Comment by IrakliLomidze** [comment] 2021-01-15 11:31
Thank you champnic

Do we need manual disposal of WV2 ?
I guess that GC will not dispose of WV2 memory.

**Comment by champnic** [comment] 2021-01-15 23:05
Generally speaking no, you shouldn't need to manually dispose the WV2, as the processes and memory should be tied to the control. However, to clean up the control you need to ensure that Dispose() is being called on it. This often happens automatically (like when closing a Form or disposing a parent) but sometimes doesn't, in which case you will need to make sure you dispose of the WV2 control yourself.

**Comment by RickStrahl** [comment] 2021-01-16 07:10
@champnic So I experimented around with disposal and no matter what I do I cannot get the WV to unload the browser processes.

Background: I'm using the WebView in WPF and it sits on a user control that gets loaded dynamically. The control gets added to a window, and I can see that the control is firing unload events so everything is working correctly from the WPF end of things.

However, when I close all of my editor and preview windows, the browser processes remain open.

I can't call Dispose() directly on the control because that causes problems as the control is getting disposed by WPF when the form/user control gets unloaded. Like you say this should be automatic except it doesn't appear to be happening. By explicitly calling dispose before it's ready to be disposed (ha) I end up with race conditions where the control things it's still alive when it's not. So this needs to happen as part of the standard release cycle of the framework I think.

**Comment by champnic** [comment] 2021-02-10 21:52
@RickStrahl - sorry for the delay in response. I've filed a bug on our backlog to take a look and verify the right disposal is happening. You can also try the new 1.0.781-prerelease package in the meantime to see if that improves things. We have also made some recent fixes around disposal to make it not fail/crash when called multiple times or out of order, but that won't be available until the next package.

**Comment by champnic** [comment] 2021-02-13 00:31
Hey @RickStrahl - Our fix for the dispose() bug should be in the latest 1.0.790-prerelease SDK package. Do you want to try it and call .Dispose() on the WebView2 to see if that fixes the problem?

**Comment by RickStrahl** [comment] 2021-02-13 01:59
So it's a WPF control - shouldn't that automatically Dispose() when the window and parent control goes out of scope?

**Comment by bddckr** [comment] 2021-02-13 19:25
For some documentation on that behavior have a look here:

> The default channel search order is the WebView2 Runtime, Beta, Dev, and Canary. When an override WEBVIEW2_RELEASE_CHANNEL_PREFERENCE environment variable or applicable releaseChannelPreference registry value is set to 1, the channel search order is reversed.
> https://docs.microsoft.com/microsoft-edge/webview2/reference/win32/webview2-idl#createcorewebview2environmentwithoptions

**Comment by cremor** [comment] 2021-06-28 07:48
> So it's a WPF control - shouldn't that automatically Dispose() when the window and parent control goes out of scope?

See #1424

**Comment by RickStrahl** [comment] 2021-10-07 03:58
Note that even if you `Dispose()` all instances of the WebView properly it still looks like the base WebView2 Edge processes stick around - I've not been able to get them to release completely even if all WebView2 instances get closed out and `Dispose()`d.

Not a huge deal in my app as the app uses WebViews through it's entire lifetime, but for other apps that might just bring up a WebView for certain tasks this is pretty sucky.

**Comment by cremor** [comment] 2021-10-07 07:10
@RickStrahl That's not normal, you should investigate why the processes stick around for you. As you can read in #1424 the expected behavior is that all processes are closed when you dispose the last WebView2 instance. That's why I had to implement the workaround described in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1424#issuecomment-869429813 to keep the processes running.

I just tested this again with SDK 1.0.992.28 and runtime 94.0.992.38 and can confirm that it still behaves that way.

**Comment by mwetzko** [comment] 2022-02-21 17:02
I had the same issue as @RickStrahl that has brought me here.

The test [app](https://github.com/mwetzko/test/blob/fa5e5e36f32175baa67efae7f1f64e25b1eabdae/dotnet/webview2/WebView2%20Dispose/WebView2%20Dispose/Program.cs) when executed by Visual Studio 2022 (.NET 6) will start up more webview2 processes than executed directly.

Run via Visual Studio:
![image](https://user-images.githubusercontent.com/49561427/154996260-e77310bb-d40b-4201-850b-7aafaaa1f568.png)

Then, when the app is stopped, some of them are still running:
![image](https://user-images.githubusercontent.com/49561427/154996514-2241883f-1a1f-4695-a9bd-d572a8f656f3.png)

Run directly:
![image](https://user-images.githubusercontent.com/49561427/154996977-93b310ef-0e0c-4033-856e-83f730bbda65.png)

Then, if stopped, everything is fine:
![image](https://user-images.githubusercontent.com/49561427/154997155-44210314-67b2-41ac-8fbb-7ed00a5e5bda.png)

I double checked the entire process list, not running anywhere, so cleanup of all processes is done well on my system.

Hope this helps clarifying!

**Comment by champnic** [comment] 2022-02-28 23:11
@mwetzko The WebView2 processes you see under "devenv.exe > WebViewHost.exe" are because VS is using WebView2 itself to display UI. It's not directly related to the code you are running. Your WebView2 processes are children under "WebView2.Dispose.exe", and correctly get cleaned up when your app stops.

**Comment by yizhao5** [comment] 2022-08-18 02:07
> @champnic So I experimented around with disposal and no matter what I do I cannot get the WV to unload the browser processes.
> 
> Background: I'm using the WebView in WPF and it sits on a user control that gets loaded dynamically. The control gets added to a window, and I can see that the control is firing unload events so everything is working correctly from the WPF end of things.
> 
> However, when I close all of my editor and preview windows, the browser processes remain open.
> 
> I can't call Dispose() directly on the control because that causes problems as the control is getting disposed by WPF when the form/user control gets unloaded. Like you say this should be automatic except it doesn't appear to be happening. By explicitly calling dispose before it's ready to be disposed (ha) I end up with race conditions where the control things it's still alive when it's not. So this needs to happen as part of the standard release cycle of the framework I think.


@RickStrahl, Hello.

- Description:

Open multiple new windows in WPF and close them to only one left. It is found that the number of window instances or its class member WebView2 instances will not decrease.

- Cause Analysis:

After debugging and verification, I found that the WPF window instance may have been referenced all the time, which causes the GC to fail to recycle. This causes a memory leak.

Therefore, all references to some window instance need to be released before it is closed, so that the GC can recycle it. However, there may be more than one place where the window instance has been referenced. It may be user code or other places. For the continuous reference of the window instance, there is not only the WebView2 object of the user code, but also the Menu in the xaml. For WebView2 object, we can use Dispose() to release the reference. In addition, please check whether there is a problem with the Menu of the xaml. Thanks.

- Test Results:

The sample code [WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9367072/WpfApp1.zip) in the attachment can reproduce the continuous reference window instance problem of xaml Menu.
![image](https://user-images.githubusercontent.com/109595412/185276023-c1f67ab9-7019-4af4-9deb-e38f864b246e.png)
Fig. 1. Removing the Menu in xaml can release the window instance, otherwise it cannot.

**Closed** 2022-09-10 00:15 UTC
Labels: bug, tracked
