### ISSUE TITLE
The pages of google services are looped (not loaded) with a clean cache and a changed user agent.

### ISSUE THREAD

**Issue by Nuliax7** [MicrosoftEdge/WebView2Feedback#1988] opened 2021-12-04 15:50 UTC
**Description**
Strange browser behavior when working with google services.
Tested on 3 computers (win10 and win11). At the first start, without a formed cache and a custom user agent, the call to Google (or Youtube) is looped (err_too_many_redirects). If you do not specify the user agent, the google page is loaded. And restarting with an already formed cache is supported by another user agent. This behavior was only noticed on google services, several other sites load fine with the same actions. I am attaching a test program and netlog.

**Version**
SDK: 1.0.1083-prerelease
Runtime: 96.0.1054.43
Framework: WPF
OS: Win10, Win11

**Netlog and App**
https://drive.google.com/file/d/1vf085dckRi0aZ6sC2VrQH0nC-Vo8EsQl/view?usp=sharing
https://drive.google.com/file/d/1swRIQG8s7QDTUoAK8oEcY_e8rPI9jA6m/view?usp=sharing

[AB#37717773](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37717773)

**Comment by champnic** [comment] 2021-12-07 01:18
Hey @Kindles7 - thanks for the bug report! Do you see the same behavior if you use Chrome or the Edge browser (you can do this in the DevTools)? My guess is that this is not something specific to WebView2, but rather how the Google services are choosing to respond to the custom user agent string.

**Comment by Kindles7** [comment] 2021-12-07 10:20
@champnic , In other browsers, this behavior is not noticed, only with WebView2. For WebView2, I installed real, latest user agents copied from browsers (edge, chrome, firefox). If a clean start of WebView2 contains interference from the code into the user agent, then Google services are looped. 
I also noticed that if you open DevTools in WebView2, when the page has not loaded and open the same link through DevTools in a separate window, then everything starts working in WebView2.

![problem](https://user-images.githubusercontent.com/61284630/145011103-a7024944-695d-423a-a66d-ec91fbb31067.jpg)

Then I just refreshed the page in WebView2.
![result](https://user-images.githubusercontent.com/61284630/145011100-324e3617-7365-403a-8116-86c598a223ef.jpg)

**Comment by nirbil** [comment] 2021-12-14 13:39
I can confirm this is happening with different google services - google.com, youtube.com.
Also, I believe this is unrelated to the UserAgent and happens regardless of changing or leaving it as default.
If you load a webview2 with a clean cache and navigate to youtube.com, it will just fail.

**Comment by nirbil** [comment] 2021-12-15 09:46
This problem happens when you start with a clean environment and try to navigate to youtube or google.
I noticed however that sometimes after a few navigations it can get resolved, and once it's resolved it doesn't happen again until you restart with a clean environment. So probably cookies related?
Also, in my experiments user-agent manipulations don't resolve it.
Also, I wouldn't put it past Google that this is done purposefully to hurt Microsoft as part of the browser wars.

**Comment by nirbil** [comment] 2021-12-15 09:46
A temporary remedy for this is to navigate to http://accounts.google.com and to http://www.youtube.com/account, these pages work and enable subsequent navigation to youtube and google also to work, I'm guessing they are setting the right cookies or something.

**Comment by bhe-gtk** [comment] 2022-01-12 11:35
Is there any chance this will be fixed anytime soon?

**Comment by jasonstephen15** [comment] 2022-12-14 21:02
@bhe-gtk @nirbil @Nuliax7 - Can you please verify that you are still seeing this issue. We are trying to reproduce with no success.

**Comment by Nuliax7** [comment] 2022-12-15 17:38
@jasonstephen15 
I tried to reproduce it and also failed. I have a problem solved.

**Comment by bhe-gtk** [comment] 2022-12-16 09:38
@jasonstephen15
I cannot reproduce this either, seems to be solved. (WV 1.0.1293.44 + Edge 108.0.1462.46)

**Comment by jasonstephen15** [comment] 2022-12-16 15:24
Thanks. Sounds like this is not an issue anymore so closing the issue.

**Closed by jasonstephen15** 2022-12-16 15:24 UTC
Labels: bug, tracked
