### ISSUE TITLE
[Bug]: Method not found: Microsoft.Web.WebView2.Core.CoreWebView2Profile.remove_Deleted

### ISSUE THREAD

**Issue by leo-schick** [MicrosoftEdge/WebView2Feedback#4086] opened 2023-10-21 10:29 UTC
### What happened?

I implemented the WebView2 in a WPF application running on .NET 6 which throws the following exeption when I open the page where it is used:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/67712864/d76a9549-887a-467a-9658-6325c02e261c)

```Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2Profile.remove_Deleted(System.EventHandler`1<System.Object>)'.```

Full stack trace: 
```
 	Microsoft.Web.WebView2.Wpf.dll!Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async.__Init|0()	Unbekannt
 	[Wiederaufnehmen der asynchronen Methode]	
>	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.Web.WebView2.Wpf.WebView2.ExecutionContextCallback(object s) Zeile 287	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Zeile 183	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.Web.WebView2.Wpf.WebView2.MoveNext(System.Threading.Thread threadPoolThread) Zeile 324	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.Web.WebView2.Wpf.WebView2.MoveNext() Zeile 302	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask) Zeile 301	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.GetActionLogDelegate.AnonymousMethod__0() Zeile 438	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unbekannt
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unbekannt
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Zeile 183	C#
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(nint hwnd, int msg, nint wParam, nint lParam, ref bool handled)	Unbekannt
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(nint hwnd, int msg, nint wParam, nint lParam, ref bool handled)	Unbekannt
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unbekannt
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unbekannt
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(nint hwnd, int msg, nint wParam, nint lParam)	Unbekannt
 	[Übergang von Nativ zu Verwaltet]	
 	[Übergang von Verwaltet zu Nativ]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)	Unbekannt
 	PresentationFramework.dll!System.Windows.Application.RunDispatcher(object ignore)	Unbekannt
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window)	Unbekannt
 	****.dll!***.App.Main()	Unbekannt
```

After confirming the exception, the WPF application will open the page and the app is working fine.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

1.0.2045.28

### SDK Version

1.0.2045.28

### Framework

WPF

### Operating System

Windows 11

### OS Version

22621.2428 - 22H2

### Repro steps

I have this in a huge project, but I guess when doing the following steps, you will end up in this issue:

1. create a WPF project
2. bind the WebView2 into the main page
3. activate debug non-managed code
4. start the app

### Regression

No, this never worked

**Comment by leo-schick** [comment] 2023-10-21 10:30
p.s. a similar error has been reported in this issue: #3375 / but since it is closed and relates to a older version, I guess this was something already fixed...

**Comment by victorhuangwq** [comment] 2023-10-23 21:08
@champnic Seems like the problem in #3375 was addressed by you - the error thrown does look similar. Could this be a regression?

**Comment by champnic** [comment] 2023-10-24 20:42
Yes this looks like the same issue, closing as a duplicate.

**Closed by champnic** 2023-10-24 20:42 UTC
Labels: bug
