### ISSUE TITLE
Managing cookies

### ISSUE THREAD

**Issue by michalkania** [MicrosoftEdge/WebView2Feedback#84] opened 2019-11-28 15:08 UTC
Hey!
What I always need and want is a way to manage cookies:
- Ability to get them all at once (only the ones crated by the app's browser, nothing system wide). Temporary ones too (no expiration date, http-only etc.).
- Retrieve them by URI. 
- Adding my own. 
- Deleting a particular one.
- Deleting all for the URI
- Getting rid of all of them.

**Comment by david-risney** [comment] 2019-11-29 22:22
Thanks for the great feedback! This is a good one we definitely need to add. Can you elaborate on what you plan to do with this feature?

This is very similar to #4

**Comment by michalkania** [comment] 2019-11-30 07:05
Oh yes, you're right. I'm sorry, but I didn't notice this one somehow.

Long story short - I want a user to be able to continue working on a mobile exactly where he left off (one or multiple site sessions). I hope for Xamarin to have support for WebView2 - that would speed up things a lot.

If I'll have more to add I'll do it in #4

**Comment by gplwzz1989** [comment] 2020-07-24 03:34
What I always need and want is a way to manage cookies

please refer to the CEFSharp

**Comment by viktoriya-lysenko** [comment] 2023-11-09 21:52
We still need an API for deleting all cookies for the URI (#5 in the original bullet point list). When user logs off and we need to clear all cookies for particular URL without touching all the other cookies. There is a workaround which is first to get all the cookies for said URL and delete one by one, but performance is just horrible if there are a lot of cookies. This affects our customer.
ICoreWebView2CookieManager has a function DeleteCookies, but it takes a name (of the cookie) as a parameter and this parameter is required. We would like to be able to put nullptr there to be able to delete all the cookies.
There is also DeleteCookiesWithDomainAndPath function that has the same problem.
If there will be a different function without a name as a parameter that would also work of cause.

**Comment by nishitha-burman** [comment] 2023-11-09 22:02
Hi @viktoriya-lysenko have you looked at [issue #4](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4) which was marked as duplicate of the original issue? If that doesn't address your question can you please open a new github issue since the original post has various feature requests and is from 2019?

**Comment by viktoriya-lysenko** [comment] 2023-11-09 22:23
#4 is not addressing the problem we have. We have a workaround, but performance is really bad.

**Comment by viktoriya-lysenko** [comment] 2023-11-09 22:23
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4154 here is the new one.

**Comment by nishitha-burman** [comment] 2023-11-09 22:38
Closing as the new question is tracked in #4154.

**Closed by nishitha-burman** 2023-11-09 22:38 UTC
Labels: feature request
