### ISSUE TITLE
EnsureCoreWebView2Async from ContainsFullScreenElementChanged kills app with 0x80000003

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#3510] opened 2023-05-24 16:39 UTC
**Description**
Calling `EnsureCoreWebView2Async()` in a new window created within WebView2 `ContainsFullScreenElementChanged` event crashes the whole application, even with VS debugger attached and wrapped around try-catch.

### Event viewer:
Faulty module:  EmbeddedBrowserWebView.dll
Error code: 0x80000003
Offset: 0x00000000003bcf3d

**Version**
SDK: Nuget 1.0.1774.30
Runtime: Canary Version 115.0.1875.0
Framework: WPF
OS: Win 11

**Repro Steps**
First window:
```
public Window()
{
	InitializeComponent();
	Run();
}
async void Run()
{
	await webView.EnsureCoreWebView2Async();
	webView.CoreWebView2.ContainsFullScreenElementChanged += CoreWebView2_ContainsFullScreenElementChanged;
}
private void CoreWebView2_ContainsFullScreenElementChanged(object? sender, object e)
{
	var d = new Window2();
	d.ShowDialog();
}
```
Second window:
```
public Window2()
{
	InitializeComponent();
	Run();
}
async void Run()
{
	try
	{
		await webview.EnsureCoreWebView2Async(); // <--- Hard crash after 5-10 seconds
	}
	catch
	{
	}
}
```

**Screenshots**

**Additional context**
I can actively reproduce the crash. Opening window 2 outside of the event doesnt crash my app. If I close windows2 before it typically crashes and dispose the webview, my app doesn't crash. I've tried opening my window in UI thread with using Application.Currrent.Dispatcher.Invoke but that doesn't really matter / hasn't fixed the problem.

For each crash entry in event viewer there is always the same warning before it happens, might be related?!

```
The authorization settings for "application-specific" make the user "*REMOVED*" (SID: S-1-5-21-1875289390-106630000000000-1001) at the address "Localhost (using LRPC)" no authorization of the "Local activation" type for the COM server application with the CLSID
{2593f8B9-4EAF-457C-B68A-50F6B8EA6B54}
  and the appid
*REMOVED*
  granted in the application container "not available" (SID: not available). The security authorization can be changed with the administrative tool for component endings.
```

**Comment by LiangTheDev** [comment] 2023-05-26 17:24
This sounds like the reentrance issue discussed in https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#reentrancy.

We don't expect window2 to be able to initialize WebView2, and do expect the app to break into debugger after about 30s if one is attached. But don't expect it crash if running out of debugger. So, there might be something else going on. What is the stack of the crash?

**Comment by Symbai** [comment] 2023-05-27 05:03
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/14368203/3a65b9bf-5380-44d9-9f28-317e4883e7c7)

**Comment by LiangTheDev** [comment] 2023-05-30 17:51
The stack above is the expected break into debugger to warn developers about reentrance issue. Since the issue is now resolved for you, I am closing this issue.

**Closed by LiangTheDev** 2023-05-30 17:51 UTC
Labels: bug
