### ISSUE TITLE
Is it possible to make a silent installation of WebView2RuntimeX86

### ISSUE THREAD

**Issue by scar16** [MicrosoftEdge/WebView2Feedback#1487] opened 2021-07-02 07:20 UTC
Hi team,
I try to make a silent installation with 'MicrosoftEdgeWebView2RuntimeInstallerX86.exe /q /norestart' like I know it from other MS Installer, but I got this errorcode: 0x80040c01
What I have to do to make a silent installation possible. I do not find a hint in the web, how it is to do.
best regards
Arno

**Comment by scar16** [comment] 2021-07-02 08:15
Is there anywhere a description of the parameters what you can give to MicrosoftEdgeWebView2RuntimeInstallerX86.exe

**Comment by leonhsl** [comment] 2021-07-02 08:24
Try this?

> MicrosoftEdgeWebView2RuntimeInstaller{X64/X86/ARM64}.exe /silent /install

Also you can find more relevant information here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by scar16** [comment] 2021-07-02 09:54
Thanks a lot, this seems to work :-)
Do you know, if it is possible to get the errorcode of this command, because if I run it in this way it run's asynchron in background and I don't recognize, if it was successful or not.
So at least: Is it possible to run it synchron and get the exitcode back?

**Comment by cremor** [comment] 2021-07-02 18:29
It is a bug that the installer is exiting before the installation in complete. See #1349

**Comment by scar16** [comment] 2021-07-05 06:31
Thanks for the hint. I implement the workaround with the registry key, what seem's to work.

**Comment by leonhsl** [comment] 2021-07-06 01:55
Yeah checking the registry key is a workable solution for now.  Let me mark this one as a duplicate of #1349.

**Closed by leonhsl** 2021-07-06 01:55 UTC
