### ISSUE TITLE
Printing window cannot see all

### ISSUE THREAD

**Issue by laoniu2020** [MicrosoftEdge/WebView2Feedback#3798] opened 2023-09-20 07:03 UTC
**Description**
I am using WebView2 control to display webpages in my WinForms application.  The content is normal, but when call 
 webView.CoreWebView2.ShowPrintUI();
or 
webView.CoreWebView2.ExecuteScriptAsync("window.print();");
Can't see all the content.

**Version**
SDK:  1.0.2045.28
Runtime: 118.0.2088.9
Framework: 4.6
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/577581/93dbf01b-1f9f-4ee0-abc2-5565153405e3)
after click print button
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/577581/2ac2b72b-ce99-46b1-843f-0bdbe4cde91b)

edge dev browser open the url and print:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/577581/60a4663a-892c-4b04-aa34-c4e45edcf432)

[AB#46740922](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46740922)

**Comment by fvanheeswijk** [comment] 2023-09-27 12:00
We are experiencing the same issue, the print dialog is not correctly in view so the print button for example cannot be used.
It reproduces in our Windows Forms application when running Beta build 118.0.2088.17 of the WebView2 browser. It also reproduces with Dev build 119.0.2116.0. When running the Edge browser standalone it does seem to work correctly.

Can you confirm that you can reproduce this issue within a Windows Forms application and that it will be fixed in this beta version?

**Comment by laoniu2020** [comment] 2023-09-27 13:44
We encountered this problem on two machines and sidestepped it by installing the historical version. Which version will fixe this issue？

**Comment by johna-ms** [comment] 2023-09-28 03:17
Hello sorry for the delay in responding. I'm able to reproduce this and it looks legit. This may be related to a different dialog bug we've had. I will look into it and get back.

And thank you for testing on prerelease channels! This helps us catch issues before they get to stable.

**Comment by johna-ms** [comment] 2023-09-28 03:23
Confirmed this is a dupe of #3763. I'm closing this issue, you can follow for updates there

**Closed by johna-ms** 2023-09-28 03:23 UTC
Labels: bug, tracked
