### ISSUE TITLE
Popup a message box on the webview2 window, the message box can not close.

### ISSUE THREAD

**Issue by suihc** [MicrosoftEdge/WebView2Feedback#1543] opened 2021-07-19 05:40 UTC
**Description**

[WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6837903/WpfApp1.zip)
Popup a message box on the webview2 window, the message box can not close.
Expect:
The message box can close.
**Version**
SDK: WebView2 1.0.864.35
Runtime: WebView2 Runtime 91.0.864.54
Framework: WPF
OS: Windows 10

**Repro Steps**

1、Run the demo in attach
2、Click the blank area and enter F7 two or more times.
3、The message box can not close, and the application can not focus.

**Screenshots**
![webview2Bug](https://user-images.githubusercontent.com/54104006/126108206-d63cc22d-6ea2-479d-9c31-9b9f8a7cd1f4.png)
![webview2Bug2](https://user-images.githubusercontent.com/54104006/126108211-082b3dcc-6e57-44a8-956c-ba64ec60a270.png)

**Additional context**

**Comment by champnic** [comment] 2021-07-21 05:39
Hey @suihc - I believe your app is working as intended. Showing a message box is "modal", meaning that while it's open other app content can't be interacted with. The message box was able to be closed by pressing "OK" or the close button "X" when I ran your app. Is this not the behavior you expected?

**Closed by champnic** 2021-07-21 05:39 UTC
Labels: bug
