### ISSUE TITLE
[Bug] System.InvalidCastException error with Edge Canary version Version 88.0.670.0+

### ISSUE THREAD

**Issue by xxi123** [MicrosoftEdge/WebView2Feedback#535] opened 2020-10-14 15:27 UTC
I receive System.InvalidCastException when running my winform application. My application Target CPU x86, Target Framework: 4.7.2 . I tested it on Windows 10 x64 bit and Windows 7 x64 bit with Edge Canary version  88.0.670.0. Both of them has same System.InvalidCastException. Then, I try to uninstall Edge Canary and install Edge Dev with version 87.0.658.0 and then I don't receive System.InvalidCastException anymore. And on my other computer, I try to install Edge Dev with version 87.0.658.0 without uninstalling the Canary, I don't receive System.InvalidCastException too and when I uninstall the Edge Dev I receive that exception again.

Error message:
`System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2ExperimentalEnvironment'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{E01F1563-A31A-494E-BDF1-9C4E65373C19}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.CoreWebView2CreateCoreWebView2EnvironmentCompletedHandler.Invoke(Int32 errCode, ICoreWebView2Environment created_environment)'`

![Screenshot_2](https://user-images.githubusercontent.com/44320218/96009145-81af3e80-0e6a-11eb-8528-2505d880275a.png)

[AB#29810717](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29810717)

**Comment by DjSt3rios** [comment] 2020-10-14 16:47
I also have the same issue with this version. I guess we'll just have to wait for Microsoft to release a hotfix

**Comment by xxi123** [comment] 2020-10-14 18:19
Tested on Canary Version 88.0.671.0 still receive System.InvalidCastException

**Comment by champnic** [comment] 2020-10-14 18:28
Thanks for the report, I've filed a bug on our end to look into this! Sounds like the issue was recently introduced in a runtime update around 88.0.670.

In the meantime, you can continue development against Dev, Beta, or the WebView2 Runtime, all of which update at a slower cadence (though I imagine the next Dev release will probably run into the same issue :( )

**Comment by xxi123** [comment] 2020-10-14 18:31
Thank you for the response. I use the Dev version now and my application run without exception

**Comment by champnic** [comment] 2020-10-14 22:32
We've tracked down the issue and have a fix in the works. The cause was an update to the runtime/browser that needed to happen, but it exposed a couple of issues in our .NET SDK.  I'll update when we have the fix ready to deploy.

**Comment by champnic** [comment] 2020-10-19 20:49
This should be fixed in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). Unfortunately we weren't able to do a runtime fix for this, and so you'll have to upgrade the SDK from 0.9.628-prerelease. We will be marking that prerelease SDK as Deprecated and removing it shortly. Those of you on Dev and/or Beta will see this issue soon as the code moves through the runtime channels (when their version gets to 670+).

If this is still failing after updating the SDK please let us know. Thanks!

**Closed by champnic** 2020-10-19 20:49 UTC
Labels: bug, tracked
