### ISSUE TITLE
Unable to respond to mouse messages under windowless mode

### ISSUE THREAD

**Issue by mulintong** [MicrosoftEdge/WebView2Feedback#1955] opened 2021-11-23 07:45 UTC
**Description**

When document opened, the mouse is always an arrow and cannot scroll the wheel.
Is works normally when use runtime 95.0.1020.53, but no affects when use runtime 96.0.1054.29.

**Version**
SDK: 1.0.1020.30
Runtime: 96.0.1054.29
Framework: Win32
OS: Win10

**Repro Steps**
Use https://github.com/MicrosoftEdge/WebView2Samples/commit/e23e8dca306489806f456749be33b25bfb5570d8
Manually switch the runtime version 95.0.1020.53 and 96.0.1054.29. Stable appearance.
It seems that it can be restored to normal after clicking other positions of the window. 

**Screenshots**

**Additional context**

[AB#37203247](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37203247)

**Comment by champnic** [comment] 2021-11-24 01:41
@mulintong Hey Tony - could you add some details to the repro steps?

* Which sample app are you running, the WebView2ApiSample?
* Are you clicking any buttons or doing other setup in the sample app?
* When do you expect the mouse to not be an arrow but are seeing the arrow?

Thanks!

**Comment by mulintong** [comment] 2021-11-24 03:17
@champnic Hey Champnic.

Yes, I use the WebView2APISample.vcxproj.  Afater run the sample app, click Menu - [Window] - [WebView Creation Mod] - [Visual DCom] , then Menu - [Window] - [Create WebView].

When the mouse is over a hyperlink in the web page, it should be a hand rather than still an arrow. Of course, mouse scrolling should work directly, but nothing happens.

Thanks!

**Comment by kingcean** [comment] 2021-11-29 09:58
@champnic Hi Champnic,

This is not only about how mouse cursor is presented (like a hand or pointer), but the root cause is also that user cannot click/tap the clickable element, e.g. hyperlink, in _windowless_ mode of WebView2. The version of Microsoft Edge is 96.0.1054.29. You can repro this by running WebView2ApiSample.

F.Y.I this worked correctly when the version of Microsoft Edge was 95.0.1020.53.

**Comment by champnic** [comment] 2021-11-29 22:12
I've added this bug to our backlog and we'll take a look right away. Thanks!

**Comment by champnic** [comment] 2021-11-30 00:52
We have a fixed checked in and it should be going out with the stable runtime update around end of week. You should be able to verify using the Canary channel that the issue is resolved. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Closed** 2023-03-04 05:50 UTC
Labels: bug, tracked
