### ISSUE TITLE
CTRL+F dialog breaks window focus

### ISSUE THREAD

**Issue by dmex** [MicrosoftEdge/WebView2Feedback#1225] opened 2021-04-27 06:48 UTC
Opening the find dialog using CTRL+F steals focus from the application window and does not return focus to the application window after pressing ESC or when manually closing the find dialog using the X button as seen here:

This is espeically problematic when hosting the browser inside a Win32 Tab Control/MDI window as users are forced to manually refocus the window to preform other actions.

This can be easily reproduced using the [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/):
![image](https://user-images.githubusercontent.com/1306177/116196827-4ecdf780-a777-11eb-9658-5bf43226da70.png)

**Version**
SDK: 1.0.818.41
Runtime: 90.0.818.46
Framework: Win32
OS: Win10

[AB#32972107](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32972107)

**Comment by champnic** [comment] 2021-04-29 19:48
Thanks for the bug report @dmex! I've added it to our backlog to get fixed.

**Comment by frankdekker** [comment] 2021-11-22 20:59
@champnic 
For us this is on of the last issues before we can deploy our application to our customers. Any timeline for a fix, or even better a Find API for this?

**Comment by champnic** [comment] 2022-03-10 23:15
This should be fixed in runtimes 100.0.1177.0+. Thanks!

**Comment by RendijsSmukulis** [comment] 2022-05-13 08:20
This doesn't appear to be solved, or there's a different identical issue. Am running a newer runtime (101.0.1210.39), with latest pre-release SDK (1.0.1248-prerelease).

The best repro I could find is pressing Ctrl+F when focus is on WebView2, then clicking the app's title bar just above the find dialog. After that, the app stops responding to any keyboard or mouse inputs. See attached video.

https://user-images.githubusercontent.com/4180387/168241914-c7a09b5a-8057-4939-8318-42a6c98386a2.mp4

**Comment by champnic** [comment] 2022-05-13 18:25
@RendijsSmukulis We're still looking into the "Find on Page hang" bug. We are tracking the investigation in #1889.

**Comment by champnic** [comment] 2022-08-16 21:01
This is now fixed in 105.0.1323.0+. We had to revert the previous fix due to a regression.

**Closed by champnic** 2022-08-16 21:01 UTC
Labels: bug, tracked

**Comment by frankdekker** [comment] 2022-09-01 12:10
Hi @champnic  Should this be fixed in 106.0.1368.0 canary? I can still reproduce the issue in our application. Using versions:

Windows: 10
.Net version: 6.0.6
WebView2 version: 1.0.1340.0
MS Edge version: 106.0.1368.0 canary

^ above information from the dll

Steps:
1) basicly start application with 1 WebView2 instance
2) start a search with CTRL+F
3) with the **mouse** select a different window (from another application) so the application loses focus.
4) click back to the original application
5) >> application can't regain focus anymore

Pressing alt+tab away and to the application restores the problem and then ctrl+F works fine for quite some time.
