### ISSUE TITLE
Running as admin fails with COMException (0x80070490)

### ISSUE THREAD

**Issue by wilsonmfg** [MicrosoftEdge/WebView2Feedback#1981] opened 2021-12-02 15:13 UTC
Run as regular user works, Right-Click and Run as Administrator gives a COMException.  It's not a file system permissions issue that I can tell. I'm using the Fixed version runtime to narrow this down.

**Version**
SDK: 1.0.1054.31, but it's been an issue since the 0.9.x and maybe older
Runtime: FixedVersionRuntime.96.0.1054.41.x86, but also older and x64
Framework: .NET Framework 4.7.2
OS: Win10, Win7, latest Windows Updates, and all older

**Exception**
```
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
```

Below is a test form, download the latest Fixed Runtime from https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section, extract following the instructions at https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-fixed-version-runtime-distribution-mode

Update the code below with the path to what you extracted

```
using Microsoft.Web.WebView2.Core;
using System.Windows.Forms;

    public partial class Form1 : Form {
        private Microsoft.Web.WebView2.WinForms.WebView2 webView;
        public Form1() {
            InitializeComponent();
            webView = new Microsoft.Web.WebView2.WinForms.WebView2();
            ((System.ComponentModel.ISupportInitialize)(webView)).BeginInit();
            webView.Dock = DockStyle.Fill;
            Controls.Add(webView);
            ((System.ComponentModel.ISupportInitialize)(webView)).EndInit();

            AttachControlEventHandlers();
        }

        void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e) {
            if (e.IsSuccess) {
                webView.CoreWebView2.Navigate("http://microsoft.com");
                return;
            }
            MessageBox.Show($"WebView2 creation failed with exception = {e.InitializationException}");
        }

        private void AttachControlEventHandlers() {
            var webView2Environment = CoreWebView2Environment.CreateAsync(@"C:\path\to\Microsoft.WebView2.FixedVersionRuntime.96.0.1054.41.x86").Result;

            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
            webView.EnsureCoreWebView2Async(webView2Environment);
        }
    }
```

Running Edge as admin does work, what does it take to be able to run WebView2 apps as admin?  I'm aware of the security implications, my use case is for intranet and local file content and so those concerns do not apply.

**Comment by MarkusSchreiner** [comment] 2022-07-01 08:25
I've got a very similar issue last year (2021) with WebView2 when my application was started "as Administrator".
Right now, I tried it again and now it worked.
Was this issue fixed by the WebView2-developers?

**Comment by wilsonmfg** [comment] 2022-08-30 16:49
I just tried with the "latest" and it seems to be working now.  would be nice to know what version fixed it, but as of now it might be fixed, or just temporarily working due to a different bug or side effect.

**Comment by ChenXiao-001** [comment] 2022-09-14 12:03
I tried the 'latested' but still doesn't work.

**Comment by sln162** [comment] 2022-12-27 18:21
Now this problem is encountered by several users' machines every day. Restarting the resource manager can help him solve it, but some machines need 30 seconds or even longer to recover.

**Comment by LiangTheDev** [comment] 2023-05-10 16:37
Closing this one. It is the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/2984. Basically, we make some improvements, but the issue is not totally resolved.

**Closed by LiangTheDev** 2023-05-10 16:37 UTC
Labels: bug
