### ISSUE TITLE
Tab key moves to next visible WebView2

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#718] opened 2020-12-08 09:17 UTC
### Not sure if this is by design:

If you have more than one WebView2 visible (in my case with same UserDataFolder), tabbing from the last active element, moves to the next visible WebView2.

If you hide the next WebView2, it stops at the last active element, and doesn't cycle round the same page (shift tab has the same behaviour).

[AB#31012791](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31012791)

**Comment by champnic** [comment] 2020-12-08 20:05
We recently ran into #686 which seems similar. My gut feeling is that this isn't by design, so I'll open a bug for us to double-check. Thanks!

**Comment by tofuandeve** [comment] 2021-01-27 21:48
@ukandrewc Hi, I'm working on fixing this bug. Could you clarify which app this bug happened on? I was able to get it to repro on WinForms app but not WPF, just want to double check to make sure we don't miss out any detail! Thanks!

**Comment by ukandrewc** [comment] 2021-01-28 09:40
@tofuandeve Yes, it was Winforms, haven't tried in anywhere else.

**Comment by champnic** [comment] 2021-03-25 20:32
This should be fixed in the 1.0.824-prerelease SDK. Please give it a try and let us know if you run into any further issues. Thanks!

**Closed by champnic** 2021-03-25 20:32 UTC
Labels: bug, question, tracked
