### ISSUE TITLE
Cancelling events with subsequent redirects is not working

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#576] opened 2020-10-26 12:52 UTC
## Description
When catching the NavigationStarting we are presented with the option to cancel the event, which should lead to the browser staying at the current address. But if the navigation is part of a redirected flow, the cancel event does have an effect.

## Version
SDK: 1.0.674-prerelease
Runtime: 88.0.673.0 (Official build) dev (64-bit)
Framework: WPF
OS: Microsoft Windows 10 Pro, 10.0.18363 Build 18363

## Repro Steps
I have produced a minimal working example to show the problem:

**MainWindow.xaml**
```
<Window x:Class="TestWebView2App.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="800" Width="1000">

  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
      <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>

    <Button Content="Navigate back to start"
            Click="Button_Click" />

    <wv2:WebView2 Name="WebView"
                  Grid.Row="1"
                  Source="XXX\LinkExamples.html" />

    <ScrollViewer Height="150"
                  Grid.Row="2">
      <TextBox x:Name="WebViewEvents" 
               Text="*** EVENT OVERVIEW ***"
               Foreground="OrangeRed"
               Background="Black"
               IsReadOnly="True" />
    </ScrollViewer>

  </Grid>
</Window>
```

**MainWindow.xaml.cs**
```
using System;
using System.Windows;

namespace TestWebView2App
{
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();

      WebView.CoreWebView2Ready += WebView_CoreWebView2Ready;
    }

    private void WebView_CoreWebView2Ready(object sender, EventArgs e)
    {
      WebView.NavigationStarting += WebView_NavigationStarting;
      pdfAddress = WebView.Source;
    }

    private void WebView_NavigationStarting(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs e)
    {
      if (e.IsUserInitiated)
      {
        e.Cancel = !e.IsRedirected;

        WebViewEvents.Text += Environment.NewLine + $"Navigation to '{e.Uri}', is from user: '{e.IsUserInitiated}', is redirected: {e.IsRedirected}, is cancelled: {e.Cancel}";
      }
    }

    private Uri pdfAddress = new Uri("http://google.com");
    private void Button_Click(object sender, RoutedEventArgs e)
    {
      WebView.Source = pdfAddress;
    }
  }
}
```

**LinkExample.html**
```
<html>
	<body>
		Here is a link that will cause some redirects: <br />
		<a href="http://microsoft.com">http://microsoft.com</a>
	</body>
</html>
```

## Extra / Helpful 
Before navigating:
![image](https://user-images.githubusercontent.com/47817657/97173896-90aebe80-1791-11eb-8492-4317a07f543c.png)

After navigation, I did not expect the two last calls to be made, as they are descendants of the original call that got cancelled:
![image](https://user-images.githubusercontent.com/47817657/97173924-9b695380-1791-11eb-8da8-86d2b81c2d5b.png)

After navigation where e.IsCancelled is always set to true instead of being conditional on e.IsRedirected. I did not expect to navigate away from the 'LinkExamples' since all the events has been marked for cancelling:
![image](https://user-images.githubusercontent.com/47817657/97173992-b8058b80-1791-11eb-8066-76c5398d7d55.png)

[AB#29999399](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29999399)

**Comment by cbra-caa** [comment] 2020-10-26 12:53
Might potentialle be related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/400 where cancelling the event has no effect either.

**Comment by dmcgloin** [comment] 2020-10-28 06:15
Upvote for addressing this bug. Thank you

**Comment by pagoe-msft** [comment] 2020-10-28 21:06
@cbra-caa 

This is definitely a bug. We will investigate!

**Comment by champnic** [comment] 2020-11-02 21:57
This is probably a dupe of #560 - the fix will be available in the next SDK release. Can you try without redirects? My guess is you'll find the same broken behavior. If so I'll close this issue and we'll track the fix in #560.

**Comment by cbra-caa** [comment] 2020-11-04 08:41
Yeah, its the same behavior without the redirects (dupplicate of #560). 
You can close this one ;)

**Closed** 2020-11-04 18:35 UTC
Labels: bug, tracked

**Comment by dmcgloin** [comment] 2020-11-24 18:17
@cbra-caa Hello, wondering if you've tried 1.0.707-prerelease? For me, this issue is still happening.
