### ISSUE TITLE
WmiPRVSE.EXE high CPU

### ISSUE THREAD

**Issue by brianclink** [MicrosoftEdge/WebView2Feedback#1233] opened 2021-04-28 00:49 UTC
We use webview2 to embed an edge browser in our application.  We have been running this in-house without any issue.  It also has been deployed to multiple sites without an issue.  One client is experiencing periodic high CPU of WmiPRVSE.EXE process, and is using our application on an RDSH server.  When our application's process is ended, the high CPU ends immediately.  This same client also receives Event Log messages complaining about some WMI requests failing (see below), and the process ID points back to one of the webview2 Edge Browser instances.

Id = {00000000-0000-0000-0000-000000000000}; ClientMachine = XXXX; User = XXXX; ClientProcessId = 135044; Component = Unknown; Operation = Start IWbemServices::ExecQuery - root\cimv2 : SELECT * FROM Win32_OperatingSystem; ResultCode = 0x800706BE; PossibleCause = Unknown

I obtained three dumps of the WmiPRVSE.EXE process while it was generating a high CPU, and it had about 15 threads in NtQuerySystemInformation (from WmiPrvSE.exe!CInterceptor_IWbemSyncProvider::ExecQueryAsync).  The system has over 1 million total handles.  The client could not locate one process that has a large number of handles.  The client confirmed that Costly performance counters are not enabled.  I searched the memory of the dump and found about 18 instances of the string "Select * from Win32_ComputerSystem where DomainRole=1", not sure if this is the actual active query being performed at the time of the dump, or if stale strings.

Is there something that the Edge webview2 browser control could be doing to cause WMI high CPU?

[AB#32977061](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32977061)

**Comment by brianclink** [comment] 2021-04-28 14:18
Just a note that we are backlevel, currently running 89.0.774.50, we will be updating to the latest and will retry - wondering if anything that could have been related to our high CPU WMI issue was fixed in the meantime.

**Comment by brianclink** [comment] 2021-04-29 15:06
We are still working on updating to the latest webview2 control.  In the meantime the client is using a configuration option to use an external browser instead of the embedded browser, and as a result the high CPU WMI is not occurring anymore, which ties the high CPU WMI to the use of the embedded webview2 browser.  Hope to get some feedback as to how the embedded browser uses WMI and why it could be triggering a high CPU in the WmiPRVSE.EXE process.

**Comment by champnic** [comment] 2021-04-29 23:23
Hey @brianclink - thanks for the report. Does your client experience the same high CPU usage when launching either Google Chrome or Microsoft Edge? Can you share the command line of the process that's failing the WMI calls so we can see what type of runtime process it is?

I do see some WMI usage in our codebase, but none of it is querying from Win32_OperatingSystem, and the only query I see for Win32_ComputerSystem is "SELECT HypervisorPresent FROM Win32_ComputerSystem". I'm definitely not an expert though so I'll reach out on our team to see if I can find out more. Thanks!

**Comment by brianclink** [comment] 2021-05-03 22:33
We have a configuration option to use the external browser (Edge) instead of the embedded browser, and they have been running with this option and not experiencing the high CPU.  I don't have the specific command-line for the process at this time.  I will have to circle back to the client to gather additional information - is there additional troubleshooting tips for determining the source for the high WMI CPU?

**Comment by champnic** [comment] 2021-05-04 17:31
Thanks for the added info. It looks like we have a change a couple of weeks ago that disables our WMI calls altogether, so you could have your client try out the latest Microsoft Edge Canary/Dev builds instead of the stable WV2 Runtime and see if the issue gets resolved.

It also sounds like you should be able to use [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see what is running inside of WmiPRVSE.exe. This might be helpful in determining what's happening inside the WmiPRVSE.exe that's spiking CPU:
![image](https://user-images.githubusercontent.com/45700886/117044928-ccd45600-acc3-11eb-8eeb-b93e5c511237.png)

Thanks!

**Comment by brianclink** [comment] 2021-05-12 19:56
We did enhance our application to be able to use the Dev version of webview2 so that we could test with it.  We used to get intermittent errors in event log regarding WMI but now those have ceased, so it was a good sign that something changed, and we are hopeful that the high CPU issue will go away - although we don't have direct evidence of what is causing the high CPU.  We did not have an opportunity to check that high CPU process as you show above, the client doesn't want to experience the high CPU on their production server, and we have not been able to reproduce this on our end.

We did work with the client today, to install Edge Dev onto their production RDSH server, but we could not proceed to test our application as they were uncomfortable once they determined that shortcuts on the server were opening Edge Dev despite our assurances that nothing would change.  So Edge Dev was immediately removed.

They will (hopefully) wait until the general release of a new WebView2 that includes those 'fixes' (WMI calls were removed).

Now the question is when will it happen?  When will there be a newer general release of WebView2 that includes the code that removed the WMI calls?

Thank you!

**Comment by champnic** [comment] 2021-05-12 22:57
@brianclink That's understandable, thanks for the follow-up! The WMI change will ship to stable with WebView2 Runtime 91+, which should be around the end of May (week of the 24th).

**Comment by brianclink** [comment] 2021-05-13 14:19
Thanks @champnic for your assist, we look forward to using the new release when it becomes available.  I also hoping that the everygreen bootstrapper will bring down that new stable 91+ release once it is available, we will look out for that.

**Comment by brianclink** [comment] 2021-05-27 12:56
Thanks for mentioning the other issue, but I don't think our client is seeing this.  Our client is only seeing high CPU on the WmiPRVSE.EXE process.  We have setup our own RDSH server and unable to reproduce a high CPU on WmiPRVSE.EXE on either old or new (dev) webview2 versions.

**Comment by brianclink** [comment] 2021-06-01 16:05
We had a call with the client today, and unfortunately we were still seeing high CPU of WmiPRVSE.exe and there were WMI Activity event logs pointing back to the webview2 process, which seems to indicate that the webview2 is still using WMI.  I will include some screen captures here and event log snippets shortly.  The webview2 that was installed (evergreen) by the client today is v91.0.864.37, although the one we had tested in our lab was  v90.0.818.66.

**Comment by brianclink** [comment] 2021-06-01 16:30
We saw an error in event log WMI-Activity event ID 5858: Id = {00000000-0000-0000-0000-000000000000}; ClientMachine = XXXXX; User = XXXXX; ClientProcessId = 36312; Component = Unknown; Operation = Start IWbemServices::ExecQuery - ROOT\CIMV2 : SELECT HypervisorPresent FROM Win32_ComputerSystem; ResultCode = 0x80041032; PossibleCause = Unknown, and the ClientProcessId pointed back to a webview2 process that had already exited (we used process start auditing in group policy to track process creation).  I found an article related to this, but not sure if has anything to do with high CPU, but the WMI return code 0x80041032 may be caused by not enumerating full result set from WMI call: https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/wmi-activity-event-5858-logged-with-resultcode-0x80041032 . I will follow-up with additional info / screen captures.

**Comment by brianclink** [comment] 2021-06-01 17:50
![2021-06-01-10_54_48-Audit-Process-Creation](https://user-images.githubusercontent.com/4602264/120368057-9a784180-c2df-11eb-81ae-f3a64d37c718.png)
![wmi-error](https://user-images.githubusercontent.com/4602264/120368487-20948800-c2e0-11eb-8cf5-1b98e073c66c.png)
PID 36312 (decimal) = 0x8dd8 (hex)

**Comment by brianclink** [comment] 2021-06-01 22:01
We were able to reproduce the high CPU in WMI in our labs based on our work this morning with the client.  After further investigation, we unexpectedly found a WMI call in our code that was being called frequently when used on a shared server with multiple users logging on.  Although it looks like webview2 still uses WMI calls, and the WMI event log error entries were pointing to instances of the webview2 control, this led us in the wrong direction and I believe now that the high CPU originated from a code issue in our application.  I will follow-up if we still need help with webview2 related to WMI, but I think this one will be resolved by us.

**Comment by champnic** [comment] 2021-06-01 22:16
That's great news, thanks for the investigation here @brianclink, and glad you found a root cause (hopefully). I'll close this issue for now, but please let me know if you still believe the CPU is originating from WebView2. Thanks!

**Closed by champnic** 2021-06-01 22:16 UTC
Labels: bug, tracked
