### ISSUE TITLE
Chrome DevTools Protocol Fetch.enable cannot receive RequestPattern parameters - System.ArgumentException

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftEdge/WebView2Feedback#2842] opened 2022-09-30 22:41 UTC
**Description**
I would like to call `Fetch.EnableAsync()` method with a `RequestPattern` parameter but I got an error:

> Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll but was not handled in user code
Value does not fall within the expected range.

**Version**
SDK:  WebView2: 1.0.1343.22, WebView2.DevToolsProtocolExtension: 1.0.824
Runtime: 
Framework:  WPF
OS:  Win11, 22H2

**Repro Steps**

I have some code like this:
```csharp
private DevToolsProtocolHelper devToolsProtocolHelper;
devToolsProtocolHelper = webView.CoreWebView2.GetDevToolsProtocolHelper();
...
var patterns = new RequestPattern[] { new RequestPattern { RequestStage = "Response" } };
// The below line throws an exception
await devToolsProtocolHelper.Fetch.EnableAsync(patterns);
// Also tried the code below but got the same error:
await webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.enable", JsonSerializer.Serialize(patterns));
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3395915/193365773-e24e190b-ec1e-4ac3-9481-61f674601ba4.png)

**Additional context**

[AB#41812449](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41812449)

**Comment by chinasmu** [comment] 2022-10-03 06:43
In my winform app, I try this
` await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.enable", "{\"patterns\":[{\"urlPattern\":\"*\", \"requestStage\":\"Response\"}]}");`

It working good.
About "RequestPattern[]", is it form CefSharp Common? I did not see any ref in webView2.

**Comment by victorthoang** [comment] 2022-10-03 18:48
Hello @yanxiaodi ,

I have assigned this to @imicy, who will help figure out how to approach the bug you're seeing. Thanks for your find!

**Comment by yanxiaodi** [comment] 2022-10-08 00:25
@chinasmu Thanks. I think I got it.

@imicy @victorthoang So if we call the method like 
```
await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.enable", "{\"patterns\":[{\"urlPattern\":\"*\", \"requestStage\":\"Response\"}]}");
```
It works. Because the parameter is an object that has a `patterns` field, which has the array as the value. But if we call the method like 
```
var patterns = new RequestPattern[] { new RequestPattern { RequestStage = "Response" } };
// The below line throws an exception
await devToolsProtocolHelper.Fetch.EnableAsync(patterns);
```
The parameter is an array, not an object that has a `patterns` field.

**Comment by yanxiaodi** [comment] 2022-10-14 04:01
That's not an intuitive way to use this API. As a user, when I use `await devToolsProtocolHelper.Fetch.EnableAsync(patterns);`, the parameter has the `RequestPattern[]` type. Users would not know why it needs a `ExpandoObject`.

I think that's an error of the wrapper?

**Comment by yunate** [comment] 2022-10-18 09:26
@yanxiaodi thanks for your suggestion.
About `Users would not know why it needs a ExpandoObject.` The reason is the `CallDevToolsProtocolMethodAsync` require its json string param must like `{"patterns":[{"urlPattern":"","resourceType":"","requestStage":"Response"}]}`.

About `can change the parameter type for this API`, we will talk about this with our team, but the origin API will be retained for version compatible.

**Comment by champnic** [comment] 2022-11-21 23:51
The format of CDP API is outside the scope of WebView2 and is currently By Design.

**Closed by champnic** 2022-11-21 23:51 UTC
Labels: bug, tracked
