### ISSUE TITLE
Using of WPF execution assemblie separately from WebView2 assemblies

### ISSUE THREAD

**Issue by LightDiode** [MicrosoftEdge/WebView2Feedback#227] opened 2020-05-28 10:19 UTC
I need to store my exe file separately from dlls, and with common dotnet assemblies with a strong name I can use GAC for this purpose. How can I deal with WebView2 assemblies?

**Comment by LightDiode** [comment] 2020-05-28 11:30
There are 3 .net assemblies without a strong name in build folder:
- Microsoft.Web.WebView2.Core.dll
- Microsoft.Web.WebView2.WinForms.dll
- Microsoft.Web.WebView2.Wpf.dll

And one assembly which is not .net:
- WebView2Loader.dll

**Comment by david-risney** [comment] 2020-05-28 19:58
Thanks for the feedback! Yes we need to give the .NET assemblies strong names. 
Duplicate of #181 

For the loader DLL though we don't have a great solution. Can you describe your scenario more about why you need to store your exe separately from your dlls? Thanks!

**Comment by david-risney** [comment] 2020-05-28 19:58
Duplicate of #181

**Comment by mikemeinz** [comment] 2020-05-28 20:08
I store DLLs with my .NET exe. I deploy using Publish (ClickOnce) feature of Visual Studio where the assemblies are signed using a Strong Name Key File. Needs all DLLs to be Strong Named.

**Comment by LightDiode** [comment] 2020-05-28 23:09
When I need to use an application from the folder where I cannot store any additional files. For example when I call wpf application from credential provider, and I need to store exe near of CP dll

**Closed** 2021-12-02 04:53 UTC
Labels: bug, .NET
