### ISSUE TITLE
WinForms: Unable to focus WebView2 when it's the only focusable control on a form

### ISSUE THREAD

**Issue by billybooth** [MicrosoftEdge/WebView2Feedback#397] opened 2020-08-19 20:54 UTC
As discussed in #185, which appears to be related, when the WebView2 is the only focusable control on a WinForms form, the inner Chromium window cannot receive input focus either programattically via `WebView2.Focus()` or via the keyboard/tab stops.

This issue is present in the 0.9.579 prerelease and can easily be replicated by simply removing (or disabling) all of the focusable controls except the `WebView2` from the [WebView2Samples](https://github.com/MicrosoftEdge/WebView2Samples) WinForms sample.

Not a huge deal (can be worked around), but just wanted to let you know.  Thanks again for all the work you're doing on this.  Very much looking forward to being able to leverage a modern web view!

[AB#28588555](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28588555)

**Comment by pagoe-msft** [comment] 2020-08-20 03:37
@billybooth

Thanks so much for pointing this out! Out of curiosity, could you give us some context on what you're building and what scenarios this could potentially be an issue?

I've filed a bug for us to investigate further!

**Comment by billybooth** [comment] 2020-08-20 03:52
I acknowledge it's probably not a common scenario to have a WebView2 on a form with no other focusable controls, but the initial work I'm doing with it involves the end-user needing to authenticate against an external/upstream identity provider.  We basically present an authentication dialog containing only a `WebView2` similar to the ones presented, by say Visual Studio or GitHub Desktop on Windows:

![](https://user-images.githubusercontent.com/1764319/29399339-1e3f39b0-8329-11e7-868a-4d406c7cdfd4.png)

Such a scenario where the user is dropped into a WebView with default inputs makes the focus problem very apparent.

**Comment by ShaunLoganOracle** [comment] 2020-08-20 17:50
I have a similar use case as @billybooth - using a window/form with only a WebView2 control for authenticating via 3rd party web apps.

**Comment by billybooth** [comment] 2020-08-20 17:54
@ShaunLoganOracle, it's working beautifully for us, btw, although the discussion in [#374](https://github.com/MicrosoftEdge/WebViewFeedback/issues/374#issuecomment-677635773) is making me a bit nervous.

**Comment by jamesoli** [comment] 2020-12-10 19:38
@billybooth I'm currently trying to reproduce the issue but not exactly sure what your app is doing. I took the WebView2Samples app, stripped out everything besides the webview, and navigated to a simple page with a form and it had focus.

Can you describe in a little more detail about how you're trying to set focus? For example, is it through JavaScript or through C#?

**Comment by billybooth** [comment] 2020-12-10 22:10
@jamesoli, thanks for getting to this one.  I haven't updated my own project in a bit, but I just pulled `1.0.721-prerelease` into the `WebView2WindowsFormsBrowser` from the `WebView2Samples` and find that the issue reported here is fixed.  Previously, unless you used the mouse to click on the webview2, you could not put keyboard focus into the DOM (via the tab key or focusing the webview2 control via C#) at all when the webview2 was the only control on a form.  That no longer appears to be the case.  👍 

That said, in `1.0.721-prerelease`, there are still some apparent focus issues.  For example, in the vanilla WebView2Samples app with all of the controls on the form, attempt to set keyboard focus to the search input element (it has an autofocus attribute) of https://www.bing.com/ without using the mouse or JavaScript.  Tabbing into the webview2 control or setting focus to the webview2 control programmatically via C# should set the keyboard focus to the default input.  When I focus the control, I get accelerator key events but I can't get to the DOM without tabbing into it.  The basic problem I have is that I would like the webview2 control, when focused, to behave like the Edge browser with respect to keyboard input focus, i.e., when I navigate to a page, I would like the default form input to be focused as it is in a proper browser, and that simply isn't the case through `1.0.721-prerelease`.

Thanks again for your time and consideration on this one!

**Comment by billybooth** [comment] 2020-12-11 17:18
One aside noted in this issue report was the loss of input focus when a form containing a `WebView2` is deactivated and then reactivated.  That still occurs in the vanilla `WebView2Samples`; if you put focus on the search input element of https://www.bing.com/, then deactivate the `BrowserForm` and subsequently reactivate it, keyboard focus is not restored to the previously focused input element.  In this case, the `WebView2` gives up control focus entirely.  I could file a new issue if you'd like, but it seems that all of these focus issues are pretty closely related and should be rolled into #721.

**Comment by jamesoli** [comment] 2020-12-16 22:57
You're right that currently when the WebView2 control is focused, it doesn't auto focus by default. This is due to how we host the actual content for the WebView.

In Win32 world, we have an API called [Move Focus](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller?view=webview2-1.0.664.37#movefocus) that does what you're describing.

For WinForms, I think we should have some way for the actual content of the WebView to be able to get focus. My thought is that webView2Control.Focus() should just work and do what you're describing. This would require us to do some underlying work.

There are other options like bringing over the MoveFocus API but I'm not hot on that option.

**Comment by champnic** [comment] 2021-01-30 01:54
This should be fixed in the 1.0.781-prerelease package. Thanks!

**Closed by champnic** 2021-01-30 01:54 UTC
Labels: bug
