### ISSUE TITLE
Visual Studio 2015 Code Analysis emits warning C28251 for WebView2.h  

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebView2Feedback#55] opened 2019-10-07 16:47 UTC
The warnings are:

\packages\microsoft.web.webview2.0.8.270\build\native\include\webview2.h(5679): warning C28251: Inconsistent annotation for 'HWND_UserSize': this instance has no annotations. See c:\program files (x86)\windows kits\8.1\include\um\oleidl.h(3900). Note: There are several prototypes for this function. This warning compares the first with instance number 7. 

\packages\microsoft.web.webview2.0.8.270\build\native\include\webview2.h(5680): warning C28251: Inconsistent annotation for 'HWND_UserMarshal': this instance has no annotations. See c:\program files (x86)\windows kits\8.1\include\um\oleidl.h(3901). Note: There are several prototypes for this function. This warning compares the first with instance number 7. 

\packages\microsoft.web.webview2.0.8.270\build\native\include\webview2.h(5681): warning C28251: Inconsistent annotation for 'HWND_UserUnmarshal': this instance has no annotations. See c:\program files (x86)\windows kits\8.1\include\um\oleidl.h(3902). Note: There are several prototypes for this function. This warning compares the first with instance number 7. 

\packages\microsoft.web.webview2.0.8.270\build\native\include\webview2.h(5682): warning C28251: Inconsistent annotation for 'HWND_UserFree': this instance has no annotations. See c:\program files (x86)\windows kits\8.1\include\um\oleidl.h(3903). Note: There are several prototypes for this function. This warning compares the first with instance number 7. 

[AB#23648678](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/23648678)

**Comment by pagoe-msft** [comment] 2019-10-07 18:51
Hi dd8,

Thanks so much for the feedback! We are looking into it on our end and get back to you.

Best, 
Palak

**Comment by pagoe-msft** [comment] 2020-01-06 19:37
Hi dd8,

We were wondering if you could better explain how you arrived at these warning messages so we can reproduce your steps. Do you see these warnings after everything compiles successfully?

Best,
Palak

**Comment by dd8** [comment] 2020-04-16 08:52
Hi

The problem also occurs on Visual Studio 2019 - here are reproduction steps:

1) Download the sample from https://github.com/MicrosoftEdge/WebView2Browser
2) Open in Visual Studio 2019 16.5.3 (with Windows SDK 10.0.18362)
3) Select Analyse menu -> Run Code Analysis -> On Solution

There are several C28251 warnings shown in the output window once compilation completes

The problem is happening because WebView2.h redefines HWND_UserSize and friends which are already defined in the Windows SDK

Windows SDK 10.0.18362 defintion:
unsigned long __RPC_USER HWND_UserSize( __RPC__in unsigned long *,unsigned long,__RPC__in HWND *);

WebView2.h definition is missing the __RPC__in annotation:
unsigned long __RPC_USER HWND_UserSize( unsigned long *,unsigned long,HWND *);

Best 
Mark

**Comment by quietfanatic** [comment] 2021-07-26 18:32
I don't know what changed since April, but I can no longer reproduce this in WebView2Browser on VS 2019 with Windows SDK 10.0.18362 and recent WebView2 packages, so I'm going to go ahead and close this issue.  Feel free to reopen it if this comes up again.

**Closed by quietfanatic** 2021-07-26 18:32 UTC
Labels: bug
