### ISSUE TITLE
The sender object for ProcessFailed event is garbled when webview2 instance is killed from task manager

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#974] opened 2021-02-23 16:39 UTC
**Description**
1. For a single webview2 instance, 4 to 6 processes are getting created in task manager.
2. But, only 1 among those 6 process when killed from task manager sends a garbled sender object in the API. Because of this garbled object not able to perform any further operations. How do we handle this?
3. All the other process return the correct sender object. Both correct and incorrect sender object screenshots are attached below.

![image](https://user-images.githubusercontent.com/956509/108875622-637cfa80-7623-11eb-8216-8aadeb272b55.png)

**Version**
SDK: 1.0.705.50
Runtime:  88.0.705.74
Framework: WPF
OS: Win10

**Repro Steps**
1. Create one webview2 browser instance.
2. In the task manager, 4 to 6 processes get created for that single instance.
3. When that process is killed, we get a ProcessFailed event in the app for handling crashes. But, only for one process kill the sender object is garbled and due to which not able to perform any operations on that CoreWebView2 (sender) instance. Getting exception like **"The group or resource is not in the correct state to perform the requested operation".**

**Screenshots**
**In case of ProcessFailed event, when the sender object is correct.**
![image](https://user-images.githubusercontent.com/956509/108874586-4c89d880-7622-11eb-8123-e0d6d0c6b610.png)

**But only for one process in task manager, when ProcessFailed event happens, the sender object is garbled.**
![image](https://user-images.githubusercontent.com/956509/108874659-5e6b7b80-7622-11eb-9705-cee80fe5830b.png)

**Additional context**

**Comment by Syul968** [comment] 2021-02-23 18:57
Hi @chaitanyajun12,

Thanks for your report. The WebView2 Runtime uses multiple processes (see [Process model](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model)) to power the webviews in the app. This is why there are multiple processes listed in Task Manager.

When WebView2 Runtime's **browser process** exits unexpectedly (for example, it is killed from Task Manager) the webviews which were using that process will automatically move to the `Closed` state (see [COREWEBVIEW2_PROCESS_FAILED_KIND](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.705.50#corewebview2_process_failed_kind)). Since the underlying WebView2 Runtime's browser process connection has been lost, many operations will be restricted when this happens. The app has to recreate a new WebView to recover from this failure.

**Comment by chaitanyajun12** [comment] 2021-02-24 04:17
Hi @Syul968,
Thank you for the reply.

This is the XAML we have to which we attach the `WebView2` instance.
`<ContentControl Margin="0,0,0,0" Name="Container" />`

Via the below code trying to associate a new `WebView2` instance.
`Container.Content = new WebView2()`

Now the browser instance loads and after this trying to kill the process via Task manager.
Yes, we are trying to create a new webview2 instance and assign that to the `Content` variable of `ContentControl` object again.

But, this assignment goes through, but post that we get the error **"The group or resource is not in the correct state to perform the requested operation".** This happens only for the single process when the `sender` object is garbled as shown above in the screenshot.

Do you mean to say that even when the sender object is garbled, it should work and the handling is possible at the app level?

**Comment by Syul968** [comment] 2021-02-24 06:08
Is the garbled WebView2 instance the one that received the `ProcessFailed` event? If so, are you performing any other call/access onto such instance? If not, it is possible that the framework is trying to access the restricted methods and producing the exception. We have seen this a couple of times (see #774). Removing the closed control from the visual tree should fix the issue in that case.

> Do you mean to say that even when the sender object is garbled, it should work and the handling is possible at the app level?

Could you clarify what "it should work" is referring to in the question above?

**Comment by chaitanyajun12** [comment] 2021-02-24 06:54
Yes the garbled instanced is the one which received the `ProcessFailed` event. Earlier I was trying to perform some calls on that instance. But, seeing that its failing now I'm not. Now I'm trying to replace my `ContentControl`'s `Content` object with new webview2 instance. This initialization goes through, but the garbled instance throws "COREWEBVIEW2_MOVE_FOCUS_REASON" exception.

     Could you clarify what "it should work" is referring to in the question above?

What I meant here was, even though the object is garbled we can get the app back to stabilized state without exception?

**Comment by Syul968** [comment] 2021-02-25 19:28
It is expected that the instance that lost its browser process will not be able to perform these operations (as they depend on the supporting process). Even in this case, there should be no exceptions as long as you don't make further calls to the instance, but the framework might be calling some of these restricted methods.

Could you share the details of the exception you are getting?
Could you try explicitly removing the instance from the visual tree on `BrowserProcessExited` process failed event, that is, before attaching a new instance?

**Comment by chaitanyajun12** [comment] 2021-02-26 07:25
After receiving the ProcessFailed event, we are trying to set the Content with a new XAML. This Content object has the corrupted `sender` as shown in the first issue summary. On it we are trying to do, 

    BrowserContainer.Content = <NewContentControlConfirmationUI>

On performing the above operation we are getting the below exception,
![image](https://user-images.githubusercontent.com/956509/109268652-65b4a400-7831-11eb-9db0-3ece0df6f5fc.png)

I think internally some methods of this corrupted view are getting called which is resulting in this exception.

**Comment by orrindeng** [comment] 2021-02-26 11:16
I'm getting this issue too. No WebView2 process alive. 
I've listened the `ProcessFailed` event. But when I remove the broken WebView2 control from the visual tree. 
```webBrowserHolder.Child = null;```

Exception happens:
```
The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_IsVisible(Int32 IsVisible)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_IsVisible(Boolean value)
   at Microsoft.Web.WebView2.Wpf.WebView2.UIElement_IsVisibleChanged(Object sender, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyPropertyChangedEventHandler.Invoke(Object sender, DependencyPropertyChangedEventArgs e)
   at System.Windows.UIElement.RaiseDependencyPropertyChanged(EventPrivateKey key, DependencyPropertyChangedEventArgs args)
   at System.Windows.UIElement.OnIsVisibleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.OnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.RemoveVisualChild(Visual child)
   at System.Windows.FrameworkElement.set_TemplateChild(UIElement value)
   at System.Windows.StyleHelper.ClearGeneratedSubTree(HybridDictionary[] instanceData, FrameworkElement feContainer, FrameworkContentElement fceContainer, FrameworkTemplate oldFrameworkTemplate)
   at System.Windows.StyleHelper.DoTemplateInvalidations(FrameworkElement feContainer, FrameworkTemplate oldFrameworkTemplate)
   at System.Windows.Controls.ContentPresenter.OnTemplateChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Controls.ContentPresenter.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at C1.WPF.C1TabControl.UpdateSelectedContent()
   at C1.WPF.C1TabItem.OnContentChanged(Object oldContent, Object newContent)
   at System.Windows.Controls.ContentControl.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at C1.WPF.C1TabItem.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Forguncy.Views.MainView.InitReportsWebBrowser(WebView2 webBrowser)
```

**Comment by johna-ms** [comment] 2021-02-26 18:17
Hey all, I'll be looking into this. This is definitely a bug. There's a fix for this specific issue in the works but it's being held up because it's implicated with other behaviors. I'm working on getting this turned around soon.

**Comment by JeffD35** [comment] 2021-03-03 21:03
Thanks for looking into this. I can also reproduce this in a WinForms app.

Version: 88.0.705.81

**Comment by johna-ms** [comment] 2021-03-03 22:06
Hey all. A fix for this should be in Edge Dev by 3/9. That should be in the WebView runtime by next month

**Comment by chaitanyajun12** [comment] 2021-03-04 16:31
So, to get this fixed we will need fix in WebView2 runtime alone or even in WebView2 SDK package as well?

**Comment by johna-ms** [comment] 2021-03-04 18:56
You should only need the runtime

**Closed** 2023-05-08 22:09 UTC
Labels: bug
