### ISSUE TITLE
Custom display ContextMenuItem

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3735] opened 2023-08-23 07:58 UTC
**Is your feature request related to a problem? Please describe.**

Custom display ContextMenuItem, some controls use the left click, I still want it to display a custom menu, such as Edge Settings button, webVIew2 does not have a similar function
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/d927fe6c-2e2d-40a6-b560-71b0923bef4b)

**Describe the solution you'd like and alternatives you've considered**

**Comment by lflores-ms** [comment] 2023-08-23 17:24
Hi @1339240789,

We have the [ContextMenuRequested](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus?tabs=csharp) API which is built for this purpose.

**Comment by ajtruckle** [comment] 2023-08-23 19:17
@lflores-ms They said _left-click_ and the context menu API is for _right-click_. Looks like they have a "..." icon at the top (which in Edge shows a menu). They want control over that menu.

Or, is that menu already catered for in the `ContextMenuRequested `API?

**Comment by lflores-ms** [comment] 2023-08-23 22:35
Thanks @ajtruckle. It's not clear to me what @1339240789 meant as there are both references to "ContextMenuItem" and left-click.

For Edge's _three-dot menu_, we do not support this menu as it's a browser feature not applicable to WebView2.  Are you trying to access any of the options from this menu?

**Comment by 1339240789** [comment] 2023-08-24 01:06
I mean can custom create a right-click menu for custom show without ContextMenuRequested event

**Comment by 1339240789** [comment] 2023-08-24 01:08
Because there are places where I want to left-click and pop up a menu

**Comment by darbid** [comment] 2023-08-24 04:54
Hey @1339240789 maybe you might need a little help.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/3191525/ba00f70d-705a-41e7-8d49-4dfbe455be47)

I have added a blue frame and red line to your image. Everything inside this blue frame is the web browser. This is the part which webview2 does. Outside of the blue frame which I have marked with a red line is what the developer creates. It's the window of your browser. Anything here you make.

** Left click context menu in blue frame**
If you want to make the suggestion for a left click context menu on the browser itself, then the main question I think most people would have is, how do you differentiate between a left click on a link or HTML button, or in a HTML text box and a left click, which should show the context menu? If you can answer that question, then this possibly could be your suggestion.

** Left click context menu in red part**
For the developers part which I have marked with the red line, you can of course do whatever you like. You can have context menus appearing here with a left click however maybe what you are thinking about is the functionality which many browsers have for the back and forward arrows normally at the top left of the window if you click one of these, with the Left mouse button, the browser navigate backwards or forwards. However if you hold your left button down for a long period of time a context menu appears showing your history going backwards, for example. I have done something exactly like that in my implementation of a window in WPF. It was not too difficult to handle except that the resulting context menu which is actually a new WPF window had some focus issues. I think this was mainly caused by the fact that the context menu was shown while the left mouse button was being held down on another element, and therefore the context menu could not take focus.

** Doing it yourself**
I do fear that your suggestion may not be implemented. In this case maybe you could do it yourself. Given what and how Webview2 has been implemented it is very much kind of like a foreign object inside your window. This is made worse by the surface being run in a separate process, making it (I think) impossible for languages like c# to sub class parts of the underlying windows. As a result, you may not be simply able to detect a mouse click and show a context menu as you would do in most common frameworks like WPF or Windows forms. 

One possible way of doing this would be to add some JavaScript to your HTML page which detects a long mouse click and then send a message back to your code in which case you could show a context menu at the position of your mouse. My JavaScript skills are not great, so I am unsure of the possible side-effects of trying to catch a long click on a whole webpage, for example frames and other elements which steal events may make it unreliable.

Hope this helps.

**Comment by 1339240789** [comment] 2023-08-24 07:23
@darbid  okay,thanks

**Comment by victorhuangwq** [comment] 2023-10-04 22:12
Closing this feature request as not planned.

**Closed by victorhuangwq** 2023-10-04 22:12 UTC
Labels: feature request
