### ISSUE TITLE
MFCProj or ATLProj are not compatible with WebView2 

### ISSUE THREAD

**Issue by nikitavirg** [MicrosoftEdge/WebView2Feedback#1211] opened 2021-04-22 13:38 UTC
**Description**
I tried to build Microsoft.Web.WebView2.1.0.774.44 , and I have a problem to copy the dll, on PostBuild events

The issue happens when I have a MFCProj or ATLProj  on my vcxproj

   <Keyword>MFCProj</Keyword> or    <Keyword>ATLProj  </Keyword>

In this case the dll is not search on good path see error from Visual studio:

Here is the following error on Visual  studio
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4651,5): error MSB3030: Could not copy the file "C:\.......\desktop-ctxt-interactive\packages\Microsoft.Web.WebView2.1.0.774.44\build\runtimes\win-x86\native\WebView2Loader.dll" because it was not found.

My workaround is tu change MFCProj or ATLProj to   <Keyword>Win32Proj</Keyword>
But It would be great to accept also MFCProj or ATLProj on your target

**Version**
SDK: Microsoft.Web.WebView2.1.0.774.44
Visual studio 2019

**Repro Steps**

**Screenshots**

**Additional context**
What I see is that of the file Microsoft.Web.WebView2.targets we have the following condition sometimes
'$(Keyword)' == 'Win32Proj'">

So that's why it is not working on my side, if I put Win32Proj it is working.

**Comment by champnic** [comment] 2021-04-24 00:30
This looks like a dupe of #506 and has been fixed in 1.0.824-prerelease or 1.0.818.41 SDK packages. Thanks!

**Closed by champnic** 2021-04-24 00:30 UTC
Labels: bug
