### ISSUE TITLE
ProcessFailed ExitCode 40

### ISSUE THREAD

**Issue by wilva** [MicrosoftEdge/WebView2Feedback#2429] opened 2022-05-06 13:10 UTC
We've been trying to use WebView2 on a new server.
It has WebView2 version 101.0.1210.32.
When trying to create the control it fails and triggers the ProcessFailed event.

ExitCode 40 [] 
ProcessFailedKind 1 (RenderProcessExited)
reason 4 (LaunchFailed)

But ExitCode 40 is not documented.

We already looked at chromium for that as well over at: https://source.chromium.org/chromium/chromium/src/+/main:tools/metrics/histograms/enums.xml;l=16265;drc=30670e617aba4c49814bedfea8c10e36f5db0c77

And… ofcourse error 40 is missing So I went to here: https://chromium.googlesource.com/chromium/src/+/1b1f5fcd8d83eb29bd4531eeff59b178cf2a0eb8/chrome/browser/ui/views/sad_tab_view.cc and it’s also missing there. 

Would be nice to know why it is failing and what ExitCode 40 actually means.

Thanks!

**Comment by Syul968** [comment] 2022-05-17 00:41
Hi @wilva,

Does this issue reproduce if you try to launch the [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample) app? Or in the Edge browser?

`ExitCode` 40 is not an actual exit code since the process couldn't even start. The "exit code" being reported here comes from the process launcher component and it's [related to sandbox setup](https://source.chromium.org/chromium/chromium/src/+/main:sandbox/win/src/sandbox_types.h;l=104;bpv=1;bpt=1?q=sandbox::ResultCode). Is there any antivirus software installed on the device?

Thanks,
Luis

**Comment by wilva** [comment] 2022-05-20 20:37
Thanks Luis,

Sorry for the delay, had to wait for the customer to come with the reply.
They ran some tests on the server and MS Edge works.

The WebViewSample application gives the following error:
![image](https://user-images.githubusercontent.com/43706927/169606794-108fb5e3-7032-4da3-9b95-48aec69d837b.png)
After trying to agree to try and reload the control the following comes up:
![image](https://user-images.githubusercontent.com/43706927/169606924-a19b2594-f92c-4c75-85c4-e68f6d2ac34f.png)
followed by:
![image](https://user-images.githubusercontent.com/43706927/169607013-2c91bf1e-29d8-4899-aa7a-8d31d684abaf.png)
After which the application crashes.

Hope this helps,
Wil

**Comment by Syul968** [comment] 2022-05-31 23:57
Hi again @wilva,

Sorry for the delay. Is this issue still reproducible on the customer end? There's a new WebView2 version rolling out this week (`102.0.1245.30`), it'd be helpful if you could confirm if this is still an issue with the new version.

I'm following up on the error on our side. In the meantime, would you please share an estimate of how many devices are impacted? Also, if the application is working on other devices, is there any difference in OS/environment configuration or group policies? Any additional information we might get on system permissions and access can be relevant.

Thanks,
Luis

**Comment by Syul968** [comment] 2022-06-01 22:05
Thanks for the additional info, will keep for the record. Closing.

**Closed by Syul968** 2022-06-01 22:05 UTC
Labels: question
