### ISSUE TITLE
Header referrer is missing if redirect new window request to new tab control. 

### ISSUE THREAD

**Issue by Dave-Jalpan** [MicrosoftEdge/WebView2Feedback#1402] opened 2021-06-15 03:13 UTC
I want to open a new tab instead of new window. But while doing that one of the application throws exception "Error: No referrer", as application is expecting referrer value in header. So how I can pass referrer in header from e.NewWindow while redirecting new window request to new tab?

```

private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    baseTemplate.AddTab(e.Uri, true); /// Creating new tab instead opening new window. 
    e.Handled = true;
}

```

**Comment by champnic** [comment] 2021-06-17 05:48
Closing as a duplicate of #1397. Thanks!

**Closed by champnic** 2021-06-17 05:48 UTC
