### ISSUE TITLE
SetVirtualHostNameToFolderMapping doesn't take effect when called from WebMessageReceived handler

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#1018] opened 2021-03-02 10:05 UTC
**Description**

**Version**
SDK: 1.0.781-prerelease
Runtime: Canary 90.0.810.0
Framework: Win32
OS: Win10 1909
**Repro Steps**

Calling SetVirtualHostNameToFolderMapping on a folder from within a WebMessageReceived handler will result in a ERR_NAME_NOT_RESOLVED error when attempting to access the file from that folder using `fetch`.  The return value from SetVirtualHostNameToFolderMapping is S_OK.  This works as expected when the SetVirtualHostNameToFolderMapping is called elsewhere (such as right after the browser control is created).

This doesn't seem to be a timing issue as I've attached the 2 functions to separate buttons on the UI in my test application.  
**Screenshots**

**Additional context**
My test application contains some wrapping logic, I will attempt to create a minimal reproducible sample using a sample app

[AB#32011248](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32011248)

**Comment by romanan** [comment] 2021-03-03 00:43
I was able to reproduce this using the WebView2GettingStarted sample, relevant code here:
https://github.com/romanan/super-octo-lamp/blob/250781cad8d4427612da36cb3f5e8832847c7821/HelloWebView.cpp#L151-L165

This [HTML](https://github.com/romanan/super-octo-lamp/blob/main/HTMLPage1.html)  contains 2 buttons, first button sends a message, second one calls 'fetch' on a URL that should be mapped.

**Comment by champnic** [comment] 2021-03-05 23:22
Thanks for the report! I've added it to our backlog to take a look.

**Comment by LiangTheDev** [comment] 2021-04-14 21:15
This is a limitation by design: it would work if you reload the page.

More details on what happens: the sub resource loader is created when the page is loaded and any modification to the virtual host name mapping after the page is loaded would not impact the resource loader that is already up and running.

**Comment by hjlld** [comment] 2021-04-21 03:16
I find the same issue. Temporarily i have to use this method before `Navigate()`.

**Comment by champnic** [comment] 2021-04-21 03:25
Closing this issue as it's a current technical limitation. We're updating the docs to reflect this limitation.

**Closed by champnic** 2021-04-21 03:25 UTC
Labels: bug, tracked
