### ISSUE TITLE
[DMC]: wpf don't work in latest prerelease 0.9.628 #920

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#492] opened 2020-09-29 16:48 UTC
Please review the customer issue located here: 
https://github.com/MicrosoftDocs/edge-developer/issues/920

Thank you.

**Comment by champnic** [comment] 2020-09-29 16:56
Followed up on dev thread. This is a dupe of #431, closing.

**Closed by champnic** 2020-09-29 16:56 UTC
Labels: question
