### ISSUE TITLE
COMException reading WebResourceResponse content

### ISSUE THREAD

**Issue by m4wayne** [MicrosoftEdge/WebView2Feedback#3229] opened 2023-02-18 05:10 UTC
In CoreWebView2.WebResourceResponseReceived EventHandler, I use Response.GetContentAsync to get the response content and get the following error:
![image](https://user-images.githubusercontent.com/6783828/219830232-d29527bf-efa5-4b9e-b89c-ca58af82f23d.png)

-----------------------------------------------------Split line--------------------------------------------------------- 

![image](https://user-images.githubusercontent.com/6783828/219831089-0f4729f0-caa6-4a51-83f8-4798b79204f2.png)

These codes were working fine before, and they are not working since yesterday.The error usually received is "The pipe is being closed. (0x800700E8)", the other error "No class registered" is present only once. I've looked at https://github.com/MicrosoftEdge/WebView2Feedback/issues/1839 and https://github.com/MicrosoftEdge/WebView2Feedback/issues/1826 and haven't been able to solve the problem I'm having.
Updated the windows patch yesterday, I still get the same error after uninstalling the patch.
![image](https://user-images.githubusercontent.com/6783828/219840901-da0f46cf-24f0-49f7-a6f2-b2e1ee7c53b4.png)

Here is the record I intercepted using Fiddler.Exception An error occurred while intercepting the sequence number 9 response.The response content of serial number 9 is normal when displayed in the browser.
![image](https://user-images.githubusercontent.com/6783828/219830718-087c6324-1275-46a8-b8cc-b290d634d52c.png)

Who can help me, thanks!

WebView2: 1.0.1264.42 and 1.0.1587.40
Runtime: 110.0.1587.50
Framework: .NET6 Winform
OS: Win10 22H2(19045.2604)
Visual Studio:Community 2022 (64 位) - Current版本 17.4.5

The above content was machine translated by Google, so the content may be a little strange.

[AB#43494200](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43494200)

**Comment by m4wayne** [comment] 2023-02-18 12:54
After the computer is started, the first test result of the program is "No class registered" error, and all subsequent test results are "The pipe is being closed. (0x800700E8)" error.

**Comment by m4wayne** [comment] 2023-02-19 04:11
After testing, it is found that Response.GetContentAsync() will report an error after getting the redirected response body (the response status code is 200, and the response body has data). Redirects include 301, 302, 307, 308

**Comment by m4wayne** [comment] 2023-02-19 07:56
Just tested in the 109.0.1518.78 runtime environment, the Response.GetContentAsync code can run normally. Is this an unknown bug of 110.0.1587.x? I have the same error when running on 110.0.1587.46.
Please help me!

**Comment by novac42** [comment] 2023-02-20 06:53
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by m4wayne** [comment] 2023-02-21 01:30
@ElyssaJyu @novac42 Thanks for following up.

**Comment by ElyssaJyu** [comment] 2023-02-21 07:24
Hi @m4wayne, could you give a description about your scenario and provide a sample project that I can simply repo the exception? It will be easier to find the root cause. Thanks.

**Comment by m4wayne** [comment] 2023-02-22 04:03
Hi @ElyssaJyu
I use WebView2 to open a web page. In the WebResourceResponseReceived() function, the program determines what to do next according to the content returned by the GetContentAsync() function.

WebView2: 1.0.1587.40
Runtime: 110.0.1587.50 or 109.0.1518.78
Framework: .NET6
OS: Win10 22H2(19045.2604)
Visual Studio:Community 2022 (64 位) - Current版本 17.3.6

WebView2Demo usage guide：
1. Start the WebSimulator,for example: cd WebSimulator && dotnet run
2. Start the WebView2Demo
3. Click the "登录(Login)" button
4. Observe the content of the Visual Studio output window
5. Use different running versions, such as 109.0.1518.78 or 110.0.1587.x
At the same time, I provide the program running gif file and Fiddler packet capture record for your reference.
https://github.com/m4wayne/WebView2Demo

**Comment by m4wayne** [comment] 2023-02-22 05:28
I use WebView2 to open a web page. In the WebResourceResponseReceived() function, the program determines what to do next according to the content returned by the GetContentAsync() function.

WebView2: 1.0.1587.40
Runtime: 110.0.1587.50 or 109.0.1518.78
Framework: .NET6
OS: Win10 22H2(19045.2604)
Visual Studio:Community 2022 (64 位) - Current版本 17.3.6

WebView2Demo usage guide：

Start the WebSimulator,for example: cd WebSimulator && dotnet run
Start the WebView2Demo
Click the "登录(Login)" button
Observe the content of the Visual Studio output window
Use different running versions, such as 109.0.1518.78 or 110.0.1587.x
At the same time, I provide the program running gif file and Fiddler packet capture record for your reference.Thanks.
[https://github.com/m4wayne/WebView2Demo](WebView2Demo)

**Comment by ElyssaJyu** [comment] 2023-02-24 07:22
Hi @m4wayne, thanks for your provided details.  I have cloned your project and saw the expception.gif.  Also, I saw the comment in [issue 1839](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1839#issuecomment-1089158292).  

> There is an exception will be thrown if the response body is empty for 302/307 redirect and other https request with 200 works fine. Response code should give the content.

Will this resolve your question?  
 You mentioned runtime 109.0.1518.78 works with no exception, but 110.0.1587.x will throw it. I will continue investigate it. Thanks.

**Comment by m4wayne** [comment] 2023-02-25 10:44
Hi @ElyssaJyu,https://github.com/MicrosoftEdge/WebView2Feedback/issues/1839#issuecomment-1089158292 didn't solve my problems.
The page content I need to get comes from the response after redirection(302). This is a third-party website, and I cannot change it.
Did you receive the same error when running the WebView2Demo project I provided?
It is gratifying that 109.0.1518.78 can work normally at present. I have specified the runtime used by the project as 109.0.1518.78. So it has no impact on my work progress.
Take your time, thanks.

**Comment by ElyssaJyu** [comment] 2023-02-27 02:15
Hi @m4wayne, we've tracked it internally, and I will sync with you later. Thanks for your provided info.

**Comment by m4wayne** [comment] 2023-02-27 14:01
Great! Thanks for getting back to me!
@ElyssaJyu

**Comment by RoederSi** [comment] 2023-03-10 09:41
Having a similar issue with win32 webview2 browser. 
Trying to get the response content after redirects (302) always returns the result ERROR_NO_DATA, although there is content. This happens for the original (302) request and the redirected (200) which used to return content before runtime version 110.0.1587.x.
I would appreciate any info on this issue.

**Comment by champnic** [comment] 2023-06-07 23:22
This should be fixed in WebView2 runtimes version 116.0.1902.0+. Thanks!

**Closed by champnic** 2023-06-07 23:22 UTC
Labels: question, tracked

**Comment by m4wayne** [comment] 2023-06-16 06:27
Thanks all.
