### ISSUE TITLE
How to achieve await like functionality in Win32/C++ for ExecuteScript handler?

### ISSUE THREAD

**Issue by raroraca** [MicrosoftEdge/WebView2Feedback#2717] opened 2022-08-25 05:49 UTC
Hi All,

Regarding the thread safety and blocking the UI thread, webview2 document has mentioned that we cannot use waitforsingleobject or Task.Result. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#block-the-ui-thread 

Instead, an example given to use await for ExecuteScript, which doesn't blocks the main thread execution and message pump continues.
How can we achieve the same in Win32/C++ so that we can have ExecuteScript call in Synchronous manner?

**Comment by raroraca** [comment] 2022-08-30 13:08
@Syul968 Can you please update if we have a way to get the Synchronous way for ExecuteScript?

**Comment by raroraca** [comment] 2022-09-12 05:30
@champnic Can you please have a look at this request?

**Comment by champnic** [comment] 2022-09-12 20:14
Hey @raroraca - There's a discussion on this very topic happening here in #136:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/136#issuecomment-1241117732

Feel free to join the discussion and ask follow-up questions there.

**Comment by Syul968** [comment] 2022-09-23 03:06
Duplicate of #136

**Closed by Syul968** 2022-09-23 03:06 UTC
Labels: question
