### ISSUE TITLE
Microsoft.Web.WebView2 1.0.705.50 builds fail for MFC projects

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebView2Feedback#857] opened 2021-01-26 17:01 UTC
**Description**
Microsoft.Web.WebView2.targets uses the test `$(Keyword) == 'Win32Proj'` to check for a native app project and `$(Keyword) != 'Win32Proj'` for a .NET Project

Unfortunately MFC apps use $Keyword = 'MFCProj' so the .NET file copy of WebView2Loader.dll on line 67 is done, instead of the native copy on line 53, which fails because the WebView2Loader.dll relative paths are wrong

**Version**
SDK: 1.0.705.50
Runtime: 88.0.750.50
Framework: MFC
OS: Win10

**Repro Steps**
1) In VS 2019 create an MFC App with default settings in New Project wizard.
2) Build will succeed
3) Use Manage Packages NuGet Packages for Solution to install WebView2 1.0.705.50 into MFC project
4) Build will fail with 3 file copy errors

**Comment by dd8** [comment] 2021-01-26 17:04
This is probably the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/851

**Comment by jhandley** [comment] 2021-01-26 23:07
I can confirm that changing that check on line 53 to compare to "MFCProj" instead of "Win32Proj" fixed the issue with my project as reported in #851. Would be fantastic to get this resolved in the next release.

**Comment by mariusbancila** [comment] 2021-01-27 13:48
This is what I get too:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4846,5): error MSB3030: Could not copy the file "C:\Work\MFCWebView2Demo\packages\Microsoft.Web.WebView2.1.0.705.50\build\runtimes\win-x86\native\WebView2Loader.dll" because it was not found.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4846,5): error MSB3030: Could not copy the file "C:\Work\MFCWebView2Demo\packages\Microsoft.Web.WebView2.1.0.705.50\build\runtimes\win-x64\native\WebView2Loader.dll" because it was not found.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4846,5): error MSB3030: Could not copy the file "C:\Work\MFCWebView2Demo\packages\Microsoft.Web.WebView2.1.0.705.50\build\runtimes\win-arm\native\WebView2Loader.dll" because it was not found.
```
This is fixed when I change the file Microsoft.Web.WebView2.1.0.705.50\build\native\Microsoft.Web.WebView2.targets as explained in https://github.com/MicrosoftEdge/WebView2Feedback/issues/506. 

The question is, when is this going to be fixed in the NuGet package?

**Comment by champnic** [comment] 2021-01-28 00:57
Going to close this issue as it does look like a duplicate of #506 (unless I'm missing something?). I think we'll have a fix for this in the next SDK package (not the ones being released this week).

**Closed by champnic** 2021-01-28 00:57 UTC
Labels: bug

**Comment by dd8** [comment] 2021-01-29 09:14
@champnic Great that it's been fixed. 

Is it worth keeping issues open until the fix has been released? 

If they're closed before release then they don't show up in Github issue search (unless you change the default search criteria) which means people can't easily find the workaround (or know that a fix is queued for release) and will report duplicate issues.

**Comment by champnic** [comment] 2021-02-01 22:45
Yes we like to keep issues open until a fix is released in an SDK/runtime. In this case I closed it because I believe it's captured by issue #506, and we like to have one issue per bug/feature request, so #506 will remain open until a fix gets released (which should also fix this one).

If you think #506 is similar you can add details to it, or if you think #506 is sufficiently different than this issue I can reopen this one and get it tracked as a separate bug on our backlog. Thanks!

**Comment by dd8** [comment] 2021-02-02 11:51
@champnic That makes sense - when I made the comment #506 had been closed. It's open again and has all the info anyone bumping into the problem needs.

**Comment by champnic** [comment] 2021-02-03 00:09
Doh, sorry I missed that!
