### ISSUE TITLE
WebView2 application is rendered poorly on secondary monitor with higher resolution 

### ISSUE THREAD

**Issue by harunurhan** [MicrosoftEdge/WebView2Feedback#3844] opened 2023-10-04 14:58 UTC
**Description**

WebView2 application is rendered poorly on secondary monitor with higher resolution, for example when your main monitor is Full HD and the other one is 4K or 2K.

**Version**
SDK: 1.0.1462.37
Runtime: 117.0.2045.47
Framework: WinForms
OS: Win11, Win10

**Regression**
Was this working before but has regressed?  Not sure
If yes, what version did this last work on? 

**Repro Steps**

- Have multiple monitors
- Set resolution of the main monitor to a lower setting
- Launch `WebView2WinFormBrowser` from the sample apps
- Move `WebView2WinFormBrowser` to a secondary monitor with higher resolution
- You will see that it's lower quality, the text is blurry etc.

**Screenshots**

### secondary monitor with higher resolution
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4868667/36dd0265-de96-4e11-bebc-e39c3f3d20e4)

### main monitor with lower resolution
![Screenshot 2023-10-04 164233](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4868667/7d5d1088-e32c-4580-98a1-acc1541d8038)

**Additional context**

**Comment by harunurhan** [comment] 2023-10-04 15:36
this maybe a WinForms bug or just a missing setting on the sample app.

**Comment by johna-ms** [comment] 2023-10-17 23:37
Thanks for reporting this! It is a duplicate of issue #3060 so I'm closing this. Issue 3060 is on our backlog, but we don't expect to look at it for a while.

**Closed by johna-ms** 2023-10-17 23:37 UTC
Labels: bug
