### ISSUE TITLE
WinForms WebView2 - how to handle Ctrl+Click on a link

### ISSUE THREAD

**Issue by joergbattermann** [MicrosoftEdge/WebView2Feedback#371] opened 2020-08-06 21:08 UTC
I can register an event handler for the WinForms webView2 UserControl's .CoreWebview2.NewWindowRequested event and that event gets raised whenever I right click > and then select/click > 'Open in new Tab' in the context menu, however NOT when I hold the [Ctrl] key + left click a link. The later opens an entirely new browser window outside my application's context / control.

How _can_ I handle both - new window- AND new tab requests?

Thanks!
-J

[AB#28262280](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28262280)

**Comment by pagoe-msft** [comment] 2020-08-07 17:44
@joergbattermann ,

Thanks for pointing this out! This is a known issue caused by a change in the web platform behavior. Previously, a new tab would replace the content in the WebView, now it opens a new window. We are exploring creating a NewTabRequested Event or also firing the NewWindowRequested Event

**Comment by joergbattermann** [comment] 2020-08-07 18:42
Thanks for the clarification @pagoe-msft! 👍 Either one of the solution(s) would be fine for me, as long as I can differentiate between new window and new tab requests.

Hope this makes it into one of the next releases 🤞

**Comment by ukandrewc** [comment] 2020-08-07 20:56
On NewWindowRequested, any plans to provide settings from window.open, so we can set size, etc?

**Comment by pagoe-msft** [comment] 2020-08-07 21:22
@ukandrewc - I'll add that to our backlog as well! Do you mind creating a separate GH issue?

**Comment by pagoe-msft** [comment] 2020-11-23 21:42
Hi Everyone,

This was addressed in the [1.0.707-prerelease](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#10707-prerelease) version.

**Closed by pagoe-msft** 2020-11-23 21:42 UTC
Labels: feature request

**Comment by clairernovotny** [comment] 2020-12-21 14:20
I don't see a way to tell the difference to tell if the user did a ctrl+click  or not?
