### ISSUE TITLE
External applications started from WebView2 (like Zoom) are displayed under WebView2 icon group

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3245] opened 2023-02-28 11:58 UTC
**Description**
Any external applications started from WebView2 are displayed under the WebView2 icon group instead of its own icon group. 

**Version**
SDK: 1.0.1671-prerelease
Runtime: Evergreen, 110.0.1587.57
Framework: WPF
OS: Win11

**Repro Steps**
1. Create a MSIX installer for WebView2WpfBrowser sample app
2. Install and start the app
3. Make sure zoom is not running
4. Open a zoom link

**Expected**: Zoom is opened with its own icon group
**Actual**: Zoom is opened under WebView2WpfBrowser instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/8770144/221847748-9ca62716-8f6a-4765-a33e-8f52cb5f04f0.png)
![image](https://user-images.githubusercontent.com/8770144/221847768-b6107826-348c-4381-bdc3-c25f5e41dedd.png)

**Additional context**
This is a regression as it was working fine in version `107.0.1418.26` and seems to be broken since `109.0.1518.78`. I haven't checked the versions between those two.

[AB#44146549](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44146549)

**Comment by novac42** [comment] 2023-03-01 05:52
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by plantree** [comment] 2023-03-08 05:23
Hi @q71114,

Did you mean, you open a Zoom link in `WpfBrowser` and the Zoom process is running under it, instead of independently?

**Comment by q71114** [comment] 2023-03-08 08:55
Hey @plantree,

Yes, the expected behavior is to have the Zoom process appearing under its own icon group in the taskbar.

**Comment by plantree** [comment] 2023-03-13 02:44
Hi @q71114,

It seems that `open zoom link` just opens a new window, not the local application. Is it?

**Comment by q71114** [comment] 2023-03-13 09:09
Hey @plantree 

It does open the local application, it's just displayed under the wrong icon group. See the screenshot I attached.

**Comment by plantree** [comment] 2023-03-15 07:42
Hi @q71114,

1. Could you check the property of Zoom process? 

2. And if it is convenient, could you uninstall Zoom to check?

**Comment by q71114** [comment] 2023-03-15 08:56
1. Which property are you interested in?
2. The issue remains after zoom is uninstalled / reinstalled.

Note: This is **NOT** a Zoom issue, we have user reports about the same issue with other applications like: Word, PowerPoint, Roblox. Also as I mentioned in the bug report this was working fine in version `107.0.1418.26` and before.

**Comment by plantree** [comment] 2023-03-16 02:20
Hi @q71114,

1. Right click the process, and we can see `Properties`, like: 

![image](https://user-images.githubusercontent.com/20148487/225492279-daafa94f-ea7f-4aa2-a011-20f519af2700.png)

2. Uninstall Zoom is to check whether **a local application** or **a new webpage** is opened.

If it's possible, could you provide a simple `.exe` to reproduce the issue? Thanks.

**Comment by q71114** [comment] 2023-03-16 10:29
We hung up on Zoom unnecessarily but it's irrelevant because it happens with any other apps as well. Let me give you another example with Excel.

This problem can only be reproduced with installed application. 
You can use a [test installer I built](https://duckduckgo-my.sharepoint.com/:u:/p/qnguyen/Ebh45_TOGcZEn6h6ciGCyCcBEkdtqjmxOC7tlhMnO86vXA?e=rZYhy9) for that you need to add this [self signed certificate](https://duckduckgo-my.sharepoint.com/:u:/p/qnguyen/EQkqmh5Z4QpNi-TCKc5sjigBJXOyz5i8yNdrnRKjtLSbzg?e=SnFftT) I created. 
If you don't want to do that, then build your own installer using [this branch](https://github.com/q71114/WebView2Samples/tree/installer) with your own certificate.

Steps to reproduce
1. Install the provided or built installer.
2. Make sure Excel is not running
3. Start the installed app
4. Download [this sample excel file](https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_10.xls) from the installed app
5. Open the downloaded excel file from the Downloads dialog
![image](https://user-images.githubusercontent.com/8770144/225588692-59b7a417-2ba5-41c9-b011-54f46ade674d.png)
6. Excel icon appears under the icon group of the installed app instead of its own icon group
![image](https://user-images.githubusercontent.com/8770144/225589022-80c0c428-8dcb-4f20-90f3-8f15d7a7a9f2.png)
7. Open any excel file now and it will appear under the same icon group instead of its own icon group
![image](https://user-images.githubusercontent.com/8770144/225589448-f65b06e4-9a29-46bf-8b88-6a657f906206.png)

**Comment by plantree** [comment] 2023-03-22 02:50
Hi @q71114,

Thanks for your materials!

I saw your examples and it seems that it is based on official samples. For convenience, I ran directly with the local WPF sample application and the excel file was opened in an individual icon group. Just like this: 

![image](https://user-images.githubusercontent.com/20148487/226788760-e68117b1-3b84-474e-ad09-0bd1db621ba4.png)

I'll try to build the installer with my own signed certificate, and if it's convenient for you, can you check if the original sample apps are working properly?

**Comment by q71114** [comment] 2023-03-22 09:58
> I saw your examples and it seems that it is based on official samples. For convenience, I ran directly with the local WPF sample application and the excel file was opened in an individual icon group. Just like this:

Did you test with an installed WPF app? It's only reproducible with an installed app.
If so did you make sure that Excel wasn't running before you started the test?

> can you check if the original sample apps are working properly?

It seems to be a WiX project for the C++ sample app, so a bit different than what I linked, but I can give it a try.

**Comment by Shangminx** [comment] 2023-04-11 09:54
Hi @q71114 , I reproduced this issue. Yes, the excel icon is displayed under the webview2 app icon exactly. But I don't think it is an issue about webview2. Because you can run the exe file(**under WindowsApps folder**) directly, and find the subprocess icon displayed correctly. 
Three process view in Process Explorer:
![image](https://user-images.githubusercontent.com/119831188/231123968-a81567fd-c135-4d3e-81d0-454822983bd1.png)
I think it is a mechanism of MSIX package. According to https://learn.microsoft.com/en-us/windows/msix/overview,  _The MSIX app process and its child processes run inside the container and are isolated using file system and registry virtualization._

**Comment by q71114** [comment] 2023-04-11 10:52
Hi @Shangminx,

I disagree about this not being a WebView2 issue because it was working fine in version `107.0.1418.26` and seems to be broken since `109.0.1518.78`.  You can check it by trying the same thing using a packaged WebView `107.0.1418.26` and it should work properly.

**Comment by Shangminx** [comment] 2023-04-28 10:54
@q71114 , I'm investigating this. I think it's related to the package identity(AppUserModelID) of subprocess inheriting.

**Comment by pdolanjski** [comment] 2023-06-15 17:11
@Shangminx, are there any updates on this? We're getting many user complaints that this bug breaks navigation via the taskbar in Windows since many apps are forced into one icon group.

**Comment by Shangminx** [comment] 2023-06-16 06:45
@pdolanjski , We have already found a workaround for this. This item is tracked in our backlog. Will fix it soon.

**Comment by pdolanjski** [comment] 2023-09-14 04:08
Could you please update us on the status, @Shangminx / @victorhuangwq ? When can we expect the fix to land?

This bug is completely breaking the ability for many users to use our app, because if you close the instance of our app, but another app (like Zoom) is still open and erroneously grouped in with our app's icon, then clicking our app's icon in the taskbar doesn't actually launch our app. See the attached example:
![WebViewIconIssue](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5330819/15e18898-d013-4d86-bbe9-6b34914419c1)

This is causing users to think our app is broken, or they are forced to close all windows under our app's icon (which is confusing since the other grouped in icons aren't our app at all).

**Comment by Shangminx** [comment] 2023-09-18 08:20
@q71114 @pdolanjski , I checked in the fix to canary version last week. You can use the canary runtime to test it.

**Comment by lezzi** [comment] 2023-09-18 17:05
Hi @Shangminx, I tested the latest Canary today, looks like there is a good improvement overall, but regression for Zoom is still there. Let me share below the tests I did:
* Canary 119.0.2108.0 (latest)
  * Excel (open file) - ✅works properly (fixed).
  * Teams (install) - ✅works properly (fixed).
  * Discord (install) - ✅works properly (fixed).
  * Zoom (join meeting) - 🟥 still shows as a subprocess under the same taskbar icon (not fixed), a regression compared to the 107.0.1418.26 runtime. 
* Evergreen 116.0.1938.81
  * 🟥 All mentioned apps don't work as expected and are displayed under the same taskbar icon.
* Old 107.0.1418.26
  * ✅ All mentioned apps work properly and are displayed under their own taskbar icons.

For tests, I used the steps from the https://github.com/MicrosoftEdge/WebView2Feedback/issues/3245#issuecomment-1471690071 and pointed the app to different runtimes (a test app must be packaged and installed).
<img width="125" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/5619119/eb660ec5-85ad-4069-ab35-b0e04ed8f92e">

**Comment by Shangminx** [comment] 2023-09-26 00:54
@lezzi , I will checkin a fix soon for opening an external app like zoom.

**Comment by pdolanjski** [comment] 2023-10-26 03:24
@Shangminx should we expect the fix for zoom coming soon?

**Comment by Shangminx** [comment] 2023-10-26 03:28
@pdolanjski yes, my fix code is in PR.

**Comment by Shangminx** [comment] 2023-11-20 07:12
@pdolanjski @lezzi , I checked in the fix PR, you can test it in canary env.

**Comment by pdolanjski** [comment] 2023-11-21 18:46
Thank you, @Shangminx.

We re-tested Zoom, Discord, Teams, and Adobe PDF reader and they all work as expected now (same as prior to the regression).

**Closed** 2024-04-03 22:33 UTC
Labels: bug, tracked
