### ISSUE TITLE
WPF app when running in background using edge webview results in msedgewebview2.exe consuming high CPU

### ISSUE THREAD

**Issue by RSN1907** [MicrosoftEdge/WebView2Feedback#3207] opened 2023-02-09 16:21 UTC
**Description**

I have a WPF based application which uses edge webview , however when WPF app is running in background (mainly it will be hidden by giving negative coordinates )  msedgewebview2.exe consumes high CPU (0.3-0.5) consistently , however once WPF app is visible CPU usage comes back to less than 0.1 which is ok

**Version**: Microsoft Edge Webview2 runtime 109.0.1518.78
SDK: 
Runtime: 
Framework: WPF
OS: Win10

**Repro Steps**

WPF app hidden in background will result in msedgewebview2.exe consume consistent high CPU usage between 0.3 -0.5 

CPU usage of msedgewebview2.exe should be low

**Screenshots**

**Additional context**

[AB#43584561](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43584561)

**Comment by Srinivass0704** [comment] 2023-02-09 18:01
@champnic  Which traces would help you in debugging this issue from msedgewebview2 perspective

**Comment by champnic** [comment] 2023-02-10 20:14
Hey @Srinivass0704 - Thanks for the bug report and sorry you are hitting this. This is indeed a strange finding. Are you seeing this with any basic WPF app or just your app specifically?

**Comment by Srinivass0704** [comment] 2023-02-12 07:11
@champnic  Thanks for checking, I haven't tried with other apps yet,  but seen consistently with my app. Will collecting any specific traces help?

**Comment by champnic** [comment] 2023-02-16 01:41
@RSN1907 An ETW trace would probably be the most helpful in this case:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md

**Comment by RSN1907** [comment] 2023-02-16 06:34
@champnic  I will collect traces and upload,thanks

**Comment by RSN1907** [comment] 2023-02-22 15:37
@champnic  @novac42  Can you share your mail id so that I can share the etw trace

**Comment by champnic** [comment] 2023-02-22 22:55
You can email me at `champnic@microsoft.com`

**Comment by RSN1907** [comment] 2023-02-23 08:37
@champnic  I have mailed traces,can you kindly check,thanks in advance

**Comment by RSN1907** [comment] 2023-02-27 09:53
@champnic  @novac42  Did you receive the traces sent via gmail?

**Comment by champnic** [comment] 2023-02-28 20:03
Sorry about that - found the email and responded.

**Comment by champnic** [comment] 2023-02-28 23:33
Hey @RSN1907 - Can you take the trace again but use this file? https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/WebView2_CPU.wprp

It looks like the current trace doesn't include CPU sampling. The GPU usage does indicate something might be getting drawn. Is there a reason you are using negative coordinates to hide the app instead of hiding the application (and setting the WebView2 visibility to false)?

**Comment by RSN1907** [comment] 2023-03-01 13:53
@champnic  Thanks for looking, I have mailed traces as suggested, can you kindly check ? there are no animations running

**Comment by champnic** [comment] 2023-03-01 23:11
Hey @RSN1907 - It does look like the page is running some animations. The trace is showing an animation tick function getting hit. If you use a completely blank page like `about:blank` or a really simple HTML page, do you still see the issue? You can also try using the DevTools to see if you can find where an animation may be coming from: https://developer.chrome.com/docs/devtools/css/animations/

**Comment by RSN1907** [comment] 2023-03-02 15:09
Thanks @champnic  for pointers I will check and get back

**Comment by RSN1907** [comment] 2023-03-12 14:32
@champnic  When I dont run the animation I am not seeing the issue, is there anything that can be done to resolve this issue while running animation?

**Comment by champnic** [comment] 2023-03-13 19:45
Hey @RSN1907 - Glad you found the animation. If I'm understanding correctly, the main issue is that when the WPF is in foreground it doesn't consume much CPU, but when moved offscreen it consumes more CPU? If you just make a different app take foreground (but don't offscreen the WPF app) do you see the same thing? I'm wondering if it's related to being foreground/background, or if it's due to being offscreen.

**Comment by RSN1907** [comment] 2023-03-14 08:48
@champnic The main issue is when the app is offscreen animation will be run and we are seeing the high CPU in this flow, once app becomes foreground we wont be running the animation, so we can conclude problem is with animation running consuming high CPU

**Comment by champnic** [comment] 2023-03-14 18:33
Hey @RSN1907 - There's probably not much you can do - do you need to run the animation? As often? Decrease the code you are executing in the animation?

I'm going to Close this issue as it seems to be By Design that we are consuming CPU because of the running animation. Thanks!

**Closed by champnic** 2023-03-14 18:33 UTC
Labels: bug, tracked
