### ISSUE TITLE
Webview runtime cannot be downloaded from Windows 7

### ISSUE THREAD

**Issue by jfgimenezx** [MicrosoftEdge/WebView2Feedback#1230] opened 2021-04-27 19:42 UTC
Hi,

if you try to download the runtime from Windows 7, you always get an error. It seems it's related to a certificate issue. These are the messages I get in spanish:

- Internet Explorer 11:
   "Existe un problema con el certificado de seguridad de este sitio web."
   ...

- Edge Chrome:
   "Su conexión no es privada.
   Es posible que los atacantes estén intentando robar tu información de msedge.sf.dl.delivery.mp.microsoft.com (por ejemplo contraseñas, mensajes o tarjetas de crédito)." 

It happens by downloading any of them: link, bootstrapper, evergreeen installer or fixed version.

BTW, Edge Chrome can be downloaded successful. The problem is related only to WebView runtime download.

Well, I know that Windows 7 is old and deprecated, but I have a few customers running it yet  :-(

[AB#32973367](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32973367)

**Comment by champnic** [comment] 2021-04-29 20:41
Thanks for the bug report @jfgimenezx. I'll forward this info on to our website team. Can you include the exact url you are navigating to? Is it:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?

**Comment by jfgimenezx** [comment] 2021-04-30 10:16
Hi @champnic,
yes, thats the url. Also, I tried .../es-es/... to see the webpage in spanish, but the same result.
Thanks!

**Comment by champnic** [comment] 2021-11-05 22:27
Hey @jfgimenezx - Sorry for the delay here. We were unable to reproduce the issue, so I'm going to close it out. Let me know if you are still running into it. Thanks!

**Closed by champnic** 2021-11-05 22:27 UTC
Labels: bug, tracked
