### ISSUE TITLE
URL redirection not working in Runtime 92.0.902.55 and above

### ISSUE THREAD

**Issue by foodcorner** [MicrosoftEdge/WebView2Feedback#1581] opened 2021-07-29 11:06 UTC
Hi,

We are facing  issue .After Updating Microsoft Edge WebView2 Runtime 92.0.902.55 . Redirection not working like my URL IP:Port/web#login?name=ram when console window.location whole URL not printing (only printing upto /web ) before that in older version it was working fine . Kindly help in priority it is buggy version .I already register issue but no response from Microsoft and Webview2 team .

https://docs.microsoft.com/en-us/answers/questions/490882/microsoft-edge-webview2-runtime-92090255-issue.html

Thanks
Prithvi

Window 10 

[AB#38467094](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38467094)

**Comment by champnic** [comment] 2021-08-04 05:17
Hey Prithvi,

This is the correct forum for reaching the WebView2 team. Looks like you are already getting some help on the other thread though. Do you have a sample that reproduces the issue? I noticed that on one example you are using localhost (127.0.0.1) IP and on the other example it looks like maybe a production IP (hence it being crossed out?). Could that be the issue here?

Thanks!

**Comment by foodcorner** [comment] 2021-08-04 09:49
Hi Nic Champagne Williamson, 

   It is also producing in production IP . If you want I share my screen . 
   
   Thanks 
   Prithavi Raj Nagar

**Comment by champnic** [comment] 2021-08-04 15:56
Thanks for the info. 
* Do you still see the issue if you load the page in Microsoft Edge or Google Chrome browsers?
* Do you still see the issue if you use a newer version of the runtime? https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel
* Do you still see the issue if you use an older version (through Fixed Version)? 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
![image](https://user-images.githubusercontent.com/45700886/128213695-27a77d1c-5603-469f-89cb-31030c705b8f.png)

**Comment by foodcorner** [comment] 2021-08-09 11:27
Dear 

1. Do you still see the issue if you load the page in Microsoft Edge or Google Chrome browsers?
Ans : I tried with Chrome and MSEdge it is working fine with that .It is happening for latest web view2 . 

2. It is also occurring for latest browser . 

Thanks 
Prithavi

**Comment by champnic** [comment] 2021-08-10 20:32
Thanks for verifying. I've added this bug to our backlog!

**Comment by lamposu** [comment] 2022-03-09 03:45
I found an issue that the parameters in url will missing when rediraction, Chrome is correct.
![Chrome](https://user-images.githubusercontent.com/34417123/157368732-d953ce5d-e28b-45f1-8a26-a1cc894f169f.jpg)
![webview2](https://user-images.githubusercontent.com/34417123/157368749-142bc5f5-1375-4bd1-86a6-d91bc554798d.jpg)
:

**Comment by champnic** [comment] 2022-03-09 04:15
Hey @lamposu - Unless I'm missing something, aren't those params set and returned by the server? Is the server looking at the user agent string and deciding to not add the params?

**Comment by lamposu** [comment] 2022-03-09 05:20
@champnic I don't known exactly, The webpage is provide by others. The params is set in the url, the redirection maybe happen in Nginx RPProxy, http redirect to the https, and the Edge browser result is the same with Chrome, only webiew2 has problem.

![Edge](https://user-images.githubusercontent.com/34417123/157377932-6519e477-7c08-444a-b7a3-1e19a6a6e982.jpg)

**Comment by champnic** [comment] 2022-03-09 18:55
Can you try taking some network logs?
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/diagnostics.md#network-logs

Is there anyway we can try to repro this, using an url or a sample app?

**Comment by abhishek1234321** [comment] 2022-05-05 04:38
> 

That is because we were redirecting the URL, it is the popup window and not the main window, I will record a video and put it here in sometime

**Comment by champnic** [comment] 2023-03-04 05:59
This is fixed in runtimes 102.0.1218.0+. Thanks!

**Closed by champnic** 2023-03-04 05:59 UTC
Labels: bug, tracked
