### ISSUE TITLE
Webwiew2 ExecuteScripts on HostObject fails 

### ISSUE THREAD

**Issue by rajankapadia** [MicrosoftEdge/WebView2Feedback#2977] opened 2022-11-16 15:09 UTC
**Description**
we are using Webview2 win32 control in our application with ExecuteScripts to call the CPP code exection. once we have updated webview2 runtime version from 98 to 102 we have started seeing sometime this executescript on CPP Hostobject is not returing any result. 

**Version**
SDK: WebView2.1.0.1418.22
Runtime: Microsoft.WebView2.FixedVersionRuntime.107.0.1418.42.x86 
Framework: win32
OS: win10 Enterprise

**Repro Steps**
we are using Webview2 win32 control in our application with ExecuteScripts to call the CPP code exection. once we have updated webview2 runtime version from 98 to 102 we have started seeing sometime this executescript on CPP Hostobject is not returing any result. 

**Screenshots**

**Additional context**

[AB#42497283](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42497283)

**Comment by victorthoang** [comment] 2022-11-18 19:17
Hello @rajankapadia,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by david-risney** [comment] 2022-11-18 19:20
Do I understand correctly that you are implementing your own C++ based IDispatch object and you are calling AddHostObjectToScript to make that object available in script, and then you are calling ExecuteScript to inject script that interacts with the IDispatch object you added?

What does the injected script do and what was it returning and what, exactly is it returning now?

**Comment by rajankapadia** [comment] 2022-12-05 06:32
Hi @victorthoang  and @david-risney  : Do let me know if we want to provide sample code to reproduce this issue. what will be best way to share the sample code as a working APP for VC++ code?

**Comment by david-risney** [comment] 2022-12-05 17:52
Code that reproduces the issue would be great! If you are able to share via a github project that would work well.

**Comment by rajankapadia** [comment] 2022-12-06 13:33
Thank you @david-risney for help .
We will work on creating sample code.

Meanwhile, I have try to capture additional debugging logs to understand this issue using below flag in my code.

![image](https://user-images.githubusercontent.com/10866173/205925743-3850d71e-9954-4a31-a1c5-0e0ce13d86f0.png)

but webview log is not capturing the CPP HOSTOBJECT call. is there any additional setting we have to use?

**Comment by vsp09** [comment] 2023-01-12 10:13
Hi @david-risney,
Here is the repo [webview2_issue](https://github.com/vsp09/webview2_issue) for sample application where we have added the required information in REDME.md file with problem statement.

**Comment by david-risney** [comment] 2023-01-12 18:42
Thanks. Is the github repo missing the samplepage.html file I see referenced in the code?

**Comment by vsp09** [comment] 2023-01-12 18:49
Hi @david-risney, this file available inside the Debug folder.

**Comment by david-risney** [comment] 2023-01-12 18:50
Oh I see. Thanks!

**Comment by rajankapadia** [comment] 2023-01-16 07:10
Hello @david-risney , 
Thank you for helping us on resolving this issue.  
Are you able to reproduce this issue in your environment with sample code provided by @vsp09 ?
Please let us know if any help needed to recreate this issue.

Any tentative release timeline when this issue will be resolution will be available in webview2 build?

@victorthoang 

Thanks,
Rajan

**Comment by rajankapadia** [comment] 2023-01-20 05:12
Hi @david-risney , @victorthoang  Any more update on this bug?

Thanks,
Rajan

**Comment by david-risney** [comment] 2023-01-20 17:13
Sorry I don't have an update yet.

**Comment by rajankapadia** [comment] 2023-01-24 06:00
@nishitha-burman FYR. Can we get the tentative date for this bug fix? we have to plan our product release with this fix.
Thank you.

-Rajan

**Comment by nishitha-burman** [comment] 2023-01-27 00:01
Hello,

We have someone looking at the issue. @rajankapadia & @VikramPawar09 the repo link here https://github.com/MicrosoftEdge/WebView2Feedback/issues/2977#issuecomment-1380101051 shows me an error page.

**Comment by VikramPawar09** [comment] 2023-01-27 13:22
Hi @nishitha-burman,
            
Thank you for the update. Can you try to access the repo again?

**Comment by monica-ch** [comment] 2023-01-27 23:52
@rajankapadia and @VikramPawar09 Looks like the issue is not reproducible in upcoming WebView2 Runtimes 110+.  Can you test the sample app using Edge beta channels and confirm it works?

Steps to test a WebView2 app using preview channels : https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Beta binaries are located here C:\Program Files (x86)\Microsoft\Edge Beta\Application\WebView2Version

**Comment by rajankapadia** [comment] 2023-01-30 11:26
Thank you @monica-ch .  we will download the beta and confirm if issue is reproducible in our env or not.
May we know more details on what was Rootcause and fixes has fixed this issue in Beta version? This will help us to know little better in future when we update the Webview2 version. 
 How we ensure this kind of issues will not visible again when we move our application support to EVERGREEN?

Thank you for support again.

@nishitha-burman 
@VikramPawar09 

-Rajan

**Comment by VikramPawar09** [comment] 2023-02-02 12:26
Hello @monica-ch,

We have tested sample application & our product application, it' working with the WebView2 Runtimes v110.0.1587.30 (Edge beta). Thank you for the quick help !
Also as mentioned in  [#2977(comment) ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2977#issuecomment-1408453202) by @rajankapadia may we know more details about root-cause and fix has done for related to this issue. 

@nishitha-burman Any tentative release date for stable version of WebView2 Runtime v110.

Thank you !
Vikram Pawar

**Comment by monica-ch** [comment] 2023-02-03 05:32
@VikramPawar09 and @rajankapadia Thanks for the confirmation, we are still investigating to find out the details of the root cause and fix that fixed in 110. I'll update the thread once I have more details.

The rollout for stable WebView2 runtime version 110 is scheduled for end of next week.

**Comment by monica-ch** [comment] 2023-02-06 06:42
@VikramPawar09 and @rajankapadia 

We are actually failing to unregister a dispatch event before adding a new one for a frame causing to ignore the new dispatcher. When host object call result comes back, we don't have a dispatch at all as we released it for another script context.

This is related to the ExecuteScript API, when the script context was destroyed mojo interface is still valid and not released immediately that causing the issue. While in 110 we fixed an issue to release the mojo interface when script context was destroyed before a new page is established. That means the dispatcher registered was released before a newer one is registered again.

However, to make the fix robust, we always unregister possible disptacher for the same frame when registering a new one. I'll let you know when this fix is in to re-verify the changes.

As we register/unregiser of dispatchers more robust, there shouldn't be any issues in future.

**Comment by monica-ch** [comment] 2023-02-08 20:48
@VikramPawar09 We made register/unregister dispatch events more robust, and change is in Edge Canary 112.0.1670.0+. Can you re-test using the canary channel (it should match with result of 110 runtime).

When you update the Webview2 app to use with Evergreen runtime, we recommend the WebView2 app to test regularly against a Microsoft Edge preview channel (Beta, Dev, and Canary).

**Comment by monica-ch** [comment] 2023-02-10 17:34
Closing the issue as it is fixed in WebView2 Runtimes 110+.

**Closed by monica-ch** 2023-02-10 17:34 UTC
Labels: bug, tracked

**Comment by rajankapadia** [comment] 2023-02-14 04:46
Thank you @monica-ch and @nishitha-burman for helping us in fixing this issue.

@VikramPawar09

**Comment by VikramPawar09** [comment] 2023-02-15 05:01
Hi @monica-ch,
We have tested our product application on Edge Canary 112.0.1681.0 and its working as expected without any issue. 

@nishitha-burman 
@rajankapadia
