### ISSUE TITLE
SaveAs functionality

### ISSUE THREAD

**Issue by jgrahovac** [MicrosoftEdge/WebView2Feedback#1090] opened 2021-03-18 16:54 UTC
I'm using WebView2 in C++. How can I implement SaveAs option from right click menu? It is supposed to launch SaveAs dialog to save html file.

[AB#32723386](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32723386)

**Comment by lungareakshay** [comment] 2021-03-20 06:30
Hi @jgrahovac,

Not sure how to implement it is the C++. But if you have implemented already it and it is not working, it might be due to you are running application in Administrator mode. I have faced similar problem. I had WPF application where I was using SaveAs and Print functionality of WebView2, but it was not opening SaveAs dialog box. It was due to Admin mode.

Hope this might help you. Happy Coding :)

Thanks,
AkshayL

**Comment by champnic** [comment] 2021-03-23 00:24
If this is the admin/elevated issue, we are tracking that in #802. Otherwise I would expect this to just work.

**Comment by rgup63** [comment] 2021-04-19 05:59
Does webview2 support `ShowSaveAsDialog()` to open save dialog box?  I can see same is supported in IE based web browser like this` WebBrowser.ShowSaveAsDialog();` . I am looking for something similar to this in webview2.

**Comment by champnic** [comment] 2021-04-19 21:25
@rgup63 No we don't support that as a WebView2 API today. Do you want me to open that as a feature request?

**Comment by rgup63** [comment] 2021-04-21 04:29
@champnic Yes please, I think we should have this feature in webview2 also.

**Comment by champnic** [comment] 2021-04-21 18:09
Done :)

**Comment by szanto90balazs** [comment] 2021-10-21 15:03
Hi @champnic 👋 

Any update on this one? It would be a very useful feature to programmatically trigger the "Save As" flow, since the `Ctrl+S` hotkey is disabled (which is documented here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features). Currently the only available option is to use the context menu. This way it's not possible to add the "Save As" to the main menu and assign a hotkey to it.

The only way "Save" can be triggered, if customization is made to the context menu. Still, this is only restricted to the context menu and it's also an experimental feature as of today. 

Last, I think it would worth removing the `Ctrl+S` input gesture text from the "Save As" context menu item, as it is disabled on purpose.

![image](https://user-images.githubusercontent.com/1934067/138304994-e903e1a1-1e18-45db-86c0-e1fd4dac1247.png)

Thanks in advance!

**Comment by JasonJShuler** [comment] 2022-02-09 01:57
Just dropping a line - I assumed this capability would be available and wasted 6 hours today.

Also, WHY ISN'T THIS OPEN SOURCE???

This is exactly the sort of thing that should be - it boggles the mind in fact. You wrote a closed-source, verifiably half-a**ed web browser control for your open-source-based browser to be used on your open source dev platforms... and you made it closed.

No DOM, no ability to save pages... this remains a HUGE regression from the IE controls. I'd be better of reparenting the window or some whacky alternative.

**Comment by nishitha-burman** [comment] 2022-06-08 23:33
Hello,

You can use JavaScript APIs to implement SaveAs. Here is an example:
```typescript
var request = new XMLHttpRequest();
request.open("GET", "https://www.bing.com/");
request.responseType = "text";
request.send();
request.addEventListener("loadend", loadEnd);
async function loadEnd(e) {
    const content = request.responseText;
    const opts = {
        types: [{
            description: 'html file',
            accept: { 'text/html': ['.html'] },
        }],
    };
    const handle = await window.showSaveFilePicker(opts);
    const writable = await handle.createWritable();
    writable.write(content);
    writable.close();
}
```

Let us know if this works!

**Comment by szanto90balazs** [comment] 2022-06-09 19:06
Hello @nishitha-burman,

We aim to download all the assets related to the page. If I understand it correctly, the proposed solution only downloads the HTML page, but not the other assets (CSS, JS, image files, ...) as opposed to the browser's SaveAs functionality.

**Comment by nishitha-burman** [comment] 2022-06-14 17:18
Hi @szanto90balazs,

Thank you for your reply. We are currently investigating. Some follow-up questions: 
1. Can you please describe your scenario where you would like to use SaveAs programmatically?
2. Would you like this functionality triggered by any hotkey? 
3. What file format(s) would you like to save the file as? 
4. Do you want to save the assets into different folders or everything in one file?

Thank you,
Nishitha

**Comment by szanto90balazs** [comment] 2022-06-16 18:41
@nishitha-burman I'll try to answer your follow up questions:

> Can you please describe your scenario where you would like to use SaveAs programmatically?

From the context menu, from any WPF menu which might be shared globally across webview instances or using a global hotkey

> Would you like this functionality triggered by any hotkey?

Yes.

> What file format(s) would you like to save the file as?

The same formats that's offered by the "Save as" dialog triggered from the context menu.

> Do you want to save the assets into different folders or everything in one file?

It would be good enough to stick to the same formats provided just like Save As does.

![image](https://user-images.githubusercontent.com/1934067/174142153-f5d48bc0-aa27-4fc6-bf5c-e1e38da7a084.png)

@yildirimcagri Good idea, I'll look into it.

**Comment by szanto90balazs** [comment] 2022-07-26 09:31
@yildirimcagri The workaround you suggested worked great. I was also able to override the global Ctlr+S shortcut, so I can trigger SaveAs using key bindings.

This SO post helped significantly with the implementation: https://stackoverflow.com/questions/6554494/how-can-i-send-a-right-click-event-to-an-automationelement-using-wpfs-ui-automa

Works with multiple displays as well, but the example code needs to be changed to get the screen the WebView2 is displayed on.

**Comment by nishitha-burman** [comment] 2022-07-26 22:44
Sounds good, thanks for the update @szanto90balazs. Closing this issue since the workaround works.

**Comment by champnic** [comment] 2022-08-17 18:30
We've removed the "Ctrl+S" hotkey text from the context menu, and it should be in runtime versions 105.0.1340.0+.

We're also going to reopen this issue to track future improvements to invoking SaveAs. While there is a workaround that exists, it's relatively cumbersome and non-intuitive.

**Comment by champnic** [comment] 2022-08-18 19:25
@Mips128 from issue #2654 was also asking for the ability to set a path and type when saving to avoid launching the dialog and initiate the save silently.

**Comment by Mips128** [comment] 2022-08-19 12:52
@champnic thanks for integrating this feature request into this ticket. I just want to point out that the discussed work around does not work in our case, due to the save dialog that appears.

**Comment by Mips128** [comment] 2022-11-11 09:37
I just want to kindly ask the following two questions: 
Do you have any news regarding this feature request? Do you know if and when it will be implemented?

**Comment by nishitha-burman** [comment] 2022-11-11 21:21
Hi @Mips128,

This feature request is in our backlog and something we will be looking into next year.

**Comment by nishitha-burman** [comment] 2023-01-12 22:17
Hello,

We are looking into this feature and I have a couple of questions:
1. What kind of file types are you looking for support with the SaveAs functionality (e.g. HTML pages, PDF, images, video, etc.)?
2. Are you looking to build your own SaveAs dialog, trigger a built in one, or require no dialog (silent SaveAs)? 
3. If you want to use a built in SaveAs dialog, what kind of customizations do you require? 
4. Do you require to set a default file path to save the file in?

Thank you!

**Comment by mikkelmogensen** [comment] 2023-01-12 22:39
I am looking to build my own SaveAs dialog for HTML pages, PDF, images, video, etc

**Comment by donid** [comment] 2023-01-19 08:31
@nishitha-burman 
Hi, I have been hoping that WebView2 would implement SaveAs for quite a while.
For me, the MHTHML format would be most important, so that I can save (archive) a whole page.
Similar to PrintToPdfAsync and PrintToPdfStreamAsync it is always useful to be able to specify a filename or to receive a stream instance. This would provide great flexibility and the SaveAs API would be consistent to PrintToPdf.

**Comment by nishitha-burman** [comment] 2023-01-26 23:32
Thank you for the feedback @mikkelmogensen and @donid. We are currently working on a SaveAs API and I would like to better understand your requirements. @donid are you looking to build your own SaveAs dialog or trigger the built-in SaveAs dialog? Are you also looking for an API to close the dialog? 

Thanks!

**Comment by donid** [comment] 2023-01-27 05:54
@nishitha-burman 
I am very happy to hear that this feature is in progress.
My use-case would be to save pages as MHTML to  a common folder that has been configured in advance - so, I would not need to use the built-in SaveAs dialog.

**Comment by nishitha-burman** [comment] 2023-01-27 18:46
@donid Thanks for the details. To clarify, you don't require any SaveAs dialogs (custom or built in)?

**Comment by donid** [comment] 2023-01-27 19:28
@nishitha-burman 
I am planing to use the SaveAs (MHTML) feature in a WinForms application. Maybe I will (optionally) allow the user to specify a filename by invoking the SaveFileDialog component that is provided by WinForms. Even if I would allow the user to choose the file format, that could easily be done with that component. So, I don't see any advantage in having api-access to WebView2's SaveAs dialog. Another scenario where I might use the new SaveAs feature is automated saving of web-pages, controlled by a command line interface (no dialogs at all).

**Comment by AndreaMontanari89** [comment] 2023-01-27 19:46
> 

Same scenario for me, can't wait for this feature! ✌️

**Comment by nishitha-burman** [comment] 2023-02-08 17:54
@mikkelmogensen can you provide more details on your scenario for PDF, images, video? Are you looking support for a scenario where you save the whole page that contains images, pdf, video or the scenario where end user hovers over an image or pdf and do "Save-image-as"?

**Comment by mikkelmogensen** [comment] 2023-02-08 19:14
@nishitha-burman 
Thanks for providing this feature
I am looking for both.

I have built my own dialog window for DownloadStarting and now I am looking to build my own SaveAs dialog for complete webpage and PDF and link and image and video.

Maybe some along the lines of SaveAsStarting

I would also like to build my own open/upload dialog, which I don't believe is possible yet, but maybe I will have to open a separate issue?

**Comment by 5JjLF5jFEhfRU** [comment] 2023-02-22 23:44
All I'm ideally looking for is to have me set the path silently & save the page as a MHTML file

**Comment by first-zhangwei** [comment] 2023-05-12 05:22
@nishitha-burman @champnic 
I have a similar scenario: I have added a custom context menu item and upon clicking it, I can get a download link through the ContextMenuTarget. The problem is how can I start a download task to download the file pointed by this link? Is it possible to support both silent download and non-silent download? Oh, one more question, does Webview2 use multi-threaded downloading by default?

**Comment by mikkelmogensen** [comment] 2024-04-29 20:46
A TotalBytesToReceive property would be appreciated for SaveAsUIShowing event

**Comment by nishitha-burman** [comment] 2024-07-03 17:50
Hello, the [SaveAs API](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#experimental-apis-2) is now available as experimental. Please give it a try and let us know if you have any feedback!

**Comment by nishitha-burman** [comment] 2024-08-13 16:34
Hello, the [SaveAs API](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#promotions) is now available as stable 🎉🎉 Please open this issue if you have any questions/concerns.

**Closed by nishitha-burman** 2024-08-13 16:34 UTC
Labels: feature request, tracked
