### ISSUE TITLE
Access file explorer from webview2 control

### ISSUE THREAD

**Issue by pvr20** [MicrosoftEdge/WebView2Feedback#1817] opened 2021-10-12 03:36 UTC
Hi all,
I am enhancing a winform app to replace webbrowser control with webview2 control.
It calls a third party URL which has a drag,drop and browse files option. Web browser control opens local file explorer to upload the  files, but webview2 control doesnt open file explorer. 
Can anyone give some leads on how to enable this on webview2?

Thanks !

**Comment by d2phap** [comment] 2021-10-12 09:01
You can use C# to open File picker, then send a message to the webview2:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms#step-8---communication-between-host-and-web-content

Or use JavaScript, then send message to backend
```js
// Use Input element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
const filePicker = document.createElement('input');
filePicker.type = 'file';
filePicker.onchange = (e) => {
  console.log(e.target.files);
}


// Use File System API: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker
const selectedFiles = await window.showOpenFilePicker();
```

**Comment by animalis007** [comment] 2022-11-14 18:53
> > @pvr20 If you open that same page in the Microsoft Edge browser does it behave as you expect? We should be matching the behavior of the browser for file uploads, so it might be a bug if there's a difference.
> > I just tried going to Onedrive in my sample app and "Upload" > "Files" opened the file upload dialog as expected.
> 
> @champnic, It works on Microsoft Edge browser. It just doesnt work in webview2 control inside my app. I am not sure if there is some config/setting that I am missing. Could you share how you have initialized the webview2 control in your sample app?

Did you ever figure this out? I am having the same issue. Works in Edge, but in my app clicking on the input does nothing. It does  flash a spinning circle for a few milliseconds then disappears.

**Comment by champnic** [comment] 2022-11-14 19:49
@animalis007 Can you share some info on your app? Or maybe a sample which reproduces the issue? If you are building a UWP/WinUI2 app, then we only just added support for that and it may not be available in your SDK or Runtime version yet.

**Comment by animalis007** [comment] 2022-11-14 20:21
It is a WinForms App used for various maintenance screens within our company. Some of these launch WebBrowser.cs to display other home built web pages. We are converting them one by one to use WebView2. Upon opening a 'screen' designated for WebView2 the WebView2 instance is initialized, then we call EnsureCoreWebView2Async with a CoreWebView2Envirnment and then we create a request with webview2.CoreWebView2.Environment.CreateWebResourceRequest(url, "GET", null, headerWithAuthToken); Lastly we call webView2CoreWebView2.NavigateWithWebResourceRequest(request);

This has worked well for all other 'screens' we have converted thus far, but this is the first instance using an input with type=file.

The html input is simple:
`<input accept=".xls,.xlsx" id="File" name="File" style="width:500px;" type="file" value="">` but upon clicking on the Browse button from the WebView2 display nothing happens other than a quick flash of a 'loading' circle. This circle in only present for maybe 100 miliseconds.

**Comment by champnic** [comment] 2022-11-14 21:14
If you try that page in a simplified WinForms app does it correctly load the file dialog there? I was unable to reproduce the broken behavior in my WinForms app using the same `<input>` that you are using. I'm not sure if you are seeing something weird due to the specifics of your app or machine.

**Comment by animalis007** [comment] 2022-11-15 15:52
> If you try that page in a simplified WinForms app does it correctly load the file dialog there? I was unable to reproduce the broken behavior in my WinForms app using the same `<input>` that you are using. I'm not sure if you are seeing something weird due to the specifics of your app or machine.

I created a generic WinForms app pointing to my same website and still could not get the file xplorer to open from the <input>. I then tried pointing the form to https://onedrive.com as suggested from previous posts and it worked however on inspecting the onedrive page the Upload button is not a standard <input> of type=file. It is a <button> with multiple embedded <span> so I'm not sure this is a valid test.

I then tried using "https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_file" as the source and again it does NOT work from my WebView2 generic app

**Comment by champnic** [comment] 2022-11-17 00:20
Can you share the test app you created? Good callout on the onedrive.com example. My sample app using the w3schools.com link you used works as expected on my machine. I'm curious if it's something to do with the host app (.NET version or framework, WebView2 version) or the host machine itself (permissions?).

**Comment by animalis007** [comment] 2022-11-17 02:21
[WindowsForms_WebView2_App.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10027151/WindowsForms_WebView2_App.zip)

**Comment by champnic** [comment] 2022-11-17 21:29
Your sample app works fine on my machine when I hit 'Run'. This may be related to something with machine configuration. 

Do file choosers work fine for you in Edge/Chrome browsers?
Do you get any errors or debug output when it fails for you, through VS or debugging tools? Any messages in the Devtools console?
Do you get any errors in the Windows Event Viewer (try under "Windows Logs > Application")?
Do you see any errors from your exe or msedgewebview2.exe when looking at procmon?
https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by animalis007** [comment] 2022-11-17 23:13
> Your sample app works fine on my machine when I hit 'Run'. This may be related to something with machine configuration.
> 
> Do file choosers work fine for you in Edge/Chrome browsers? YES 
Do you get any errors or debug output when it fails for you, through VS or debugging tools? NO
Any messages in the Devtools console? NO 
Do you get any errors in the Windows Event Viewer (try under "Windows Logs > Application")? NO
Do you see any errors from your exe or msedgewebview2.exe when looking at procmon? https://learn.microsoft.com/en-us/sysinternals/downloads/procmon hard to tell, its a bit overwhelming with info and constantly adding more even when not running. I will work on filtering the data to see if I can find anything in here

**Comment by champnic** [comment] 2022-11-18 19:19
@animalis007 Are you running your application as admin/elevated? We have a known issue where file dialogs wouldn't show when running the host app elevated. We recently checked in a fix for that but it hasn't shipped to stable yet.

**Comment by animalis007** [comment] 2022-11-18 20:00
Indeed I was. I've got VS set to always open running as Admin, so I didn't even think about that. Running the .exe directly without admin the Explorer opens as expected.

When do you think the fix for admin will ship approx? Just need a rough timeline to update my project manager with.

**Closed** 2022-11-21 21:48 UTC
Labels: question
