### ISSUE TITLE
System.DllNotFoundException at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions

### ISSUE THREAD

**Issue by henrygo2208** [MicrosoftEdge/WebView2Feedback#2820] opened 2022-09-23 12:48 UTC
i've developed a **excel vsto**. After deploying to some client computer i meet this problem. the webview2 runtime is latest version **105.0.1343.42** and the office version is **2016 pro plus** and the os is **win11**. the stack trace is as follow :
`Application: EXCEL.EXE Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(System.String, System.String, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2EnvironmentOptions, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler) at Microsoft.Web.WebView2.Core.CoreWebView2Environment+<CreateAsync>d__3.MoveNext() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at System.Runtime.CompilerServices.TaskAwaiter 1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult() at SjExcelAddIn.Components.BaseWebviewForm+<InitWebview>d__9.MoveNext() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at SjExcelAddIn.Components.BaseWebviewForm+<BaseWebviewForm_Load>d__8.MoveNext() at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object) at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() `

**Comment by yizhao5** [comment] 2022-10-18 10:00
@henrygo2208. Hello. According to your error message, it should be that the SDK of Webview2 did not find the Runtime. Please install the [Evergreen Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) of Webview2 and deploy to the default installation path. Thanks.

**Comment by henrygo2208** [comment] 2022-10-18 11:00
> @henrygo2208. Hello. According to your error message, it should be that the SDK of Webview2 did not find the Runtime. Please install the [Evergreen Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) of Webview2 and deploy to the default installation path. Thanks.

I've install runtime, but there is a weird problem: Closing the computer, one or more  days passed, the above problem disappeared.

**Comment by yizhao5** [comment] 2022-10-19 02:09
@henrygo2208. Yes, it may be caused by the environment problem. If your problem is solved, please close it. Thanks.

**Comment by henrygo2208** [comment] 2022-10-19 02:23
> @henrygo2208. Yes, it may be caused by the environment problem. If your problem is solved, please close it. Thanks.

But it is very unsure to know when the program could normally run. Do you have any thought to inspect this kind of thing?

**Comment by yizhao5** [comment] 2022-10-19 02:52
@henrygo2208. This error log shows that it is truly that the runtime of webview2 was not found. So, it can be inferred that the installation path is wrong, or an environmental problem, etc.

If there is no error, it should be running normally. If you want to verify whether your **excel vsto** calls Webview2, you can use _Process Hacker 2_ to check. Thanks.
![image](https://user-images.githubusercontent.com/109595412/196586061-b796138a-4649-49c6-b11c-1149e6be9527.png)

**Comment by henrygo2208** [comment] 2022-10-19 02:58
> @henrygo2208. This error log shows that it is truly that the runtime of webview2 was not found. So, it can be inferred that the installation path is wrong, or an environmental problem, etc.
> 
> If there is no error, it should be running normally. If you want to verify whether your **excel vsto** calls Webview2, you can use _Process Hacker 2_ to check. Thanks. ![image](https://user-images.githubusercontent.com/109595412/196586061-b796138a-4649-49c6-b11c-1149e6be9527.png)

OK. I'll try it out. Thank you very much.

**Closed** 2022-10-19 02:59 UTC
Labels: question
