### ISSUE TITLE
Mouse cursor disappears in webview2 in Windows11 touch screen mode(Windows11触屏模式下，webview2中鼠标光标消失问题)

### ISSUE THREAD

**Issue by zhaiyingwei** [MicrosoftEdge/WebView2Feedback#3485] opened 2023-05-15 08:05 UTC
Computer model: Thinkbook 14s Yoga gen 2 (with touch screen)

System version: 22H2 (OS internal version 22621.1702)

Recently, I was developing some applications at work and needed to match some touchscreens, and the mouse cursor would disappear under the WebView2 plug-in (the official documentation says WebView2 is equivalent to the Edge browser).

At this point, slide the touchpad or drag the mouse, the cursor will not appear. But after testing, I found that the mouse seems to be under the browser at this time. But it is not that the mouse or touchpad is not available, it is simply invisible.

When the touchpad or mouse is used to operate other software, the cursor will show up again, but as long as you drag it to the software interface just now, it will disappear again.
(电脑型号：Thinkbook 14s Yoga gen 2 (有触摸屏)

系统版本：22H2(OS内部版本22621.1702)

最近在工作中开发一些应用，需要对一些触摸屏进行匹配，鼠标光标就会在WebView2插件下消失不见(官方文档上说WebView2相当于Edge浏览器)。

此时，滑动触摸板或者拖动鼠标，光标都不会出现。但经过测试发现，此时鼠标好像在浏览器的下方。但并不是鼠标或触摸板不可以用，只是单纯看不见。

当把使用触摸板或鼠标操作其他软件时，光标又会显示出来，但只要拖到刚才的软件界面上，又会消失。)

[AB#44786470](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44786470)

**Comment by novac42** [comment] 2023-05-16 09:46
Hi @zhaiyingwei, may you tell us which framework are you using (UWP/Win32/WPF...?) and what's the SDK version number?

**Comment by zhaiyingwei** [comment] 2023-05-17 04:58
Hi~@novac42 ,The framework we use is MFC and the version of webview2Loader.dll is 1.0.902.49!

**Comment by novac42** [comment] 2023-05-19 07:47
Thanks. I've assigned this to a dev who can help follow up on this.

**Comment by champnic** [comment] 2023-05-19 22:48
@zhaiyingwei 1.0.902.49 is quite old. Can you try updating your SDK and see if the issue persists?

**Comment by MattSty** [comment] 2023-05-25 06:36
Facing the same issue inside an WPF (.Net 4.8) application. Used version of WebView2 is 1.0.1774.30.
Everything ist fine till I use the touch to scroll around on a web page opened inside webview. After leaving the window with webview on it mouse pointer is gone inside this application. After closing all windows (of this app) mouse pointer is back. As zhaiyingwei has written, mouse is still present, only the pointer is not visible (on mouse move over a button inside the app the button reacts to events)

**Comment by champnic** [comment] 2023-05-25 18:32
Thanks for confirming. Sounds like this affects across frameworks (at least MFC and WPF) and is present in both old and newer versions of the SDK.

@MattSty + @zhaiyingwei - what runtime versions are you using? Have you always seen this behavior, or is this a regression?

I've added this as a bug on our backlog.

**Comment by MattSty** [comment] 2023-05-25 19:34
@champnic 
Not sure which runtime you're asking for. I've used the webview the first time with wpf ...so difficult to say more on that.
As written, my issue's gone after disposing the control...

**Closed** 2023-07-10 06:50 UTC
Labels: bug, tracked, status-circle back

**Comment by exotexot** [comment] 2023-08-10 08:42
I'm having a similar issue using UWP. 

https://github.com/react-native-webview/react-native-webview/issues/3093

**Comment by champnic** [comment] 2023-08-10 23:14
What version of WinUI 2 package is being used in your example @exotexot?

**Comment by exotexot** [comment] 2023-08-11 11:43
Hi @champnic. In my react-native-windows app, react-native-webview by default loads https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1018-prerelease

In my Nuget Manager, I've tried upgrading to the lastest version 1.0.1901.177, but it fails to build because of:

`Error	APPX1111	Payload contains two or more files with the same destination path 'WebView2Loader.dll', but they are different sizes. Source files: 
C:\Users\Normelle\.nuget\packages\microsoft.web.webview2\1.0.1018-prerelease\build\native\x64\WebView2Loader.dll
C:\dev\cat7112\windows\packages\Microsoft.Web.WebView2.1.0.1901.177\build\native\x64\WebView2Loader.dll	cat72	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets	1987	`

I tried cleaning and rebuilding the solution, but it always somehow references the "1.0.1018-prerelease" version, and I can't get it to build.

**Comment by champnic** [comment] 2023-08-11 17:28
@exotexot 1018-prerelease is quite old. I'm not sure why it's keeping around the old one when you try to upgrade to the newer one. It's interesting that they are being loaded from completely different places. When you used the nuget manager, did you do so for the project or the solution? Did it show that the old version was already installed and so you just needed to update the version, or did you have to search for the package and install the newest?
