### ISSUE TITLE
synchronous call issue

### ISSUE THREAD

**Issue by sajjadarashhh** [MicrosoftEdge/WebView2Feedback#2678] opened 2022-08-13 05:39 UTC
in C# .net maui 6 Blazor Hybrid Application When we wana to call synchronously IJSInProcessRuntime we have issue with WebView 2
our issue is described more in this comment:
https://github.com/dotnet/maui/issues/5804#issuecomment-1168617027

**Comment by yizhao5** [comment] 2022-10-11 09:18
@sajjadarashhh. Excuse me. Has your problem been solved? Sorry, I had some other works some time ago.

I have git clone your sample code from your [https://github.com/sajjadarashhh/Dotnet.TestMauiFreeze](https://github.com/sajjadarashhh/Dotnet.TestMauiFreeze). But compile error.

Can you tell me **Description** and **Repro Steps** of the template, so we can help you solve the problem faster and better. thanks.

**Comment by sajjadarashhh** [comment] 2022-10-11 10:06
yeah i can please wait i reproduce that repo to make easier to understan our problem.
thanks

**Comment by sajjadarashhh** [comment] 2022-10-12 01:38
@yizhao5 i commit again that repo please get that and trying to start project with .net 6
that project when starting freezed due to webView2 Dont support single thread operations 
SteveSandersonMS described Here :https://github.com/dotnet/maui/issues/5804#issuecomment-1168617027

**Comment by sajjadarashhh** [comment] 2022-10-12 12:59
that errors just in your local pc you need .net 6.0.5 and Visual studio 2022 Preview to compile this project!

**Comment by yizhao5** [comment] 2022-10-14 07:24
Yes. Thanks. After I replace Visual Studio 2022 with Visual Studio 2022 Preview, I can successfully compile your project.

**Comment by yizhao5** [comment] 2022-10-14 08:07
@sajjadarashhh. Hello.

1. Cause Analysis:

Your project is a .NET MAUI Blazor app. Your problem is that the window will hang.

I've seen that comment you said and debugged it myself on my local machine. I preliminary located the problem with the following code block in the `Main.razor` file. If I remove the `@code {}` or just delete this line `JsRuntime.InvokeVoidAsync("window.location.reload").ConfigureAwait(false).GetAwaiter().GetResult();`, both work fine. But this should be your business code and I'll fix it in another way.
```cs
@code {
	[Inject]
	public IJSRuntime JsRuntime { get; set; }
	protected override async Task OnInitializedAsync()
	{
		JsRuntime.InvokeVoidAsync("window.location.reload").ConfigureAwait(false).GetAwaiter().GetResult();
	}
}
```

2. Example of fixing:

FreezeProblem\Main.razor
```cs
@code {
	[Inject]
	public IJSRuntime JsRuntime { get; set; }
	protected override async Task OnInitializedAsync()
	{
		// JsRuntime.InvokeVoidAsync("window.location.reload").ConfigureAwait(false).GetAwaiter().GetResult();
		var a1 = JsRuntime.InvokeVoidAsync("window.location.reload");
		var a2 = a1.ConfigureAwait(false);
		var a3 = a2.GetAwaiter();
		await Task.Run(() => a3.GetResult());
	}
}
```

3. Test Results: passed.

![image](https://user-images.githubusercontent.com/109595412/195794051-4f06cd81-db19-4814-9f8c-d41ccb3e31d9.png)

**Comment by sajjadarashhh** [comment] 2022-10-14 08:38
@yizhao5 yeah this ok
but we have problem in getter or setter in properties when we wana to use .GetResult windows is hanged 
try to using .GetResult in synchronous method.

**Comment by yizhao5** [comment] 2022-10-14 08:51
![image](https://user-images.githubusercontent.com/109595412/195803868-cb5950cb-e810-4961-a0fd-814bb07d9d76.png)
@sajjadarashhh. The awaiter.IsCompleted is true, which means it's done. I think it might be a problem with your business code, which keeps loading.

**Comment by yizhao5** [comment] 2022-10-14 10:45
@sajjadarashhh. Hello.

1. Cause Analysis:

I think I know why it refreshes frequently and has been hanging. Because you use `"window.location.reload"` in function `OnInitializedAsync()`. Function `OnInitializedAsync()` will be triggered again after `"window.location.reload"`. This forms a loop, so it is frequently refreshed and cannot be clicked.

2. Example of fixing:

FreezeProblem\Main.razor

```cs
@code {
	[Inject]
	public IJSRuntime JsRuntime { get; set; }
	private static bool isInited = false;
	protected override async Task OnInitializedAsync()
	{
		// JsRuntime.InvokeVoidAsync("window.location.reload").ConfigureAwait(false).GetAwaiter().GetResult();
		if (!isInited)
		{
			var a1 = JsRuntime.InvokeVoidAsync("window.location.reload");
			var a2 = a1.ConfigureAwait(false);
			var a3 = a2.GetAwaiter();
			await Task.Run(() => a3.GetResult());
			isInited = true;
		}
		else
		{
			await base.OnInitializedAsync();
		}
	}
}
```

3. Test Results: passed: **Not blank pages and hanging. And not frequently refreshed and cannot be clicked**.
![image](https://user-images.githubusercontent.com/109595412/195828118-9fbe574e-c34a-4ff4-ab73-0ed50023cbe9.png)

if it solves your problem, please close it. Thanks.

**Comment by sajjadarashhh** [comment] 2022-10-14 11:26
@yizhao5 no this not problem
We wana to use synchronous version of IJSInProcessRunTime!
That's not support by webview2
And we wana new feature that support this or tell we how to use this

**Comment by yizhao5** [comment] 2022-10-17 07:01
@sajjadarashhh. A bug is a bug. A feature is a feature.

Firstly, you didn't fill in the issue template, so I read your link https://github.com/dotnet/maui/issues/5804#issuecomment-1168617027, and [public GitHub repo](https://github.com/sajjadarashhh/Dotnet.TestMauiFreeze) and communicated, and found that it was the freeze problem of the MAUI app.
![image](https://user-images.githubusercontent.com/109595412/196079928-1933ae7b-4edd-436b-b6f4-1e27480c3336.png)
Fig. 1
![image](https://user-images.githubusercontent.com/109595412/196101814-5427f0fe-ed96-4677-be7d-e34fefc2b11b.png)
Fig. 2

[The solution](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2678#issuecomment-1278837699) for MAUI app's freeze and hang issues have been passed.
If you want to implement your development requirements, you can refer to [MSDN](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0), where there are many technical materials. Thanks.
Cc: @champnic @imicy @SteveSandersonMS

**Comment by sajjadarashhh** [comment] 2022-10-17 07:09
@yizhao5 Thank you for your described details.

**Comment by champnic** [comment] 2022-10-18 00:17
Thanks @yizhao5 for digging into this!

@sajjadarashhh It sounds like the main hang issue is resolved. For the question of supporting synchronous WebView2 methods, we don't currently have plans to do so. There isn't a way to do so that would work for most apps, and WebView2 is By Design run out-of-process, necessitating some level of async. For more info you can checkout #136 (and other relevant threads in this repo). Thanks!

**Closed by champnic** 2022-10-18 00:17 UTC
Labels: bug
