### ISSUE TITLE
webview2 -- The framework failed to start accidentally with the administrator

### ISSUE THREAD

**Issue by flashyyp123** [MicrosoftEdge/WebView2Feedback#3329] opened 2023-03-24 03:38 UTC
Hello everyone, I found webview2 with administrator startup even startup exception problem, in win10 system. Then reboot your computer and start up again
BUG:
Chromium内核初始化失败！
System.Runtime.InteropServices.COMException (0x80070490): 找不到元素。 (异常来自 HRESULT:0x80070490)
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__72.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
**Screenshots**

**Additional context**
Version :FixedVersionRuntime.108.0.1462.76.x86

**Comment by champnic** [comment] 2023-03-29 21:34
Hey @flashyyp123 - Thanks for the bug report, and sorry you are running into this.

It looks like you are using WPF WebView2 control with a Fixed Version runtime 108. 

Is the issue reproducible and you hit it consistently? Or did this only occur once? Do you have a sample app you could share that demonstrates the issue?

**Comment by flashyyp123** [comment] 2023-03-30 03:01
Yes, this is  a Fixed Version runtime. Serendipitous continuously When started with administrator privileges.An exception occurs at creation time.
Code Example:
 var env = await CoreWebView2Environment.CreateAsync(browserExecutableFolder, userDataFolder
                , new CoreWebView2EnvironmentOptions(additionalBrowserArguments: string.Join(" ", args)));
webView2.EnsureCoreWebView2Async(env);

**Comment by champnic** [comment] 2023-03-30 21:29
Can you confirm it works fine when not starting as admin?
What are the args that are getting passed in?

**Comment by flashyyp123** [comment] 2023-04-03 04:48
Yes,it is fine when not starting as admin ,the args is below:
List<string> args = new List<string>
            {
                "--lang=zh-CN",
                "--ignore-certificate-errors",
                "--no-proxy-server",
                "--disable-features=RendererCodeIntegrity,SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure,BlockInsecurePrivateNetworkRequests"
            };

**Comment by champnic** [comment] 2023-04-05 23:01
I've been unable to reproduce this issue so far. Can you share a sample app that demonstrates the issue?

**Comment by flashyyp123** [comment] 2023-04-21 03:02
I'm sorry, I can't reproduce it. It's accidental. I think it is an occasional BUG that runs 32-bit kernel on 64 machines. I will send the DMP file to you for analysis next time I meet it. The way I handle it now is the first step down weight, the second step run 64-bit kernel.

**Comment by champnic** [comment] 2023-04-21 18:05
Thanks for confirming. I'm going to close this for now, but if you do get the dump of the crash you can share it with me at `champnic@microsoft.com` and we'll take a look, and we can reopen this issue.

**Closed by champnic** 2023-04-21 18:05 UTC
Labels: bug
