### ISSUE TITLE
[Bug]: Crash when accessing new WebView2 types in WinAppSDK 1.5

### ISSUE THREAD

**Issue by softworkz** [MicrosoftEdge/WebView2Feedback#4421] opened 2024-03-13 17:43 UTC
### What happened?

There appears to be a mistake in compilation of WebView2Core bindings in WinAppSDK 1.5.

Newly added members (since 1.4) cannot be invoked.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

122.0.2365.80 (doesn't really matter)

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

22621.2506

### Repro steps

Repro project here: [softworkz/WinUI3WebView2ExtensionsBug](https://github.com/softworkz/WinUI3WebView2ExtensionsBug)
.
Or just execute this code snippet in a C# WinUI3 project, updated to WinAppSDK 1.5.240311000:

```cs
            var options = new CoreWebView2EnvironmentOptions();
            options.AdditionalBrowserArguments = "--enable-disble ";
            options.AreBrowserExtensionsEnabled = true;
```

**Comment by softworkz** [comment] 2024-03-13 17:52
I believe that this is not something for the WebView2 team, that's why I had also posted it @ microsoft-ui-xaml.

But I still have a 

## Question

Maybe you can help me out for working around this in some way. I need to add a browser extension and that's exactly what is not working: 

1 `CoreWebView2EnvironmentOptions.AreBrowserExtensionsEnabled `
2 `CoreWebView2.Profile.AddBrowserExtensionAsync()`

For 2, I found out that I can also use the command line arg `--load-extension=path-to-extension`

But I can't find something to achieve 1 in a diffeent way. I tried things like:

```cs
            arguments += "  --enable-edge-extensions  --enable-extensions  ";
           .....
            Environment.SetEnvironmentVariable("WEBVIEW2_EDGE_EXTENSIONS_ENABLED", "1");
            Environment.SetEnvironmentVariable("WEBVIEW2_EDGE_EXTENSIONS", "1");
            Environment.SetEnvironmentVariable("WEBVIEW2_EXTENSIONS_ENABLED", "1");
            Environment.SetEnvironmentVariable("WEBVIEW2_EXTENSIONS", "1")
```
...without success.

**Is there any other way to enable extensions in the WebView2?**
(registry, command line, environment, policies)

Thanks

**Comment by softworkz** [comment] 2024-03-14 05:44
I figured it out (the question for workaround - not the cause of the issue):

`CoreWebView2.Profile.AddBrowserExtensionAsync()` can be substituted by adding this

```
 --load-extension=\"{extensionDir}\" 
```

And  `CoreWebView2EnvironmentOptions.AreBrowserExtensionsEnabled ` can be replaced by this undocumented command line switch:

```
--embedded-browser-webview-enable-extension
```

**Comment by DmitriyKomin** [comment] 2024-03-27 20:36
The root cause is on the Edge side - in the CoreWebView SDK package, the interface including AreBrowserExtensionsEnabled - _ICoreWebView2EnvironmentOptions6_ - was missed from the base type of the underlying WinRT object. Closing this as duplicate of bug @softworkz opened on the Edge team.

**Comment by dianaqu** [comment] 2024-04-03 21:43
Fix will be available on next SDK release

**Closed** 2024-05-08 20:59 UTC
Labels: bug
