### ISSUE TITLE
File Open/Save Dialog doesn't show running w/ elevated privileges

### ISSUE THREAD

**Issue by hunkydoryrepair** [MicrosoftEdge/WebView2Feedback#802] opened 2021-01-10 22:00 UTC
**Description**
When running application "as administrator" (elevated), the File Open dialog will not appear from a file input element.
This is presumably because the renderer process is not elevated and so cannot display a window in an elevated process.  
Running the renderer as elevated would create other issues, such as not being able to drag/drop onto the view.

Considering some apps require elevation for a variety of purposes, this limits the usefulness of webview2. 

**Version**images.
SDK: 1.0.721 prerelease
Runtime: 87.0.664.75
Framework: WinForms
OS: Win10

**Repro Steps**
Launch WinForms sample app as administrator
Navigate to page with a file input `<input type="file">` (for example, images.google.com, click image icon and then Upload Images tag)
Hit "Choose File" button
Result: Nothing happens
Expectation: we need a mechanism to call back into our elevated app to present the File UI, and return/send back the selected files.  The DevTools call DOM.setFileInputFiles is not functional so not a viable workaround at this time.
Running Edge as elevated works as expected. Or, perhaps there is a way to get the file open dialog into the host UI thread. 

**Screenshots**

**Additional context**

[AB#31335334](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31335334)

**Comment by champnic** [comment] 2021-01-13 00:24
We generally don't support running as admin, but I think the ask to have an API or other mechanism to be able to handle the file dialog on the app side sounds reasonable. I'll add this as a scenario on our backlog. Thanks!

**Comment by darkguy2008** [comment] 2021-01-18 05:54
+1 to this issue. I was actually expecting to see an event we could hook on in CoreWebView2 but there isn't. In my case, my app is a non-admin one (although running as admin is a very valid reason too - consider an app that runs WebView2 as the frontend UI layer for an app that needs access to the system drives, like Balena Etcher, for instance. It won't be possible...).

I'm also getting the dreaded `"Value does not fall within the expected range."` when using `DOM.setFileInputFiles`, so we definitely need a way to either show our own UI, or a way to hook into it and send the filenames ourselves. Right now the current solution, as stated, doesn't work and there's no other alternatives (right?).

Appreciate all the work done here to fix this issue. Thanks!

**Comment by dhasi** [comment] 2021-01-19 10:19
+1 from me too. A kind of event would be okay for us. This behavior is currently the only reason that still prevents us from switching from CefSharp to WebView2. And as @darkguy2008 already said - really appreciate all work done in the whole WebView project!

**Comment by champnic** [comment] 2021-02-18 00:46
Per #941 this also affects "Save as" dialogs.

**Comment by beretboat** [comment] 2021-02-22 09:53
+1 to this.

**Comment by bandersen22000** [comment] 2021-02-22 13:12
I have the same issue in an WPF solution, please fix this. Print and save file Dialog, not working. I have also testet Version 1.0.790-prerelease, but it has the same issue.

**Comment by roblarky** [comment] 2021-02-28 07:45
My app runs with UIAccess in the manifest, so it runs elevated (though not as Administrator) and I cannot click a File input (probably the others as well, like other comments). 

When I run the portable version of my app (non-elevated), it opens and defaults to the root of my user folder. I'm guessing it's doing the same thing when elevated, but the context doesn't have access to the root of my user folder...?

I created a temp folder for the environment with Everyone-Full permission, but that doesn't change the behavior.

So +1 to either support an API based way to mitigate, or if the issue is the initial folder in the dialog, maybe the ability to specify the default open/save folder within the environment settings.

**Comment by chswin** [comment] 2021-11-21 20:47
Makes debugging it when elevated a pain in the butt... because to debug IIS I have to run as elevated

**Comment by daijialong** [comment] 2021-12-31 02:36
Workaround: monitor the click method of the element, call Winform's file selection dialog box, after success, transfer the file to base64 and transfer it to the page, and then convert it into a js file object.
![image](https://user-images.githubusercontent.com/36257973/147799780-032c6c32-b7b5-4139-955f-0f2f46de3715.png)

**Comment by hunkydoryrepair** [comment] 2021-12-31 18:39
> Workaround: monitor the click method of the element, call Winform's file selection dialog box, after success, transfer the file to base64 and transfer it to the page, and then convert it into a js file object. 

I need to chunk the file up to server, so this won't work. Reading a 100MB file and converting to base64 has some issues. I actually do something very similar for images, though.

There is a devtool API that is supposed to set the file in the File element, which I tried but I ran into a bug that completely blocked it. I haven't gone back to check if that has been fixed as there have been several releases since.

**Comment by daijialong** [comment] 2022-01-04 09:11
> 
Maybe you can first transfer the file slices to the Html side on the native side, and then merge them on the Html side. This can solve the problem of large files, but it will consume a lot of memory. Why not submit the submitted data to the native terminal for uploading, so that the steps are more concise

**Comment by zhurui37** [comment] 2022-01-07 11:26
Is there anything **I CAN DO** to solve this problem? my app need "requireAdministrator (/level='requireAdministrator')"(VS2017),and webview2 can not open file.

**Comment by daijialong** [comment] 2022-01-08 03:10
> Is there anything **I CAN DO** to solve this problem? my app need "requireAdministrator (/level='requireAdministrator')"(VS2017),and webview2 can not open file.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/802#issuecomment-1003245216

**Comment by champnic** [comment] 2022-03-10 23:27
FYI - the bug that was preventing `DOM.setFileInputFiles`from working has been fixed in runtimes 100.0.1175.0+. We're continuing to look into the fix for the core issue of not being able to display the dialogs properly. Thanks!

**Comment by ajtruckle** [comment] 2022-05-02 16:48
Surely any app should run as admin. Particularly when you need admin rights in compilation. Why such crippling behaviour? Please resolve... Thanks!

**Comment by logikonline** [comment] 2022-06-03 08:20
This does not work for StoreApps - it is blocking issue.  I cannot imagine any modern webview control crippling all forms.

Please address.

**Comment by champnic** [comment] 2022-06-03 18:20
@logikonline We're tracking the UWP work in #1639, and are actively working on it.

**Comment by BasketGolfer** [comment] 2022-06-10 18:56
Is there any information you can provide on the root cause of this issue to help troubleshoot / perhaps find a work around?

**Comment by champnic** [comment] 2022-06-10 19:02
The root cause is that the browser processes don't run as admin for security reasons, even if the host app runs as admin. The problem is that the dialogs are attempting to be displayed by the browser processes running at Medium IL, which don't have the ability to display on top of the High IL host app, so they appear in the background.

**Comment by BasketGolfer** [comment] 2022-06-13 13:21
Thanks for information. I was troubleshooting a project using Playwright connecting to Webview2. I've confirmed connecting Playwright to WebView2 causes this issue as well. I created an example where save as and downloading works then when you connect Playwright to the webview2, save as  and downloading stop working. I do not know yet if Playwright is somehow elevating rights or if it is a different root cause happening.

**Comment by logikonline** [comment] 2022-07-18 13:54
Can we please get a status update?

**Comment by superpapa** [comment] 2022-08-15 06:19
Can we please get a status update?

**Comment by champnic** [comment] 2022-08-15 21:34
We are continuing to work on the admin file dialogs work. I'll have another update when we get it checked into a prerelease SDK for testing. Thanks!

**Comment by caitano28** [comment] 2022-08-27 19:54
after so much racking my brains to solve it, I did the following, I downloaded the fixed version of the web view (eu depois de tanto quebrar a cabeça para resolver fiz o seguinte, baixei a versão fixa do web view)  and set your executable to run as administrator as in the example (e setei seu executável para executar como administrador conforme o exemplo) 
![image](https://user-images.githubusercontent.com/31899397/187045919-8c74694a-2d76-45bd-8fdd-a3c8ea383e24.png)
here is an example of the code I am using Winforms and BlazorWebview. (segue um exemplo do código estou usando Winforms e BlazorWebview.)
ctor()
{
      blazorWebView1.BlazorWebViewInitializing += OptWebView;
}

 private  void OptWebView(object sender, BlazorWebViewInitializingEventArgs e)
        {
            e.EnvironmentOptions = new CoreWebView2EnvironmentOptions();
            e.UserDataFolder = $@"C:\MyAplicationFolder\";
            e.BrowserExecutableFolder = $@"C:\MyAplicationFolder\WebView2";
            e.EnvironmentOptions.AdditionalBrowserArguments = "--allow-file-access-from-files";
        }

**Comment by bruce-yan** [comment] 2022-09-15 01:44
a month has passed 。。。

**Comment by cuiliang** [comment] 2022-09-16 12:38
If possible, please increase the priority of this issue a little bit. Thank you guys.   
We are developing an application using wpf with uiAccess = true. Users can not use webview2 to upload files to server for a long time. This is really a big issue.
Thank you.

**Comment by logikonline** [comment] 2022-09-16 21:25
Sadly the contract was discontinued cause this was never resolved in a timely manner.  I no longer require it.

**Comment by logikonline** [comment] 2022-10-07 19:12
I have a new prospect that will use Windows.  Can we get a status update?  Hopefully, it is near complete

**Comment by tofuandeve** [comment] 2022-10-07 19:41
Hi all, we are working on this issue and it is one of the highest priorities we're focusing on right now. The support for file dialog running on admin mode is currently under review and should be checked in very soon.

Thank you!

**Comment by tofuandeve** [comment] 2022-10-18 19:55
Hi all, just a quick update, the file dialog work for elevated host app is completed and will be available in v108 soon

Thank you!

**Comment by champnic** [comment] 2022-11-09 22:15
This is available for testing in versions 108.0.1436.0+. Thanks!

**Closed by champnic** 2022-11-09 22:15 UTC
Labels: feature request, tracked

**Comment by ajtruckle** [comment] 2022-11-10 11:53
How does that version number compare to NuGet Package 1.01418.22 ? That is the WebView2 I have.
________________________________

**Comment by ajtruckle** [comment] 2022-11-10 11:56
It doesn't work with my latest NuGet package 1.01418.22.
________________________________

**Comment by champnic** [comment] 2022-11-10 21:25
You need to use a runtime that is version 108.0.1436.0 or later. In this case that's Microsoft Edge Canary, Dev, or Beta.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by flashyyp123** [comment] 2022-11-14 01:55
Hello everyone, does win7 websocket affect webview2? I encountered a win7 websocket which caused msedgewebview2.exe process to crash

**Comment by logikonline** [comment] 2022-11-16 22:52
It still doesn't work - I press the File browse button on the latest Windows 11 box and nothing.

**Comment by logikonline** [comment] 2022-11-16 22:54
> You need to use a runtime that is version 108.0.1436.0 or later. In this case that's Microsoft Edge Canary, Dev, or Beta. https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Do we have any timeline when we can expect this to be in production?  Are we looking at an April rollup?

**Comment by champnic** [comment] 2022-11-16 23:20
It should ship to the stable WebView2 runtime in early December.

**Comment by cuiliang** [comment] 2022-12-26 06:41
@champnic 
Hi, I have tested the version 108.0.1462.54， open/save dialog works when 'Run as administrator' , but not works under auto elevation using 'uiAccess=true' method.  The dialogs does not show up.

**Comment by shyjusachin** [comment] 2023-01-03 06:43
@champnic Not sure this is the right item to ask this question. In Edge browser there is an option in settings 'Always ask me if I want to save a file or open it without saving' we can enable it on settings. Do we have same option available in WebView2? default behaviour is it is auto downloading when I click an .XLS file format. Instead I need that that open or save dialog like Edge.

@champnic Could you please help me on it, Thank you.

**Comment by champnic** [comment] 2023-01-05 01:24
@cuiliang Thanks for opening the new issue to track that.

@shyjusachin We don't currently have that option in WebView2. If you'd like you could open a Feature Request for that functionality.

**Comment by shyjusachin** [comment] 2023-01-05 05:32
Thank you @cuiliang for the confirmation and quick reply. Yes please, it will be very useful for us if you can open new issue Feature Request for this functionality.

**Comment by ajtruckle** [comment] 2023-01-05 05:35
@shyjusachin I think they were suggesting that you create the new feature request.

**Comment by shyjusachin** [comment] 2023-01-05 05:46
@ajtruckle Oh really. Sure I can do that. Thank you.
