### ISSUE TITLE
WebView2 crash OnWindowPositionChanged

### ISSUE THREAD

**Issue by raquibul-h** [MicrosoftEdge/WebView2Feedback#1518] opened 2021-07-10 18:35 UTC
**Description**
Exception Info: System.InvalidOperationException
   at Microsoft.Web.WebView2.Wpf.WebView2.VerifyBrowserNotCrashed()
   at Microsoft.Web.WebView2.Wpf.WebView2.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged(System.Windows.Rect)
   at System.Windows.Interop.HwndHost.UpdateWindowPos()
   at System.Windows.Interop.HwndHost.OnLayoutUpdated(System.Object, System.EventArgs)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)

**Version**
SDK: 1.0.865-prerelease
Runtime: 91.0.864.67
Framework: WPF
OS: Windows 10

**Repro Steps**
Window containing Webview2 object is tried to be shown. Webview2 crashes. Expected: Should not crash.

**Screenshots**

**Additional context**

**Comment by champnic** [comment] 2021-07-13 22:29
Hey @raquibul-h - thanks for the bug report! This sounds like the WebView2 was either not fully initialized, or the browser process crashed. Are you able to share more code about how you are initializing the WebView2 and showing the window/making it visible? Can you try listening to `CoreWebView2.ProcessFailed` event to see if the runtime processes are crashing?

**Comment by champnic** [comment] 2021-07-15 20:06
Closing as dupe of #1518 - will continue the conversation there.

**Closed by champnic** 2021-07-15 20:06 UTC
Labels: bug

**Comment by FlorianObermayer** [comment] 2022-06-20 12:13
> Closing as dupe of #1518 - will continue the conversation there.

Should be dupe of #1531.
