### ISSUE TITLE
Latest dev channel version (110.0.1556.0) huge performance hit

### ISSUE THREAD

**Issue by nirbil** [MicrosoftEdge/WebView2Feedback#3077] opened 2022-12-19 08:46 UTC
I've noticed there has been a significant performance hit in WebView2's latest dev channel version.
Navigation times seems to have been increased by an order of magnitude, and the component is behaving very sluggishly compared to the standard version channel.
Is this a known issue? Has there been a significant change that may have resulted in this?

[AB#42864615](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42864615)

**Comment by nirbil** [comment] 2022-12-19 14:06
By my measurements there's ~7000% performance increase of a simple cached page load

**Comment by nirbil** [comment] 2022-12-22 09:46
Here's a simple UWP MainPage script for demonstrating it:

    WebView2 _webView2;
    int _iterationNum = 0;
    DateTime _startTime;
    string[] _urls = {
        "http://www.testingmcafeesites.com/testcat_ac.html",
        "http://www.testingmcafeesites.com/testcat_al.html",
    };       
    public MainPage()
    {
        this.InitializeComponent();
        //Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", @"C:\Program Files (x86)\Microsoft\Edge Dev\Application\110.0.1556.0");
        this.Content = _webView2 = new WebView2();
        _ = _webView2.EnsureCoreWebView2Async().AsTask().ContinueWith(async (task) =>
        {
            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
                () =>
                {
                    _startTime = DateTime.Now;
                    _webView2.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;
                    _webView2.CoreWebView2.Navigate(_urls[0]);
                });
        });
    }

    private void CoreWebView2_NavigationCompleted(Microsoft.Web.WebView2.Core.CoreWebView2 sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationCompletedEventArgs args)
    {
        Trace.WriteLine($"Navigation completed, url: {sender.Source}");
        if (++_iterationNum <= 100)
        {
            _webView2.CoreWebView2.Navigate(_urls[_iterationNum % _urls.Length]);
        }

        else
        {
            Trace.WriteLine($"Navigation sequence completed. # loaded pages: {_iterationNum }, total time: {DateTime.Now.Subtract(_startTime).TotalMilliseconds}ms");
        }
    }

First run it regularly, then rerun it with the `Environment.SetEnvironmentVariable` line uncommented.
100 page loads turn from taking seconds into minutes.

**Comment by victorthoang** [comment] 2022-12-27 08:28
Hello @nirbil,

Thanks for your bug report on performance. I've assigned this to a dev that can best try to replicate the issue and follow up on this. With holidays over and new year's approaching, I appreciate your patience!

Victor

**Comment by LiangTheDev** [comment] 2022-12-27 19:13
I am not able to repro the issue. The UWP sample app seems to navigate quickly. Could you please take a perf trace of a slow navigation, using instructions in https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md?

**Comment by nirbil** [comment] 2022-12-28 05:58
Strange. Are you sure you have the edge dev channel installed and that it matches the version as in the code?

**Comment by nirbil** [comment] 2022-12-28 07:11
Here's what I'm seeing with the standard version:
https://user-images.githubusercontent.com/20151466/209772923-ca8c320d-1960-4278-bd67-1b157aad7f6f.mp4

And with the dev channel version:
https://user-images.githubusercontent.com/20151466/209773045-82e86543-cb11-4cfd-9925-82b256a09cc1.mp4

**Comment by nirbil** [comment] 2022-12-28 07:15
@LiangTheDev can I get an email address to send you the trace?

**Comment by LiangTheDev** [comment] 2022-12-28 18:45
You can share the trace with me at lzhao@microsoft.com. Could you also do a test with smartscreen disabled? Basically, set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS environment variable with --disable-features=msSmartScreenProtection and see whether it makes any difference.
FWIW, I am testing with Dev channel and not seeing the issue.

**Comment by nirbil** [comment] 2022-12-28 19:42
Disabling the msSmartScreenProtection does help to bypass the problem.
I'll try and send a trace tomorrow.

**Comment by LiangTheDev** [comment] 2022-12-28 19:56
In that case, a different trace might be more helpful than the ETW trace. I'll have to ask around to know which trace to collect.

I suspect that the issue is that smartscreen no longer able to resolve the domain name for the navigated to site and only allow the navigation after 2s timeout. Does the issue happen for all sites like example.com, google.com, bing.com, etc.?

**Comment by LiangTheDev** [comment] 2022-12-28 20:52
To get the triage trace, it could be more involved. Could you do this:

1. Modify the code to create another window with another WebView, navigate that WebView to edge://tracing/.
2. Click on the "Record" button, and "Edit categories" in the opened dialog, then click on "None" button under the "Record Categories" in the expaned UI, now scroll down and click on the check box of "SmartScreen"
3. Click on "Record" button
4. Now repro the navigation issue in the other webview
5. Click on "Stop" button in the trace recording window, and then click on "Save" button, give a name for the trace file to be saved, remember the path of the trace file and share it.

I suspect that the issue is also repro-able in [Win32 WebView2 sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample), so you can also use it to do the above instead of modifying your app. If using the sample app, use "Window" -> "Create New Window" menu to create another window with WebView, and the file is saved in Downloads folder.

**Comment by nirbil** [comment] 2022-12-29 09:49
> I suspect that the issue is that smartscreen no longer able to resolve the domain name for the navigated to site and only allow the navigation after 2s timeout. Does the issue happen for all sites like example.com, google.com, bing.com, etc.?

It seems to be happening on any website...

Here's a triage trace of a webview alternating between two urls from www.testingmcafeesites.com:
[SmartScreenTraceSimple.json.gz](https://github.com/MicrosoftEdge/WebView2Feedback/files/10318713/SmartScreenTraceSimple.json.gz)

And here's a trace of a webview alternating between google and bing:
[SmartScreenTraceGoogleBingStart.json.gz](https://github.com/MicrosoftEdge/WebView2Feedback/files/10318720/SmartScreenTraceGoogleBingStart.json.gz)

Interestingly, after alternating for a few minutes it suddenly resolves and starts to run fast, here's a trace:
[SmartScreenTraceGoogleBingEnd.json.gz](https://github.com/MicrosoftEdge/WebView2Feedback/files/10318727/SmartScreenTraceGoogleBingEnd.json.gz)

**Comment by LiangTheDev** [comment] 2022-12-29 18:32
The log confirmed my guess. Is the device now totally normal again?

**Comment by nirbil** [comment] 2022-12-29 18:46
No, I meant that if I leave it running and retrying for a few minutes then it suddenly gets resolved. But restarting the app brings back the same slow pace

**Comment by LiangTheDev** [comment] 2022-12-29 18:56
Got it, I am asking SmartScreen team to look into it. Will report back when we found something or need further helps from you for more logs.

**Comment by LiangTheDev** [comment] 2023-01-04 01:54
@nirbil Could you help us collecting more information?

- Collect the netlog in similar ways as the SmartScreen log above. Nagivate the extra WebView to edge://net-export, select the " Include raw bytes (will include cookies and credentials)" and click on the "Start logging to disk" and provide a path that the app has access to like the one in the app's package folder %LOCALAPPDATA%\Packages\<App-package-family-name>\LocalState\edge-net-export-log.json. Note that the default Downloads folder doesn't really work for UWP apps. Repro the issue and stop the trace. Please share the trace file via email as the log will include all cookies and credentials sent from the app. More information about netlog tracing is at https://textslashplain.com/2020/01/17/capture-network-logs-from-edge-and-chrome/ if you are interested.
- Does the same issue happen in Edge browser dev channel or Win32 sample app running outside of UWP environment?

**Comment by nirbil** [comment] 2023-01-04 08:17
It doesn't happen on Edge dev channel, also doesn't happen on the Win32 sample app (adjusted it to use the dev channel).

**Comment by LiangTheDev** [comment] 2023-01-04 20:28
@nirbil thanks for the info and netlog.

What we've found:
- We are able to open USP socket and send request to DNS server, but no response is received and the socket is closed due to timeout. It seems that the connection from the UWP app to DNS server's UDP port 53 is blocked, by security software or app container rules? The blocking should be specific to app conatiners, and that's why Edge browser and win32 apps are not impacted.
- There is a change in Chromium >=109 that moved to use built in DNS resolver (https://chromium-review.googlesource.com/c/chromium/src/+/3995682). It might be related.

The reason that navigation becomes faster after a while probably is that the code fallbacks to OS resolver and cache can be used.

To move forward:

- Could you try to disable build in DNS resolver by setting WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS environment variable with --disable-features=AsyncDns and see whether it makes any difference.
- To understand/confirm that it is something that blocks UDP port from the UWP app, could you collect one more log, from cmd.exe running as admin:
  - netsh trace start scenario=InternetClient_dbg
  - repro
  - netsh trace stop
  - share nettrace.cab

**Comment by nirbil** [comment] 2023-01-05 07:50
I sent you a netsh trace by email.
Disabling the AsyncDns does resolve the issue.
Also I should mention that my device is running Win10. Might be related.
Also notice that I'll be offline for the next week so won't be able to help.

**Comment by LiangTheDev** [comment] 2023-01-05 20:46
Thanks for the info and logs. I think that we figured out what's going on. It is an issue with WebView2 Runtime and your machine is fine.

DNS server is normally not part of public internet and access it requires "privateNetworkClientServer" capability (which is shown as "Private Networks (Client & Server)" in Visual Studio).
If a UWP app doesn't have that capability, packages from Chromium's built-in resolver would be dropped, and we will have this problem.

When I drop the "privateNetworkClientServer" capability from my test app, I can also repro the slow navigation. You can confirm this analysis by adding "privateNetworkClientServer" capability to your app and see whether that also resolves the issue.

We will try to make a change to disable the AsyncDns feature for UWP WebView2. Before the fix is released and to be safe if we are not able to make the change before 109 is released, you can workaround the issue using --disable-features=AsyncDns extra browser switch in the app.

**Comment by LiangTheDev** [comment] 2023-01-14 01:34
The issue should now be fixed in latest Edge build in all channels.

**Comment by nirbil** [comment] 2023-01-16 06:09
:thumbsup: looking good

**Closed** 2023-01-16 06:09 UTC
Labels: bug, tracked
