### ISSUE TITLE
CoreWebView2NavigationStartingEventArgs.Cancel not working

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#560] opened 2020-10-21 16:59 UTC
**Description**
Navigation not cancelled (I'm fairly sure it did on previous releases)
**Version**
SDK: 1.0.674-prerelease
Runtime: 88.0.673.0 (Official build) dev (32-bit) 
Framework: WinForms
OS: Win7 32 bit SP1

**Repro Steps**
```
Private Sub WVBrowser_NavigationStarting(sender As Object, e As CoreWebView2NavigationStartingEventArgs) Handles 
  Me.NavigationStarting
  e.Cancel = True ' Doesn't cancel
```

[AB#29899723](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29899723)

**Comment by champnic** [comment] 2020-10-22 03:35
Yes this is a known issue with 1.0.674-prerelease that we have a fix for. It will be available in the next SDK. Thanks!

**Comment by pagoe-msft** [comment] 2020-11-23 21:47
Hi Everyone,

This was addressed in the [1.0.664.37 version](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes?view=WebView2-dotnet-1.0.707-prerelease#1066437).

**Closed by pagoe-msft** 2020-11-23 21:47 UTC
Labels: bug

**Comment by dmcgloin** [comment] 2020-11-24 18:06
@champnic I'm trying 1.0.707-prerelease, and this issue does **not** appear fixed for me. Triple-checking my code but when I try to cancel at the `NavigationStarted` event, the browser strill proceeds to the bogus redirect URL instead of stopping the load.

**Comment by ukandrewc** [comment] 2020-11-24 19:05
e.Cancel works for me on 1.0.707.0 Winforms.

**Comment by champnic** [comment] 2020-12-01 23:41
@dmcgloin Could you see if cancelling a navigation works with something simple? I think we have a bug or two where cancellation in particular fails in certain scenarios, like malformed URLs, etc.

**Comment by fsuk** [comment] 2020-12-02 07:47
Does not work for me in WPF even with the simplest example.

**Comment by champnic** [comment] 2020-12-10 20:17
@fsuk Could you add some details about your simple example - SDK/runtime versions, code, etc?

I just tried in a WPF app with 1.0.721-prerelease SDK, and when I do `e.Cancel = true;` during the NavigationStarting event, it cancels the navigation.

**Comment by Nevcairiel** [comment] 2021-04-19 12:34
I'm also experiencing issues with Cancel on 1.0.774.44.

The website is using a JS .click() on a <a> element, and i'm trying to suppress that navigation event. The target URL requires authentication, so WebView2 pops up the credentials box, and the request is not silently canceled.

**Comment by champnic** [comment] 2021-04-19 22:34
@Nevcairiel This sounds like a separate issue. Can you please open it in a new issue to track? Thanks!

**Comment by kha1ne** [comment] 2021-10-13 12:20
Hello @champnic

Issue we are experiencing is on redirect request, we are getting only one occurrence of `ICoreWebView2NavigationCompletedEvent` in which source URI contains the redirect URI.

Hello, just curious is this solved already in newer runtime versions? 

While we are at it, is there any way that we can download older fixed version of runtime `91.xx`?

**Comment by anovik** [comment] 2022-01-10 05:35
@champnic It seems there is still a problem with Cancel CoreWebView2NavigationStartingEventArgs for WinUI3 in Microsoft.WindowsAppSdk 1.0.0, could you please check?

**Comment by champnic** [comment] 2022-01-10 18:23
@anovik Hey Anna - would you mind opening that as a new issue with more details on what the issue is and how to reproduce it? Thanks!

**Comment by anovik** [comment] 2022-01-11 07:59
@champnic I've opened [#2072](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2072)
