### ISSUE TITLE
[Problem/Bug]: IsPasswordAutofillEnabled not working anymore

### ISSUE THREAD

**Issue by Kay-Burchardt** [MicrosoftEdge/WebView2Feedback#4473] opened 2024-04-05 13:25 UTC
### What happened?

We noticed that password autofill in Webview2 is not working anymore. Originally we activated it in the Webview2 settings. Some time ago, I changed our implementation to use profiles. Back then, password autofill still worked. After we realized that it's not working anymore, I tried to enable it through the profile property instead of the webview2 setting. But that didn't help. I observed the protocols of our former automated tests, and it seems that it still worked with Webview2 runtime v 121 but stopped with 122. Unfortunately we are using the evergreen installer and the fixed version 121 is not available for download anymore, so I cannot validate it.   

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.65

### SDK Version

120.0.2210.55

### Framework

Win32

### Operating System

Windows 11

### Repro steps

Enable property IsPasswordAutofillEnabled of either IWebview2Settings or IWebview2Profile. Fill password field of arbitrary form and submit. In the past, Webview2 asked to store password. But not anymore. 

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

Runtime 121?

[AB#50049182](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50049182)

**Comment by vbryh-msft** [comment] 2024-04-05 18:34
I see different names of the API - [IsGeneralAutofillEnabled](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings4?view=webview2-1.0.2365.46#get_isgeneralautofillenabled) and [IsPasswordAutosaveEnabled](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings4?view=webview2-1.0.2365.46#get_ispasswordautosaveenabled) - which ones are you using? Are all of them broken for you?

**Comment by Kay-Burchardt** [comment] 2024-04-08 06:35
We are using both. IsGeneralAutofillEnabled is still working as expected. Only IsPasswordAutosaveEnabled is broken.

**Comment by maurawinstanley** [comment] 2024-04-08 22:00
@Kay-Burchardt I was able to reproduce the bug, we will open a bug on our side and will add updates to this thread.

**Comment by DeanFredrickson** [comment] 2024-04-21 19:45
Did you find a solution to this problem?  I am having the same problem. :)

**Comment by liulichen0603** [comment] 2024-04-23 02:57
@DeanFredrickson We have located the cause and made a fix. This fix will be available to you after 4.25 if all goes well.

**Comment by milesbuckton** [comment] 2024-04-29 08:50
It looks like this is working now! 😄🙌🏻

**Comment by DeanFredrickson** [comment] 2024-05-02 15:40
It is still now working for me. the version I have is: 1.0.2478.35, is that the correct update?  Or is it my code?  
 private void webViewCoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
 {
     CoreWebView2Settings Settings;
     Settings = dashboardWebview.CoreWebView2.Settings;
     Settings.IsPasswordAutosaveEnabled = true;
     Settings.IsGeneralAutofillEnabled = true;
 }

**Comment by DeanFredrickson** [comment] 2024-05-12 19:55
> @liulichen0603 It is still not working for me. the version I have is: 1.0.2478.35, is that the correct update? Or is it my code?
> private void webViewCoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
> {
> CoreWebView2Settings Settings;
> Settings = dashboardWebview.CoreWebView2.Settings;
> Settings.IsPasswordAutosaveEnabled = true;
> Settings.IsGeneralAutofillEnabled = true;
> }

**Comment by DRAirey1** [comment] 2024-08-26 14:25
What's the status of this? I'm running into the same problem using the above code - no passwords are being remembered or prompted to be remembered.

**Comment by vbryh-msft** [comment] 2024-08-26 15:58
@DRAirey1 What is your runtime version that it is not working and what is the last one you have seen working. Thanks

**Comment by DRAirey1** [comment] 2024-08-26 16:08
Not sure I understand the question. I'm targeting WinUI. Here are the settings:

    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

**Comment by DRAirey1** [comment] 2024-08-26 16:30
@vbryh-msft Just to make sure it wasn't my code that was at fault, I downloaded the samples from [https://github.com/MicrosoftEdge/WebView2Samples]WebView2Samples and ran into the same problem: no prompt, no saved passwords.

**Comment by champnic** [comment] 2024-09-05 23:55
This is fixed in runtimes 124.0.2478.63+. Thanks!

@DRAirey1 In the sample app, make sure you select "Settings > Toggle Password Autosave" to enable password saving.
In your app, make sure `CoreWebView2.Profile.IsPasswordAutosaveEnabled = true`. It's false by default.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.ispasswordautosaveenabled?view=webview2-dotnet-1.0.2739.15

**Closed by champnic** 2024-09-05 23:55 UTC
Labels: bug, tracked, regression

**Comment by DRAirey1** [comment] 2024-09-17 20:13
@champnic - Have you actually taken the sample application and forced it to autofill the password field? Try using the URL of "https://portal.azure.com/" and then please let me know what you did to change the sample app, because I can't get it to work with your suggestion.

**Comment by champnic** [comment] 2024-09-17 22:02
I tested the sample app at https://fill.dev/form/login-simple using runtime version 127.0.2651.105, with the "Settings > Toggle Password Autosave" enabled in the WebView2APISample application.

What is your setup? Are you seeing this fail on other pages besides https://portal.azure.com?

**Comment by DRAirey1** [comment] 2024-09-17 22:24
> using WebView2 runtime version 127.0.2651.105

Let's start with this. What do you mean "runtime version"? Is that a package version, a framework version? What? Nothing I use starts with a version of 127. It looks more like a NuGet package version. Show me exactly how you set this in your .csproj files, please.

> "Settings > Toggle Password Autosave" 

Where do you see a 'settings' option in the IDE? If this is supposed to be code, then please show the code.

**Comment by champnic** [comment] 2024-09-21 04:30
Hey @DRAirey1 -

The WebView2 runtime is a platform component that is shipped with Windows (or distributed separately). You can learn more here:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?tabs=dotnetcsharp
When you launch the WebView2 sample app it will tell you what version of the runtime it's using. You can also open Windows Settings > Apps > Installed Apps and search for 'WebView2' to see what version is installed on your machine:
![image](https://github.com/user-attachments/assets/71beab89-0207-4181-904e-bf6dd9479055)


The :"Toggle Password Autosave" setting can be found in our WebView2APISample application. Here is some information about how to get it: https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/webview2apissample

**Comment by DRAirey1** [comment] 2024-10-09 14:48
@champnic  Ah, now I understand your comments. The WPF does indeed have a 'Settings -> Toggle Password Autosave'. The WinUI example doesn't. The Password Autosave appears to work in the WPF example, but not in the WinUI example, so I'm guessing that there's some configuration issue possibly with cookies, profiles or browser history settings. What settings/configuration do I need in the WinUI example that will allow it to save passwords like the WPF example?

**Comment by champnic** [comment] 2024-10-09 18:10
@DRAirey1 Aha good catch!

After you set the setting to true, are you navigating to a new page? Settings typically only take effect after a new navigation or reload.

**Comment by DRAirey1** [comment] 2024-10-09 18:12
Setting it exactly as it appears in the code snippet above: during initialization.

**Comment by hyptocrypto2** [comment] 2024-10-15 16:38
Facing the same issue on my end. Using wails(golang framework for gui apps) and it uses webvew2 as a backend. 
GeneralAutofill and PasswordAutosave are both enabled (validated with runtime calls to webview2 api). Save and Autofill works for username/emails inputs. But not for passwords. 
Webview2 version: 129.0.2792.89

Any updates/ideas on whats happening here?

**Comment by dealsweb** [comment] 2025-04-07 06:27
Does this working for anyone? We have tried this but no luck.
