### ISSUE TITLE
WebView2 doesn't rescale until window resize when using RDP

### ISSUE THREAD

**Issue by Parma114** [MicrosoftEdge/WebView2Feedback#2202] opened 2022-02-21 10:43 UTC
There seems to be an issue accessing CoreWebView2Controller.ShouldDetectMonitorScaleChanges &  CoreWebView2Controller.RasterizationScale properties in WPF Webview2. Currently, CoreWebView2Controller is private member of WebView2. We have a desktop app with EdgeWebView2 browser used as UI.

The version of WebView2.Core & WebView2.Wpf dlls used are from Microsoft.Web.WebView2.1.0.1108.44 package. WPF desktop app is based on .NET4.8.

Let us know how can we set the ShouldDetectMonitorScaleChanges & RasterizationScale properties & also what's the default values?

[AB#38343499](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38343499)

**Comment by santoshsampath** [comment] 2022-02-22 10:48
To provide some more context, we are seeing DPI change is not immediately reflected when we connect/disconnect to a workstation via RDP. Workstation has 100% scale factor and when we do RDP, it would have 200%. 
Only when we resize our app, it gets adjusted. Our app uses per-monitor v2 DPI awareness manifest.

Is the app supposed to set the above property or any other related WPF property to automatically handle DPI changes.

**Comment by champnic** [comment] 2022-03-01 00:58
Hey @Parma114 and @santoshsampath - It's By Design that the controller is not exposed to the .NET controls. Instead the controls should integrate with the UI frameworks to work seamlessly. It sounds like we may have a bug here when changing the DPI over RDP.

Can you confirm that the host app process and the child WebView2 process are Per-Monitor V2 aware in the Task Manager? If you go to the "Details" tab you should be able to display a column for "DPI Awareness" (right-click column header > Select columns > DPI Awareness).

**Comment by santoshsampath** [comment] 2022-03-01 09:53
Yes they are:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/6291206/156146636-c6676b88-9131-4c1a-9e75-d04aecbc59ce.png">

**Comment by champnic** [comment] 2022-03-02 07:02
I believe procexp.exe doesn't show v1 vs v2, but Task Manager should.

Do you see the same behavior locally, or only over RDP?

**Comment by santoshsampath** [comment] 2022-03-03 04:49
<img width="988" alt="image" src="https://user-images.githubusercontent.com/6291206/156498030-8fe8faa5-7585-43e2-b79f-b7b10205435f.png">

I don't have Windows client handy. I have asked Parmanand to verify. I am not sure if Mac vs Windows RDP also makes a difference other than checking locally.

But it does know the DPI, just that it only adjusts if we resize the window.

**Comment by Parma114** [comment] 2022-03-03 09:46
@champnic, with Windows RDP I'm able to reproduce the issue, but locally it's scaling correctly.

**Comment by champnic** [comment] 2022-03-08 04:56
Thanks for confirming - I'll update the title.

**Comment by champnic** [comment] 2022-05-03 19:13
This is fixed in runtime versions 102.0.1216.0+. Thanks!

**Closed by champnic** 2022-05-03 19:13 UTC
Labels: bug, tracked
