### ISSUE TITLE
WebView steals focus from newly started process

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#1526] opened 2021-07-13 14:23 UTC
**Description**
Using the following code will sporadically only open the browser tab without activating the browser.
```
CoreWebView2_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
{
  Process.Start(new ProcessStartInfo(e.Uri));
  e.Cancel = true
}
```

The expected behavior would be for the link to be opened in the associated browser / program, and then that program would be placed in front / activated. But for some reason I have some users where this behavior does not happen. The browser receives the address and opens a tab, but the application with the WebView stays in front.
The same behavior has not been reproducible with the old System.Windows.Forms.WebBrowser.
The behavior has been reproduced with the following browsers: Chrome, Firefox, Edge, IE.

**Version**
SDK: 1.0.864.35
Runtime: Runtime 91.0.864.67
Framework: WPF
OS: Win10
Setup: Laptop, connected to a second screen

**Repro Steps**
In the attached video, a user who consistently experiences the problem shows it off in a sample application. Notice that the problem occurs sporadically, and the related 'fix' used also only works every second time. After the fix has worked once, it then continues to work without being applied. Possibly pointing to some state-wise problem?
 
https://user-images.githubusercontent.com/47817657/125467384-8f565657-668a-49c4-b508-f66dc3463956.mp4

Code for the sample application:
```
<Window x:Class="TestWebView2App.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="800" Width="1280">

  <Window.Resources>
    <Style TargetType="{x:Type CheckBox}">
      <Setter Property="HorizontalAlignment" Value="Left" />
      <Setter Property="VerticalContentAlignment" Value="Center" />
      <Setter Property="Foreground" Value="White" />
      <Setter Property="FontSize" Value="12" />
      <Setter Property="Margin" Value="0 0 0 8" />
    </Style>
  </Window.Resources>

  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <Grid Background="Black"
          Height="170">
      <Grid.ColumnDefinitions>
        <ColumnDefinition Width="Auto" />
        <ColumnDefinition Width="*" />
      </Grid.ColumnDefinitions>

      <StackPanel Margin="16 16 16 16">
        <CheckBox x:Name="Fix1"
                  Content="Use the fix /SwitchToThisWindow()/" />
        
        <CheckBox x:Name="Fix2"
                  Content="Use the fix /ShowWindow()+SetForegroundWindow()/" />
        
        <CheckBox x:Name="Fix3"
                  Content="Use the fix /SetActiveWindow()/" />

        <StackPanel Orientation="Horizontal">
          <Label Content="Dispatch fix unto queue"
                 Foreground="White"
                 Margin="0 0 8 8" />

          <ComboBox x:Name="FixDispatch"
                    Height="21"
                    SelectedIndex="0">
            <ComboBoxItem Content="None" />
            <ComboBoxItem Content="Normal" />
            <ComboBoxItem Content="Loaded" />
            <ComboBoxItem Content="Input" />
          </ComboBox>
        </StackPanel>

        <StackPanel Orientation="Horizontal">
          <Label Content="Delay (ms) before using fix:"
                 Foreground="White"
                 Margin="0 0 8 0" />

          <TextBox x:Name="FixDelay"
                   Text="0"
                   Width="100"
                   Foreground="White"
                   Background="Black"
                   Height="21"
                   BorderBrush="White" />
        </StackPanel>
      </StackPanel>

      <ScrollViewer x:Name="TextScroller" 
                    Grid.Column="1"
                    HorizontalAlignment="Right">
        <TextBlock x:Name="LogBox"
                   Foreground="White"
                   TextWrapping="Wrap" />
      </ScrollViewer>
    </Grid>

    <wv2:WebView2 x:Name="WebView"
                  Source="https://www.microsoft.com"
                  Grid.Row="1" />

  </Grid>
</Window>
```

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;

namespace TestWebView2App
{
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();
    }

    public override void OnApplyTemplate()
    {
      base.OnApplyTemplate();

      WebView.NavigationStarting += WebView_NavigationStarting;
      Logger.AddLogLine($"WebView runtime is {CoreWebView2Environment.GetAvailableBrowserVersionString()}");
      LogBox.Text = Logger.ToString();
    }

    private bool IsFirstNavigation { get; set; } = true;
    private StringBuilder Logger { get; } = new StringBuilder();
    private void WebView_NavigationStarting(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs e)
    {
      if (IsFirstNavigation || e.IsRedirected)
      {
        IsFirstNavigation = false;
        return;
      }
      
      e.Cancel = true;
      var process = Process.Start(new ProcessStartInfo(e.Uri) { UseShellExecute = true });
      Logger.AddLogLine($"Browser pId: {process.Id}, name: {process.ProcessName}, mainHwnd: {process.MainWindowHandle}");

      var appProcess = Process.GetCurrentProcess();
      Logger.AddLogLine($"App pId: {appProcess.Id}, name: {appProcess.ProcessName}, mainHwnd: {appProcess.MainWindowHandle}");

      DispatcherPriority dispatcherPriority;
      switch(((ComboBoxItem)FixDispatch.SelectedItem).Content)
      {
        case "Normal":
          dispatcherPriority = DispatcherPriority.Normal;
          break;

        case "Loaded":
          dispatcherPriority = DispatcherPriority.Loaded;
          break;

        case "Input":
          dispatcherPriority = DispatcherPriority.Input;
          break;

        default:
          dispatcherPriority = DispatcherPriority.Inactive;
          break;
      }

      if (dispatcherPriority == DispatcherPriority.Inactive)
      {
        FinalizeNavigation(process);
      }
      else
      {
        Logger.AddLogLine($"Dispatching fixes with priority '{dispatcherPriority}'");
        Dispatcher.BeginInvoke(dispatcherPriority, new Action(() => FinalizeNavigation(process)));
      }      
    }

    private void FinalizeNavigation(Process process)
    {
      if (int.TryParse(FixDelay.Text, out int fixDelay) && fixDelay > 0)
      {
        Logger.AddLogLine($"Running fixes with delay {fixDelay} ms");

        var delayedFixes = Task.Run(async delegate { await Task.Delay(fixDelay); });

        delayedFixes.Wait();
      }

      RunFixes(process);

      if (!process.HasExited)
        process.WaitForInputIdle();

      Task.Run(async delegate
      {
        await Task.Delay(1000);

        Logger.AddLogLine($"Foreground hwnd: {Win32Helper.GetForegroundWindow()}");
        Logger.AppendLine();

        Dispatcher.Invoke(new Action(() =>
        {
          LogBox.Text = Logger.ToString();
          TextScroller.ScrollToEnd();
        }));
      });
    }

    private void RunFixes(Process process)
    {
      var windowHandle = Win32Helper.FindWindow(process.Id, process.ProcessName);
      if (Fix1.IsChecked == true)
      {
        Logger.AddLogLine($"Using fix1 - browser hwnd: {windowHandle}");
        // https://stackoverflow.com/a/58303210/8568156
        Win32Helper.SwitchToThisWindow(windowHandle, true);
      }

      if (Fix2.IsChecked == true)
      {
        Logger.AddLogLine($"Using fix2 - browser hwnd: {windowHandle}");
        Win32Helper.ShowWindow(windowHandle, Win32Helper.SW_RESTORE);
        Win32Helper.SetForegroundWindow(windowHandle);
      }

      if (Fix3.IsChecked == true)
      {
        Logger.AddLogLine($"Using fix3 - browser hwnd: {windowHandle}");
        Win32Helper.SetActiveWindow(windowHandle);
      }
    }
  }

  public class Win32Helper
  {
    [DllImport("user32.dll")]
    public static extern bool SetForegroundWindow(IntPtr hWnd);

    [DllImport("user32.dll")]
    public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

    [DllImport("user32.dll", SetLastError = true)]
    public static extern void SwitchToThisWindow(IntPtr hWnd, bool turnOn);

    [DllImport("user32.dll", SetLastError = true)]
    public static extern IntPtr SetActiveWindow(IntPtr hWnd);

    [DllImport("user32.dll")]
    public static extern IntPtr GetForegroundWindow();

    [DllImport("user32.dll")]
    private static extern bool EnumWindows(EnumWindowsProc enumProc, IntPtr lParam);

    // Delegate to filter which windows to include 
    public delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);
    
    [DllImport("user32.dll", SetLastError = true)]
    public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);

    public const int SW_RESTORE = 9;

    [Flags]
    public enum SWP : uint
    {
      SWP_NOSIZE = 0x0001,
      SWP_NOMOVE = 0x0002,
      SWP_NOZORDER = 0x0004,
      SWP_NOREDRAW = 0x0008,
      SWP_NOACTIVATE = 0x0010,
      SWP_FRAMECHANGED = 0x0020,
      SWP_SHOWWINDOW = 0x0040,
      SWP_HIDEWINDOW = 0x0080,
      SWP_NOCOPYBITS = 0x0100,
      SWP_NOOWNERZORDER = 0x0200,
      SWP_NOSENDCHANGING = 0x0400,
      SWP_DRAWFRAME = SWP_FRAMECHANGED,
      SWP_NOREPOSITION = SWP_NOOWNERZORDER,
      SWP_DEFERERASE = 0x2000,
      SWP_ASYNCWINDOWPOS = 0x4000
    }

    /// <summary>
    /// https://forums.codeguru.com/showthread.php?392273-RESOLVED-How-to-get-window-s-HWND-from-it-s-process-handle
    /// </summary>
    public static IntPtr FindWindow(int processId, string processName)
    {
      var matches = new List<(Process process, IntPtr hWnd)>();

      EnumWindows(delegate (IntPtr hwnd, IntPtr param)
      {
        GetWindowThreadProcessId(hwnd, out uint windowId);
        var process = Process.GetProcessById((int)windowId);

        if (process.ProcessName == processName)
          matches.Add((process, hwnd));

        return true;
      }, IntPtr.Zero);

      var perfectMatch = matches.FirstOrDefault((item) => item.process.Id == processId);

      return perfectMatch == default
        ? matches.FirstOrDefault().hWnd
        : perfectMatch.hWnd;
    }
  }

  public static class StringBuilderExtension
  {
    public static StringBuilder AddLogLine(this StringBuilder sb, string text)
      => sb.AppendLine($"{DateTime.Now.ToString("HH:mm:ss")} // " + text);
  }
}
```

**Comment by champnic** [comment] 2021-07-13 22:24
Hey @cbra-caa - thanks for the bug report! I believe this is a duplicate of #1092. We currently have a half-fix for that that will handle cases where the external app is being launched from NavigationStarting, NewWindowRequested, or WebMessageReceived events, with a broader fix coming later. You can try using Canary (93.0.947.0+) to see if that fixes the issue for you.

The underlying issue is that because WebView2 is out-of-proc, when it has focus it has foreground rights and your host app doesn't. We need to call `AllowSetForegroundWindow` before giving control back to your app, but can't just add blanket calls everywhere. Another workaround (though less desirable) is to take focus away from the WebView2 before launching the external app.

Thanks!

**Closed by champnic** 2021-07-13 22:24 UTC
Labels: bug

**Comment by cbra-caa** [comment] 2021-07-14 11:28
Thanks for the pointer - missed that one 👍

I'll try with the focus trick
