### ISSUE TITLE
hang in webview2 when SetWindowLongPtr

### ISSUE THREAD

**Issue by bmexue** [MicrosoftEdge/WebView2Feedback#2592] opened 2022-07-14 08:51 UTC
**Description**

We use parent wnd is in another process, webview in self process.
maybe find hang  in webview2 when SetWindowLongPtr

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by nishitha-burman** [comment] 2022-07-14 20:37
Hi @bmexue can you provide more details such as the version numbers and repro steps?

**Comment by bmexue** [comment] 2022-07-15 01:48
@nishitha-burman  EmbeddedBroserWebview.dll   103.0.1264.44  below is call stack,  thanks you,
![image](https://user-images.githubusercontent.com/4737430/179130409-a0e7288e-c838-4195-9a12-63f336b0e2f8.png)

**Comment by bmexue** [comment] 2022-07-15 08:03
@bradp0721  What have SetWindowwLongPtr here want to do？  Set parent window？

**Comment by yunate** [comment] 2022-07-18 02:49
Yes, looks like below:
![image](https://user-images.githubusercontent.com/37793342/179438436-274d52f8-c596-47ef-8430-0f27c9546c6f.png)

**Comment by yunate** [comment] 2022-07-18 02:51
> @bradp0721 What have SetWindowwLongPtr here want to do？ Set parent window？

Yes, looks like below:
![image](https://user-images.githubusercontent.com/37793342/179438436-274d52f8-c596-47ef-8430-0f27c9546c6f.png)

**Comment by bradp0721** [comment] 2022-07-18 20:16
@bmexue are you able to consistently reproduce this hang? Can you provide a repro app?

**Comment by bmexue** [comment] 2022-07-19 02:57
@bradp0721   I can consistently reproduce this hang, is not must be present。 I found in https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra.   
Do not call SetWindowLongPtr with the GWLP_HWNDPARENT index to change the parent of a child window. Instead, use the [SetParent](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setparent) function.

Is this docs is useful?

**Comment by bmexue** [comment] 2022-07-19 03:03
@bradp0721   and , our parent windows is in another process created, webivew2 main process(which invoke CoInitializeEx and init webview2) is our child process.  This usage is not safety when webview2 use SetWindowLongPtr?

**Comment by bradp0721** [comment] 2022-07-19 20:18
We are not calling SetWindowLongPtr with GWLP_HWNDPARENT. We are calling SetWindowLongPtr with GWLP_STYLE to set WS_CHILD before calling SetParent. That is the documented behavior for how to take a window previously parented to the desktop and make it a child.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setparent
"Conversely, if hWndNewParent is not NULL and the window was previously a child of the desktop, you should clear the WS_POPUP style and set the WS_CHILD style before calling SetParent."

When this happens, do you have more than one WebView2 created? Or does this hang happen on the first WebView2 creation? How often are you able to hit the hang?

**Comment by clock75** [comment] 2022-11-03 00:40
CoreWebView2EnvironmentOptions.AdditionalBrowserArguments -> '--disable-gpu'

**Comment by bradp0721** [comment] 2023-02-08 23:05
We were able to reproduce this hang internally and root caused the issue. This should be fixed in the latest stable WebView2 runtime (v109).

**Closed by bradp0721** 2023-02-08 23:05 UTC
Labels: bug
