### ISSUE TITLE
File Download API

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#419] opened 2020-09-01 20:03 UTC
To be able to intercept and handle a file download, including blobs.
Ideal scenario would be a **BeforeFileDownload** event that allows dev access to the downloaded file.
Unless I've missed something and there is already a way to do that.
Thanks

[AB#27202431](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27202431)

**Comment by dhammika777** [comment] 2020-09-01 20:30
Waiting for the feature!!!

**Comment by JoshuaWeber** [comment] 2020-09-01 21:00
Hi. I've started to spec out the solution to this. I'm still a bit unclear on what the use case is for this. If I could get more details from you it would help out.

I'm kind of curious why you describe this as tied to a download event. I'm assuming this is independent from just an app triggered http request. Is the trigger for behavior a user action (e.g. user clicks a link, that triggers a download). And you need to be involved in the flow?

**Comment by ukandrewc** [comment] 2020-09-02 08:13
@JoshuaWeber Yes, you've got it ;-)
Ideally this would include types that can be handled by Edge, such as PDF.
I was basing this request on other web controls that **don't** trigger a navigation started event for downloads.
I really need to check more of how WebView2 behaves with downlods, to be sure of what I'm asking for.

**Comment by dhammika777** [comment] 2020-09-02 11:13
@JoshuaWeber  I'm from SAP and we would like to use it in Excel as an embedded browser control for our OAuth2 workflow. However, we have 2 use-cases;

 1. disable all downloads   (case for regular logon process)
 2. get notified when a file download is being started and then cancel it     
     (start file download is the point that user has successfully authenticated himself on the browser, then we do not want the file download to happen, but (close the browser &) copy the cookies / XCSRF tokens and use them in HTTP WebRequests from .net)

Hope the above is clear enough..

**Comment by ukandrewc** [comment] 2020-09-02 11:24
Same as @dhammika777 with added:

Need to control anything that would be considered a download, including blobs and content that can be displayed inside Edge, e.g. PDF.

I appreciate we can intercept most content, and download it ourselves inside **NavigationStarting** but this doesn't work for blob content.

Ideal Events would be **DownloadStarting** and **DownloadCompleted**. Similar to **NavigationStarting/Completed**, with options to see URI, change filepath, use default behaviour or Cancel and handle the download.

**Comment by JoshuaWeber** [comment] 2020-09-02 17:13
Thanks for sharing this additional info. I think I understand the scenario. I'm going to see if I can put together a proposal to share out. Keep an eye out for it in the future.

**Comment by ukandrewc** [comment] 2020-09-02 19:05
Great, thanks

**Comment by wjvii** [comment] 2020-09-05 20:17
This sounds like something I am also extremely interested in. In our market we must conduct business a lot via website vs webapis and one thing we interact with constantly are files, usually pdfs, that are linked to via a webpage that must be downloaded and then uploaded into our database. Ideally what we want is to be able to do is iterate over all the links to pdfs on the page and within the hosted browser control download them all into our database vs having to download them one by one to disk and then re-upload them into our database. If that is not an option then I would like to be able to at least have the user click on the document and be able to provide a way for them to save it directly to the database. What is particularly important is that this happens in the security context of the browser that was established when we logged in because if not, the user will be denied access. This may be where the per document option might have to come into play, but let me decide what to do with the data, ideally let me get it in a stream or a byte array if not. Then my code can store it in the database vs saving it to disk.

Thank you very much for considering a feature to support this type of capability.

**Comment by studylamp** [comment] 2020-09-15 13:58
They closed my identical request, saying that http file downloading is outside of the scope of web controls. (Which is an odd thing to say, since every other web control I know of, including WebView, has it.)

https://github.com/MicrosoftEdge/WebViewFeedback/issues/302

**Comment by ukandrewc** [comment] 2020-09-15 14:07
I think the difference is that you were asking for an API to use for downloading, whereas this is just asking for events to control existing downloads.

For your needs, did you know you can get the cookies using DevTools Protocol for using WebClient, etc. Or as MS suggested, use XHR to download your data, then you don't need to get the cookies?

**Comment by studylamp** [comment] 2020-09-15 14:36
> I think the difference is that you were asking for an API to use for downloading, whereas this is just asking for events to control existing downloads.

If they decide that distinction is relevant, and decide to implement it, that would be great. Then we could just navigate to download URLs and get the same outcome we need.

> For your needs, did you know you can get the cookies using DevTools Protocol for using WebClient, etc. Or as MS suggested, use XHR to download your data, then you don't need to get the cookies?

Yes, both of these were considered. DevTools is not a good thing to rely on, especially since we disable DevTools in the browser to start with, and IIRC it can be disabled by policy? And relying on Javascript running in the browser to download large media files (potentially gigabytes) is not really a good option for us.

Anyway, I have a functioning workaround for all of it.

**Comment by michael-russin** [comment] 2020-09-15 15:16
We would also find some hooks into the download file process helpful.  The main reason would be to provide a custom UI for download/save/open options.   Currently the WebVew2 will show the file download progress on the bottom the page which is nice but doesn't fit in with our existing application.   Our users are used to a popup message with a message asking if they would like to save or open or cancel the file.

**Comment by ukandrewc** [comment] 2020-09-15 16:25
@michael-russin We are the same, we need to offer the user the choice to import content from the browser, into our application. BTW there are **DevTools Protocol Page** events that can at least tell you when a file download has started and is complete.

**Comment by JoshuaWeber** [comment] 2020-09-15 20:45
@studylamp I am thinking about these asks as different scenarios. With possibly different implementation / solutions. 

1) is to interact with the user initiated download flow. For example the user clicking on a pdf link and the app performing extra work with the download. This is the work I'm currently investigating and specing out. 
2) App generated downloads for a long running download (such that WebApis for download don't work because the user may navigate away from the page). I also think this is a valid scenario. It is also a proposed [WebApi addition](https://wicg.github.io/background-fetch/), or [blog post](https://developers.google.com/web/updates/2018/12/background-fetch). I'm also curious to understand the tradeoffs in your case about doing the long running download in the host app, instead of in the JS layer.

**Comment by cbra-caa** [comment] 2020-10-21 15:57
Our current use case is that the WebView is acting as a preview component for a folder structure containing files. But if a file is broken, f.ex. an image which has been corrupted the WebView will start a download of this file instead of showing an error page. The same can be said for files that do not naturally have a preview, f.ex. a Zip-file.

What we would like to do is intercept the call and replace it with a navigation event to a page which explains the nature of the lack-of-preview.

Currently we can catch it on the backside via NavigationCompleted, as it will return that

`CoreWebView2NavigationCompletedEventArgs.IsSuccess = false
CoreWebView2NavigationCompletedEventArgs.CoreWebView2NavigationCompletedEventArgs = ConnectionAborted`

but we would rather have something along the lines of what @ukandrewc  posted (https://github.com/MicrosoftEdge/WebView2Feedback/issues/419#issuecomment-685656445)

**Comment by dbuechel** [comment] 2020-11-09 12:05
We'd be interested in an API which would allow handling of uploads as well, not just downloads.

**Comment by wf-soft** [comment] 2020-11-25 11:58
Can't access download events and iframe's kernel, it will be just a browser, and can't do more.

**Comment by DineshSolanki** [comment] 2020-11-26 11:26
+1

**Comment by alexisuk24** [comment] 2020-12-03 15:53
Hi @JoshuaWeber, I have the following use case that would require the exposing of Upload/Download APIs (and some others currently available in CefSharp which appears to be where most developers are migrating from to WebView2).

We maintain a tool that monitors for captive portals on public Wi-Fi connections and facilitates a user to authenticate to these captive portals before forcing a VPN connection to be established.  This tool is allow-listed in our host based firewall policy and we use hooks into the browser to prevent the user from using the tool to upload files, download files, copy/paste into and out of the browser.  Currently WebView2 does not respect the AllowDrop WinForms property and therefore we cannot prevent drag/drop of a hyperlink lnk file or a drag/drop upload form.  We also, cannot prevent File Open and File Save common dialogs that appear when a website requests an upload or provides a download.

Hopefully this use case clearly articulates why we would need WebView2 to additionally implement the following CefSharp events or equivilent:

`
ChromiumWebBrowser.MenuHandler (OnBeforeContextMenu, OnContextMenuCommand and RunContextMenu)
ChromiumWebBrowser.KeyboardHandler (OnPreKeyEvent and OnKeyEvent)
ChromiumWebBrowser.DialogHandler (OnFileDialog)
ChromiumWebBrowser.DragHandler (OnDragEnter)
`

If you think this should be a separate feature request, happy to open a new issue.

**Comment by JoshuaWeber** [comment] 2020-12-03 16:20
Thanks for all the engagement on this discussion everyone. It really does help us. We have been doing some investigation and design work to solve this scenario. And are planning to post a proposal for review soon.

**Comment by JoshuaWeber** [comment] 2020-12-03 16:27
@alexisuk24 I think I understand your scenario, but I'd like to confirm. I think your root problem is you want to disable upload/download/copy/paste for your tool. Because WebView2 doesn't follow the WinForms AllowDrop property (I think you are disabling this property), drag and drop is acting as a escape from your limits on behavior. This download API may also act as a way to catch those escapes.

I do see the drag drop part as a bit independent. While not exactly your issue (it is just direct control instead of linking to WinForms) #278 is an issue asking to disable drag and drop. Perhaps that would also help in your scenario?

**Comment by alexisuk24** [comment] 2020-12-03 16:38
@JoshuaWeber yes, #278 covers my need to control (disable) drag/drop behavior, I would be satisfied with the AllowDrop=False fully disabling any drag/drop features in the WebView2 control, but CefSharp's DragHandler pattern works for us too and has more flexibility for others potentially

**Comment by alexisuk24** [comment] 2020-12-03 16:43
@JoshuaWeber yes, the root problem is that we want to prevent the WebView from facilitating:

- Any downloads
- Any uploads
- Any copy/paste in or out
- Any popups (including new browser windows)
- Any ability to navigate to a new location based on a drag/drop event

or more simply put, any ways the user could use the embedded WebView2 to exfiltrate data or download content that wasn't explicitly typed into the control for the purposes of authenticating to a Wi-Fi hotspot with a captive portal

**Comment by jasonstephen15** [comment] 2020-12-04 04:44
@dbuechel - Thanks for your comment regarding the need to handle uploads. Just to better understand your use case, do you mind expanding on your app's scenario, and what you'd like out of an API to handle uploads? Would simply disabling uploads be enough?

**Comment by dbuechel** [comment] 2020-12-04 10:50
@jasonstephen15 We are building the open-source lockdown software [Safe Exam Browser](https://github.com/SafeExamBrowser) which contains a configurable browser component currently built with CefSharp / CEF. The browser can be configured to e.g. permit or deny file downloads / uploads as well as whether a user may browse the entire file system or only a certain folder when down- or uploading. So the API should ideally provide the same functionality as CefSharp / CEF currently does:

* Control over file system dialog:
  https://cefsharp.github.io/api/85.3.x/html/T_CefSharp_IDialogHandler.htm
  https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/Handlers/DialogHandler.cs
* Control over downloads:
  https://cefsharp.github.io/api/85.3.x/html/T_CefSharp_IDownloadHandler.htm
  https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/Handlers/DownloadHandler.cs

Really awesome would be if there also were an API to control / monitor file uploads (e.g. something like an IUploadHandler which doesn't exist in CefSharp / CEF) to be able to e.g. show status info about file uploads to users.

**Comment by jasonstephen15** [comment] 2020-12-07 16:46
@dbuechel - Got it noted, thanks! As Josh mentioned above, the download api spec should be out sson!

**Comment by jasonstephen15** [comment] 2021-01-08 20:30
Hi all! We are working to release the custom download api spec soon for review - the api should include ways to disable downloads, expose download metadata, and more! Aside from the custom download api, we are also in the works of changing the download experience in response to the Browser's changes. Here is a quick overview post: https://github.com/MicrosoftEdge/WebView2Feedback/issues/797, would appreciate any feedback thanks!

**Comment by jasonstephen15** [comment] 2021-01-27 01:39
Hi all, thank you for your patience! We've completed our design for the [Custom Download API](https://github.com/MicrosoftEdge/WebView2Feedback/pull/858/files?short_path=4950770#diff-49507708bcbcf26557279cf38a0dc688cf32374ba0aa65c383cab5aa6b5d11b5)! We would appreciate any feedback.

**Comment by DineshSolanki** [comment] 2021-02-08 15:34
> 
> 
> Hi all, thank you for your patience! We've completed our design for the [Custom Download API](https://github.com/MicrosoftEdge/WebView2Feedback/pull/858/files?short_path=4950770#diff-49507708bcbcf26557279cf38a0dc688cf32374ba0aa65c383cab5aa6b5d11b5)! We would appreciate any feedback, please leave it in the PR above!

This looks good, when can we use it.

**Comment by DineshSolanki** [comment] 2021-02-10 09:54
is there a way to allow multiple downloads programmatically, I hide the webview control while executing some scripts and the user can't click to allow multiple downloads.

**Comment by darbid** [comment] 2021-02-15 13:18
Just looking at your proposal. Looks similar to the Chrome Extension API which makes sense you both have only what CEF gives you.  I would therefore ask why you don't expose when the filename is resolved? Correct me if I am wrong but what do we show as the name of the file being downloaded in the UI?

**Comment by soumas** [comment] 2021-04-22 12:07
I am about to replace the old WebBrowser with the new WebView2 control in a project. I miss the possibility to refuse any file download ().
Is there already a forecast when the Download API will be released? Thank you!

**Comment by jasonstephen15** [comment] 2021-04-28 01:59
Hi all, thank you for your patience! Our download API has finally reached our pre-release package and is ready to be tried out in an experimental state! Would love to hear any feedback!

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentaldownloadoperation?view=webview2-1.0.865-prerelease

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental2?view=webview2-1.0.865-prerelease#add_downloadstarting

**Comment by soumas** [comment] 2021-04-28 12:17
Thanks for the good news, @JoshuaWeber! I can confirm that canceling downloads works as expected.

**Comment by jarno9981** [comment] 2021-04-30 17:02
@jasonstephen15  , @JoshuaWeber              ( is there any example for c# download handler like documentation)

**Comment by darbid** [comment] 2021-04-30 17:51
Have a look at the notes. Scroll down for C# https://github.com/MicrosoftEdge/WebView2Feedback/blob/bbffbe5fcad3f3c1e23a4b2f83fc9887c58e9625/specs/CustomDownload.md

**Comment by jarno9981** [comment] 2021-04-30 19:00
@darbid  
![Schermafbeelding 2021-04-30 191655](https://user-images.githubusercontent.com/53493418/116742021-189eab00-a9f7-11eb-80f3-b00c3aee5d50.png)

Few Issues Returning From Latest  webview 2

**Comment by jasonstephen15** [comment] 2021-05-06 19:16
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/CustomDownload.md

**Comment by jasonstephen15** [comment] 2021-05-06 19:19
Closing this issue as the API is now experimental, although feel free to continue feedback on this thread or open new issues! Thanks all.

**Closed by jasonstephen15** 2021-05-06 19:19 UTC
Labels: feature request

**Comment by wjvii** [comment] 2021-05-10 21:59
How do I handle the download of a pdf file? When I click on a pdf link in the webview2 control I need to save the pdf but it opens it in the webview2 control instead of triggering the download event. It does trigger the NavigationStarting event but how do I think download that pdf instead?

Thank you in advance.

**Comment by MSE1188** [comment] 2022-07-16 12:24
Same here. I am having a online pdf shown in the webview, but no download. I cannot use httpclient class for download, as the webview2 holds the cookies to access this pdf. How can I trigger the download automatically?

**Comment by darbid** [comment] 2022-07-16 12:37
You can check what the site is sending and copy it, including cookies, but it really is just reinventing the wheel.

**Comment by MSE1188** [comment] 2022-07-17 08:08
Thanks, I found a workaround by passing the cookies to a httpclient and then run the download there. For anyone who is interested:
```csharp
public async Task<Stream> Download(string url)
        {
            var clientCookies = new CookieContainer();
            using (var handler = new HttpClientHandler() { CookieContainer = clientCookies })
            using(var client = new HttpClient(handler))
            {
                var cookies = await this.webview.CoreWebView2.CookieManager.GetCookiesAsync(url);
                foreach(var ck in cookies)
                {
                    clientCookies.Add(ck.ToSystemNetCookie());
                }
                var response = await client.GetAsync(url);
                if(response.StatusCode != HttpStatusCode.OK)
                {
                    throw new InvalidOperationException($"Downloading from url '{url}' failed with status code '{response.StatusCode}'.");
                }
                return await response.Content.ReadAsStreamAsync();
            }
        }
```
However, would be really great, if I could simply start the download from the webview itself. The ChromiumWebBrowser (CefSharp) had a [StartDownload](https://cefsharp.github.io/api/93.1.x/html/M_CefSharp_WebBrowserExtensions_StartDownload.htm) extension for this. Something like this would be nice to have on CoreWebView2 :)
