### ISSUE TITLE
Navigation Completed event not raised occasionally

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#420] opened 2020-09-02 22:43 UTC
**Description**
I am using WebView2 to run the YouTube embedded player. Occasionally, I do not get a Navigation Completed event raised.

**Version**
SDK: 0.9.579-prerelease
Runtime: Microsoft Edge Webview2 Runtime 86.0.622.3
Framework: WinForms 
OS: Windows 10 1909 OS Build 18363.959

**Repro Steps**
**webView.NavigateToString(HTMLText)** where HTMLText contains HTML and JavaScript to invoke the YouTube embedded player to play a video.

Log the **Navigation Completed** events.

Let me know if you need more detail.

**Comment by pagoe-msft** [comment] 2020-09-03 16:34
Thanks @mikemeinz ,

I've filed a bug for us to investigat this.

**Comment by mikemeinz** [comment] 2020-09-08 15:00
Additional information.

Log entries for some WebView2 events that occur. Notice that **Navigation Completed** event is missing for some of the navigations. In each instance, the same HTML with embedded JavaScript is executed. 

LogTime                          LogRecord
2020-09-01 08:00:01	Navigation Starting 1
2020-09-01 08:00:01	Content Loading 1
2020-09-01 08:00:01	Frame Navigation Starting 1
2020-09-01 08:00:04	Frame Navigation Starting 2
2020-09-01 08:00:04	Frame Navigation Completed 1
2020-09-01 08:00:06	Frame Navigation Completed 2
2020-09-01 10:00:00	Navigation Starting 1
2020-09-01 10:00:00	Content Loading 1
2020-09-01 10:00:00	Frame Navigation Starting 1
2020-09-01 10:00:01	Frame Navigation Completed 1
2020-09-01 10:00:02	Frame Navigation Starting 2
2020-09-01 10:00:02	Frame Navigation Completed 2
2020-09-01 13:30:01	Navigation Starting 1
2020-09-01 13:30:01	Content Loading 1
2020-09-01 13:30:01	Frame Navigation Starting 1
2020-09-01 13:30:01	Frame Navigation Completed 1
2020-09-01 13:30:04	Frame Navigation Starting 2
2020-09-01 14:00:00	Navigation Starting 1
2020-09-01 14:00:00	Content Loading 1
2020-09-01 14:00:00	Frame Navigation Starting 1
2020-09-01 14:00:02	Frame Navigation Starting 2
2020-09-01 14:00:02	Frame Navigation Completed 1
2020-09-01 14:00:04	Frame Navigation Completed 2
2020-09-01 14:00:04	Navigation Completed
2020-09-01 15:30:01	Navigation Starting 1
2020-09-01 15:30:01	Content Loading 1
2020-09-01 15:30:01	Frame Navigation Starting 1
2020-09-01 15:30:01	Frame Navigation Completed 1
2020-09-01 15:30:03	Frame Navigation Starting 2
2020-09-01 15:30:03	Frame Navigation Completed 2
2020-09-01 16:00:01	Navigation Starting 1
2020-09-01 16:00:01	Content Loading 1
2020-09-01 16:00:01	Frame Navigation Starting 1
2020-09-01 16:00:01	Frame Navigation Completed 1
2020-09-01 16:00:02	Frame Navigation Starting 2
2020-09-01 16:00:02	Frame Navigation Completed 2
2020-09-01 19:30:01	Navigation Starting 1
2020-09-01 19:30:01	Content Loading 1
2020-09-01 19:30:01	Frame Navigation Starting 1
2020-09-01 19:30:01	Navigation Completed
2020-09-01 19:30:03	Frame Navigation Starting 2
2020-09-01 19:30:03	Frame Navigation Completed 2
2020-09-01 20:00:00	Navigation Starting 1
2020-09-01 20:00:01	Content Loading 1
2020-09-01 20:00:01	Frame Navigation Starting 1
2020-09-01 20:00:02	Frame Navigation Starting 2
2020-09-01 20:00:02	Frame Navigation Completed 1
2020-09-01 20:00:05	Frame Navigation Completed 2
2020-09-01 21:30:01	Navigation Starting 1
2020-09-01 21:30:01	Content Loading 1
2020-09-01 21:30:01	Frame Navigation Starting 1
2020-09-01 21:30:01	Frame Navigation Completed 1
2020-09-01 21:30:02	Frame Navigation Starting 2
2020-09-01 21:30:03	Frame Navigation Completed 2
2020-09-01 22:30:01	Navigation Starting 1
2020-09-01 22:30:01	Content Loading 1
2020-09-01 22:30:01	Frame Navigation Starting 1
2020-09-01 22:30:01	Frame Navigation Completed 1
2020-09-01 22:30:02	Frame Navigation Starting 2
2020-09-01 22:30:02	Frame Navigation Completed 2
2020-09-01 23:00:01	Navigation Starting 1
2020-09-01 23:00:01	Content Loading 1
2020-09-01 23:00:01	Frame Navigation Starting 1
2020-09-01 23:00:01	Navigation Completed
2020-09-01 23:00:02	Frame Navigation Starting 2
2020-09-01 23:00:02	Frame Navigation Completed 2
2020-09-02 00:00:01	Navigation Starting 1
2020-09-02 00:00:01	Content Loading 1
2020-09-02 00:00:01	Frame Navigation Starting 1
2020-09-02 00:00:01	Frame Navigation Completed 1
2020-09-02 00:00:02	Frame Navigation Starting 2
2020-09-02 00:00:02	Frame Navigation Completed 2
2020-09-02 03:30:01	Navigation Starting 1
2020-09-02 03:30:01	Content Loading 1
2020-09-02 03:30:01	Frame Navigation Starting 1
2020-09-02 03:30:01	Frame Navigation Completed 1
2020-09-02 03:30:03	Frame Navigation Starting 2
2020-09-02 08:00:01	Navigation Starting 1
2020-09-02 08:00:01	Content Loading 1
2020-09-02 08:00:01	Frame Navigation Starting 1
2020-09-02 08:00:01	Frame Navigation Completed 1
2020-09-02 08:00:03	Frame Navigation Starting 2
2020-09-02 08:00:03	Frame Navigation Completed 2
2020-09-02 10:00:01	Navigation Starting 1
2020-09-02 10:00:01	Content Loading 1
2020-09-02 10:00:01	Frame Navigation Starting 1
2020-09-02 10:00:03	Frame Navigation Starting 2
2020-09-02 10:00:03	Frame Navigation Completed 1
2020-09-02 10:00:05	Frame Navigation Completed 2
2020-09-02 10:00:05	Navigation Completed
2020-09-02 11:30:01	Navigation Starting 1
2020-09-02 11:30:01	Content Loading 1
2020-09-02 11:30:01	Frame Navigation Starting 1
2020-09-02 11:30:01	Frame Navigation Completed 1
2020-09-02 11:30:03	Frame Navigation Completed 2
2020-09-02 12:30:00	Navigation Starting 1
2020-09-02 12:30:01	Content Loading 1
2020-09-02 12:30:01	Frame Navigation Starting 1
2020-09-02 12:30:01	Frame Navigation Completed 1
2020-09-02 12:30:02	Frame Navigation Starting 2
2020-09-02 12:30:02	Frame Navigation Completed 2
2020-09-02 14:00:01	Navigation Starting 1
2020-09-02 14:00:01	Content Loading 1
2020-09-02 14:00:01	Frame Navigation Starting 1
2020-09-02 14:00:01	Frame Navigation Completed 1
2020-09-02 14:00:03	Frame Navigation Starting 2
2020-09-02 14:00:03	Frame Navigation Completed 2
2020-09-02 15:00:01	Navigation Starting 1
2020-09-02 15:00:01	Content Loading 1
2020-09-02 15:00:01	Frame Navigation Starting 1
2020-09-02 15:00:01	Frame Navigation Completed 1
2020-09-02 15:00:03	Frame Navigation Starting 2
2020-09-02 15:00:03	Frame Navigation Completed 2
2020-09-02 15:30:01	Navigation Starting 1
2020-09-02 15:30:01	Content Loading 1
2020-09-02 15:30:01	Frame Navigation Starting 1
2020-09-02 15:30:01	Frame Navigation Completed 1
2020-09-02 15:30:03	Frame Navigation Starting 2
2020-09-02 15:30:03	Frame Navigation Completed 2
2020-09-03 08:00:01	Navigation Starting 1
2020-09-03 08:00:01	Content Loading 1
2020-09-03 08:00:01	Frame Navigation Starting 1
2020-09-03 08:00:02	Frame Navigation Completed 1
2020-09-03 08:00:04	Frame Navigation Starting 2
2020-09-03 10:00:01	Navigation Starting 1
2020-09-03 10:00:01	Content Loading 1
2020-09-03 10:00:01	Frame Navigation Starting 1
2020-09-03 10:00:02	Frame Navigation Starting 2
2020-09-03 10:00:02	Frame Navigation Completed 1
2020-09-03 10:00:05	Frame Navigation Completed 2
2020-09-03 10:00:05	Navigation Completed
2020-09-03 11:00:01	Navigation Starting 1
2020-09-03 11:00:01	Content Loading 1
2020-09-03 11:00:01	Frame Navigation Starting 1
2020-09-03 11:00:01	Frame Navigation Completed 1
2020-09-03 11:00:04	Frame Navigation Starting 2
2020-09-03 11:00:04	Frame Navigation Completed 2
2020-09-03 12:30:01	Navigation Starting 1
2020-09-03 12:30:01	Content Loading 1
2020-09-03 12:30:01	Frame Navigation Starting 1
2020-09-03 12:30:01	Frame Navigation Completed 1
2020-09-03 12:30:03	Frame Navigation Starting 2
2020-09-03 12:30:03	Frame Navigation Completed 2
2020-09-03 16:00:00	Navigation Starting 1
2020-09-03 16:00:00	Content Loading 1
2020-09-03 16:00:00	Frame Navigation Starting 1
2020-09-03 16:00:01	Frame Navigation Completed 1
2020-09-03 16:00:02	Frame Navigation Starting 2
2020-09-03 16:00:02	Frame Navigation Completed 2
2020-09-03 17:30:00	Navigation Starting 1
2020-09-03 17:30:00	Content Loading 1
2020-09-03 17:30:01	Frame Navigation Starting 1
2020-09-03 17:30:01	Navigation Completed
2020-09-03 17:30:02	Frame Navigation Starting 2
2020-09-03 17:30:02	Frame Navigation Completed 2
2020-09-03 18:30:00	Navigation Starting 1
2020-09-03 18:30:00	Content Loading 1
2020-09-03 18:30:00	Frame Navigation Starting 1
2020-09-03 18:30:01	Frame Navigation Completed 1
2020-09-03 18:30:02	Frame Navigation Starting 2
2020-09-03 18:30:02	Frame Navigation Completed 2
2020-09-03 22:00:00	Navigation Starting 1
2020-09-03 22:00:00	Content Loading 1
2020-09-03 22:00:00	Frame Navigation Starting 1
2020-09-03 22:00:01	Frame Navigation Completed 1
2020-09-03 22:00:02	Frame Navigation Starting 2
2020-09-03 22:00:02	Frame Navigation Completed 2
2020-09-03 22:30:00	Navigation Starting 1
2020-09-03 22:30:00	Content Loading 1
2020-09-03 22:30:01	Frame Navigation Starting 1
2020-09-03 22:30:01	Frame Navigation Completed 1
2020-09-03 22:30:02	Frame Navigation Starting 2
2020-09-03 22:30:02	Frame Navigation Completed 2
2020-09-04 08:00:01	Navigation Starting 1
2020-09-04 08:00:01	Content Loading 1
2020-09-04 08:00:01	Frame Navigation Starting 1
2020-09-04 08:00:01	Frame Navigation Completed 1
2020-09-04 08:00:03	Frame Navigation Starting 2
2020-09-04 09:30:01	Navigation Starting 1
2020-09-04 09:30:01	Content Loading 1
2020-09-04 09:30:01	Frame Navigation Starting 1
2020-09-04 09:30:01	Frame Navigation Completed 1
2020-09-04 09:30:03	Frame Navigation Starting 2
2020-09-04 09:30:03	Frame Navigation Completed 2
2020-09-04 11:00:00	Navigation Starting 1
2020-09-04 11:00:00	Content Loading 1
2020-09-04 11:00:01	Frame Navigation Starting 1
2020-09-04 11:00:01	Frame Navigation Completed 1
2020-09-04 11:00:02	Frame Navigation Starting 2
2020-09-04 11:00:02	Frame Navigation Completed 2
2020-09-04 12:00:00	Navigation Starting 1
2020-09-04 12:00:01	Content Loading 1
2020-09-04 12:00:01	Frame Navigation Starting 1
2020-09-04 12:00:01	Frame Navigation Completed 1
2020-09-04 12:00:03	Frame Navigation Starting 2
2020-09-04 12:00:03	Frame Navigation Completed 2
2020-09-04 14:00:01	Navigation Starting 1
2020-09-04 14:00:01	Content Loading 1
2020-09-04 14:00:01	Frame Navigation Starting 1
2020-09-04 14:00:01	Frame Navigation Completed 1
2020-09-04 14:00:03	Frame Navigation Starting 2
2020-09-04 14:00:03	Frame Navigation Completed 2
2020-09-04 16:00:00	Navigation Starting 1
2020-09-04 16:00:00	Content Loading 1
2020-09-04 16:00:00	Frame Navigation Starting 1
2020-09-04 16:00:01	Frame Navigation Completed 1
2020-09-04 16:00:02	Frame Navigation Starting 2
2020-09-04 16:00:02	Frame Navigation Completed 2
2020-09-04 17:30:00	Navigation Starting 1
2020-09-04 17:30:01	Content Loading 1
2020-09-04 17:30:01	Frame Navigation Starting 1
2020-09-04 17:30:01	Frame Navigation Completed 1
2020-09-04 17:30:03	Frame Navigation Starting 2
2020-09-04 17:30:03	Frame Navigation Completed 2
2020-09-04 19:30:00	Navigation Starting 1
2020-09-04 19:30:00	Content Loading 1
2020-09-04 19:30:02	Frame Navigation Starting 1
2020-09-04 19:30:03	Frame Navigation Completed 1
2020-09-04 19:30:03	Navigation Completed
2020-09-04 19:30:04	Frame Navigation Starting 2
2020-09-04 19:30:04	Frame Navigation Completed 2
2020-09-04 21:30:01	Navigation Starting 1
2020-09-04 21:30:01	Content Loading 1
2020-09-04 21:30:01	Frame Navigation Starting 1
2020-09-04 21:30:01	Frame Navigation Completed 1
2020-09-04 21:30:03	Frame Navigation Starting 2
2020-09-04 21:30:03	Frame Navigation Completed 2
2020-09-04 23:00:01	Navigation Starting 1
2020-09-04 23:00:01	Content Loading 1
2020-09-04 23:00:01	Frame Navigation Starting 1
2020-09-04 23:00:01	Navigation Completed
2020-09-04 23:00:02	Frame Navigation Starting 2
2020-09-04 23:00:02	Frame Navigation Completed 2
2020-09-05 08:00:00	Navigation Starting 1
2020-09-05 08:00:00	Content Loading 1
2020-09-05 08:00:01	Frame Navigation Starting 1
2020-09-05 08:00:01	Navigation Completed
2020-09-05 08:00:02	Frame Navigation Completed 2
2020-09-05 09:00:00	Navigation Starting 1
2020-09-05 09:00:00	Content Loading 1
2020-09-05 09:00:00	Frame Navigation Starting 1
2020-09-05 09:00:02	Frame Navigation Starting 2
2020-09-05 09:00:02	Frame Navigation Completed 1
2020-09-05 09:00:05	Frame Navigation Completed 2
2020-09-05 09:00:05	Navigation Completed
2020-09-05 10:30:00	Navigation Starting 1
2020-09-05 10:30:00	Content Loading 1
2020-09-05 10:30:00	Frame Navigation Starting 1
2020-09-05 10:30:01	Frame Navigation Completed 1
2020-09-05 10:30:02	Frame Navigation Starting 2
2020-09-05 10:30:02	Frame Navigation Completed 2
2020-09-05 11:00:01	Navigation Starting 1
2020-09-05 11:00:01	Content Loading 1
2020-09-05 11:00:01	Frame Navigation Starting 1
2020-09-05 11:00:01	Frame Navigation Completed 1
2020-09-05 11:00:02	Frame Navigation Starting 2
2020-09-05 11:00:02	Frame Navigation Completed 2
2020-09-05 12:00:01	Navigation Starting 1
2020-09-05 12:00:01	Content Loading 1
2020-09-05 12:00:01	Frame Navigation Starting 1
2020-09-05 12:00:01	Navigation Completed
2020-09-05 12:00:02	Frame Navigation Starting 2
2020-09-05 12:00:02	Frame Navigation Completed 2
2020-09-05 14:00:01	Navigation Starting 1
2020-09-05 14:00:01	Content Loading 1
2020-09-05 14:00:01	Frame Navigation Starting 1
2020-09-05 14:00:01	Navigation Completed
2020-09-05 14:00:02	Frame Navigation Starting 2
2020-09-05 14:00:02	Frame Navigation Completed 2
2020-09-05 15:30:00	Navigation Starting 1
2020-09-05 15:30:01	Content Loading 1
2020-09-05 15:30:01	Frame Navigation Starting 1
2020-09-05 15:30:01	Navigation Completed
2020-09-05 15:30:02	Frame Navigation Completed 2
2020-09-05 16:00:01	Navigation Starting 1
2020-09-05 16:00:01	Content Loading 1
2020-09-05 16:00:01	Frame Navigation Starting 1
2020-09-05 16:00:01	Frame Navigation Completed 1
2020-09-05 16:00:03	Frame Navigation Starting 2
2020-09-05 16:00:03	Frame Navigation Completed 2
2020-09-05 17:30:00	Navigation Starting 1
2020-09-05 17:30:00	Content Loading 1
2020-09-05 17:30:01	Frame Navigation Starting 1
2020-09-05 17:30:01	Frame Navigation Completed 1
2020-09-05 17:30:02	Frame Navigation Starting 2
2020-09-05 17:30:02	Frame Navigation Completed 2
2020-09-05 18:30:01	Navigation Starting 1
2020-09-05 18:30:01	Content Loading 1
2020-09-05 18:30:01	Frame Navigation Starting 1
2020-09-05 18:30:01	Frame Navigation Completed 1
2020-09-05 18:30:02	Frame Navigation Starting 2
2020-09-05 18:30:02	Frame Navigation Completed 2
2020-09-05 22:00:00	Navigation Starting 1
2020-09-05 22:00:00	Content Loading 1
2020-09-05 22:00:00	Frame Navigation Starting 1
2020-09-05 22:00:01	Navigation Completed
2020-09-05 22:00:02	Frame Navigation Starting 2
2020-09-05 22:00:02	Frame Navigation Completed 2
2020-09-05 22:30:00	Navigation Starting 1
2020-09-05 22:30:00	Content Loading 1
2020-09-05 22:30:00	Frame Navigation Starting 1
2020-09-05 22:30:01	Navigation Completed
2020-09-05 22:30:02	Frame Navigation Starting 2
2020-09-05 22:30:02	Frame Navigation Completed 2
2020-09-06 08:00:00	Navigation Starting 1
2020-09-06 08:00:00	Content Loading 1
2020-09-06 08:00:00	Frame Navigation Starting 1
2020-09-06 08:00:01	Frame Navigation Completed 1
2020-09-06 08:00:02	Frame Navigation Starting 2
2020-09-06 08:00:02	Frame Navigation Completed 2
2020-09-06 09:30:01	Navigation Starting 1
2020-09-06 09:30:01	Content Loading 1
2020-09-06 09:30:01	Frame Navigation Starting 1
2020-09-06 09:30:01	Navigation Completed
2020-09-06 09:30:03	Frame Navigation Starting 2
2020-09-06 09:30:03	Frame Navigation Completed 2
2020-09-06 11:00:00	Navigation Starting 1
2020-09-06 11:00:00	Content Loading 1
2020-09-06 11:00:00	Frame Navigation Starting 1
2020-09-06 11:00:01	Frame Navigation Completed 1
2020-09-06 11:00:02	Frame Navigation Starting 2
2020-09-06 11:00:02	Frame Navigation Completed 2
2020-09-06 12:00:00	Navigation Starting 1
2020-09-06 12:00:00	Content Loading 1
2020-09-06 12:00:00	Frame Navigation Starting 1
2020-09-06 12:00:00	Frame Navigation Completed 1
2020-09-06 12:00:02	Frame Navigation Starting 2
2020-09-06 12:00:02	Frame Navigation Completed 2
2020-09-06 14:00:00	Navigation Starting 1
2020-09-06 14:00:00	Content Loading 1
2020-09-06 14:00:01	Frame Navigation Starting 1
2020-09-06 14:00:01	Frame Navigation Completed 1
2020-09-06 14:00:02	Frame Navigation Starting 2
2020-09-06 14:00:02	Frame Navigation Completed 2
2020-09-06 16:00:00	Navigation Starting 1
2020-09-06 16:00:00	Content Loading 1
2020-09-06 16:00:01	Frame Navigation Starting 1
2020-09-06 16:00:01	Frame Navigation Completed 1
2020-09-06 16:00:02	Frame Navigation Starting 2
2020-09-06 16:00:02	Frame Navigation Completed 2
2020-09-06 17:30:00	Navigation Starting 1
2020-09-06 17:30:00	Content Loading 1
2020-09-06 17:30:01	Frame Navigation Starting 1
2020-09-06 17:30:01	Frame Navigation Completed 1
2020-09-06 17:30:02	Frame Navigation Starting 2
2020-09-06 17:30:02	Frame Navigation Completed 2
2020-09-06 19:30:01	Navigation Starting 1
2020-09-06 19:30:01	Content Loading 1
2020-09-06 19:30:01	Frame Navigation Starting 1
2020-09-06 19:30:01	Frame Navigation Completed 1
2020-09-06 19:30:03	Frame Navigation Starting 2
2020-09-06 19:30:03	Frame Navigation Completed 2
2020-09-06 21:30:00	Navigation Starting 1
2020-09-06 21:30:00	Content Loading 1
2020-09-06 21:30:00	Frame Navigation Starting 1
2020-09-06 21:30:01	Frame Navigation Completed 1
2020-09-06 21:30:02	Frame Navigation Starting 2
2020-09-06 21:30:02	Frame Navigation Completed 2
2020-09-06 23:00:01	Navigation Starting 1
2020-09-06 23:00:01	Content Loading 1
2020-09-06 23:00:01	Frame Navigation Starting 1
2020-09-06 23:00:01	Frame Navigation Completed 1
2020-09-06 23:00:02	Frame Navigation Starting 2
2020-09-06 23:00:02	Frame Navigation Completed 2
2020-09-07 08:00:00	Navigation Starting 1
2020-09-07 08:00:00	Content Loading 1
2020-09-07 08:00:00	Frame Navigation Starting 1
2020-09-07 08:00:01	Frame Navigation Completed 1
2020-09-07 08:00:02	Frame Navigation Starting 2
2020-09-07 08:00:02	Frame Navigation Completed 2
2020-09-07 09:30:00	Navigation Starting 1
2020-09-07 09:30:00	Content Loading 1
2020-09-07 09:30:00	Frame Navigation Starting 1
2020-09-07 09:30:02	Frame Navigation Starting 2
2020-09-07 09:30:02	Frame Navigation Completed 1
2020-09-07 09:30:05	Frame Navigation Completed 2
2020-09-07 09:30:05	Navigation Completed
2020-09-07 11:00:00	Navigation Starting 1
2020-09-07 11:00:00	Content Loading 1
2020-09-07 11:00:01	Frame Navigation Starting 1
2020-09-07 11:00:01	Frame Navigation Completed 1
2020-09-07 11:00:02	Frame Navigation Starting 2
2020-09-07 11:00:02	Frame Navigation Completed 2
2020-09-07 12:00:01	Navigation Starting 1
2020-09-07 12:00:01	Content Loading 1
2020-09-07 12:00:01	Frame Navigation Starting 1
2020-09-07 12:00:01	Frame Navigation Completed 1
2020-09-07 12:00:03	Frame Navigation Starting 2
2020-09-07 12:00:03	Frame Navigation Completed 2
2020-09-07 14:00:00	Navigation Starting 1
2020-09-07 14:00:00	Content Loading 1
2020-09-07 14:00:01	Frame Navigation Starting 1
2020-09-07 14:00:01	Frame Navigation Completed 1
2020-09-07 14:00:02	Frame Navigation Starting 2
2020-09-07 14:00:02	Frame Navigation Completed 2
2020-09-07 16:00:01	Navigation Starting 1
2020-09-07 16:00:01	Content Loading 1
2020-09-07 16:00:01	Frame Navigation Starting 1
2020-09-07 16:00:01	Frame Navigation Completed 1
2020-09-07 16:00:03	Frame Navigation Starting 2
2020-09-07 16:00:03	Frame Navigation Completed 2
2020-09-07 17:30:00	Navigation Starting 1
2020-09-07 17:30:00	Content Loading 1
2020-09-07 17:30:00	Frame Navigation Starting 1
2020-09-07 17:30:01	Navigation Completed
2020-09-07 17:30:02	Frame Navigation Starting 2
2020-09-07 17:30:02	Frame Navigation Completed 2
2020-09-07 19:30:01	Navigation Starting 1
2020-09-07 19:30:01	Content Loading 1
2020-09-07 19:30:01	Frame Navigation Starting 1
2020-09-07 19:30:01	Frame Navigation Completed 1
2020-09-07 19:30:02	Frame Navigation Starting 2
2020-09-07 19:30:02	Frame Navigation Completed 2
2020-09-07 21:30:00	Navigation Starting 1
2020-09-07 21:30:00	Content Loading 1
2020-09-07 21:30:01	Frame Navigation Starting 1
2020-09-07 21:30:01	Frame Navigation Completed 1
2020-09-07 21:30:02	Frame Navigation Starting 2
2020-09-07 21:30:02	Frame Navigation Completed 2
2020-09-07 23:00:00	Navigation Starting 1
2020-09-07 23:00:00	Content Loading 1
2020-09-07 23:00:00	Frame Navigation Starting 1
2020-09-07 23:00:01	Frame Navigation Completed 1
2020-09-07 23:00:02	Frame Navigation Starting 2
2020-09-07 23:00:02	Frame Navigation Completed 2

**Comment by RedburnM** [comment] 2020-09-10 17:13
Duplicate of #366 ?

**Comment by mikemeinz** [comment] 2020-09-16 17:19
Sorry MSFT team.
I am closing this issue because I found that my logging routine was not necessarily writing every entry to the log file. Therefore, I have no proof that this issue is really occurring.

While I work on resolving my logging problem, if someone else notices this issue, please file a report.

Thanks.

**Closed** 2023-06-01 22:12 UTC
Labels: bug
