### ISSUE TITLE
onbeforeunload doesn't seem to be called when the window is closed

### ISSUE THREAD

**Issue by jdaless** [MicrosoftEdge/WebView2Feedback#746] opened 2020-12-16 19:07 UTC
**Description**

Check [here](https://github.com/dotnet/aspnetcore/issues/28678#issuecomment-746687354). Blazor circuits aren't being terminated when the window is closed. 

**Version**
SDK: 1.0.721-prerelease
Runtime: Using Evergreen bootstrapper, 87.0.664.60
Framework: WPF
OS: Win10

**Repro Steps**

See linked issue above.

[AB#44875818](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44875818)

**Comment by Fab06460** [comment] 2022-09-23 14:39
Hi, I would be also interessed in a fix for this issue: beforeunload event handler is never called when a webview2 window is closed by the user (WPF).
Thanks !

**Comment by fvanheeswijk** [comment] 2023-03-08 15:50
Is there any update on this?

**Comment by champnic** [comment] 2023-06-01 22:34
Sorry looks like we missed this one. I've added this to our backlog. In general I don't think we want the WebView2 control to block the window hosting it from trying to close, but there should be a way for the native app host to pause the window closing, try to close WebView2 (and potentially cause a beforeunload dialog) and then continue closing the window or not depending on the outcome.

**Comment by fvanheeswijk** [comment] 2023-06-30 12:10
It looks like you fixed this already? We don't see the issue anymore.

**Comment by monica-ch** [comment] 2023-07-05 21:49
Closing the issue as it is not reproduced anymore, may be underlying framework has fixed the issue.

**Closed by monica-ch** 2023-07-05 21:49 UTC
Labels: bug, tracked

**Comment by CommonGuy** [comment] 2023-07-06 12:02
I can still reproduce this. Is this tied to some specific SDK/runtime version or am I doing something wrong?

**Comment by monica-ch** [comment] 2023-07-06 17:26
@CommonGuy I am testing the [sample app](https://github.com/jdaless/WebView2Blazor) mentioned in the thread with the latest stable WV2 runtime and SDK version.

Note: Also, commented `window['Blazor'].disconnect` code in WebView for testing purposes.
