### ISSUE TITLE
Returning Date object in javascript does'nt work

### ISSUE THREAD

**Issue by cmakloufi** [MicrosoftEdge/WebView2Feedback#1496] opened 2021-07-05 13:01 UTC
**Description**
When executing a script that return a Date object with ICoreWebView2::ExecuteScript, the result string in the handler is "{}". 
With IE WebView, it seems to stringify the object in the result variable.

**Version**
SDK: 1.0.902-prerelease
Runtime: Microsoft Edge Canary 93.0.939.0
Framework: Win32
OS: Win 10 1909 18363.836

**Repro Steps**
Execute a script like "new Date('Jun 24 2016 11:55:30 GMT');". With WebView2 it returns "{}".
With IEWebView it returns the stringified date ("2016-06-24T11:55:30.000Z").

[AB#34467217](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34467217)

**Comment by champnic** [comment] 2021-07-12 19:09
Thanks for the bug report @cmakloufi! I've added it to our backlog. Sounds from #105 that you can use `date.toString()` for now to workaround this issue.

**Comment by champnic** [comment] 2023-03-04 05:29
Closing as a dupe of #105.

**Closed by champnic** 2023-03-04 05:29 UTC
Labels: bug, tracked
