### ISSUE TITLE
[Bug]: ‘Find in page’ focus loop

### ISSUE THREAD

**Issue by lezzi** [MicrosoftEdge/WebView2Feedback#4469] opened 2024-04-04 14:59 UTC
### What happened?

When ‘Find in page’ dialog focus is manually changed to the native UI (WPF), it enters a focus loop that jumps back and forth.

This seems to be broken only in the stable runtime.

![763E4A0F-5642-4EF9-BCCC-BCD775CE0CA1](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5619119/23100c89-ccdd-4559-a7d6-eadb6c37aa0f)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.65

### SDK Version

2470.0, 1722.45

### Framework

WPF

### Operating System

Windows 11

### OS Version

22631.2861

### Repro steps

1. Clone and launch the [WPF sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser).
2. Launch it and ensure it targets the runtime `123`.
3. Click `Ctrl` + `F` to open the ‘Find in page’ dialog.
4. Type any text.
5. Attempt to focus any WPF UI by left clicking outside the WebView2 area, for example a window title or menu.
6. Observe the focus loop.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

122.0.2365.80, 124.0.2478.19, 125.0.2501.0

[AB#49911452](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/49911452)

**Comment by pdolanjski** [comment] 2024-04-04 15:10
@nishitha-burman we just discovered this regression (which looks to only apply to v123). It's breaking the Find in page functionality in our browser. Is there any chance of a quick fix that can be cherry picked to stable?
It's somewhat limited in that it'll only affect those who use the functionality, but it is a highly frustrating experience as the bug precludes you from clicking on other native UI (eg. you can't close a tab without clicking multiple times when the Find in page dialog is open).

Our other option is to wait until v124 hits stable, but even in that scenario, we wanted to highlight this issue in case there's an underlying cause that is likely to regress again.

**Comment by champnic** [comment] 2024-04-08 20:43
Hey @lezzi / @pdolanjski - thanks for surfacing this! Given it seems to be resolved I'm going to close this out, but please let us know if you experience this in the future. We won't be able to cherry-pick a fix to 123 for this issue. We're working on adding some UI tests that are better able to catch things like this in the future.

**Closed by champnic** 2024-04-08 20:43 UTC
Labels: bug, tracked, regression
