### ISSUE TITLE
WebView2 getting stuck / Freezes  on some windows 10 machines with (Intel HD) Graphic on latest Runtime VER(108.0.1462.46)

### ISSUE THREAD

**Issue by markismail7** [MicrosoftEdge/WebView2Feedback#3063] opened 2022-12-13 15:07 UTC
Hi @champnic    
Sorry i had to change the question as i have more details on what's going on,  after hours of researching. Webview2 crashes and causing the app to crash with the latest Microsoft Edge Webview2 Runtime Version (108.0.1462.46). This happens only on computers  with (Intel HD) Graphic integrated that runs Windows 10.

There is no fix for it as of right now, Luckly i keep a previous version of Microsoft Edge Webview2 Runtime. I had my customers downgrade Webview2 Runtime to 101.0.1210.39 . Problem is fixed on those computers. However Webview2 Runtime updates automatically, so we need fix from Microsoft asap.

Thanks
Mark

Thanks 

[AB#42831673](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42831673)

**Comment by champnic** [comment] 2022-12-13 23:05
Hey @markismail7 - Do you have some sample code or an app that can reproduce this issue? I assume you are trying to close down a WebView2 control and are seeing some process sticking around. Can you expand on the scenario, as well as what you mean by "not being able to handle it"? Thanks!

**Comment by digiofficerobin** [comment] 2022-12-14 13:36
Hi @champnic , we are having the same issue here with an increasing number of users reporting this issue. We have a VSTO addin in Outlook which starts a form with a WebView2 control. I have made a memory dump of Outlook and the msedgewebview2 process at the time the processes are hanging. 

I cannot make any sense out of it in Visual Studio, but maybe you can get a clue about what to look for.

Webview2 process:
![image](https://user-images.githubusercontent.com/16424069/207607274-b7f4c10e-09fb-4f28-a90e-5a5f2b472faf.png)

Webview 2 callstack:
![image](https://user-images.githubusercontent.com/16424069/207607360-02ebb300-7687-49d4-aefd-abcd1e319c44.png)

Outlook with our addin:
![image](https://user-images.githubusercontent.com/16424069/207608996-5a7e3093-2af4-41f1-82a6-b412870ebcaa.png)

**Comment by digiofficerobin** [comment] 2022-12-15 12:33
@champnic The issue can be replicated by executing this small Windows program. The source code is included.

Start the executable in the bin\debug folder. Click on the button. This opens a form with a WebView2 component and loads the msn website. Close the window and reopen it by clicking again on the button. The program hangs in 3 to 5 iterations.

The problem doesn't arise on every machine.

[WebView2Test.Src.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10236921/WebView2Test.Src.zip)

**Comment by markismail7** [comment] 2022-12-16 01:47
> Hey @markismail7 - Do you have some sample code or an app that can reproduce this issue? I assume you are trying to close down a WebView2 control and are seeing some process sticking around. Can you expand on the scenario, as well as what you mean by "not being able to handle it"? Thanks!

Let me just clarify, and you know i only contact you if there is a real issue. As i have thousands of customers. For the past 2 weeks,  i've been getting too many calls about the same problem from customers who are using windows10. I checked it out, For example, my app opens webview2 for the first time and load a website. It load perfectly without any problems. If the customer goes back to app and closes webview2 and open it again. It will take over 20 seconds to do so. That is if it does load at all. I have not encountered  this problem on Windows 11 at all. But the hard part, not all windows 10 users are having this problem. If i open task managers on those affected machines, id see multiple webview2 opened. If i stop the processes, basically it works again till the problem occurs. Something is not being able to handle the processes of webview2 on those machines. Its like the process of webview2 is getting stuck or crashed. This problem started happening after the latest update of Edge webview2 runtime on windows 10. Sorry for the late reply, i had an emergency. If you any more information about those machines please let me know. Keep in mind, it does not happen on every machine that runs windows10
Thank You

**Comment by markismail7** [comment] 2022-12-16 01:47
@champnic 

Let me just clarify, and you know i only contact you if there is a real issue. As i have thousands of customers. For the past 2 weeks,  i've been getting too many calls about the same problem from customers who are using windows10. I checked it out, For example, my app opens webview2 for the first time and load a website. It load perfectly without any problems. If the customer goes back to app and closes webview2 and open it again. It will take over 20 seconds to do so. That is if it does load at all. I have not encountered  this problem on Windows 11 at all. But the hard part, not all windows 10 users are having this problem. If i open task managers on those affected machines, id see multiple webview2 opened. If i stop the processes, basically it works again till the problem occurs. Something is not being able to handle the processes of webview2 on those machines. Its like the process of webview2 is getting stuck or crashed. This problem started happening after the latest update of Edge webview2 runtime on windows 10. Sorry for the late reply, i had an emergency. If you any more information about those machines please let me know. Keep in mind, it does not happen on every machine that runs windows10
Thank You

**Comment by digiofficerobin** [comment] 2022-12-16 09:37
We have two users at our site who has this problem consistently. When the user starts the test app (see my previous comment) and hit the button, then 3 'msedgewebview2' processes are started and of course the process of the app 'WebView2Test'. The app hangs. Then I let the user made 4 memory dumps and have opened these in Visual Studio 2022.

The problem is probably in the direction of a deadlock (race condition) in the multiple threads of the multiple processes. Therefore I made parallel threads screenshots of the 4 processes. See below. I hope this gives you more insight into the problem.

Main process 'WebView2Test' (last C# codeline).
![image](https://user-images.githubusercontent.com/16424069/208068530-9a99ea1a-dcc4-427a-97b7-046ba4737dba.png)

Main process 'WebView2Test'. Parallel call stack.
![image](https://user-images.githubusercontent.com/16424069/208068546-78738264-7a94-46a1-b0e0-8c0933b2e9e8.png)

Subprocess 1 'msedgewebview2'.
![image](https://user-images.githubusercontent.com/16424069/208068733-c9e2d505-31ef-4c93-a08b-d0ec6f2a0e01.png)

Subprocess 2  'msedgewebview2'.
![image](https://user-images.githubusercontent.com/16424069/208068763-39c6714c-abb2-46b9-a270-9e0242ea8f83.png)

Subprocess 3 'msedgewebview2'.
![image](https://user-images.githubusercontent.com/16424069/208068814-0031fffb-37a9-4358-9c49-b6184333ffeb.png)

**Comment by markismail7** [comment] 2022-12-16 14:43
Hi @champnic ,
I figured out why this happening only on to certain machines that run Windows 10.  At least that's what it seems like. Every computer that is upgrading from 21H2 or 20H2 to 22H2 on windows 10 is having this issue. I'll keep you posted. But definitely all, its windows10 22H2 upgrade is causing the issue.

Thank you

**Comment by digiofficerobin** [comment] 2022-12-20 11:53
The issue seems resolved with the update of 108.0.1462.54.

**Comment by champnic** [comment] 2023-01-03 18:56
I've added this bug to our database to track, though sounds like it may be resolved. @markismail7 Do you still see the issue with 108.0.1462.54 that @digiofficerobin mentions?

**Comment by champnic** [comment] 2023-01-06 21:42
Tentatively closing this issue, but please let me know if you are still seeing it with the newer runtime versions and we can reactivate. Thanks!

**Closed by champnic** 2023-01-06 21:42 UTC
Labels: bug, tracked
