### ISSUE TITLE
[Problem/Bug]: Download PDF from HTTP blocked 

### ISSUE THREAD

**Issue by Tifoso-1979** [MicrosoftEdge/WebView2Feedback#4500] opened 2024-04-23 09:55 UTC
### What happened?

With version 124.0.2478.51 PDF files have been blocked from HTTP source (internal network). With version 123.0.2420.97 it was working without restriction. I have also tried to add this HTTP source to allow list "insecure content" but it doesn't help.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.51

### Framework

Other

### Operating System

Windows 10

### OS Version

Win10, 22H2, 19045.4291

### Repro steps

download pdf from http source (internal trusted network/Source). pdf have been blocked, error message "file can't be downloaded"

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

123.0.2420.97

[AB#50289352](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50289352)

**Comment by Tifoso-1979** [comment] 2024-04-23 13:56
additional note:
the problems seems to be releated with the build in pdf viewer in edge. open pdf from untrusted source HTTP and try to save show me the error.

**Comment by monica-ch** [comment] 2024-04-23 18:14
@Tifoso-1979 Do you also see the same issue in Edge browser?

**Comment by monica-ch** [comment] 2024-04-23 22:10
@Tifoso-1979 In WebView2 124.0.2478.51+, downloading files over HTTP is blocked and displays the message “xxx can’t be downloaded securely” . This is by design and aligned to the Chromium ["HTTPS by default" initiative](https://blog.chromium.org/2023/08/) to provide enhanced security.

To address the issue you’re facing with the app, here are the workarounds you can consider:

1. Upgrade to HTTPS: Upgrading to HTTPS can enhance security and may resolve certain issues related to content downloading or display.
2. Manual File Keeping: For the default downloads UI, instruct end users to manually keep the file when prompted. 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/69160047/8e044042-cc25-4880-a7f0-574b5f95bc30)
4. Use [DownloadStarting](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.2420.47): Implement the DownloadStarting event in your application. This allows the app to handle download requests and potentially block the default download dialog, enabling downloads to proceed without interruption.

Here’s a sample code snippet on how you might use the DownloadStarting event:
```
webView.CoreWebView2.DownloadStarting += (sender, args) =>
{
    // Implement custom download handling logic here
    args.Handled = true; // Set to true to block the default download dialog
};

```

**Comment by Tifoso-1979** [comment] 2024-04-24 06:04
thank you for the answer.
Is there a possibility to configure an exeption. In the edge browser settings it is possiblice to configure and allow insecure content but this is not matching with the buildin pdf viewer.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/167864843/61205752-dcdc-409e-ad02-9ca37da85e38)

**Comment by mrn3ff** [comment] 2024-04-25 17:26
We are also experiencing this issue with the build mentioned...  When our users attempt to download a PDF from our online CRM platform the PDF will pop out in a new window (Edge window). The URL field with some content is **about:blank** and cannot be exempt. The URL field with other content we attempt to download (_from the same CRM platform_) will show the full **https://*** URL and we can successfully download the PDF.

**Comment by andrej-w** [comment] 2024-04-30 04:46
Same as here with the Edge Browser https://techcommunity.microsoft.com/t5/enterprise/mixed-mode-content-download-warning/m-p/4118977
But there is no setting in WebView2 for "Insecure downloads over HTTP"

**Comment by monica-ch** [comment] 2024-04-30 20:48
@Tifoso-1979 @andrej-w  Currently, there is no direct API or setting in WebView2 that allows you to add sites and explicitly allow “insecure content.”

Could you please create a feature request with us? Keep in mind that it may take some time for us to investigate and release the requested feature due to backlog priorities. However, you can follow a workaround.

**Comment by monica-ch** [comment] 2024-04-30 22:22
@Tifoso-1979 @andrej-w @mrn3ff We've reverted the download warning in Edge/Webview2 for HTTP in recent stable patch [see here](https://techcommunity.microsoft.com/t5/enterprise/mixed-mode-content-download-warning/m-p/4118977) and expected to be turn on very soon. Please work on to upgrading to HTTPS or use DownloadStarting to allow downloads to avoid issues when the feature is turned on.

**Comment by monica-ch** [comment] 2024-04-30 22:35
We recommend apps to setup automated pipeline to test important features with pre-release channel to figure out this regression way ahead of stable.

https://github.com/MicrosoftEdge/WebView2Announcements/issues/93

**Comment by Tifoso-1979** [comment] 2024-05-01 05:18
@monica-ch 
thank you for the help. 
With the version 124.0.2478.67 it is working as before. In the release notes it is written that this security will be enabled again with version 127.x. For me it is important that we can configure exceptions which are working for the **_built-in pdf_** feature and classic browser mode.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/167864843/642307fe-3497-47f0-8244-21627e3e06d4)

**Comment by monica-ch** [comment] 2024-05-13 17:10
@Tifoso-1979 I am closing the current issue. Feel free to open a feature request to allow/block Insecure content in WV2.

**Closed by monica-ch** 2024-05-13 17:10 UTC
Labels: bug, tracked, regression
