### ISSUE TITLE
Creating a WebView synchronously in win32?

### ISSUE THREAD

**Issue by beretboat** [MicrosoftEdge/WebView2Feedback#740] opened 2020-12-14 08:21 UTC
I'm using [CreateCoreWebView2Controller](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.664.37#createcorewebview2controller), which is asynchronous. 
Is there any way to create a WebView synchronously in win32? 
I saw #697, but it's not win32.

[AB#31562227](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31562227)

**Comment by ysc3839** [comment] 2020-12-15 17:35
There's no way to do this.
You said:
> The problem is in the message loop of our app

in #724
I think you should try to fix the message loop. Can you give some minimal reproducible code?

**Comment by beretboat** [comment] 2020-12-16 02:18
> There's no way to do this.
> You said:
> 
> > The problem is in the message loop of our app
> 
> in #724
> I think you should try to fix the message loop. Can you give some minimal reproducible code?

Actually, this has nothing to do with #724. The message loop is not an issue now. But still, we need a way to create a WebView synchronously. 

We're using CEF in our app, and we'd like to replace CEF with WebView2. In CEF we could create a WebView synchronously, so we have lots of code like this:

```
// pseudo code
CefBrowser *browser = CefBrowserHost::CreateBrowserSync(...)
browser->loadURL("URL");
browser->loadScript("...");
```

We'd like to be able to do the same in WebView2:
```
// pseudo code
wil::com_ptr<ICoreWebView2> webView = CreateWebView2(...);
//webView is ready.
webView->Navigate("www...");
// other calls to webView.
```

I know that we could manipulate the webView in the callback of creating like this:
```
// pseudo code
CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr,
    Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
        [hWnd](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
                    env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(                
[hWnd](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {

                wil::com_ptr<ICoreWebView2> coreWebView2;
                controller->get_CoreWebView2(&webviewWindow);
                coreWebView2.query_to(&webView);
                webView->Navigate("www...");
                // other calls to webView.
                return S_OK;
            }).Get());
        return S_OK;
    }).Get());
```
But the actual code is much more complicated than just `webView->Navigate("www...");`. For our app, which is huge and has a lot of CEF code, the effort to switch to WebView2 without a way to creating a WebView synchronously will be huge.

**Comment by ysc3839** [comment] 2020-12-16 07:26
A solution is to run a message loop in your "create webview" function  to make it "looks like sync".
```
// pseudo code
auto create_webview() {
	wil::com_ptr<ICoreWebView2> coreWebView2;

	CreateCoreWebView2EnvironmentWithOptions(..., [&](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
		env->CreateCoreWebView2Controller(..., [&](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
			controller->get_CoreWebView2(&webviewWindow);

			PostQuitMessage(0);

			return S_OK;
		}).Get());
		return S_OK;
	}).Get());

	while (GetMessage(...)) {
		...
	}
	return coreWebView2;
}
```

**Comment by romanan** [comment] 2021-01-29 06:05
We've had some luck using a small message loop while waiting for the callback.  Since the native application has many message handlers, we don't want to run random code while waiting for this, I'm trying to limit the messages that are pumped.  The window handle of the window that WebView2 is using is not available via API, so the handle parameter to GetMessage must be NULL.  But I've discovered that the message ID appears to be 0x401 (WM_USER + 1), so the loop likes this:
MSG msg;
while (!created && GetMessage(&msg, NULL, WM_USER + 1, WM_USER + 1)
{
  TranslateMessage(&msg);
  DispatchMessage(&msg);
}
Will this be sufficient to make sure that the WebView receives messages from the child process?

**Comment by jschroedl** [comment] 2021-01-29 15:12
IMO it would really behoove MS and us WebView2 clients to have either 1) [BEST] an API allowing synchronous creation (and Javascript execution) or 2) [GOOD] an explicit sample illustrating synchronous creation and JS execution.  

The issue list is littered with folks trying to cobble together message loops or other techniques to perform synchronous actions on the control. Having us all experiment and head in different directions can only spell trouble down the road when internals change. The old WebView OCX was synchronous and that's the code we need to migrate.

**Comment by kfke** [comment] 2021-01-29 16:02
I agree with you and hope that someone will pay attention to this and give us a clean solution to this problem

**Comment by RayIon** [comment] 2021-01-29 20:11
I have to +1 this as well.. I'm working with a Win32/C++ application and I'll have to code a solution to this as well. An 'official' best practice or example would be great.

**Comment by jschroedl** [comment] 2021-01-29 20:14
Pinging @champnic @liminzhu in case this falls off their radar since it's not tagged as "bug". Can we change this from Question to Bug?

**Comment by romanan** [comment] 2021-01-31 13:13
Here's my final solution:
`    auto hwnd = FindWindowEx(HWND_MESSAGE, NULL, L"Chrome_MessageWindow", NULL);  // This Window name is undocumented
    MSG msg;
    while (!donePredicate() && GetMessage(&msg, hwnd, 0, 0))
    {
        // From observation, the Edge hidden window uses WM_USER + 1.  Since there's no API access to the window, there's no
        // way to be sure that only its messages are retrieved.
        ASSERT(msg.message == WM_USER + 1);
        TranslateMessage(&msg);  // Probably not necessary for this scenario
        DispatchMessage(&msg);
    }
`

From this it's clear that the key window that needs to receive messages is this "Chrome_MessageWindow".  I would like to raise a feature request that clients be able to choose between sync or async calls (not just to create).  If the API can't change, maybe a helper header file that contains the above code, so at least clients will be updated if the name of the window or the message ID changes.

**Comment by romanan** [comment] 2021-02-01 02:56
If anyone tries to reuse my code snippet above, be careful.  It worked fine for the first browser window, but if your application displays multiple browsers at once it fails, there are multiple message windows with the same class name.  I finally gave up and just did something like this:
` while (!donePredicate() && GetMessage(&msg, NULL, WM_USER + 1, WM_USER + 1)`
` {
`        // Since there are multiple windows of the same class, the call to GetMessage can't be restricted by HWND as there's no API access.`
`        // Perform some checking here to make sure we don't pump unrelated custom messages`
`        GetClassName(msg.hwnd, name, MAX_NAME);`
`        ASSERT(0 == wcscmp(name, L"Chrome_MessageWindow")); // This Window name is undocumented.  If this ASSERT fires, Edge may have renamed the window`
`}`

**Comment by champnic** [comment] 2021-02-01 23:20
@jschroedl Thanks for the ping, I had missed this one over winter break. I've added this as a feature request on our backlog. I encourage you all to use the control asynchronously if possible, as the WebView2 is using cross-process async messaging. However, I realize that this can cause pain especially when migrating from a previously synchronous control. 

Are you all blocked from using the control asynchronously, or is it just that it would require rewriting a lot of code? If blocked, can you expand a bit on why? Thanks!

**Comment by szilvaa-adsk** [comment] 2021-02-01 23:55
@champnic  Creating the browser windows synchronously is only part of the problem. We also want to execute code in the browser synchronously. We were able to do this with CEF before because enough details of the asynchronous message passing were exposed that we could "wait" for the callback. We need something similar with WebView2. 
We need a `WaitUntil( predicate)` that simply dispatches messages on `Chrome_MessageWindow` until predicate returns true.

**Comment by romanan** [comment] 2021-02-03 07:06
Ironically, I found one piece of our UI that does try to be asynchronous: it uses std::async to run a Javascript script to fire an event.  This worked in CEF but fails as ExecuteScript returns: "This method can only be called from the thread that created the object."

**Comment by champnic** [comment] 2021-02-04 00:37
@romanan The WebView2 API surface is single-threaded - as the error message states, you would have to make sure the ExecuteScript call happens on the thread that created the WebView2. ExecuteScript is itself async and non-blocking, so should be safe to run on the UI thread and unnecessary to try and run it on a different thread.

**Comment by romanan** [comment] 2021-02-04 00:41
> @romanan The WebView2 API surface is single-threaded - as the error message states, you would have to make sure the ExecuteScript call happens on the thread that created the WebView2. ExecuteScript is itself async and non-blocking, so should be safe to run on the UI thread and unnecessary to try and run it on a different thread.

Yes, you're right, this really just exposed a bug in our previous code.  The code was not thread safe and should not be running in a separate thread, no one had noticed until now.

**Comment by laurent0502** [comment] 2021-09-27 11:01
Hello,

I've also the same  problem. In brief, I explain you my problem. 

I created a class EdgeBrowser with a constructor who receives the handle of my WIN32 component (HWND component). In my constructor, I do something like that : 

```
EdgeBrowser::EdgeBrowser(HWND hwnd)
{
      _hwnd = hwnd;
      EdgeBrowser::_beginAsyncOperation = true;
      this->CreateWebView();
      
      while (EdgeBrowser::_beginAsyncOperation)
      {
             Sleep(10);
             MSG msg;
             for (int nmsg = 0; nmsg < 50; ++nmsg)
             {
                    int rc = PeekMessage(&msg, NULL, 0, 0, PM_REMOVE);

                    if (rc == 0)
                    {
                           break;
                    }
                    TranslateMessage(&msg);
                    DispatchMessage(&msg);
             }
      }
}
```

And in a part of my "CreateWebView" function with the different listeners : 

```
void EdgeBrowser::CreateWebView 
{
          // other code
          HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(nullptr, userDataDir.c_str(),nullptr,Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(this,&EdgeBrowser::OnCreateCoreWebView2EnvironmentCompletedHandler).Get()); 
}
```

```
HRESULT EdgeBrowser::OnEnvironmentReadyCompletedHandler(HRESULT result, ICoreWebView2Environment* env)
{
HRESULT createBrowserControlsResult = m_uiEnv->CreateCoreWebView2Controller(this->_thisHandler, Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(this,&EdgeBrowser::OnCreateCoreWebView2ControllerCompletedHandler).Get());
          
HRESULT createBrowserOptionsResult = m_uiEnv->CreateCoreWebView2Controller(this->_thisHandler,Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>( this,&EdgeBrowser::OnCreateCoreWebView2ControllerOptionsCompletedHandler).Get());
}
```

```
HRESULT EdgeBrowser::OnCreateCoreWebView2ControllerOptionsCompletedHandler(HRESULT result, ICoreWebView2Controller* host)
{
       m_optionsController = host;
       HRESULT getOptWebViewResult = m_optionsController->get_CoreWebView2(&m_optionsWebView);
       
       //other code
       EdgeBrowser::_beginAsyncOperation = false;
       return S_OK;
}
```

In my application, I've a button to load the browser. When I click on the button, it opens and creates well the webBrowser (white rectangle).

BUT when I try to create the web Browser when I open a window (who contains different components : buttons, edittext,...) of my application through the Event WM_SHOWWINDOW, I don't see my web browser EXCEPTED IF I put in comment all the loop "while" in the constructor EdgeBrowser.

Why ? Can you give me a solution please ? It would be friendly.

**Comment by raroraca** [comment] 2022-08-26 09:06
@champnic Do we have any update on this request?

**Comment by champnic** [comment] 2022-09-07 23:45
No update - it's unlikely we'll visit this issue soon.

**Comment by champnic** [comment] 2023-03-04 05:01
We don't currently have plans to continue exploring a synchronous version of our API. Closing this item.

**Closed by champnic** 2023-03-04 05:01 UTC
Labels: feature request, tracked
