### ISSUE TITLE
Creating Multiple WebView2 Instances causes 0x8007139f error on one Instance

### ISSUE THREAD

**Issue by mingchengzack** [MicrosoftEdge/WebView2Feedback#2703] opened 2022-08-19 18:51 UTC
**Description**
When we try to run two sample apps` WebView2APISample` at the same time, run `.\WebView2APISample.exe ; .\WebView2APISample.exe` , one instance pops up the error of 0x8007139f.
![Screenshot 2022-08-19 113426](https://user-images.githubusercontent.com/38195223/185684764-95030d29-66fc-4507-87d7-b6579a5acde8.png)

**Version**
SDK: 1.0.1340-prerelease (but should be reproduced with 1.0.1293.44 as well)
Runtime: 104.0.1293.54
Framework: Win32
OS: Win 11

[AB#41026429](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41026429)

**Comment by victorthoang** [comment] 2022-08-21 23:22
@mingchengzack I will ask around and see if I can find someone best suited to investigate this. Thanks!

**Comment by Syul968** [comment] 2022-08-22 17:42
Hi @mingchengzack,

This is a racing condition where the WebView2 Runtime configuration appears to be different for the two app processes requesting creation. Delaying the second launch a bit will prevent the race. Is this an issue with your project?

Thanks,
Luis

**Comment by mingchengzack** [comment] 2022-08-22 17:46
> Hi @mingchengzack,
> 
> This is a racing condition where the WebView2 Runtime configuration appears to be different for the two app processes requesting creation. Delaying the second launch a bit will prevent the race. Is this an issue with your project?
> 
> Thanks, Luis

Yes as we can launch two our apps at the same time. Is there a better way to prevent this? Also is it possible to prevent this racing condition on your side as we are using the same environment options which shouldn't cause this configuration different problem?

**Comment by Syul968** [comment] 2022-08-22 17:59
I have opened a work item on our end to track this. The issue is well understood and I'm working on a fix but it will take a while to be available since this is happening in the WebView2 Runtime. If checked in right now, it would reach WebView2 Runtime for our 106 release in late September per our [Release Schedule](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule#microsoft-edge-releases).

Unfortunately, there's no other workaround since this is in the WebView2 Runtime. If you know the environment configuration is the same, your app can handle `errorCode` `ERROR_INVALID_STATE` to retry creation with [ICoreWebView2CreateCoreWebView2ControllerCompletedHandler](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2createcorewebview2controllercompletedhandler?view=webview2-1.0.1293.44).

**Comment by mingchengzack** [comment] 2022-08-22 22:43
@Syul968 Thanks. We are going to go with retry for now. Could you update in this thread when you guys get the fix in?

**Comment by Syul968** [comment] 2022-08-25 21:37
The fix is now available in 1361+ builds and is expected to reach the WebView2 Runtime for our 106 release: [Release Schedule](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule#microsoft-edge-releases).

You can test the fix for your application by installing latest [Edge Canary Channel](https://www.microsoftedgeinsider.com/en-us/download) and setting the channel preference for you app: [Approaches to making your app use a specific browser channel](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel#approaches-to-making-your-app-use-a-specific-browser-channel).

**Closed** 2022-08-31 18:37 UTC
Labels: bug, tracked, circle back
