### ISSUE TITLE
WebView2 slow down significatly after 8-10 times attemps when loading local resource with WebResourceRequested event

### ISSUE THREAD

**Issue by Jimex** [MicrosoftEdge/WebView2Feedback#3398] opened 2023-04-17 13:07 UTC
**Description**
After repeatedly loading the local resource 8-10 times, we noticed a significant delay of 1-2 seconds in the loading time. This delay is impacting the application's overall performance and needs to be addressed.

Please refer to the log below.

2023-04-17 20:55:40.6161 [INFO] ===========================================================
2023-04-17 20:55:40.6420 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:55:40.9128 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:55:40.9128 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:55:41.0565 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:55:41.0698 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:55:41.0698 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:55:47.3615 [INFO] ===========================================================
2023-04-17 20:55:47.3615 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:55:47.3897 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:55:47.3897 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:55:47.4508 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:55:47.4508 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:55:47.4508 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:55:52.6113 [INFO] ===========================================================
2023-04-17 20:55:52.6113 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:55:52.6279 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:55:52.6279 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:55:52.6894 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:55:52.6894 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:55:52.6894 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:55:56.6648 [INFO] ===========================================================
2023-04-17 20:55:56.6648 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:55:56.6744 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:55:56.6744 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:55:56.7230 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:55:56.7230 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:55:56.7230 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:01.7369 [INFO] ===========================================================
2023-04-17 20:56:01.7601 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:01.7703 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:01.7703 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:01.8347 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:01.8347 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:01.8347 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:56:06.6970 [INFO] ===========================================================
2023-04-17 20:56:06.7061 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:56:06.7061 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:56:06.7061 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:56:06.7715 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:56:06.7715 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:56:06.7715 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:11.6891 [INFO] ===========================================================
2023-04-17 20:56:11.6891 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:11.7061 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:11.7061 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:11.7721 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:11.7721 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:11.7721 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:56:15.3852 [INFO] ===========================================================
2023-04-17 20:56:15.3946 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:56:15.3946 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:56:15.3946 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:56:15.4381 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:56:15.4395 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:56:15.4395 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:19.2680 [INFO] ===========================================================
2023-04-17 20:56:19.2680 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:19.2911 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:19.2911 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:19.3450 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:19.3477 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:19.3477 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:56:23.7922 [INFO] ===========================================================
2023-04-17 20:56:23.8043 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:56:23.8170 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:56:23.8170 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:56:23.8424 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:56:23.8424 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:56:23.8424 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:28.6676 [INFO] ===========================================================
2023-04-17 20:56:28.6781 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:28.6781 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:28.6781 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:28.7511 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:28.7526 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:28.7526 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:56:33.2685 [INFO] ===========================================================
2023-04-17 20:56:33.2685 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:56:33.2837 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:56:33.2837 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:56:33.3483 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:56:33.3483 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:56:33.3483 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:40.0763 [INFO] ===========================================================
2023-04-17 20:56:40.0871 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:40.0980 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:40.0980 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:40.1504 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:40.1504 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:40.1504 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser
2023-04-17 20:56:42.3436 [INFO] ===========================================================
2023-04-17 20:56:42.3532 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html started
2023-04-17 20:56:42.3679 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html ended
2023-04-17 20:56:42.3679 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index_1.html return to browser
2023-04-17 20:56:44.3662 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg started
2023-04-17 20:56:44.3662 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg ended
2023-04-17 20:56:44.3662 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/163.jpeg return to browser
2023-04-17 20:56:48.7102 [INFO] ===========================================================
2023-04-17 20:56:48.7102 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html started
2023-04-17 20:56:48.7205 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html ended
2023-04-17 20:56:48.7205 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/index.html return to browser
2023-04-17 20:56:50.7246 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg started
2023-04-17 20:56:50.7246 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg ended
2023-04-17 20:56:50.7246 [INFO] ProcessRequestResource:http://view_content.225.dicttango.app/358.jpeg return to browser

**Version**
SDK: Windows App SDK 1.3.230331000
Runtime: 
Framework: WINUI3
OS: Windows 11

**Repro Steps**
1) Create a new project using WinUI3 and add a WebView2 control to it.
2) Use the WebResourceRequested event to load a local resource in the WebView2 control.
3) Repeat the loading process 8-10 times 

[AB#44281149](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44281149)

**Comment by novac42** [comment] 2023-04-19 07:03
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by Jimex** [comment] 2023-04-21 00:32
I've created a sample project that reproduces the issue, which you can access at https://github.com/Jimex/TestWebView2.

This project repeatedly loads two HTML files, with one of them containing a JPEG image embedded in a simple tag, and the web page also loads a JavaScript file. The size of the JPEG is around 300 to 400kb.

Upon running the project, you'll notice that the first few loading instances are very smooth, but then the page suddenly gets stuck, and the page will not be shown during this time. 

I've also attempted to add ".example" to the host, but this doesn't seem to have any effect.

![WebView2Issue](https://user-images.githubusercontent.com/3145858/233513007-5c872382-16c3-41e4-9103-acdd1d7982e8.gif)

**Comment by aluhrs13** [comment] 2023-04-26 18:49
@Jimex - Thanks for the sample app! The issue isn't reproducing for me from what I can tell, it seems to be consistently loading at the same speed. Can you follow the directions at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md to get an ETW trace of this reproing?

**Comment by aluhrs13** [comment] 2023-04-28 16:21
aluhrs at microsoft dot com 🙂

**Comment by Jimex** [comment] 2023-04-29 04:20
> aluhrs at microsoft dot com 🙂

I have sent you the trace file, thank you.

**Comment by aluhrs13** [comment] 2023-08-10 17:57
@Jimex, please let us know if Liang's suggestion worked. Will close in ~7 days if no further responses.

**Closed** 2023-08-23 16:17 UTC
Labels: bug, tracked, status-circle back
