### ISSUE TITLE
Closing out a child form while the find in page bar is open crashes webview2 in parent form

### ISSUE THREAD

**Issue by TheZooKeeper** [MicrosoftEdge/WebView2Feedback#1097] opened 2021-03-19 21:09 UTC
**Description**
Closing out a child form while the find in page bar is open crashes webview2 in parent form. I get a CoreWebView2ProcessFailedEvent ProcessFailedKind of BrowserProcessExited {0} 

**Stack**
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>AuctionPro.exe</AppDomain><Exception><ExceptionType>System.Runtime.InteropServices.COMException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)</Message><StackTrace>   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rectangle value)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message&amp;amp; m)
   at System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace><ExceptionString>System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rectangle value)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message&amp;amp; m)
   at System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in Microsoft.Web.WebView2.Core.dll
The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)

**Version**
SDK: 1.0.774.44
Runtime: edg/89.0.774.57"
Framework: WinForms
OS:  Win10 1909

**Repro Steps**
I included a link to a repo that has a test app.  The methods show/Showdialog in frmMain.cs produce different bugs.  To produce the bug:
1. Start the app
2. Press Button1
3. Press cntrl+f
4. without closing the find form, close frmChild
5. In this case, the error pops up when you close the main form

**Link To Example**
https://github.com/TheZooKeeper/Webview2CrashTest

[AB#32257574](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32257574)

**Comment by champnic** [comment] 2021-03-26 03:59
Hey @TheZooKeeper - thanks for the bug report, and I appreciate the repro app! I've opened this as a bug on our backlog to take a look.

**Comment by MikeCheel** [comment] 2021-06-18 20:29
I also have users experiencing this error. Any progress or work arounds?

**Comment by champnic** [comment] 2021-06-18 21:00
We have folks actively looking at this bug and believe we have a root cause. I'll let you know when we have a fix available to try.

**Comment by MikeCheel** [comment] 2021-06-22 18:39
Not sure if this is part of it or not but it is being reported that setting the userDataFolder parameter to a folder inside Environment.SpecialFolder.ApplicationData (roaming user app data folder) can also cause the issues when users are on the same server using the app at the same time. They think that switching to the local application data folder will fix it. I am going to try and see if it fixes this for me.

**Comment by champnic** [comment] 2021-08-03 21:11
This should be fixed in runtimes 93.0.952.0+. Thanks!

**Closed by champnic** 2021-08-03 21:11 UTC
Labels: bug, tracked

**Comment by TheZooKeeper** [comment] 2021-08-19 12:12
Do we have a planned general release for that runtime.  I see it is in the canary branch.

**Comment by champnic** [comment] 2021-08-19 17:18
Stable WebView2 Runtime should ship version 93 around the beginning of September (around 2 weeks from now).
