### ISSUE TITLE
Library is not registered. (Exception from HRESULT:0x8002801D (TYPE_E_LIBNOTREGISTERED))

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3094] opened 2023-01-02 13:21 UTC
The initialization could not be completed at all, but I found that Edge on his machine was normal. ETW logs have been collected, actually this is not the first case, The chances of this error continue to increase as our number of users increases,There have been 13 cases.
The error message is as follows:
Library is not registered. (Exception from HRESULT:0x8002801D (TYPE_E_LIBNOTREGISTERED))
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- End of stack trace in previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()

[ETW Logs](https://drive.google.com/file/d/16So4Oy8sm6ImJHqFlm6PfELxl1USCGl6/view?usp=sharing)

**Version**
SDK: 1.0.1462.37
Runtime: 108.0.1462.54
Framework: .Net 4.5.2
OS: Win10 19044

**Comment by novac42** [comment] 2023-01-03 11:17
@sln162 Thanks for the report. We will take a look at the trace and get back to you.

**Comment by sln162** [comment] 2023-01-21 19:26
@novac42 Is there any update please?

**Comment by novac42** [comment] 2023-01-30 08:22
@sln162 Hi sorry for the late response. Team's bandwidth was limited in January and I've assigned another dev to look into this issue. Will keep you posted.

**Comment by yunate** [comment] 2023-01-31 08:29
@sln162 I am looking into this issue.
The reason is: The app run the browser process(msedgewebview2.exe) failure.  There are many reasons for starting msedgewebview2.exe failure. Such as "insufficient permissions", "missing msedgewebview2.exe's dependencies"... But I cannot sure which the reason is, I guess it may be the loss of some dependent files.

Could you help to test:
1. Download the latest runtime and extract to local directory: [download link](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section)
![image](https://user-images.githubusercontent.com/37793342/215706715-bcc7870a-d18e-49bb-9676-83bf35bac707.png)
2. Download the sample app from GitHub and set the `BrowserExecutableFolder` to the directory that just extracted to.
![image](https://user-images.githubusercontent.com/37793342/215707948-9b99391a-f29b-478d-88c7-e430033dda67.png)

 Check if the sample app can run successfully.

**Comment by sln162** [comment] 2023-02-01 14:54
@yunate I'm trying to find a client to work with...
I remember trying this method at that time (not sure). What is certain is that I uninstalled WebView2 version 108, then installed version 107, and reinstalled it many times, but it was the same and could not be initialized. mistake.

**Comment by yunate** [comment] 2023-02-02 09:32
@sln162 If the root cause is not `insufficient permissions` or `missing msedgewebview2.exe's dependencies`, I don't know the specific reason. But I will contact my team to see who has encountered this problem.

**Comment by novac42** [comment] 2023-08-30 10:14
@sln162 Does this issue still occur with latest runtime and SDK?

**Comment by sln162** [comment] 2023-08-30 13:37
@novac42 It has not appeared again recently, the last time it appeared was on April 29, 2023, with a runtime version of 112.0.1722.58

**Comment by victorhuangwq** [comment] 2023-10-10 18:26
Closing issue as it's resolved

**Closed by victorhuangwq** 2023-10-10 18:26 UTC
Labels: bug
